Installation instructions for Sun's Java 6 and Adobe's Flash.

** Java
   :PROPERTIES:
   :CUSTOM_ID: java
   :END:
For Debian prior to Wheezy, you will need to add the non-free repository
to your /etc/apt/sources.list. Here is the corresponding line in mine :

#+begin_src shell
  deb http://ftp2.fr.debian.org/debian/ squeeze main contrib non-free
  deb-src http://ftp2.fr.debian.org/debian/ squeeze main contrib non-free
#+end_src

Then update your system and install java :

#+begin_src shell
  $ apt-get update 
  $ apt-get install sun-java6-jre sun-java6-plugin 
  $ update-alternatives --config java 
#+end_src

/Note : sun-java6-plugin is a plugin for your browser./

For Ubuntu, use the following
[[https://github.com/flexiondotorg/oab-java6][script]] for creating a
local apt repository.

For Debian Wheezy or others, you can no longer install Sun's Java from
the repositories. The easiest way is to download the JRE from
[[http://www.oracle.com/technetwork/java/javase/downloads/index.html][the
official site]].

Extract it :

#+begin_src shell
  $ mkdir /usr/local/java
  $ tar xvzf jre-7u25-linux-i586.tar.gz -C /usr/local/java/
#+end_src

Create a symlink for Firefox :

#+begin_src shell
  $ cd ~/.mozilla/plugins
  $ ln -s /usr/local/java/jre1.7.0_25/lib/i386/libnpjp2.so
#+end_src

And, you're done !

** Flash
   :PROPERTIES:
   :CUSTOM_ID: flash
   :END:
For Flash, you just need to grab the installation archive from the
official site. Then extract it to /usr/. Finally, copy libflashplayer.so
in ~/.mozilla/plugins. This should work for iceweasel/firefox.
