#+TITLE: Reading list
#+TODO: TOREAD(t) MAYBE(m) PENDING(p) READING(r) HOLD(h) | SKIMMED(s)  DONE(d)
#+COLUMNS: %120ITEM %STATUS

* Books :book:
** Math
*** READING [#A] Gowers, T. (2010): The princeton companion to mathematics :book:math:
  :PROPERTIES:
  :Custom_ID: princetonCompanionMaths
  :END:

*** HOLD Differential topology
http://www.uib.no/People/nmabd/dt/080627dt.pdf
*** TOREAD Abstract thèse Hélène
*** TOREAD Histoire des maths
http://www-irma.u-strasbg.fr/~baumann/polyh.pdf
*** HOLD Math MPSI
Lu jusqu'à l'anneau des entiers relatifs
*** TOREAD Les maths en tête (MP) : analyse, algèbre
*** TOREAD Hastie, T., Tibshirani, R., & Friedman, J. (2009): The elements of statistical learning
Texte de référence pour classification, machine learning etc. Semble intéressant
NB :  An Introduction to Statistical Learning = version avec moins de maths.
  :PROPERTIES:
  :Custom_ID: hastie09_elemen_statis_learn
  :END:
** CS :cs:
*** READING Seibel, P. (2005): Practical Common Lisp :book:cs:
  :PROPERTIES:
  :Custom_ID: seibel05_collec
  :END:

*** READING [#A] Knuth, D. E. (1997): The art of computer programming, volume 1 : fundamental algorithms :book:cs:
  :PROPERTIES:
  :Custom_ID: taocp1
  :END:

*** HOLD Learn you a haskell for great good :cs:haskell:
Just began functors and applicative
http://learnyouahaskell.com/functors-applicative-functors-and-monoids#functors-redux

*** HOLD Real World Haskell :cs:haskell:book:
Chap 03
cite:RWH

***** READING 99 haskell :cs:haskell:exercises:
    Ex 26
*** Slides GPU :cs:
 1, OK
httalcul.math.cnrs.fr/spip.php?article292
*** Lukas' papers :cs:
*** TOREAD Davis, A., Rubinstein, M., Wadhwa, N., Mysore, G. J., Fr\'edo Durand, & Freeman, W. T. (2014): The Visual Microphone :cs:paper:sound:
  :PROPERTIES:
  :Custom_ID: davis-2014-sound-from-image
  :END:
** Medecine
*** HOLD Hall, J. (2016): Guyton and hall textbook of medical physiology :book:medecine:physiology:
  :PROPERTIES:
  :Custom_ID: hall16_guyton_hall
  :END:
**** DONE Chap 61 en cours
**** DONE Chap 34

*** READING Herring, W. (2020): Learning radiology : recognizing the basics :book:medecine:radiology:
  :PROPERTIES:
  :Custom_ID: herring20_learn
  :END:
**** DONE Chap 3

** Histoire :history:
*** Cours d'histoire 1913 :history:
*** DONE Magni, C. (2003): Les Olm\`eques: des origines au mythe :south_america:
  CLOSED: [2019-06-02 Sun 09:35]
  :PROPERTIES:
  :Custom_ID: magni2003olmeques
  :END:

Intéressant pour l'intérprétation en histoire de l'art. Assez décevant en première approche pour découvrir la civilisation
** Others :other:
*** TOREAD IPCC, 2019 : Summary for policymaker (draft) :book:climate:
https://www.ipcc.ch/site/assets/uploads/2019/08/4.-SPM_Approved_Microsite_FINAL.pdf

* Papers :paper:
** Math :math:
*** TOREAD Reinhart, A. (): Statistics done wrong :stats:
  :PROPERTIES:
  :Custom_ID: statisticsdonewrong
  :END:


  L
*** TOREAD Knill, O. (2018): Some fundamental theorems in mathematics :math:
  :PROPERTIES:
  :Custom_ID: knill18:some_fundam_theor_mathem
  :END:
*** TOREAD Greenland, S., Senn, S. J., Rothman, K. J., Carlin, J. B., Poole, C., Goodman, S. N., & Altman, D. G. (2016): Statistical tests, p values, confidence intervals, and power: a guide to misinterpretations :math:stats:
  :PROPERTIES:
  :Custom_ID: greenland-2016-p-values
  :END:

*** TOREAD Fong, B., & Spivak, D. I. (2018): Seven sketches in compositionality: an invitation to applied category theory :book:math:
  :PROPERTIES:
  :Custom_ID: fong18_seven_sketc_compos
  :END:

** CS
*** Inpainting :maths:

*** TOREAD Amsterdam, V. U. (2018): Machine learning course :course:
  :PROPERTIES:
  :Custom_ID: machinelearningVUUniv2018
  :END:

*** TOREAD Steffen, J. H. (2008): Optimal boarding method for airline passengers
  :PROPERTIES:
  :Custom_ID: steffen08_optim_board_method_airlin_passen
  :END:

** Physics :physics:
*** TOREAD Maldacena, J. (2015): The symmetry and simplicity of the laws of physics and the higgs boson
  :PROPERTIES:
  :Custom_ID: maldacena2015symmetry
  :END:
** Medecine :medecine:
*** TOREAD Rudnicka, A. R. (2005): 2. essential medical statistics (2nd edn). betty r. kirkwood and jonathan a. c. sterne, blackwell science, oxford, 2003. no. of pages: 512. price: £22.95. isbn 0-86542-871-9
  :PROPERTIES:
  :Custom_ID: rudnicka05
  :END:

  Seems to answer my questions about stats in med school
*** TOREAD Thomas, D. L. (2019): Global elimination of chronic hepatitis :infectious:
  :PROPERTIES:
  :Custom_ID: thomas19_global_elimin_chron_hepat
  :END:
*** TOREAD Grenfell, B. T., Bjørnstad, O. N., & Finkenstädt, B. F. (2002): DYNAMICS OF MEASLES EPIDEMICS: SCALING NOISE, DETERMINISM, AND PREDICTABILITY WITH THE TSIR MODEL :infectious:modeling
  :PROPERTIES:
  :Custom_ID: Grenfell_2002
  :END:
Technique++ : modélisation stochastique

*** TOREAD Jaulhac, B., Saunier, A., Caumes, E., ouiller, K., Gehanno, J., Rabaud, C., Perrot, S., … (2019): Lyme borreliosis and other tick-borne diseases. guidelines from the french scientific societies (ii). biological diagnosis, treatment, persistent symptoms after documented or suspected lyme borreliosis :infectious:
  :PROPERTIES:
  :Custom_ID: jaulhac19_lyme_borrel_other_tick_borne_diseas
  :END:
Dernières recos sur Lyme

*** TOREAD Figoni, J., Chirouze, C., Hansmann, Y., Lemogne, C., Hentgen, V., Saunier, A., Bouiller, K., … (2019): Lyme borreliosis and other tick-borne diseases. guidelines from the french scientific societies (i): prevention, epidemiology, diagnosis :infectious:
  :PROPERTIES:
  :Custom_ID: figoni19_lyme_borrel_other_tick_borne_diseas
  :END:
Dernières recos sur Lyme

*** TOREAD Khuong, T. M., Wang, Q., Manion, J., Oyston, L. J., Lau, M., Towler, H., Lin, Y. Q., … (2019): Nerve injury drives a heightened state of vigilance and neuropathic sensitization in drosophila :animals
 * :PROPERTIES:
 * :Custom_ID: khuong19_nerve_injur_drives_heigh_state
 * :END:
*** TOREAD Goupil, B., Fr\'ed\'eric Balusson, Naudet, F., Esvan, M., Bastian, B., Chapron, A., & Frouard, P. (2019): Association between gifts from pharmaceutical companies to french general practitioners and their drug prescribing patterns in 2016: retrospective study using the french transparency in healthcare and national health data system databases medecine:
  :PROPERTIES:
  :Custom_ID: goupil19_assoc_between_gifts_from_pharm
  :END:

** Other
*** SKIMMED Hausfather, Z., Drake, H. F., Abbott, T., & Schmidt, G. A. (2019): Evaluating the performance of past climate model projections :climate:
  :PROPERTIES:
  :Custom_ID: hausfather19_evaluat_perfor_past_climat_model_projec
  :END:
Comparaison de modèles de climat contre des observations pour la température
moyenne : même des vieux modèles des années 70 sont précis.

*** TOREAD Keehn, R. J. J., Iversen, J. R., Schulz, I., & Patel, A. D. (2019): Spontaneity and diversity of movement to music are not uniquely human animals:
  :PROPERTIES:
  :Custom_ID: keehn19_spont_diver_movem_to_music
  :END:
*** SKIMMED Mueller, P. A., & Oppenheimer, D. M. (2014): The pen is mightier than the keyboard
  :PROPERTIES:
  :Custom_ID: mueller14_pen_is_might_than_keyboar
  :END:
Notes papier + études > notes sans étude, PC avec étude et PC sans études
Mais ça ne montre pas que les notes PC sont moins bonnes ?
Par contre, les notes sous PC sont plus copiés-collées donc moins de réflexion

*** TOREAD Steffen, J. H., & Hotchkiss, J. (2012): Experimental test of airplane boarding methods
  :PROPERTIES:
  :Custom_ID: steffen12_exper_test_airpl_board_method
  :END:
