#+title: Douleur
#+author: Alexis Praga
#+latex_header: \usepackage{booktabs}
#+latex_header: \input{header}
#+latex_header: \usepackage[linesnumbered,ruled,vlined]{algorithm2e}
#+OPTIONS: H:4

\input{bacteries-header}

* 132 : Antalgiques
** Palier 1 et AINS
*** Paracétamol
1ere intention, surtout douleur chronique

Prescription : 3-4g/24h (adulte) avec délai 4-6h. Délai 1h, dure 4-6h. Enfant : 60mg/kg/24g
espacée de 6h 

Seul pour douleurs faibles/modérées, avec opioïdes sinon

Tolérance :
- si surdosage : 
  - hépatotoxique \thus urgence \skull \thus N-acétylcysténine
  - insuf rénale aigüe et nécrose tubulaire
  - thrombocytopénie
- sinon bonne tolérance. Surveiller HTA, hypersensibilité
  
*** AINS
COX-1 : protège muqueuse gastro-duodénale et pro-agrégant. COX-2 : inflammation,
effet anti-agrégant

Antalgique à faible dose. Pour douleurs {ostéo-articulaire, trauma, post-op,
néplasiques}, coliques néphrétiques, dysménorrhées essentielles, migraines.

OS, injectable (limiter à 48h !) ou pommade/gel

Effets indésirables :
- digestif [fn:2]: 
  - mineur : nausées, vomissements, gastralgies, douleurs abdo
  - grave : ulcère, perforation digestive, hémorragie
  - autres : ulcère oesophagien[fn:1], aggravation diverticulose,
    anorectites/brûlures anales
  - FR : { > 65 ans, ATCD ulcère/hémorragie dig, infection \bact{helicobacter},
    maladie générale sévère}, {+ AINS, + corticoïdes, +anticoag/agrégants,
    +aspirine}
    \thus FR \ge 3 ou aspirine : éviter !
- rein :
  - \danger risque hypovolémie, néphropathie, âgé, association (diurétique, IEC,
    ARAII)
  - insuf rénale fonctionnel (créat !), rétention hydrosodée, hyperkaliémie,
    néphropathie intestitielle, (nécrose papillaire) 
- cutanés/muqueus fréquents : bénin, urticaire (sd Lyelle/Stevens-johnson)
- allergiques (rhinite, conjonctivite, oedème de Quincke, asthme) ou respiratoire
- si anémie, chercher saignement digestif
- hépatite (souvent silencieuse)
- sd confusionnel (âgé)
- CV : rétention hydrosodée, \inc risque thrombotique artériel
  
Éviter interactions : AINSE aspirine, {anticoag, ticlopidine}, {diurétiques,
IEC}, lithium, corticoïdes, méthotrexate

\fbox{Surtout douleurs aigües}

** Palier II
60mg codéine = 50mg tramadol = 10mg morphine

\fbox{Douleurs modéres/intenses d'emblée ou ne répondant pas au palier I}

Douleurs aigües (courte) ou chronique (courte/long)

Codéine : 
- agoniste opioïde naturel \thus métabolite * morphine
- seul (sirop, dihydrocodéine) ou avec paracétamol. 
- 1-2 comprimés toutes 6-8h
  
Tramadol : 
- seul, libération prolongée (LP) sur 12h [fn:3] ou immédiate (LI)[fn:4]
- max 400mg/j.
- IV lente seulement en hôpital

Poudre d'opium avec paracétmal : 1-2 gélules toutes 4h (max 10/j)

Contre-indications : insuf respiratoire, asthme grave, insuf hépatocellulaire
sévère, enfants < 12 ans [codéine] ou 3 ans [tramadol], allaitement, épilepsie
non contrôlé [tramadol], +(ant)agoniste morphinique, +IMAO[fn:5] [tramadol].

Effets indésirables :
- ceux des opioïdes = sédation, vertige, {constipation, nausées, vomissements},
  {bronchospasme (dépression respiratoire)}, rétetion d'urine
- sécheresse buccale, douleurs abdo, troubles visuels, convulsion (si facteurs)

Éviter codéine si enceinte. \dec posologie si âgé

** Palier III
AMM : 
- douleurs /non/ cancéreuse = morphine, oxycodone, fentanyl (transdermique)
- douleurs cancéreuse = idem et fentanyyl transmuqueus, hydromorphone
  
*** Formes 
- Agonistes purs
  - Morphine (agoniste) : référence. Sous forme de chlorhydrate (inject) ou
    sulfate (orale en LP ou  LI)
  - Hydromorphine (agoniste) : délai 2h, dure 12h. Seconde intention dans cancer
  - Oxycodone (agoniste) : morphine x2. LP (12h) ou LI  (4h)
  - Fentanyl : morphine x50-150. Transdermique (délai 12-18h et dure 72h) en
    relais ou transmuqueuse (délai 10min et dure 1-2h)
  - Méthadone : substitutif pour dépendance aux opiacés
- Agonistes partiels : buprénorphine = morphine x30. Effet plafond
- Agoniste-antagonistes : nalpubphine = pédiatrie++, effet plafond, parentéral
  seulement. 
- Antagonistes : naloxone  

*** CI
Insuf respi décompensée, insuf hépatocellulaire sévère, insuf rénale sévère,
épilepsie non contrôlée, trauma crânier et HTIC, intox alcoolique aigüe, +IMAO,
associer agonistes avec a. partiel ou a-antagonistes

*** ECI
- Constipation (fréquent !):
 - préventif = laxatif oral systématique, hygiéno-diététique, oxycodone et
   naloxone
 - curatif : \inc laxatif, fécalome ?, ttt rectal.[fn:6] 
- Nausées, vomisseements(fréquent !):
 - préventif : anti-émétique
 - curatif : neuroleptique action centrale, corticoïdes, sétrons, droperidol
- Somnolence : \dec dose ou rotation
- Dépression respi (FR < 10min) : réa et naloxone
- Trouble s confusionnels, cognitifs : \dec doses, rotation
- Dysurie, rétention :[fn:7] \dec doses, sondage, chercher médicaments favorisants
- Prurit : antihsistaminique, rotation
  
Dépendance : pyschologique (recherche compulsvie), physique (sd sevrage)

*** Surdosage
Somnolence, respi irrégulière, FR < 10/min
Échelle de sédation (0 à 3)[fn:8], de qualité de respiration (R0 à R3)[fn:9]

Réat et injection narcan (naloxone) : 0.4mg par dose de 0.04mg/2min jusque R1/R0

*** Indications :
- Douleurs aigüe : très intenses ou (modéré/sévère ne répondant pas au palier
II). Oral (parentéral si urgence)
- Douleurs chroniques cancéreuses ou (non cancéreuses après échec étiologique,
  palier 1, II et techniques). Oral et LP.

Équivalence :
- morphine : 1 oral = 1/2 SC = 1/3 IV 
- 1 morphine Iv = 1 oxycodone IV/SC
- oxycodone . 1 oral = 1/2 IV/SC

Prescription : ordonnance sécurisée, \le 28j


* Footnotes

[fn:9] R0 = normale, R3 = pauses/apnée

[fn:8] 0 = éveillé, 3 = très somnolent, éveillable par stimulation tactile. 

[fn:7] Y enser si HTA, douleurs abdo, agitation inhabituelle
 

[fn:6] Si 0 selles : bithérapie laxative, lavement rectal, antagoniste
morphinique périph

[fn:5] Inhibiteurs de la monoamine oxydase

[fn:4] Toutes 4-6h

[fn:3] 1 prise/j, 24h si 2 prises/j

[fn:2] NB : coxibs \dec probabilité de développer un ulcère simple/compliqué
mais retard circatrisation d'un ulcère gastrique ...

[fn:1] Donc toujours prendre avec de l'eau, debout et sans être à jeun !
