#+title: Endocrinologie
#+author: Alexis Praga
#+latex_header: \usepackage{booktabs}
#+latex_header: \input{header}
#+latex_header: \usepackage[linesnumbered,ruled,vlined]{algorithm2e}
* 35 : Contraception
** Contraception hormonale
Oestroprogestatifs
- Contient {oestrogène, progestatif (gen 1,2 ou 3), autres progestatif}
- Administration orale, transdermique ou vaginale
- Action : {pas d'ovulation, endomètre peu à apte à la nidation, glaire
  cervicale imperméable aux spermatozoïdes}
Progestatifs seuls 
- Microprogestatifs : action sur glaire cervicale, endomètre
- Macroprogestatifs : si CI oestroprogestatifs
- Administration : orale, injection, implant, intra-utérin (stérilet)
** Pratique
Oestroprogestatifs : 
- à commencer le premier jour des règles pendant 21j puis 7 j
d'arrêt.
- au même moment
- Si oubli < 12h, ASAP sinon contraception mécanique $\ge 7$ jours
Microprogestatifs : toujours à la même heure. Si oubli < 3h, ASA, sinon
contraception mécanique $\ge 7$ jours
Macroprogestatifs : ccommencer le 5eme jour du cycle

** Contre-indications
Oestroprogestatifs : absolues =
- thromboemboliques veineux/artériels, prédisposition thromboses
- lupus évolutif, connectivites, porphyries
- vasc, cardiaque, cérébrales, oculaires
- valvulopathie, troubles rythmes thrombogènes
- HTA non contrôlée
- diabète et micro/macroangiopathie
- tumeur hormono-dépendantes (sein, utérus...)
- hépatiques sévères
- hémorragies génitales non diagnostiquées
- (tumeurs hypophysaires)
Macro/microprogestatifs : cancers {sein, endomètre}, insuf hépatique, accident
TEV récents

** Recommandation
Sans CI, oestroprogestatif minidosé et progestatif 2eme génération monophasique
(Minidril)

** Efficacité
Indice de Pearl[fn:1] < 0.07% pour oestroprogestatif
(< 2% pour les microprogestatifs)

Attention : certains inducteurs enzymatiques réduisens l'efficacité (ou
millepertuis).

Ado : sous- ou mal utilisée

** Tolérance
Oestroprogestatifs :
- bien tolérée, pas de perte de poids
- surveiller métabolisme
- active coagulation mais \inc fibrinolyse. Légère augmentation du risque
  d'accident TEV
- vasc : faible \inc PA
- cancer : ovaire = risque -50%, idem pour l'endomètre, faible \inc pour sein
Microprogestatifs : troubles des règles (spotting, aménorrhées), grossesse
extra-utérine

Macroprogestatifs : hypoestrogénie, aménorrhées, spotting

** Surveillance
Consulter si céphalée, déficit sensitivomoteur, (douleur ou oedème) MI, dyspnée,
douleur thoracique

Examen clinique : 
- préthérapeutique : gynéco, frottis cervico-vaginal dès 25 ans si
  asymptomatique.
- PA à +3mois puis tous 6 mois
- hyperoestrogénie (tension mammaire), hypoestrogénie (sécheresse vaginale)
Biologie : cholestérol total, triglycérides, glycémie à jeun à +3mois. Si FR, le
faire avant (!) prescription

Gynéco : métroragies, spottings. NB frottis cervico-utérin dès 25 ans (+1 an pui
tous 3 ans) indépendamment contraception

** Femmes à risques
Diabétique :
- non hormonale : si diabète 1 > 15 ans ou micro/macroangiopathie \thus locale
  (nullipare, peu de rapports) ou intra-utérin (multipare, diabète équilibré)
- hormonale :pas d'oestropregestatifs si {tabac, non équilibré, HTA, surpoids,
  diabète compliqué} \thus progestatif
Dyslipidémie : oestroprogestatif si < 3g/L cholestérol total, triglycérides <
9g/L

Thrombose veineuse
- prédisposant : anomalies de l'hémostase (génétique, acquises), ATCD familiaux
- dépistage : thrombose, multiples fausses couches, ATCD thrombose < 45 ans
- acétate de chlormadinone, CI oestrogène

Autres :
- HTA : oestroprogestatifs si 0 FR
- tabac = CI, migraine \land{} vascularite = spécialiste

** Urgence
- lévonorgesttrel ASAP < 72h
- ulipristal acétate ASAP < 120h mais 3x plus cher

* 37 : Stérilité du couple
Infertile : 0 grossesses après 1 an de rapports non protégés. Stérilité si
définitf.

Stérilité = partagée !!

** Interrogatoire
- Couple
- Femme : âge++ (détérioration après 35 ans), {grossesses antérieure,
  avortements}, infections/curetages++, ATCD chir/infectieux, douleurs
  pelviennes (rapports, règles), conditions de vie, radio/chimio
- Homme : trouble libido/érection, ATCD cryptorchidie/trauma testiculaire, ATCD
  chir pelvienne/scrotale, ATCD médicaux (oreillons++), tabac/anabolisants...

** Examen clinique
- \female : âge++, obésité/maigreur, tour taille et hanche, pilosité, PA,
  galactorrhé provoqué, gynéco.
  - Si anovulation (a-/oligo-ménorrhée) : hyperprolactinémie, hyperandrogénie,
    troubles comportement alimentaire, bouffées chaleur
- \male : IMC, pilosité, hypoandrisme, cicatrice chir, varicocèle,
  gynémocomastie, gynoïde/enuchoïde
  - volume testiculaire++, palpation cordospermatiques

** Examens complémentaires
Premiere intention, femme
- Hormonale++ : oestradiole, LH, FSH, prolactine plasmatique. Puis progestérone
plasmatique (si cycle réguliers)
- Écho ovarienne++
- Hystérographie++
Première intention, homme :
- spermogramme++ (concentration, mobilité, morphologie. Attention aux
  variabilités !
- hormonale++ si oligo-/azoo-spermie : testostérone, LH, FSH puir SHBG
Test poist-coïtal (discuté)

** Étiologie
Femme :
- anovulation : très fréquent ! Souvent aménorrhées ou irrégularités. Causes :
  sd des ovaires polymicrokystiques, hyperprolactinémie, insuf ovarienne
  primitive, déficit gonadotrope, psycho-nutritionnel
- obstacle mécanique :
  - anomalie du col utérin et insuf glaire cervilaie : post-conisation/curetage
  - obstacle, anomalie utérie : manoeuvres post-partum, polypes muqueux... \thus
    echographie
  - obstacle tubaire : cause majeure++. Souvent salpingite (Chlamydia++)
- Endométriose : rarement si modéré. hypstérosalpingographie pui coelioscopie
Homme :
- azoospermie 
  - sécrétoire : diagnostic = volume testiculaire < 10ml, concentration FSH
    faible
 \thus caryotype, analyse bras long Y, écho testiculaire (élimine
    cancer), déficit gonadotrope (rare)
  - obstructive : volume et concentration ormale, volume séminal \dec \thus
    examen clinique
    - cause congénitale : agénésie bilat des canaux déférent++ (soit anomalie
      biallélique gène CFTR, soit isolée)
    - acquis : infectieux  (gonocoque, tuberculose, Chlamydia) \thus échographie
  - exploration chir testiculaire et des voies excrétrices : si azoospermie
    confirmée par plusieurs spermogrammes, bilan génétique
- oligo-asthéno-térato-spermie : \dec nombre, mobilité, \inc hormes anormales
  \thus caryotype, brang long Y. Traitement = assistance médicale procréation
* 40 : Aménorrhée
Déf: absence de cycle menstruel après 16 ans (primaire) ou interruption chez
femme réglée (secondaire). Physiologique : grossesse, lactation, ménopause

Tout arrêt > 1 mois \thus enquête étiologique \danger

Atteinte de l'axe hypothalamo-hypophysio-ovarien ou anomalie tractus utérin

*Pas de traitement oestrogénique sans enquête étiologique*

** Conduite
*** Primaire
Forte proba de cause génétique/chromosomique. Chercher carences nutritionnelle

- Si absence de dév. puberture : doser FSH, LH
  - Si basses, tumeur hypothalamo-hypophysaire, dénutrition ou génétique : {sd
    de Kalmann (anosmie), mutation récepteur GnRH (rare), atteinte
    gonadotrophines (exceptionnels), mutation LH}
  - Si hautes : sd de Turner (caryotique 45, XO),
- Examen gynéco, écho pelvienne
  - Pas d'utérus : sd de Rokitanski, tissu testiculaire dans les canaux
    inguinaux (CAIS)
  - ambiguité OGA : dysgénésie gonadique, hyperplasie congénitale surrénales,
    anomalies sensibilité/biosynthèse androgènes
*** Secondaire 
Souvent acquises. 

Interrogatoire : médic, maladie endoc/chronique,
gynoc/obstétriques, insuf ovarienne (bouffées de chaleur). Douleurs pelviennes
cycliques : cause utérine

Examen clinique : 
- poids et taille (carence nutritionnelle
- hyperandrogénie : sd ovaires polykystiques, déficit 21-hydroxylase, (sd
  Cushing)
- carence oestrogénique : pas de glaire +2 semainesa après saignement \thus
  anovulation
- pas de signe d'appel : enquête nutritionnelle

Dosages hormonaux :
- hCG : grossesse
- prolactine \inc : médciament ou tumeux hypothalamo-hypophysaire (ou adénome)
- FSh \inc, estradiol \dec : insuf ovarienne primitive
- estradiol, LH, FSH basse : hypothalamo-hypophysaire ou nutritionnelle
- testostérone : tumeur surrénalienne/ovarienne
- sinon SOPK[fn:2]

** Causes

*** Déficit gonadotrope organique/fonctionnel

**** Hypothalamus, prolactine normales
Hypothalamus n'arrive pas à libérer la GnRH au bon rythme. 

Atteintes organiques : tumeur/infiltration \thus IRM
- macroadénomes hypophysaires, craniopharyngiomes
- chercher hyperprolactinémie, insuf antéhypophysaire associé

Atteintes fonctionnelles : apports nutritionnels insufissants par rapport à l'activité physique intense+++
**** Hypothalamo-hypophysaire dû à une hyperprolactinémie
Cause majeure

Médicaments ou tumeurs \thus pas de traitement dopaminergique sans imagerie \danger
**** Autres
- Endocrinopathies : sd de Cushing, dysthyroïdes déficits 21-hydroxylase
- Hypophysaire (rare) : auto-immune (majorité), sd de Sheehan (très rare, nécrose hypophysaire post-partum)
*** Anovulation non hypothalamique
**** SOPK (majorité)
 Pas de pic de LH, ni de progestérone. Oestradiol mais non cycliques

Irrégularité menstruelles, puis aménorrhées avec acné, hirsutisme

Diagnostic :
- 2 parmi : {hyperandrogénie clinique[fn:3], oligo-/a-novulation, hypertrophie
  ovarienne (écho)}
- exclure bloc 21-hydroxylase, tumeur de l'ovaire, sd Cushing
- exclure hyperprolactinémie

Diagnostic parfois difficile :
- sans hyperandrogénie \thus écho
- {atteinte partielle axe gonadotrope, macroprolactinémie} peuvent y ressembler

Acné : cherche hyperandrogénie, régularité cycle menstruel \thus éliminer
hyperplasie congénitale des surrénales

2 causes :
- tumeur ovarienne ou résistance insuline
  - virilisation si tumeur
  - imagerie si testostérone > 1.5ng/mL. Si normale, cherche hypothécose
    (obésité morbide androïde, acanthosis nigricans, insulino-résistance)
- pathologie surrénale :
  - sd de Cushing si signes hypercortisolisme \thus cortisol libre urinaire et
    freinage minute
  - tumeur surrénale \thus scanner des surrénales
  - déficit enzymatique en 21-hydroxylase (\danger formes tardives qui peuvent
    mimer SOPK)
*** Insuf ovarienne primitive
\inc FSH

Causes :
- chir, chimio, radiothérapie
- anomalie caryotype (sd Turner)
- anomalie gènes /FMR1/ (sd X fragile)[fn:4]
- auto-immune
*** Anomalie utérine
**** Congénitales :
Si dév pubertaire normale et douleurs pelviennes cycliques, imperfortanio
hyménéale/malformation vaginale \thus examen gynéco.\\
Idem sans douleurs \thus agénésie utérus ?

Difficulté : différence agénésie mullérienne isolée (46,XX)- anomalies androgènes
(46,XY) \thus testostérone
**** Secondaires :
Synéchies utérines (trauma de l'utérus), tuberculose utérine
* 47 : Puberté
** Normale
~4 ans, acquisition de la taille définitive, fonction de
reproduction. Classification de Tanner (5 stades)

\female : seins ~11 ans [8,13]ans, règles ~13ans [10,15]

\male : \inc volume testiculaire ~11.5 [9.5,14], \inc taille verge ~12.5ans.

Accélération de la croissance : 5 -> 8cm (163cm) \female, 5-10cm (175cm)
** Retards 
\male :  volume testiculaire < 4mL ou longeur < 25mm > 14 ans 

\female : pas de seins à 13 ans, pas de règles à 15 ans

Centrale ou périphérique ?
- centrale : congénital (pas de cassure de croissance, micropénise,
  cryptorchidie), acquis (tumeur ?), "fonctionnel" (maladie générale, trouble
  comportement alimentaire), isolé
- périphérique : sd de Turner chez \female, sd Klinefelter \male
- retard simple (élimination)

Clinique : 
- parents, grossesse, courbe de croissance. Chercher trbles digestifs,
polyuro-polydispsie, céphalée, anomalies champ visuel
- pathologie acquise, OGE, testicules, anosmie (Kallmann)

Âge osseux : 13 ans \male, 11 ans \female

Biologie : 
- stéroïdes sexuels, si FSH, LH basses \thus hypothalamo-hypophysaire
- testostérone chez \male, oestradial/écho chez \female

IRM indispensable ! si déficit gonadotrope (tumeur)

Caryotype si FSH élevé. Toujours chez \female de taille < -2DS avec retard
pubertaire/gonadotrophine \inc

*** Étiologies
Hypogonadotropes
- congénitaux : isolés, sd de Kallman, autres déficits hypophysaires, sd
  polymalformatifs
- acquis : tumeurs hypophysaires, post-radiothérapie 
Hypogonadotropes fonctionnels
- chroniques digestives/cardaques/respi
- sport intense
- endocrio
Hypergonadotropes
- congénitaux : sd Turner, sd Klinefelter, autres atteintes primitevs
- acquis : castration, trauma, oreillons, chimio/radio

***  Traitement
Cause si possible. Sinon doses \inc de testostérone (\male) ou oestrogènes puis
oestroprogestatif (\female)
** Précoces
Avant 8ans \female ou 9.5 ans \male
*** Centrales
8x plus fréquent chez \female que \male. Chez \female, causes
idiopathiques. Chez \male, causes tumorales à 50\%

Clinique : 
- dév prématuré harmoniaux (pas de règles chez \female)
- crises de rires (harmatome hypothalamique), tâches cutanées (neurofibromatose
  I ou sd McCune-Albright)
Biologie :
- testostérone élevée chez \male mais variabilité d'oestradiol chez \female

IRM hypothalamo-hypophysaire indispensable \danger (petite taille
définitive). Écho pelvienne pour \female

Traitement si risque de petite taille adulte : analogues GnRH jusque âge normal
de puberté
*** Périphériques
Clinique : \inc vitesse de croissance, avance maturation osseusse

Stéroïdes élevées, LH et FSH bas. Écho pelvienne chez fille

Étiologie :
- tumeurs ovarienne (rares) : écho puis histologies
- kystes folliculaires : bénins, régression spontanée possible
- sd McCune-Albright : {puberté précoce ovarienne, taches cutanées
  "café-au-lait", dysplasie fibreuses os}. \danger tableau pas toujours complet
  !\\
Oestradiol élevé, gonadotrophines basses, écho = utérus stimulé, kystes
ovariens. Dominance \female
- médicaments
- testotoxicose (rare, cellule de Leydig activé et LH basses), adénome leydigien
  (très rare)
- tumeurs à hCG (\male)
*** Avances dissociées
- Isolé des seins : beaucoup de filles [3mois, 3 ans]
- Métrorragies isolées : chercher vulvite, vulvovaginite, prolapsus urétrale,
  corps étranger. Éliminter kyste ovarien, sd McCune-Albright par l'absence des
  sein
\thus écho pelvienne
- Pilosité pubienne isolée : chercher forme d'hyperplasie congénitale des
  surrénales (\inc 17-hydroxyprogestérone, stimulation ACTH), prémature pubarche
  (élimination !)

* 48 : Cryptorchidie
** Enfant
 Localisation anormale et inaboutie du testicule. Très fréquente : 3%
 nouveaux-nés, 20% préma. 2/3 descendent spontanément à 1 an de vie

 Clinique : checher micropénis (< 2cm, hypospadias, autres)

 Explorations : endocrinienne pour toute cryptorchidie \danger
 - bilatérale : doser 17-hydroxyprogestérone chez \female virilisée pour élimire hyperplasie
   congénitale des surrénales
 - testostérone, INSL3 (cellule de Leydig), AMH, inhibine B sérique (c. de
   Sertoli), FSH, LH mesurée jusque 4-6mois[fn:5]
 - écho pour vérifier l'absece de dévirés mülleriens

 Étiologie
 - hypogonadisme hypogonadotrope congénital
 - anorchidie rare
 - si hypospade en plus, chercher dysgénésie testiculaire
 - sd polymalformatif

 Suivre l'âge de l'apparition de la puberté !

 Traitement : chir dès 2 ans, indispensable ! (risque de cancer)
** Adulte
- Risque : hypogonadisme, infertilité, cancer testicule
- Examen clinique : scrotume, gynécomastie, signes d'hypogonadisme
- Complémentaire : {FSH, LH, testostérone}, hCG si tumeur à la palpation, écho
  scrotale, spermogramme
* 51 : Retard de croissance
\danger Ne pas passer à côté de pathologies sévères

Phases : foetale (rapide, {nutrition, insuline, IGF-2}), précoce 0-3ans (rapide,
{insuline, IGF, hormones thyroïdiennes}), prépubertaire (plus lente, décroît,
{génétique, GH/IGF, hormones thyroïdiennes}), pubertaire ({stéroïdes sexuels,
GH, nutrition})

Retard statural = {taille < -2DS, ralentissements croissance, croissance <<
parents}

Prise de poids, obésite, ralentissement croissance \thus chercher
hypercorticisme, tumeux craniopharyngiome sur l'hypothalamus, hypopituitarisme

Examen :
- ATCD : taille, parents, néonatale, médicaux/chir, contexte social
- morphotype, dév. pubertaire, tous les système, psychoaffectif

** Principales causes
#+caption: Retard poid
| Maladie coeliaque             | IgA {totales, transglutamase}, fibro                   |
| Crohn                         | VS, écho anse grêle                                    |
| Mucoviscidose                 | Test sueur                                             |
| Anorexie mentale              | Courbe de poids                                        |
| Insuf rénale chroniques       | Créat, iono, explo fonctionnelles                      |
| Anémie chroniques             | NFS                                                    |
| Rachitisme hypophosphatémique | Bilan phosphocalcique                                  |
| Patho mitochondriales         | lactate/pyruvate, génétique, biopsie musc, fond d'oeil |
| Nanisme psychosocial          |                                                        |

#+caption: Retard statural
| Endocrino         | Déficit GH (congénital, acquis [tumeur]) | IRM                                 |
|                   | Hypothyroïdie                            | T4L, TSH, Ac anti-TPO               |
|                   | Hypercorticisme (iatrogène)              | Cortisol libre urinaire/à 23h, ACTH |
|                   | Déficit hormones sex.                    | Testostérone, GnRH, IRM             |
|-------------------+------------------------------------------+-------------------------------------|
| Constitutionelles | Sd Turner                                | Caryotype                           |
|                   | Sd noonan                                | Gène PTPN11                         |
|-------------------+------------------------------------------+-------------------------------------|
| Autres            | Osseuses (a-/hypo-chondroplasie)         | Radio                               |
|                   | RCIU                                     | Taille naissance                    |
|                   | Petite taille idiopathique               | Élimination                         |

- Test de stimulation de l'hormone de croissance (\danger si doute, IRM)
- Ralentissement sévère \thus bilan en urgence (craniopharyngiome, thyroïdite de
  Hashimoot) \skull
- [0, 3] ans : digestives pédiatrique (coeliaque, mucoviscidose), [3,puberté] :
  endoc constitutionnelle, à la puberté : déficit hormone, patho osseuse
- Savoir différenceier retard pubertaire syimple d'un vrai  retard

** Exploration :
- Caryotype : fille taille < -2DS ou < -1.5DS sous taille parentale moyenne
- NFS, VS, foie, rein
- IgA totales, anti-transglutaminase
- GF-1, T4L, TSH
- Radio

* 78 : Dopage
** Substances augmentant la testostérone 
- Stéroïdes anabolisant, testostérone : \inc masse musc, puissance
- Risque : thrombotique, rupture musculo-tendineuse, touble personnalité, foie,
trouble libido, adénome/cancer de la prostate
- Femmes : masculinisation, hirsutisme, acné, aménorrhée, anovulation,
  hypertrophie clitoridienne, libido exacerbée

\vspace*{0.5cm}
- Testostérone : test chromatographique + spectrométrie de masse (très sensible
  et spécifique)
- Dihydrotestostérone (DHT) : traitement gynécomastie
- Anabolisants : \inc tissu cellulaire (muscle). ES : rétention hydrosodée, HTA,
  IDM, hépatite
- hCG : diminuer épitestostérone/testostérone après dopage (IM, SC). Testée dans
  le sang ou urine.
- Anti-oestrogène : stimule production testiculaire de stéroïdes

** Hormone de croissance (GH), IGF-1
- GH \inc masse musculaire, modifie architecture sequelette, acromégalie /mais/
  pas d'effert sur volume d'activité physique. Détection difficile : approche indirecte (cascade biologique) et mesure des
forme circulante et comparaison à r-hGH
- IGF-1 mime certains effet GH

** Glucocorticoïdes, ACTH
- Glucocorticoïdes : antalgiques, psychostimulants, combativité. ES : HTA,
  oedème, rupture ligament/tendon
\danger arrêt brutal = dangereux \skull

* 120 : Ménopause et andropause
\label{sec:120}
** Ménopause
Déf: plus de règle > 1 an \pm sd climatérique, lié à une carence
oestrogénique. Vers 51 ans.

Pré-ménopause : irrégularités cycles puis dysovulation puis anovulation ~5 ans
avants.

*** Diagnostic
Clinique seulement \danger : bouffées de chaleur, \female > 50 ans. Bio
seulement si hystérectomie \thus \dec oestradiol et \inc FSH

En pratique : progestatif seul 10j/mois x3 \thus pas de saignement à l'arrêt =
diagnostic

Aménorrhée < 40 ans = pathologique !

*** Conséquences
Court terme : bouffées de chaleur, trouble sommeil/humeur, \dec sécrétions
vaginailes
Moyen terme : douleurs ostéoarticulaires, \inc perte osseuse (selon ATCD d'insuf
ovarienne prématurée, fractures no traumatique, médicaments, calcium/vit D)

Long terme :: \inc risque CV. Incertitude sur SNC

*** Traitement 
Bénéfices
- court terme : qualité de vie à +5-10 ans
- long terme :
  - prévention ostéoporose
  - cardiovasculaire et neuro = incertain
  - cancer du côlon
Risques :
- \inc cancer du sein, accident veineux thromboemboliques (mais chiffres absolus
  faibles)
- \inc AVC ischémique, lithiase bilaires

**** Thérapeutique 
- oestrogène (17\beta-oestradiol)
oral/percutané/transdermique[fn:6] 25 jours/mois
- *et* progestatif (au moins les 12 derniers jours) per os/transdermique
\danger hémorragie de privation possible. Si pendant le traitement, faire écho
pelvienne, hystéroscopie

**** CI 
Cancer du sein, endomètre, ATCD thromboembolique artériel (ischémique,
cardiopathie embolinogène) ou veineux, hémorragie génitale sans diag, hépatique

**** Mise en route
- Interrogatoire : ATCD {cancer, métabolique, vasculaire}, carence oestrogénique
- Examen physique : poids, PA, palpation seins, gynéco, frottis cervico-vaginal
- Mammograhpie !
- Cholestérol, triglycérides, glycémie

**** En pratique 
1ere intention si trouble fonctionnels importants. 2eme si risque
d'ostéoporose. Sinon au cas par cas.

**** Surveillance 
3-6mois (surdosage = douleur, tension mammaire). Puis tous les 6-12 mois,
mammographie tous les 2 ans, frottis CV tous les 3 ans.

Traitement \ge 5 ans !!

**** Alternatives
- Modulateurs spécifiques du récepteur des oestrogènes : raloxifène
- tibolone

NB : traitement local préserve tractus urogénital. Dépister FR CV. Promouvoir
exercice, calcium, vit D

** Andropause
Chez majorité des hommes mûrs/âgés en bonne santé non obèse, baisse de
testostérone inconstante (2%).

*** Démarche
 - Interrogatoire : libido, érection, énergie vitale, mobilité/activité physique
 - Examen clinique : IMC, virilisation, gynécomastie, palper testicules
 - Mesure de testostérone totale :
   - > 3.2ng/mL = normale \thus étiologies non endocrino
   - \in [2.3, 3.2] : dosier SHBG, calculer index de T libre, si bas cherche cause
   - < 2.3 ng/mL : chercher cause
*** Étiologie
Si FSH, LH élevée, insuf testiculaire primitive 
- lésionnelle : chimio, radiation, alcoolisme surtout. Autres : castration,
  torsion, orchite ourlienne
- cryptorchidie bilatérale
- chromosomique : sd Klienfelter++
- lié à sénescene, cause génétique (rare !)
Sinon hypogonadisme hypogonadotrope 
- tumeur région hypothalamo-hypophysaire : craniopharyngiome, adénome
  hypophysaire++, autres
- infiltratif : sarcoïdose, hémochromatose
- chir, radiothérapie, traumau
- hyperprolactinémie, carence nutritionnelle, Cushing, tumeur testiculaire

* 122 : Troubles de l'érection 
Nécessite : vasculaire, musculaire lisse, retour veineux, signal  nerveux,
hormonal, psychisme = fonctionnels

Déf : incapacité persistante à obtenir/maintenir érection pour rapport sexuel satisfaisant

Âge = FR (déficit neurosensorile, \inc testostérone, comorbidités)

** Conduite  diagnostique
*** Interrogatoire
- DD avec perte désire, trouble éjaculation, douleurs pendant, anomalies morphologiques
- Caractérisation : primaire/secondaire, brutal/progressif,
  permanent/situationnel, sévérité (délai trouble-consult, capacité résiduelle,
  masturbation)
- Pathologies, facteur :
    - primaire : trouble psychogène perso, complexe identitaire, trouble
      relationnel, conflit socioprof, anomalie génitale
    - secondaire : ATCD abdo-pelvien, diabète, FR CV, patho CV, neuro, trouble
      miction, endocrinopathie, troubles sommeil, traitement, déficit
      androgénique, sd dépressif, troubles addictifs
*** Clinique
- Gynécomastie, hypoandrisme, petits testicules, anomalies du pénis (La Peyronie)
- CV : HTA, pouls, souffle
- neuro : sensibilités périnée, MI
- endoc : anomalie CV
*** Bio
Glycémie, lipidique (si > 1 an), {NFS, iono, créat}, foie (si > 5 ans), déficit
androgénique

Doser prolactine, hormones thyroïdiennes

** Bilan secondaire et approfondi
Secondaire : sexo/psychologique, épreuve pharmacologique (prostaglandien,
inhibiteur de la phospohdiestérase 5)

** Étiologies
Plus fréquentes :
- vasculaire : FR = HTA
- endocrino++ : diabète
- génito-pelvien : chir pelvienne
- trauma médullaire
- neuro dégénératif
- iatrogène : antihypertenseur

** Aspects endocriniens
*** Androgènes circulants
Influe libido, intérêt sexuel. Pour l'érection . seulement spontanées !

Hypogonadisme (diag difficile) : 
- asthénie, gynécomastie, dépilation, perte force musculaire, adiposité androïde
- doser testostérone totale \pm SHBG, prolactine. FSH, LH pour l'origin (cf
  Sec. \ref{sec:120})
  
*** Hyperprolactinémie 
Tumeur hypophysaire (IRM), champ visuel si tumeur
supra-sellaire, {T4L, cortisol, IGF-1, testostérone}
\thus agoniste dopaminergique

*** Diabète
sucré = 1ere cause de trouble érectile (TE). TE fréquents chez diabètique. 

Facteurs : mal équilibré, complications, âge, ancienneté diabète

Physiopatho : neuropathie autonomie, microangiopathie \thus défaut relaxation
musculaire. Macroangiopathie \thus ischémie organes érectiles

\danger facteurs psychènes hyportants !

Diabète et TE \thus mesure testostérone systématique (hypogonadisme ?)

Clinique : 
- TE peut révéler diabète. 
- diabète et TE : cherche trouble endoc, vasc, neuro, médicament, dépression
- TE = FR d'ischémie myocardite silencieuse \danger
  
Thérapeutique : inhibiteurs des phosphodiésterases de type 5 moins efficaces

** PEC
Ttt étiologie : seulement trouble psychogène pur, chir possible, endocrino

*** Trouble endocrinien
- Si hypogonadisme confirmé par bio[fn:7] : androgène oraux/intramusc/transderm
- CI : nodule prostatique palpable, PSA > 3ng/mL
- Surveiller prostate, foie, hématocrite
  
*** Pharmacologique
- FR, Hb glyquée < 7%, psycho/sexologique
- 1ere intention : inhibiteurs des phosphodiésterases type 5 = efficaces
- Sinon apomorphine, yohimbine = peu efficace
- "Pompe" = efficace mais résistance psycho
- 2eme intention : droge vasoactive = efficace mais douleurs peniennes, priapisme
- Prothèses péniennes = dernier recours, par chirurgien spécialisé

* 124 : Ostéopathies
Ostéoporose : fragilité excessive du squelette (\dec minéraux osseux, modif
microarchitecture). T-score < -2.5 DS valeur moyenne par DXA

Dominance \female. Primaire ou secondaire :
- endocrino : hypogonadisme, sd Cushing, hyperthyroïdie, hyperparathyroïdie, diabète
- digestives, générale, génétique, médicaments, autres
  
** Hypogonadisme
Carence oestrogénique \inc ostéoclastogénèse. Aggravé par précocité,
déminarilsation
*** Anorexie mentale
Biochimie : {isoenzyme des phosphastales alcalines, ostéocalcine} (formation)
\dec, {CTx, NTx} (résorption) normaux

Aggravé par troubles nutritionnels. Hypercortisolisme hypothalamique réversible

Ostéoporose fréquente, risque de fractures $\times 7$

Traitement 
- multidisciplinaire
- pilule oestroprégestative en pratique (limite perte osseuse)

*** Activité physique intensive
Hypoestrogénie hypothalamique

Facteur : activité[fn:8], troubles menstruels, apports alimentaires

Résorption généralisée (rachis++), \inc fractures de fatigue

Traitement : si aménorrhées, \dec activité ou oestroprogestatifs

*** Pathologies hypophysaires
Prolactinomes, adénome corticotrope influent remodelage osseux

Perte osseuse rapide (8% par an), récupération variable.

Traitement : \female non ménopausée : oestrogénothérapie

*** Iatrogènes
Agonistes GnRH (patho utérines), inhibiteurs aromatase (cancer sein)

Réversible à l'arrêt (moins bien si âgée)

Traitement : bisphosphonates, denosumab

*** Dysgénésies gonadique 
Sd Turner = plus fréquent (1/2500 à naissance)

\dec masses osseuse, continue à l'adolescence. \inc risue fracture chez
l'adulte.

Traitement : oestrogénisation (hypogonadisme) et hormone de crossance. Adulte :
oestroprogestatif

** Hyperthyroïdie, traitement par hormones thyroïdiennes
Cause fréquente d'ostéoporose secondaire \thus dosage systématique TSH

Hormones thyroïdiennes \inc remodelage : résorption sur l'os cortical++ et trabuclaire

En pratique, rarement évolution jusque l'atteinte osseuse (ttt
rapide). Adapter posologie hormones thyroïdiennes au cancer thyroïdien.

Prévention :
- densitométrie
- bisphosphonates sujet âgé ou risque extrémité supérieure du fémur
- surveillance si ttt suppressif de fonction thyroïdienne

** Hypercortisolisme, corticothérapie

\dec ostéoblastes, \inc activité ostéoclaste. \dec absorption intestinale
calcium, \inc pertes urinaires calcium, hyperparathyroïdisme

Surtout trabuculaire (vertèbres, côtes, radius). Aggravé si prépubertaire, hypogonadisme
Fractures vertébrales fréquentes, surtout sd Cushing avec adénome
corticotrope/surrénalien

Traitement : 
- pré-corticothérapie : status osseux, FR
- supplément vitaminocalcique
- bisphosphonates, tériparatide si corticothérapie > 3 mois, prednison > 7.5mg/j
  et T-score $\ge -1.5$

** Hyperparathyroïdie primitive
Fréquent, notamment chez femme ménopausée. Ostéoporose fréquente \thus dépistage
systématique par DXA

Production continue PTH : \inc résorption os cortical (tiers proximal radius,
fémur). NB : souvent aussi extr supérieure du fémur et vertèbres. 

Diminution limitée (10%). Souvet favorable post-parathyroïdectomie.

Traitement : chir si T-score < -2:5. Sinon anti-ostéoclastiques[fn:9], calcimimétique[fn:10]

** Chez l'homme
   Pas de T-score reconnu. 

Fracture radius distal plus rares.

Ostéoporoses secondaires plus fréquentes chez l'homme : hypercorticisme,
hypogonadisme congénital/acquis/iatrogène, alcoolisme, hypercalciurie
idiopathiques, génétique
* 207 :Sarcoidose
  Atteinte hypothalamo-hypophysaire exceptionnelle. Conséquences : diabète
  inspide central, insufisance gonadotrope

Radio : IRM centrée sur hypothalamo-hypophyse = référence (T1,T2 injecté) \thus
infiltration plancher 3eme venticule, infundibulum, tige hypophysaire épaissie
\pm hypophyse augmente de volume

DD : tuberculose, histiocytose, lymphome, autres tumeurs de la région 

Si patient avec sarcoïdose : diagnostic = déficit endocrinien et imagerie[fn:11]

Sinon : atteinte rare[fn:12]

Radio et arguments sarcoïdose.

Traitement : sarcoïdose et déficits hormonaux

* 215 : Hémochromatose
Hémochromatose primitive : génétique, surcharge en fer. 5 pour 1 000 !

Physiopatho : 
- Absorption intestinale régule stockage de fer 
- Fer entre dans l'entérocyte (DMT1), puis stocké via ferritine ou relargé par ferroportine
- Hepicidine \dec quand besoins fer \inc (!)
- Hémochromatose : hepcidine effondrée, DMT1 et ferroportine \inc
  
Génétique : gène HFE à 95% et mutation C282Y/C282Y ou C282Y/H63D

** Clinique
En pratique, suspicion aux "3 A" : asthénie, arthralgies, \inc ALAT

*** Atteintes :
- foie : \inc ALAT ou hépatomégalie. Cirrhose \approx 90% décès
- coeur : cardiopathie dilatée, troubles rythme
- endocrino :
  - diabète++ (accumulation pancréatique de fer) insulino-pénie/-résistance
  - hypogonadisme+ : impuissance \male, aménorrhée \female, \dec libdio,
    ostéoporose
  - insuf thyriodienne exceptionnelle
- articulaire : arthrite chronique ("poignée de main"), chrondocalcinose
- cutané : mélanodermie (tardive)


** Diagnostic
- Si CS-Tf[fn:13] < 45% : si ferritine \inc, cherche hépatosidérose dysmétabolique,
  acéruléoplasminémie, mutation gène de la ferroportine 1
- Sinon, CS-Tf > 45% : 
  - si C282Y/C282Y ou C282Y/H63D : diagnostic
  - sinon, si ferritine \inc, test génétique de 2eme intention, biopsie
    hépatique

Examen complémentaires : glycémie, transaminases, écho abdo, ECG \pm écho
cardiaque, radio articulation, bilan testostérone

Dépistage chez parents (1er degér) : bilan martial \pm dépistage
génétique. \danger mutation \neq maladie

** Stades
0. Asymptomatique, CS-Tf, ferritinémie normaux
1. CS-Tf \inc 
2. CS-Tf \inc et ferritine \inc
3. Idem et expression clinique affectant qualité de vie
4. Idem et expression clinique affectant pronostic vital
   
** Traitement
À partir du stade 2

*** Saignées 
Référence. Objectif : ferritine < 50 g/L (hebdomadaire) puis entretien tous les
  2-4 mois. Ne pas dépasser 550mL !
  
CI : anémie sidéroblastique, thalassémie majeure, cardiopathies sévères

*** Autres 
- Érythraphérèse : coûteuse, plus difficile
- Chelation du fer : 2eme intention (coût, effets indésirable)
- diététique : pas d'alcool, éviter vitamine C mais *conserver* apports en fer !
- Symptomatique

** Suivi
Résultats en 3-6 mois sur été générale. 

Bilan ferrique (stade 0,1) ferritinémie, hémoglobine (stade 2 à 4)

* 219, 220 :  Facteurs de risque CV, dyslipidémies
Rappel : FR = causalité et {relation forte, \propto dose, indépendant des autres
FR, plusieus étude, exposition précède maladie, plausible, réversible++}

Risque absolu = un individu. Relatif = $\frac{R_{\text{exposé}}}{R_{\text{non exposé}}}$

Prévention : primaire (avant accident), secondaire (éviter nouvel), tertaire
(traiter séquelles}

** FR
- Non modifiable : âgé (> 50A \male, > 60A \female), ATCD familiaux IDM/mort
  subite < 55A \male, 65A \female)
- Modifiable : tabagisme, LDL \inc, HDL < 0.40g/L, diabète, insuf rénale
  chronique

Estimation : Étude Framingham, SCORE. En pratique : 
- interrogatoire  : ATCD familiaux CV, personnels, FR
- examen : athérome asymptomatique (pouls périphérique, souffle vasculaire),
  symptomatique (ECG)
  
** Tabac 
30% adulte, 25% femmes enceintes

\inc rapide du risque après sevrage (mécanisme prothrombotique du tabac). 

RR : 3 maladie coronarienne, 5 IDM/mort subite, 2-7 AOMI, 2 AVC.

\danger tabac - contraception oestroprogestative

** Hyperlipidémie
\hyphenation{hyper-cho-lesté-ro-lé-mie}
\showhyphens{hyperholestérolémie}

*** Étiologies  
Secondaire
- Bilan selon contexte : TSH, glycémie, créat, protéinurie, BU
- Comorbiditét : 
  - hypocholestérolémie : hypothyroïdie, (cholestase, anorexie mentale)
  - mixtes : sd néphrotique, grossesse
  - hypertriglycéridémie : insuf rénale chronique, alcoolisme, (obésité, diabète
    avec sd métabolique)
- Iatrogène : ciclosporine, corticoïdes, oestrogènes oraux, rétinoïdes,
  IFN-\alpha, certains antétroviraux, neuroleptiques, durétiques thiazidiques, betabloquant
Primaire
- Hypercholestérolémies familiales monogéniques
  - mutation du gène du récepteur LDL++ : hétérozygote (xanthomes tendineux,
    complications CV précoces) ou homozygote (rare, DC vers 20 ans)
  - mutation du gène de l'apoliporotéine B
  - mutation du gène PCSK9
- Hypercholestérolémies polygéniques : fréquent, complications CV tardives
- Hyperlipidémies combinées familiales : fréquent++, pas de xanthèmes,
  complicastions CV suivant intensité
- Dysbetalipoprotéinémie : xanthomes pathognomoniques
- Hypertriglycéridémie familiale : rare, pas de xanthomes
- Hyperchylomicronémie primitive : souvent hypertriglycéridémies majeurs

** HTA et risque CV
PAs \ge 140, PAd \ge 90mmHg (3 consultations à 3 mois)[fn:15]   

40% adulte. Proba \inc si sd métabolique. Aggravé par HVG, glomérulopathie

Clinique, bio, ECG

** Diabète et risque CV
Complications coronariennes ischémique : RR \female > \male.

AOMI : RR \times 5, AVC RR \times 2.

Diabète 2 : maladie coronarienne peut précéder diabète ! \thus dépistage

** PEC
Dépistage familial si pathologie métaboblique \inc risque vasc
*** Sevrage tabac
Évaluer dépendance nicotine
Poid + 5kg ern moyenne

Substituts nicotinique (6sem-6mois) : n'aggrave pas maladie coron/troubles rythmes
Varéniclide, bupropion = dernière ligne (8 semaines)
*** Activité physique
- \dec insulino-résistance, \dec triglycéridémie, \inc HDL
- \dec PA repos, \inc périmètre marche AOMI, \inc pronostic complications
coronariennes ischémiques

3x45min à 75% $O_2$

*** Diététique
- Lipides : graisses < 35%, \dec gras saturés, \inc mono-insaturés, {poisson gras, noix,
\omega_3}, \dec cholestérol
-  Autres : \inc fruits, légumes, {noix, noisettes, amandes}, sel < 6g/j, alcool
  < 3 verres vin, \dec sucres simples, -20% calories
  
Hypertriglycéridémie : 
- modérées : -20% calories ++, \inc activité physique
- majeur : arrêt alcool, régime hypo- (si obèse) ou iso-calorique avec < 30g
  lipides (si obèse) ou 20g
  
*** Hypolipémiants :
Statines :
- \dec LDL, \dec TG \inc HDL
- ES : myalgies, \inc CPK, \inc transaminases, \inc risque diabète 2
- CI : HS, grossesse, allaitement
*** Traitement hypercholestérolémies
En primaire si LDL élève à +6 mois traitement. En secondaire si complication ischémique

Objectifs :
- primaire : 
  - LDL < 1.3g/L si risque CV faible (pop générale, diabète ou
  hypercholestérolémie familale)
  - LDL < 1g/L sinon
- secondaire : systématique
  
Molécules
- hypercholestérolémies : statines
- hypertriglycéridémies : diététique si TG > 2g/L, statines si TG < 4g/L et HDL
  bas, fibrate sinon

Augmenter doses progressivtement puis suivi : 2-3 mois tant que objectifs non
atteints puis 1-2/an

** Antihypertenseurs
Diurétiques, betabloquant, inhibiteurs calcique, IEC, ARA II[fn:16]

Monoprise, monothérapie en 1ere intention

Objectif : [130, 139] et < 90mmHg. Visites mensuelles jusque l'objectif

Suivi : pas d'hypotension orthostatique, {iono, créat, DFG} +15j après
chaquement changement, suspension diurétiques, ARA si déshydratation

** Antiagrégants plaquettaire
Prévention secondaire : systématique. Clipodigrel-aspirine systématique à +1 mois
après stent, +1 ans après stent actif

* 221 : HTA, causes endocriniennes
Déf: \ge 140/90 mmHg.

Dépistage d'une HTA secondaire : systématique mais économe...

Enquête :
- initiale : ATCD familiaux HTA, souffle para-ombilical, rein/masse abdo à la
  palpation, signe d'hypercortisolisme/acromégalie, bio \thus
  protéinurie/hématurie, imagerie, hormonale (selon signes)
- si résistance malgré 3 antihypertenseurs (dont 1 diurétique), chercher toutes
  les cause d'HTA

HTA curables : 3-5%. Cf les catégories ci-dessous !

** Hyperminéralocorticisme primaire (HAP)
Physiopatho : aldostérone, cortisol, désoxycorticostérone \thus rétention sodée
\thus HTA et inhibe sécrétion de rénine.

Penser à HAP si hypokaliémie (< 3.5mmol/L) ou HTA résistante

\begin{algorithm}
  \caption{Explorations des HAP}
  Arrêt diurétiques\;
  Vérifier natriurèse+, kaliurèse > 20mmol/j\;
  \If{aldostérine/rénine \times 2}{
  Si aldo \inc et rénine \dec : HAP\;
  Si aldo \inc et rénine \inc : hyperaldo. secondaire\;
  Sinon aldo \dec et rénine \dec : autre minéralocorticisme\;
  }
\end{algorithm}

Tests dynamiques possibles : stimulation (recherche un défaut) de), freination
(rechere une freination)

*** Adénome de Conn 
Forme généralement curable
- imagerie : nodule unilatéral > 10mm au scanner.
\danger il faut prouver une sécrétion unilatérale d'aldostérone \thus
cathétérisme si scanner douteux/patient jeune/HTA résistante
- chir possible (mais tumeur bénigne, risque récidive
- si autre HAP : médicaments en continus

*** Hyperminéralocorticismes familiaux 
Lié à l'aldostérone, désoxycorticostérone, cortisol

** HTA endocrines iatrogènes
Contraception oestroprogestative, corticostéroides, réglisse

** Phéochromocytomes, paragangliomes fonctionnels
   Phéochromocytomes (PCC) : médullosurrénale. Paragangliomes fonctionnels : autres
   ganglions sympathiques
   
PCC : spontanément mortel. Dépistage :
- HTA avec céphalées, sueurs, palpitations, HTA paroxystiques/diabète sans
  surpoids
- sd familial : neurofibromatose 1 (NF1), von Hippel-Lindau (VHL), néoplasie
  endocrinienne multiple 2 (NEM2), sd phéochromocytomes-paragangliomes familiaux

Diagnostic : métanéphrines \inc.

Puis imagerie : PCC : uniques, ~5cm. PGG siègent dans l'organe de Zuckerkandl,
vessie, hiles rénaux, médiastin postérieur, péricarde, cou.

Puis médecine nucléaire

Toujours dépistage :
- clinique : taches "café-au-lait", neurofibromatomes, nodules de Lish (NF1),
  hémangioblastomes (VHL)
- génétique : NEM2, VHL
  
Toujours traitement chir mais surveillance long terme

** Sd de Cushing
Correspond hypersécrétion de cortisol

signes : acén, ecchymoses, faiblesse musc, hirsutisme, oedèmes, ostéoporose, PAd
> 105mmHg, vergetures pourpres

Étiologies :
- maladie de Cushing (adénome corticotrope) à 66%
- tumeur non hypophysaire (15%) : adénome sécrétant surrénalien ou
  corticosurrénalome

*** Démarche
- Diagnostic posiitif : cortisol sang (on cherche élévation cortisol
  vers minuit) ou salive, cortisolurie (sur 24h), test de freinage rapide
  (dexaméthasone à minuit, cortisolémie à 8h du maitn)
- Diagnostic étiologique selon ACTH :
  - ATCH diminuée \thus adénome, corticosurrénalome, hyperplasie bilatérale
  - ATCH normale ou \inc \thus test CRH. si positif : tumeur ectopique ou
    maladie de Cushing  
    
** Causes rare
   Tumeurs à rénine, acromégalie
* 238 : Hypoglycémie
Diagnostic : neuroglucopénie \land{} glycémie < 0.50g/L (0.60 chez diabétique) \land{} correction symptômes
à normalisation (triade de Whipple)

Causes :
- sécrétion inappropriée d'insuline (hypoglycémiante)
- (rare) : défaut de sécrétion d'hormones hyperglycémiantes (GH, glucagon,
  catécholamine, cortisol), déficit néoglucogénèse, défaut substrat

** Symptômes
Neuroglucopénie : faim brutale, troubles concentration, troubles moteurs,
troubles sensitifs, troubles visuels, convulsions focales/généralisése,
confusion

Coma hypoglycémique : début brutal, agité (sueurs), irritation pyramidale, hypothermie

+ souvent signes adrénergiques : anxiété, tremblements, nausése, sueurs,
  pâleur, tachycardie

** Causes 
Diabétique : traité par insulines, hypoglycémiants oraux

*** Insulinome 
1ere cause tumorale (mais rare). Maligne dans 10%, < 2cm (90%)
Clinique : manif. adrénergiques dominent

Diagnostif : épreuve de jeune. 

- Glycémie : basse
- Signes neuroglucopénie
- Insulinémie normale mais inadaptée à glycémie
- Peptide C bas 
- Pas de sulfamides

DD : prise d'insuline (peptide C élevé), de sulfonylurée (sulfamides)

Scanner en coupe fine du pancréas et écho-endoscopie si médecin habitué

Traitement : chir

*Hypoglycémie par sécrétion inaproppriée d'insuline : triade de Whipple, glycémie \le 0.45g/L (sponténément/jeûne) avec
insulinémie \ge 3 mUL/L, peptide C \ge 0.6ng/mL*
* 239 : Goitre, nodules thyroïdiens, cancers thyroïdiens
  Synthèse hormones thyroïdiennes nécissite \approx 150 \mu{}g/jour (ado,
  adulte, \times 2 chez enceinte)

Goitre = hypertrophie de la thyroïde :
- palpation > dernière phalange du pouce
- écho : volume > 20 $cm^3$ (18 femme adlute, 16 ado)

** Évaluation
   Clinique : mobile déglutition/visible cou en extension/visible à
   distance. Chercher : gene fonctionelle, signes de compression, signes de
   dysfonction thyroïdienne, ADP[fn:17]
   
Bio : 
- TSH ! si \inc, déficit production, si \dec, imprégration excessive en
hormoes thyroïdiennes.
- compléter par T4, et si TSH \inc : Ac anti-TPO, anti-Tg

Échographie

** Goitre simple
Hypertrophies normo-fonctionnelles non inflammatoires non cancéreuses

Facteurs : \female, tabac, déficience iodée

*** Évolution
Constitution à l'adolescence (cliniquement latente) puis plurirondulaire : gêne
cervicale \thus TSH, écho, ponction, scintigraphie
\danger cherche caractère plongeant sur radio !

À ce stade, complications : hématocèle, strumite, hyperthyroïdie, compression
organes de voisinages, cancerisation (5%)

*** PEC
- Ado : levothyroxine ([1,1.5\u]g/kg/j) jusque V normal. Vérifier TSH
- Adulte/agé : si multinodulaire non malin, surveillance. Si symptomatique,
  thyroïdectomie totale
- Goitre ancien, négligé : iode 131
\inc iode, notamment grossesse

*** Autres pathologies responsables
- Maladie de Basedow
- Thyroïdites : 
  - Hashimoto = hypertrophique. Goitre très ferme, expose à l'hypothyroïdie. Ac
Ant-TPO\inc\inc{}, écho : goitre diffus, hypoéchogène
  - autres thyroïdites
- Troubles de l'hormonosynthèse
  
** Nodules thyroïdes
Déf : toute hypertrophie localisée de la gande thyroïde. Majorité = bénin (5%
cancers, de très bon pronostic)

Prévalence \approx décennie du sujet. \times 2 chez \female. \inc si grossese,
déficience iode, irradiation cervicale

*** Évaluation :
Si signe d'accompagnement :
- nodule douloureux brutal : hématocèle
- nodule douloureux + fièvre : thyroïdite subaigüe
- nodule compressif + ADP : cancer
- nodule + hyperthyroïdie : nodule toxique
- nodule + hypothyroïdie : thyroïdite lymphocytaire
Si isolé : 
- TSH \dec : nodule hyperfonctionnel ? \thus scintigraphie
- TSH N : tumeur \thus écho, cytologie
- TSH \inc : thyroïdite lymphocytaire ? \thus Ac anti-TPO

Pronostic plutôt suspect : 
- homme, enfant/âgé, ATCD irradiation cervicale, > 3cm,
ovalaire, dur, irrégulier, > 20% en un an
- écho : hypoéchogène, contour irrégulier, microcalcifications, ADP
  
Bio : TSH surtout. Calcitonine (CT) ? 
- Si nodule, CT > 100pg/mL = argument solide pour cancer médullaire thyroïde.
- CT \in [20,50]pg/mL : idem ou hyperplasise des cellules C ou insuffisant rénal

Examens : 
- Échographie (classification TI-RAD de 1 à 6)
- Cytologie si nodule suspect (classification Bethesda)
- Scinti si cytol ininterprétable x2 ou indéterminé

*** Thérapeutique
- Chir si suspect clinique/écho/cyto : thyroïdectomie si dystrophie controlatérale
- Surveillance sinon
- Hormonal si bénin dans familles avec goitres plurinodulaire, < 50 ans.

Kystes, hématocèles : anéchogène \thus hormonothérapie, alcoolisation.

Grossesse : 2e trimestre ou après accouchement pour opération

Nodule oculte : < 1cm. Risque de cancer 5%, faible pouvoir agressif
- \danger si ADP, hérédité cancer médullaire thyroïde, fixation au TEP
- ponction seulement si hypoéchogène et > 8mm
** Cancers thyroïdiens
1.5% cancers, 4eme chez la femme

Découverte : fortuite++, ADP cervicale, signes de compression, flushes/diarrhée,
localisation métastatique

Anatomie :
- carcinomes différenciés d'origine vésiculaire : papillaire (85%, excellent
  pronostic), vésiculaires (5%), peu différenciés (2%)
- carcinomes anaplasiques (1%)
- carcinomes médullaires au dépens des cellules C
- autres
  
Risque de rechute/décès : 
- taille tumeur, effraction capsule thyroïdienne,
métastase (clasif TNM de I à IV)
- mortalité \propto âge, dépend de l'histologie, exérèse

*** Thérapeutique
- Plan cancer
- Chir en 1ere intention (anatomopatho pendant = certitude) : thyroïdectomie
  totale. Curage ganglionnaire si besoin (systémituqe si carcinome médullaire,
  si enfant/ado). Complications : hémorragie postopératoire \skull,
  hypoparathyroïdie (calcium + vit D), paralysie transitoire/définitive nerfs récurrents
\vspace*{10pt}
/Cancers différenciés d'origine vésiculaire/
   - iode 131 : seulement post-thyroïdectomie totale (haut risque). Après
     stimulationo par L-T4 ou injection TSH. Puis hospit après en chambre 2-5 j
     et contraception 6-12 mois. ES : {nausées, oedèmes}, {agueusie,
     sialadénite}. Scinti  obligatoire à +2-8j : fixation extracervicale à
     distance = métastases
   - hormonal : L-T4 si haut risque ou échec traitement initial. Puis mesurer TSH à
     +6sem-2mois (pas avant !)
   - surveillance : 80% des récidives à 5 ans \thus écho cervicale, rhTSH,
     Tg[fn:18] à 6-12mois : cytoponction puis imagerie si Tg > seuil. Sinon \dec LT4
   - traitement récidives : chir si cervicale. Plus compliqué si métastates
     (iode131 si fixant sinon ttt local ou molécules ciblées). Plus LT4
     
/Cancers anaplasiques/
Tuméfaction cervicale rapidement progressive, dure, adhérente, sujet âgé \thus radio-chimio. Pronostic très péjoratif

/Cancers médullaires/
TTT : chir \pm curage ganglionnaire
Surveillance : calcitonine > 150\mu{}g/L \thus bilan de localisation.
Temps doublement : 6 mois = pronostic très mauvais.

Traitement métastases = local.

Étude génétique dans tous les cas : positif \thus chercher phéochromocytome,
hyperparathyroïdie + enquêtes apparentés
* 240 : Hyperthyroïdie
Déf : hyperfonctionnement de la glande thyroïdienne. Sd de thyrotoxicose =
conséquence sur les tissus.

Prévalence élevée, 7\times femme

Physiopatho :
- TSH, TPO et Tg peuvent être des auto-antigènes
- thyroïde produit surtout thyroxine )T4), convertie en T3 par foie, muscle
  squelette. [T4] n'est à l'équilibre que +5 semaines
- effet : 
  - \inc production chaleur, \inc production énergie, \inc consommation $O_2$
  - inc débit cardiaque, système nerveux, \inc ostéclasie, \inc lipolyse, \inc
    glycémie, rétrocontrole négatif hypophysaire

** Sd de thyrotoxicose
Clinique (par fréquence \dec) :
- CV : tachycardie (régulière, repos, \inc effort), \inc intensité bruits
  coeurs, \inc PAs
- neuropsy : nervosité, tremblement fin régulier des extrémités, fatigue
  générale, troubles sommeil
- thermophobie, hypersudation, 
- amaigrissement rapide, important, avec appétit conservé
- autre : polydipsie, amyotropie, \inc frequence selles, rétraction paupière
  supérieure (gynécomastie, troubles règle)

Examen complémentaire : TSH effondrée. T4 ou T3 libre pour l'importance

Complications : 
- cardiaque (surtout personnes fragiles) : troubles rythme supraV (FA), insuf
  cardiaque (droite, avec débit N ou \inc), aggravation insuf coronaire
- crise aigüe thyrotoxique (exceptionnelle)
- musculair (âgé)
- ostéoporose (\female ménopausée) : rachis

** Étiologies (fréquence \dec)
*** Auto-immunes
**** Maladie de Basedow 
1% population. Auto-immune, sur terrai génétique. Poussées pui rémissions

Clinique : 
- goitre diffus homogène, élastique, souffle
- oculaire (spécifique, inconstant) : rétraction et asynérgie palpébrale,
  inflammation, exophtalmie, oedème paupières, inflammation conjonctive,
  limitation mouvement regard
  \thus examen ophtalmo ! (acuité visuel, cornée, papille, oculomotricité, tonus
  intraoculaire)\\
  Mauvais pronostic : exophtalmie importante, paralysie complète, neuropathie
  optique, hypertonie oculaire avec souffrance papillaire
- dermopathie (exceptionnelle) placard rouge, surélevé, induré, face ant jambes
  
Diagnostic : manif oculaire suffit. sinon : écho (hypoéchogène, vascularisé),
(scinti), Ac anti-récepteur TSH

**** Autres auto-immune
- Thyroïdite post-partum (5%) : hyper- transitoire puis hypothyroïdie. Ac
  anti-TPO mais pas Ac anti-récepteur TSH
- Thyroïdite d'Hashimoto : goitre irrégulier, très ferme. Écho :
  hypoéchogène. Ac anti-TPO mais pas anti-récepteur TSH

*** Nodules thyroïdiens hypersécrétans  
Âge plus avancé, sd de thyrotoxicose pur (pas de manif oculaire) 
- Goitre multinodulaire toxique : à la clinique, puis écho. Scinti : "en damier"
- Adénome toxique : palpation nodule unique, écho : tissulaire/partiellement
  kystique. Scinti nécessaire : reste du parenchyme "froid"

*** Iatrogènes
- Iode : produits contraste, amiodarine. 2 formes : fonctionnelle ou lésionnelle
  (lyse des cellules)
\danger sous amiodarone : T4L \inc mais T3L, TSH N 
- Hormones thyroïdiennes : pour maigrir. Diag : scinti (pas de fixation), Tg
  effondrée
- Interféron (fréq++)

*** Thyroïdite subaigüe de De Quervain
Affection banale virale. Diagnostic clinique (goitre dur et douleureux). Hyper-
puis hypo-thyroïdie

*** Thyrotoxicose gestionnelle transitoire 
Fréquent (2% grossesse). 1er trimestre : nervosité, tachycardie, pas de prise de
poids
DD : Basedow (pas Ac anti-récepteur TSH)

*** Rares
Mutations activatrices du récepteur TSH, métastase massives sécrétantes ([fn:19]K
thyroïdiens vésiculaire différencié), tumeurs placentaires/testiculaires, {sd
résistance hormones thyroïdiennes, adénome hypophysaire}

** Forme clinique 
- Enfant : généralement Basedow (néonatale/acquise) : avance staturale et
  osseuses, hyperactivité \pm signes oculaires
- Femme enceinte : passage d'Ac \thus hyper- ou hypo-thyroïde. Passe d'ATC \thus
  goitre, hypothyroïdie possible. Contraception !
- Âgé : évolution discrète (AEG, fonte musculaire, cachexie, insuf
  cardiaque). Penser thyrotoxicase si troubles rythme/insuf cardiaque
  
** Traitement
Urgence : crise aigüe thyrotoxicose, cardiothyréose chez âgé/cardiqaue,
orbitopathie maligne, cachexie vieillard, Basedow chez \female enceinte

Repos, sédatifs, bêtabloquant, contraception

Antithyroïdens de synthèse (ATS) :
- -mazole (30-60mg/j), -thiouracile (300-600mg/j) : bloque TPO
- ES : allergies cut, \inc enzymes hépatiques, neutropénie, agranulocytose++
  (\skull !!)
- surveillance : T4 libre jusque N puis T4L et TSH. NFS 10jours pendant 2 mois (agrunolcytose)
  
Chir : thyroidectomie totale sauf si adénome toxique (loectomie)

Radio-iode : simple, sans danger. CI : femme enceinte.

*** Résultats
- Basedow : thyroïdectomie \thus hypothyroïdie définitie. Radio-iode \thus
  hypothyroïdie 50%, risque aggravation orbitopathie. Donc ttt médical (1-2
  ans) puis chir/iode si récidive
- Adénome/goitre multinodulaire toxique : chir, iode
- Induite par l'iode : arrêt si possible
- Thyroïdite subaigüe : anti-inflammatoire (AINS/corticoïde)
  
*** Formes particulières
- Cardiothyréose : propanolol et anticoag. Si insuf cardiaque : tonicardiaque,
  diurétiques, vasodilatateurs, betabloquant, anticoag. Pour thyrotoxicose : ATS
  puis chir/iode 131
- Crise aigüe thyrotoxique : soins intensifs, réa, ATS, propanolol, corticoïdes,
  iode131 après 24h ATS
- Orbitopathie : si simple, collyre. Si maligne : cf spécialiste
- Femme enceinte : si transitoire, repos. Si Basedow : repos si mineur. Si forme
  importante : ATS faible dose. Si formes grave, chir (2eme trimestre) possible)
\thus surveillance avant et après accouchement  

* 241 : Hypothyroïdie
- Atteinte de la glande thyroïde  : \inc TSH et (T4L N : hypothyroïdie frustre) (T4L \dec : hypothyroïdie patente)
- Ou hypothalamo-hypophysaire : T4L \dec et (TSH (\dec ou N)  ou légèrement /inc)
  
** Sémiologie
Général :
- sd d'hypométabolisme[fn:20]
- peau pâle/jaune, sèche squamueuse dépilée, cheveux secs cassant
- myxoedeme cutanéomuqueux : faciès "lunaire", voix rauque, hypoacousie,
  macroglossie
- neuromusc : crampes, myalgies
- endocrinien : (galactorrhée), troubles règles, troubles libido
Cliniques (rare, diag fait avant) :
- CV : bradycardie sinusale, \dec contractilité, (insuf cardiaques, troubles
  rythme V), épanchement péricardique, favorise athérome coronarien
- neuromusc, neuropsy : dépressif, sd confusionnel, démence, myopathie prox,
  apnée sommeil
- coma myxoedemateux : si hypothyroïdie primaire profonde et
  aggression. Convulsion, EEG non spécifique. Hyponatrémie. Pronostic sévère

Palpation : glande ferme hétérogène, pseudonodulaire

Grossesse : 
- complication mère : HTA, prééclampsie, fausse couche, hémorragie post-partum
- complications foetus : troubles developpement neuro-intellectuel, hypotrophie
- 1er trimestre : TSH \dec, T4L limite sup. Puis TSH normale, T4L basses
  (physiologique !)

Anomalies bio :
- hémato : anémie normocytaire normochrome (si macrocytose, penser anémie de
  Biermer) troubles de coagulation,hémostase
- hypercholestérolémie, \inc CPK, hyponatrémie dilution

** Étiologies
*** Hypothyroïdie primaire
Auto-immunes :
- Thyroïdite d'Hashimoto : 
  - goitre ferme, irégulier, Ac anti-TPO. 
  - infiltraton lymphocytaire du parenchyme thyroïdien. Facteurs environement,
    terrain génétique.
  - penser à lymphome si \inc rapide du goitre
  - écho thyroïdiennes : hypoéchogène, hétérogène, vasc hétérogène (scint
    inutile)
- Thyroïdite atrophique : pas de goitre, Ac anti-thyroidiens moins
  élevés. Souvent une évolution d'Hashimoto, > 50 ans. 
- Thyroïdite du post-partum : idem, petit goitre. Normalement résolutif dans
  l'année. 5%
Non auto-immune :
- thyroïdite subaigüe de De Quervain : inflammation du parenchime. Phase de
  thyrotoxicose puis hypothyroïdie
- thyroïdite sans Ac
- thyroïdite iatrogène : interferon++, amiodarone, ATS, iode131, radiothérapie
  cervicale, lithium, ttt anti-tyrosine kinase (cancéro)
Autres : carences iodées (endémie++), hypothyroïdie congénitale (dépistage à
naissance + 72h[fn:21]

*** Démarche diagnostique
TSH puis (T4L (profondeur) et Ac anti-TPO, échographie pour étiologie)
*** Insuffisance thyréotrope
- compression région hypothalamo-hypophysaire (HH) par tumeur (adénome hypophysaire
  souvent)
- séquelle post-chir, post-radio des tumeurs de la région HH
- séquelles méningite, trauma crânien, hémorragie méningée
- génétiques (rare) 

IRM systématique !

** Traitement
Lévothyroxine (T4) 
- hypothyroïdie patente : L-T4 [50150] \mu{}g/j. Si coronarien : \inc progressivement
  de 12.5 à 25\mu{}g/j. \danger Surveillance ! (ECG hebdo si grave, hospit si coronarien
  récent, sinon patient doit consulter si douleurs thoraciques)
- hypothyroïdie frustre : 3 cas
  - TSH > 10mUI/L ou Ac anti-TPO : ttt
  - TSH < 10mUI/L et pasd'Ac anti-TPO : surveillance
  - si grossesse : dès TSH \ge 3mUI/L
  - à discuter sinon

Suivi
- hypothyroïdie primaire : objectif : TSH $\in [0.5, 2.5]$ mUI/L (\approx 10mUI/L
pour âgé, et < 2.5mUI/L pour femme eceinte)
- insuf thyréotrope : suivi sur T4L seulement
  
Situations particulières:
- grossesse : \inc posologie dès diagnostic grossesse
- \inc si interférence : \dec absorption intestinale{sulfate de fer, carbonate de calcium, hydroxyde
  d'alimunie, cholestyramine}, \inc clairance {phénobabrital, carbamazépinex, rifampicine,
  phényto¨en, sertraline, chlooriqune}, oestrogenes
- néonatale : L-T4 à vie
  
** Dépistage ?
- Adulte : si risque : signes clinique, goitre, hypercholestérolémie, ATCD
  thyroïdiennes, auto-immunité thyriodienne, irradiation cervicale, {amiodaone,
  lithium, interféron, cytokines}
- Femme enceinte : si signes, contexte thyroïdien (perso/familial), auto-immunité

* 242 : Adénome hypophysaire
** Sd tumoral
Clinique : 
- céphalées : rétro-orbitaire, localisése
- trouble visuels : "voile", par compression des voies optiques. Fond d'eil,
  acuité visuelle OK. Quadra-/hémi-anopsie temporale (sup si quadra)
- apoplexie hypophysaire (rare) brutal : céphalées violentes, sd méningé sd
  confusionnel, troubles visuel. Imagerie en urgence \danger : adénome en nécrose/hémorragie
IRM = examen de référence :
- microadénome : arrondi, homogène, hypo-T1, hypointense  après injection,
  signes indirects
- macroadénome :  > 10mm, iso-T1 et hyperintension après injection. Regarder
  expansion vers chiasma optique et sinus (sphénoïdal, cavernux)
- DD : craniopharyngiome intra-sellaire (hétérogène, hyperT2), méningiome
  intra-sellaire (dure-mère spiculée)
  
** Sd d'hypersécrétion
*** Hyperprolactinémie
Fréquente \thus cherche adénome hypophysaire (même si majorité = médicament)
Signes :
- \female : galactorrhée (pas forcément causée par prolactine ! mais chercher
  quand même), troubles du cycle menstruel (doser !)
- \male : galactorrhée, gynécomastie (rare), troubles sexuels. Hypogonadisme
  \thus doser prolactine 
- 2 sexes : risque d'ostéoporose
\begin{algorithm}
  \caption{Stratégie diagnostique hyperprolactinémie} 
  Vérifier hyperprolactinémie (kits, agrégats)\;
  Écarter grossesse, médicaments, hypothyroïdie périphérique, insuf rénale\;
  IRM : si microadénome. \;
  Sinon différentier macroadénome à prolactine VS autre tumeur associée à 
hyperprolactinémie : régression sous agoniste dopaminergique si premier\;
\end{algorithm}

*** Acromégalie
Clinique :
- Sd dyspmorphique : extrémier élargies, visage (nez élargie, front bombé, lèvres
épaisses, tendance prognathisme}
- Signes fonctionnels : sueurs, céphalées, paresthésies des mains, douleurs
articulaires, asthénie fréquente, HTA (50%)
Complications :
- CV : hypertrophie myocardite (écho), débit \inc. Puis insuf cardiaque
  congestive
- arthropathie périphérique : grosses articulations, radio (interligne \inc,
  ostéophite), rachis (spondylose d'Erdheim)
- diabète/intolérance glucose, SAS, goitre, polypes du colons
  Diagnostic : absence de freinage de la GH pendant hyperglycémie provouqée
  orale (GH > 0.4ng/mL), \inc IGH-F1
Puis bilan tumoral, retentissement fonctionnel hypophysaire, retentissement
acromégalie
*** Sd de cushing
Excès de glucocorticoïdes : causes iatrogènes ou adénomes hypophysaires
corticotropes
Clinique :
- anomalies acquises. Amyotrophie ceinture et abdomen, lenteur cicatrisation,
  peu amince (mains), ecchymoses au moindr chocs, vergétures cutanée (flancs,
  racine des membres, mammaire, péri-ombilic), visage érythrosique, congestif,
  varicosité
- moins spécifique : +10kg, graisse facio-tronculaire (visage arrondi), bosse de
  bison, hyperandrogénie, OMI
- autres : ostéoporose (asymptomatique), spanioménorrhée, \dec libido, HTA,
  troubles psy
Bio : intolérance glucide

Diagnostic : 
\begin{algorithm}
  \caption{Stratégie diagnostique hypercorticisme}
  Cortisol libre urinaire (CLU) ou freinage minute ou cortisol à minuit\;
  Si CLU \inc, réponse anormale freinage minuit, cortisol minuit > 72ng/mL\;
  Vérifier par freinage standard \thus hypercorticisme\;
  Dosage ACTH : si bas, scanner surrénales pour adénome\;
  Sinon IRHM hyperphysaire, freinage fort, test CRH, 
  test métopirone \thus sécrétion ectopique (normal) ou maladie de Cushing\;
\end{algorithm}

NB : 
- Freinage minute = cortisolémie matin après 1mg dexméthasone à 23h. Freinage
faible : urines 48h puis idem après 0.5mg dexméthasone
- DD : stress intense, dépression sérèver, psychose, alcoolsime (CLU modéré,
  freinage minute anormal) \thus épreuve du temps 
  
** Insuffisance antéhypophysaire
Clinique : face pâle, "veillot", dépigmentation aréole mammaire et OGE,
dépilation complète aisselles pubis

Signes des déficits hypophysaires :
- gonadotrope : \male = {\dec libido, pilosité visage \dec, petits
  testicules mou, infertile}, \female = {aménorrhée, dyspareunie}, ostéoporose,
  (retard pubertaire)
- corticotrope : asthénie, hypotension, amaigrissement, pas de déficit
  aldostérone ! (hyponatrémie de dilution). Risque de collapsuse CV
- hypothyroïdie modérée
- somatotrope : adulte = {\dec masse et force musc, adiposité abdo}, enfant =
  retard croissance, accidents hypoglycémiques
  
*** Bilan hypophysaire
- Déficit corticotrope : test Métopirone, cortisol < 200ng/mL si hypoglycémie (<
  0.49g/L), autres test (cortisolémie, synacthone, CRH)
- Déficit thyréotrope  : \dec T4L, TSH normale
- Déficit gonadotrope : \female préménopause : aménorrhée, oestradiol \dec,
  gonadotrophines normales, \female postménopause  : gonadotrrophine
  basses/valeurs jeunes, \male : troubles sexuels \dec testostérone
- Déficit somatotrope : déficit GH enfant++ (retard croissance, pas de réponse
  à stimulation GH) ou adulte (faire au moins 2 tests stimulation)
- Prolactine normale/élevée

IRM si déficit hypophysaire
* 243 : Insuffisance surrénale
** Insuffisance surrénale lente
Rare mais grave \skull

Physiopatho :
- cortisol (stimulé par ACTH, rétrocontrole nég. sur ACTH) : hyperglycémiant,
  stimule = {catabolisme protidique, lipogenèse, SNC, tonus vasculaire}, inhibe
  = {hormone antidiurétique}, anti-inflammatoire et antipyrétique,
  minéralocorticoïde
  Minimum 0-2h, maximum 7-9h
- aldostérone : rétention Na+, excrète K+
- androgènes surrénalien (stimulé par ACTH)
  
Insuffisance surrénale : primaire (maladie d'Addison) VS secondaire

| Primaire                                           | Secondaire        |
|----------------------------------------------------+-------------------|
| Fatigue, dépression, anorexie, nausées             |                   |
| \dec poids, hypotension, hypotension orthostatique |                   |
|----------------------------------------------------+-------------------|
| Hyperpigmentation                                  | Pâleur            |
|----------------------------------------------------+-------------------|
| HyperK, hypoNa (manque sel)                        | HypoNa (dilution) |
*** Diagnostic
\danger ne pas attendre résultats pour commencer traitment \skull

Positif 
- cortisolémie
- mesure ACTH pour différencier primaire de secondaire
- aldostérone/rénine : rénine \inc si primaire
- test Synacthène (+ Métopirone ou hypoglycémie insulinique si doute)

NB : femme enceinte = {\inc seuil, faisceau d'args}, enfant : répéter dosages
voire ttt probabiliste

Étiologies de l'IS primaire
- Auto-immune (80% adulte, 20% enfant) : 
  - polyendocrinopathie de type 1 (mutation
  facteur de transcription AIRE) ou 2 (IS + 1 parmi {thyroïdite d'Hashimoto+++,
  Basedow, diabète 1}
  - \thus autoAc anti-21-hydroxylase, scanner (surrénales atrophiques)
- tuberculose bilatérale surrénale (10%) : transplanté ou ID avec TCD tuberculose
  \thus scanner surrénales (\inc puis atrophie et calcification). Bilan des
  localisation tuberculose
- VIH (stade avancé) : iatrogène, infection opportuniste (CMV++), atteinte de
  l'hypophyse (lymphome, CMV), corticoïde anti-inflammatoire et ritonavir
\danger dénutrition \thus spécialiste
- autres : iatrogènes++[fn:22], métastases bilatérales++[fn:23], lymphomes, maladies
  infiltratives, causes vasculaires
- enfant : génétiques surtout = bloc enzymatique++ (dépistage obligatoire), adrénoleucodystrophie

Étiologies de l'IS secondaire 
- surtout interruption corticothérapie prolongée (> 7mg prednisone)
- autres[fn:24] : tumeur région hypothalamo-hypophysaire, hypophysite (auto-immune),
  granulomatose, trauma, chir hypophysaire, radiothérapie, sd de Sheehan 

*** Prise en charge
Ttt substitutif :
- glucocorticoïdes (hydrocortisone) 15-25mg/j
- minéralocorticoïde (fludrocortisone) 50-150\mu{}g/j si IS primaire

TTT cause

Éducation du patient : 
- avoir carte, hydrocortisone (comprimés et injection),
régime normosodé
- pas de laxatifs, diurétiques, millepertuis, réglisse, jus de pamplemousse
- ttt à vie
- hydrocortisone en SC si > 2 vomissement/diarrhées en < 1/2 journée
- adapter à chaleur, exercice, voyage

Surveillance clinique :
- fatigue, poids, PA
- surdosage en hydrocortisone (gonflement/rougeur visage, \inc poids, HTA, os,
  métabolisme, CV)
- surdosage en fludrocortisone
- cortisolémie, ACTH inutile !!
  
** Insuffisance surrénale aigüe
*** Y penser
- déshydratation extracellullaire avec pli cutané, hypotension
- confusion, crises convulsives
- troubles digestifs
- douleurs (musc, céphalées)
- fièvre
Biologie : 
- hémoconcentration, insuf rénale fonctionnelle++
- hypoNa, hyperK++
- hypoglycémie, acidose métabolique, anémie, hyperlymphocytose,
  hyperéosinophilie, natriurèse conservée

*** Confirmation
Si diagnostic *non* posé : dosage cortisol (\dec\dec), ATCH (\inc si primitive, N ou \dec
si secondaire). 
Ne pas attendre les résultats \skull

*** Causes 
- Insuf surrénale chronique décompensée++
- D'emblée si bloc enzymatique surrénalien (21-hydroxylase) complet (néonatale)
  ou hémorragie bilat surrénale ou apoplexie hypophysaire
- Décompension par n'importe quelle patho intercurrente

*** PEC
\danger Urgence extrème \skull
- Domicile : 100mg hydrocortisone (IV, IM, SC) puis transport
- Hopital : réa puis 
  - perfusion NaCL (et G30% si hypoglycémie)
  - ttt facteur déclenchant
  - surveiller : PA, FC, FR, oxymétrie de pouls, diurèse, T, glycémie, CS, ECG
    si hyperK

Ttt préventif : patient doit \inc ses doses, médecin traitant au courant

** Arrêt d'une corticothérapie
   Expose au rebond de la maladie causale, insuf surrénale secondaire
   (corticotrope), sd de sevrage

À risque : (ttt \ge 3 semaines par \ge 20mg prednisone) ou (corticoïdes et inhib enzymatique du
cytochromie P450 (ritonavir)) ou sd Cushing iatrogène
* 244 : Gynécomastie
  Hyperplasie tissue glandulaire mammaire, fréquente. Dû au déséquilibre
  oestrogène/testostérone (\inc et \dec respectivement). Regarder aussi TeBG,
  SHBG
** Démarche
- Clinique : palpation = ferme/rugueux, mobile arrondi, centré par le
mamelon (rien si adipomastie)
- Mammographie si doute : opacité nodulaire/triangulaire (rien si adipomastie). Élimine cancer du sein (rare) 
- Physiologique ? 
  - 2/3 des nouveaux-nés
  - pubertaire : de 13 jusque 20 ans, rétrocède . Palper testicule pour atrophie testiculaire/tumeur
  - fréquente > 65 ans. Palpation testiculaire
** Étiologie 
Évidente :
- insuf rénale chronique, cirrhose, médicaments (surtout spironolactone,
  antiandrègène, kétoconazole, neuroleptiques, ATB antirétroviraux, antiulcéreux)
Sinon exploration hormonale : T4L, TSH, hCG, testostérone totale, LH, FSH,
prolactine, oestradiol

Causes endocriniennes :
- hyperthyroïdie
- insuffisance testiculaire/hypogonadisme périphérique (8%) : sd de Klinefelter
  le plus fréquent
- hypogonadisme d'origine hypothalamique/hypophysaire: testostérone basse, LH,
  FSH normales/abaissées \thus imagerie hypophysaire, dosage
  prolactine. Hyperprolactinémie ou tumorale
- tumeur sécrétant oestrogène : oestradiol \inc, testostérone \dec \thus tumeur
  testiculaire (ou surrénalienne rarement) \thus echo testiculaire ou scanner
  abdo
- tumeur sécrétant hCG : \inc hCG \thus écho testiculaire, scanner
  cérébrales. Dans le bronches ou le foie parfois. Chimio.
- Résistance androgènes (exceptionnelle) : testostérone \inc, LH inc
- idiopathique (25%)

** Traitement
Traiter la cause. Sinon
- Pubertaire : ne rien faire
- Idiopathique : androgènes non aromatisables 3 mois. Si inefficace, chir
  plastique possible
* 245 : Diabète
Définition : glycémie à jeun \ge 1.26g/L (2 reprises) ou aléatoire \ge 2g/L[fn:25]
me
Caractéristiques diabète 1 (le diabète 2 s'y oppose) : ATCD familiaux rares, <
25 ans, début rapide explosif, symptomatologie bruyante, poids normal ou \dec,
shyperglycémie majeure > 23g/L, souvent cétose, pas de complications
dégénératives, mortalité par insuf rénale (CV pour diabète 2)

** Diabète 1
   Prévalence : 1/200 000 (10% des diabétiques). Peut survenir à tout âge. \inc
   incidence. Sex-ratio = 1

*** Physiopathologie
Carence en insuline par destruction cellules beta du pancréas. Soit auto-immun
(fréquent), soit idiopathique

Prédisposition génétique (Ag HLA, VNTR, CTLA-4, PTP-N22), facteurs
environementaux.

Processus auto-immunss : au moins un Ac parmi les suivants dans 97% : Ac
anti-{ICA, GAD, IA2, insuline, ZnT8}

Diabète \in sd polyendocrinien auto-immun : 10% d'autres maladies auto-immunes =
thyroïdopathies (Basedow, thyroïdite), Addison, atrophie gastrique de Biermer,
maladie coeliaque, vitiligo 
- \thus doser Ac anti-TPO ou TSH (thyroïdite),
anti-surrénale (Addison), anti-transglutaminase \pm anti-endomysium (coeliaque),
anti-paroi gastrique, anti-facteur intrinsèque (Biermer)
- si positif : surveillance annuelle

*** Clinique
Habituel : début rapide/explosif, sd cardinal = *polyuro-polydispsie,
amaigrissement, polyphagie*, troubles visuels transitoires, examen pauvre (fonte
musc, signes d'acidose[fn:26], glycémie veineuse, cétonurie (acidocétose
inaugurale)

Formes
- Diabète 1 lent (LADA[fn:27]) : début tardif, progessif, Ac
positif. Insulinothérapie en 2-10 ans
- Révélé par acidocétose : fréquente chez enfants, ne devrait plus être vues
- Non insulinodépendantes : 3 auto-Ac positifs \thus 100% d'avoir diabète 1 dans
  5 ans. Rémission de quelques mois possibles.
- cétosique du sujet noir d'origine africaine : mécanisme
  auto-immun. Décompensation cétosique. Auto-Ac spécifique du diabète 1
  nésgatifs.

Affirmer type 1 :
- clinique : triade maigreur/amaigrissement, cétose, < 35 ans
- sinon auto-Ac
- sinon :
  - hérédité dominante : MODY, mutation SUR1/KIR6-2 (si diabète néonatal)
  - symptômes inhabituels : sd de Wolfram (atrophie optique, surdité, diabète
    inspide < 20 ans), mitochondropathie (surdité, distrophie maculaire,
    cardiomyopathie transmission par la mère)
  - secondaire : cancer pancréas (amaigrissement), pancréatite chronique,
    mucoviscidose, hémochromatos, médicaments
    
*** Évolution
Schéma théorique : phase préclinique (destruction cellules beta), clinique (85% détruites), clinique séquellaire

Diabète instable : itérations de cétoacidoses ou hypoglyémies sévères,
psycho. DD : gastroparésie, déficit systèmes contra-insuliniques, Ac anti-insuline

*** PEC
Patient : contrôle glycémie, injection d'insuline, prévenir complications
métaboliques et vasculaires, adapter ttt, contrôle de l'alimentation \thus
éducation thérapeutiques

Objectifs : HbA1c < 7% (enfants : entre 7.5 et 8.5, complication/sujet âgé : 8%)

Autosurveillance : urinaire rare, glycémique 4/jour [fn:28], (glucose en SC si
objectifs thérapeutiques non remplis) :

Surveillance :
- HbA1c : en pourcentage Hb totale, aucun sens si modif durée de vie moyenne des globules rouges[fn:29]
- diabétologue/pédiatre endocrinologue 3/an
- {lipides, créat, microalbuminurie}
- ophtalmo, cardiologie 1/an (sympto/âgé,compliqué), dentiste 1/an

Traitement insulinique : palliatif à vie

| Type                          | Injection  | Durée | Utilisation              |
|-------------------------------+------------+-------+--------------------------|
| insuline humaine recombinante | IV, IM, SC | 7-8   | Prandiale, hyperglycémie |
| analogue rapide de l'insuline | IV, IM, SC | 4-6h  | Pompe                    |
| forme lente                   | SC         | 9-16h |                          |
| analogue lents                | 16-40h     |       |                          |

Injection :
- Résorption SC \inc si injection dans muscle, chaleur, vasodilatition, selon zone et dose, 
- Stylo à insuline (pompe si échec)
- Schéma : analogue lent (1-2/j) et analogue rapide (3-4)
- dose "pour vivre", "pour manger", "éour traiter", activité physique \thus
  éducation nutritionnelle

Effets secondaires : hypoglycémie, prise de poids légère, allergie rarissime,
lipoatrophie insulinique (immuno), lipohypertrophie si piqûres au même endroit

Non insulinique : accompagnement, alimentation variée sans interdits, exercice physique

*** Cas particuliers
Enfant/ado : 
- cétoacidoses fréquentes (risque d'oedème cérébral \inc si réa).
- difficile à équilibrer et accepter chez l'ado
- pompe chez très petit enfant

Femme :
- dépister diabète 1 pendant grossesse
- contraception à discuter : pilule oestrogestative possible si \female jeune,
  sans complication, non fumeuses, diabète bien équilibré
- qrossesse : pronostic quasi normal si équilibre dès conception
  jusqu'accouchement et non compliqué. Analogue de l'insuline. Attention : HbA1c
  \dec , \inc besoin fin grossesse et \dec post-partum, aggravation rétinopathie
  et néphropatie
- CI absolue : insuf coronaire instable
- HbA1c < 6.5%, glycémie jeun < 0.9g/L
  
Ménopause : hormonothérapie seulement si médicalement indiqué

Jeûne : 
- si intolérance gastrique : pas d'arrêt insuline, collations
liquide/hospit. Vérifier cétonurie
- pour examen à jeun : laisser agir analogue lent, surveiller glycémie
- prolongé/stress : soluté glucosé et insuline en IV
  
** Diabète 2
90% de diabète. Prévalence 4%. À risque : obèse, anomalie métabolisme
glucidique, ATCD familiaux diabète 2, ethnie noire hispanique.
Age adulte.

*** Physiopatho
Insuline n'arrive pas à avoir une réponse amximale : défaut de captation
musculaire du glucose, \inc production hépatique du glucose, lipolyse \inc acides gras
libres circulants \thus (aggrave \dec insulinosécrétion et utilisation du glucose)

Insuf de sécrétion d'insuline, s'aggrave avec l'âge et la durée

Facteurs génétique. Hyperglycémie aggrave insulinosécrétion,
insulino-résistance. \Dec sécrétion adiopkines

*** Cliniques
Signes secondaires hyperglycémie, souvent inaperçus. Décompression sévères \thus
polyurie, polydispie, amaigrissement, prurit vulvaire/balanite, infections
récidivantes

Dépistage : si
- glycémie veineuse à jeun pour : signes cliniques de diabètes, > 45 ans (tous les 3 ans), \ge 1 FR
- non caucasien/migrant, sd métabolique [fn:30]
 
DD : diabète 1 lent (LADA) (minceur, 0 ATCD, IA2 et GAD positifs), génétique
(MODY2, mitochondrial), secondaire (pancréatopathie, hémochromatose,
mucoviscidose, médicaments)

Évolution : insulinopénie -> insulinoréquerant. Pronostic selon complications.

*** Traitement 
Objectifs : normalisation HbA1c (< 6.5%), améliorer gylcémie, insulinosensibilité
Moyens  : activité physique, régime (hypocalorique si surpoids) sans sucres
rapides, traitement oraux, analogues GLP-1, insuline

Ttt oral :
- biguanide (Metformine) +++ : ES = digestif. CI = insuf rénale (?), hépatique, respiratoire
- autres sulfamides, glinides, inhibiteurs DPP-4, inhibiteurs \alpha-glucosidase
  
Surveillance glycémique :
- HbA1c essentielle : < 7% pour plupart des patients (8% si comorbidité grave,
  âgé farigle, ATCD complication macrovasc, insuf rénale chronique sévère, 9% si
  agé dépendante)
- autosurveillance glycémique : pas systématique si ttt oral (1-3 cycles/j),
  nécessaire si insuline

PEC
* Footnotes

[fn:30] IMC > 28 kg/m^2, HTA, (HDL < 0.35g/L ou
  TG > 2g/L ou dyslipidémie traitée), ATCD diabète familial/gestionnel,
  temporairement induit

[fn:29] Hémoglobinopathie, anémie hémolytique, urémie, EPO, saignées

[fn:28] De temps en temps 3h matin, postprandial

[fn:27] Latent Autoimmune Diabetes in the Adult

[fn:26] Dyspnée de Kussmaul, haleine acétonique

[fn:25] Normale à jeune < 1.10g/L

[fn:24] S'associe souvent à d'autres insuffisances de l'axe hypothalamo-hypophysaire

[fn:23] \danger élimiiner phéochromocytomes avant biopsie surrénale

[fn:22] Surrénalectomie bilatére, anticortisolique de synthèse, nécrose hémorragique 

[fn:1] $\frac{N}{N_e/10}\times 100$ avec N = nb grossesses
accidentelles, $N_e$ nombres de mois d'exposition

[fn:2] Sd des ovaires polykystiques

[fn:3] Séborrhéee, acné, hirsutisme, \inc testostérone

[fn:4] Transmission mère-fils. Expansion instable des triplets CGG jusqu'à
l'absence de transcript de FMR1 (Fragile X Mental Retardation 1). \\
\danger Risque d'IOP pour la pré-mutation seulement \thus dépister chez
\female + IOP < 40 ans par PCR et Southern Blot

[fn:5] \danger Testostérone, FSH, LH interprétables [6mois, puberté]

[fn:6] Percutané, transdermique : limite \inc facteur de coagulation.

[fn:7] Baisse libido, testostérone totale < 3 ng/mL

[fn:8] Marathon, danse classique, demi-fond, triathlone, gymnastique, cyclisme

[fn:9] Oestrogènes, raloxifène, bisphosphonates

[fn:10] Cinacalcet

[fn:11] Faire bilan hormonal : natrémie, testostérone totale et libre/ostradiol,
FSH, LH, T4L, TSH, prolactine

[fn:12] adénome hypophysaire 90%, méningiome, craniopharyngiome, patho
inflammatoires infiltratives

[fn:13] Coefficient de saturation de la transferrine

[fn:15] -5mmHg si automesure. -10mmHg si MAPA sur 14h

[fn:16] Antagonistes des récepteurs de l'angiotensine II

[fn:17] Adénopathie

[fn:18] Thyroglobuline

[fn:19] Cancer

[fn:20] Asthénie, somnolence, hypothermie, frilosité, constipation, bradycardie,
prise poids modeste

[fn:21] Clinique discrète : ictère prolongé, constipation, hypotonie, pleurs
rauques, difficulté succin, fontanelles larges, hypothermie

[fn:14] Hépatomégali stéatosique, douleurs abdo, xanthomatose éruptive, lipémie rétinienne
