#+title: Fiches d'endocrinologie
#+author: Alexis Praga
#+latex_header: \usepackage{booktabs}
#+latex_header: \input{header}

* 35 : Contraception
** Contraception hormonale
Oestroprogestatifs
- Contient {oestrogène, progestatif (gen 1,2 ou 3), autres progestatif}
- Administration orale, transdermique ou vaginale
- Action : {pas d'ovulation, endomètre peu à apte à la nidation, glaire
  cervicale imperméable aux spermatozoïdes}
Progestatifs seuls 
- Microprogestatifs : action sur glaire cervicale, endomètre
- Macroprogestatifs : si CI oestroprogestatifs
- Administration : orale, injection, implant, intra-utérin (stérilet)
** Pratique
Oestroprogestatifs : 
- à commencer le premier jour des règles pendant 21j puis 7 j
d'arrêt.
- au même moment
- Si oubli < 12h, ASAP sinon contraception mécanique $\ge 7$ jours
Microprogestatifs : toujours à la même heure. Si oubli < 3h, ASA, sinon
contraception mécanique $\ge 7$ jours
Macroprogestatifs : ccommencer le 5eme jour du cycle

** Contre-indications
Oestroprogestatifs : absolues =
- thromboemboliques veineux/artériels, prédisposition thromboses
- lupus évolutif, connectivites, porphyries
- vasc, cardiaque, cérébrales, oculaires
- valvulopathie, troubles rythmes thrombogènes
- HTA non contrôlée
- diabète et micro/macroangiopathie
- tumeur hormono-dépendantes (sein, utérus...)
- hépatiques sévères
- hémorragies génitales non diagnostiquées
- (tumeurs hypophysaires)
Macro/microprogestatifs : cancers {sein, endomètre}, insuf hépatique, accident
TEV récents

** Recommandation
Sans CI, oestroprogestatif minidosé et progestatif 2eme génération monophasique
(Minidril)

** Efficacité
Indice de Pearl[fn:1] < 0.07% pour oestroprogestatif
(< 2% pour les microprogestatifs)

Attention : certains inducteurs enzymatiques réduisens l'efficacité (ou
millepertuis).

Ado : sous- ou mal utilisée

** Tolérance
Oestroprogestatifs :
- bien tolérée, pas de perte de poids
- surveiller métabolisme
- active coagulation mais \inc fibrinolyse. Légère augmentation du risque
  d'accident TEV
- vasc : faible \inc PA
- cancer : ovaire = risque -50%, idem pour l'endomètre, faible \inc pour sein
Microprogestatifs : troubles des règles (spotting, aménorrhées), grossesse
extra-utérine

Macroprogestatifs : hypoestrogénie, aménorrhées, spotting

** Surveillance
Consulter si céphalée, déficit sensitivomoteur, (douleur ou oedème) MI, dyspnée,
douleur thoracique

Examen clinique : 
- préthérapeutique : gynéco, frottis cervico-vaginal dès 25 ans si
  asymptomatique.
- PA à +3mois puis tous 6 mois
- hyperoestrogénie (tension mammaire), hypoestrogénie (sécheresse vaginale)
Biologie : cholestérol total, triglycérides, glycémie à jeun à +3mois. Si FR, le
faire avant (!) prescription

Gynéco : métroragies, spottings. NB frottis cervico-utérin dès 25 ans (+1 an pui
tous 3 ans) indépendamment contraception

** Femmes à risques
Diabétique :
- non hormonale : si diabète 1 > 15 ans ou micro/macroangiopathie \thus locale
  (nullipare, peu de rapports) ou intra-utérin (multipare, diabète équilibré)
- hormonale :pas d'oestropregestatifs si {tabac, non équilibré, HTA, surpoids,
  diabète compliqué} \thus progestatif
Dyslipidémie : oestroprogestatif si < 3g/L cholestérol total, triglycérides <
9g/L

Thrombose veineuse
- prédisposant : anomalies de l'hémostase (génétique, acquises), ATCD familiaux
- dépistage : thrombose, multiples fausses couches, ATCD thrombose < 45 ans
- acétate de chlormadinone, CI oestrogène

Autres :
- HTA : oestroprogestatifs si 0 FR
- tabac = CI, migraine \land{} vascularite = spécialiste

** Urgence
- lévonorgesttrel ASAP < 72h
- ulipristal acétate ASAP < 120h mais 3x plus cher

* 37 : Stérilité du couple
Infertile : 0 grossesses après 1 an de rapports non protégés. Stérilité si
définitf.

Stérilité = partagée !!

** Interrogatoire
- Couple
- Femme : âge++ (détérioration après 35 ans), {grossesses antérieure,
  avortements}, infections/curetages++, ATCD chir/infectieux, douleurs
  pelviennes (rapports, règles), conditions de vie, radio/chimio
- Homme : trouble libido/érection, ATCD cryptorchidie/trauma testiculaire, ATCD
  chir pelvienne/scrotale, ATCD médicaux (oreillons++), tabac/anabolisants...

** Examen clinique
- \female : âge++, obésité/maigreur, tour taille et hanche, pilosité, PA,
  galactorrhé provoqué, gynéco.
  - Si anovulation (a-/oligo-ménorrhée) : hyperprolactinémie, hyperandrogénie,
    troubles comportement alimentaire, bouffées chaleur
- \male : IMC, pilosité, hypoandrisme, cicatrice chir, varicocèle,
  gynémocomastie, gynoïde/enuchoïde
  - volume testiculaire++, palpation cordospermatiques

** Examens complémentaires
Premiere intention, femme
- Hormonale++ : oestradiole, LH, FSH, prolactine plasmatique. Puis progestérone
plasmatique (si cycle réguliers)
- Écho ovarienne++
- Hystérographie++
Première intention, homme :
- spermogramme++ (concentration, mobilité, morphologie. Attention aux
  variabilités !
- hormonale++ si oligo-/azoo-spermie : testostérone, LH, FSH puir SHBG
Test poist-coïtal (discuté)

** Étiologie
Femme :
- anovulation : très fréquent ! Souvent aménorrhées ou irrégularités. Causes :
  sd des ovaires polymicrokystiques, hyperprolactinémie, insuf ovarienne
  primitive, déficit gonadotrope, psycho-nutritionnel
- obstacle mécanique :
  - anomalie du col utérin et insuf glaire cervilaie : post-conisation/curetage
  - obstacle, anomalie utérie : manoeuvres post-partum, polypes muqueux... \thus
    echographie
  - obstacle tubaire : cause majeure++. Souvent salpingite (Chlamydia++)
- Endométriose : rarement si modéré. hypstérosalpingographie pui coelioscopie
Homme :
- azoospermie 
  - sécrétoire : diagnostic = volume testiculaire < 10ml, concentration FSH
    faible
 \thus caryotype, analyse bras long Y, écho testiculaire (élimine
    cancer), déficit gonadotrope (rare)
  - obstructive : volume et concentration ormale, volume séminal \dec \thus
    examen clinique
    - cause congénitale : agénésie bilat des canaux déférent++ (soit anomalie
      biallélique gène CFTR, soit isolée)
    - acquis : infectieux  (gonocoque, tuberculose, Chlamydia) \thus échographie
  - exploration chir testiculaire et des voies excrétrices : si azoospermie
    confirmée par plusieurs spermogrammes, bilan génétique
- oligo-asthéno-térato-spermie : \dec nombre, mobilité, \inc hormes anormales
  \thus caryotype, brang long Y. Traitement = assistance médicale procréation
* 40 : Aménorrhée
Déf: absence de cycle menstruel après 16 ans (primaire) ou interruption chez
femme réglée (secondaire). Physiologique : grossesse, lactation, ménopause

Tout arrêt > 1 mois \thus enquête étiologique \danger

Atteinte de l'axe hypothalamo-hypophysio-ovarien ou anomalie tractus utérin

*Pas de traitement oestrogénique sans enquête étiologique*

** Conduite
*** Primaire
Forte proba de cause génétique/chromosomique. Chercher carences nutritionnelle

- Si absence de dév. puberture : doser FSH, LH
  - Si basses, tumeur hypothalamo-hypophysaire, dénutrition ou génétique : {sd
    de Kalmann (anosmie), mutation récepteur GnRH (rare), atteinte
    gonadotrophines (exceptionnels), mutation LH}
  - Si hautes : sd de Turner (caryotique 45, XO),
- Examen gynéco, écho pelvienne
  - Pas d'utérus : sd de Rokitanski, tissu testiculaire dans les canaux
    inguinaux (CAIS)
  - ambiguité OGA : dysgénésie gonadique, hyperplasie congénitale surrénales,
    anomalies sensibilité/biosynthèse androgènes
*** Secondaire 
Souvent acquises. 

Interrogatoire : médic, maladie endoc/chronique,
gynoc/obstétriques, insuf ovarienne (bouffées de chaleur). Douleurs pelviennes
cycliques : cause utérine

Examen clinique : 
- poids et taille (carence nutritionnelle
- hyperandrogénie : sd ovaires polykystiques, déficit 21-hydroxylase, (sd
  Cushing)
- carence oestrogénique : pas de glaire +2 semainesa après saignement \thus
  anovulation
- pas de signe d'appel : enquête nutritionnelle

Dosages hormonaux :
- hCG : grossesse
- prolactine \inc : médciament ou tumeux hypothalamo-hypophysaire (ou adénome)
- FSh \inc, estradiol \dec : insuf ovarienne primitive
- estradiol, LH, FSH basse : hypothalamo-hypophysaire ou nutritionnelle
- testostérone : tumeur surrénalienne/ovarienne
- sinon SOPK[fn:2]

** Causes

*** Déficit gonadotrope organique/fonctionnel

**** Hypothalamus, prolactine normales
Hypothalamus n'arrive pas à libérer la GnRH au bon rythme. 

Atteintes organiques : tumeur/infiltration \thus IRM
- macroadénomes hypophysaires, craniopharyngiomes
- chercher hyperprolactinémie, insuf antéhypophysaire associé

Atteintes fonctionnelles : apports nutritionnels insufissants par rapport à l'activité physique intense+++
**** Hypothalamo-hypophysaire dû à une hyperprolactinémie
Cause majeure

Médicaments ou tumeurs \thus pas de traitement dopaminergique sans imagerie \danger
**** Autres
- Endocrinopathies : sd de Cushing, dysthyroïdes déficits 21-hydroxylase
- Hypophysaire (rare) : auto-immune (majorité), sd de Sheehan (très rare, nécrose hypophysaire post-partum)
*** Anovulation non hypothalamique
**** SOPK (majorité)
 Pas de pic de LH, ni de progestérone. Oestradiol mais non cycliques

Irrégularité menstruelles, puis aménorrhées avec acné, hirsutisme

Diagnostic :
- 2 parmi : {hyperandrogénie clinique[fn:3], oligo-/a-novulation, hypertrophie
  ovarienne (écho)}
- exclure bloc 21-hydroxylase, tumeur de l'ovaire, sd Cushing
- exclure hyperprolactinémie

Diagnostic parfois difficile :
- sans hyperandrogénie \thus écho
- {atteinte partielle axe gonadotrope, macroprolactinémie} peuvent y ressembler

Acné : cherche hyperandrogénie, régularité cycle menstruel \thus éliminer
hyperplasie congénitale des surrénales

2 causes :
- tumeur ovarienne ou résistance insuline
  - virilisation si tumeur
  - imagerie si testostérone > 1.5ng/mL. Si normale, cherche hypothécose
    (obésité morbide androïde, acanthosis nigricans, insulino-résistance)
- pathologie surrénale :
  - sd de Cushing si signes hypercortisolisme \thus cortisol libre urinaier et
    freinage minute
  - tumeur surrénale \thus scanner des surrénales
  - déficit enzymatique en 21-hydroxylase (\danger formes tardives qui peuvent
    mimer SOPK)
*** Insuf ovarienne primitive
\inc FSH

Causes :
- chir, chimio, radiothérapie
- anomalie caryotype (sd Turner)
- anomalie gènes /FMR1/ (sd X fragile)[fn:4]
- auto-immune
*** Anomalie utérine
**** Congénitales :
Si dév pubertaire normale et douleurs pelviennes cycliques, imperfortanio
hyménéale/malformation vaginale \thus examen gynéco.\\
Idem sans douleurs \thus agénésie utérus ?

Difficulté : différence agénésie mullérienne isolée (46,XX)- anomalies androgènes
(46,XY) \thus testostérone
**** Secondaires :
Synéchies utérines (trauma de l'utérus), tuberculose utérine
* 47 : Puberté
** Normale
~4 ans, acquisition de la taille définitive, fonction de
reproduction. Classification de Tanner (5 stades)

\female : seins ~11 ans [8,13]ans, règles ~13ans [10,15]

\male : \inc volume testiculaire ~11.5 [9.5,14], \inc taille verge ~12.5ans.

Accélération de la croissance : 5 -> 8cm (163cm) \female, 5-10cm (175cm)
** Retards 
\male :  volume testiculaire < 4mL ou longeur < 25mm > 14 ans 

\female : pas de seins à 13 ans, pas de règles à 15 ans

Centrale ou périphérique ?
- centrale : congénital (pas de cassure de croissance, micropénise,
  cryptorchidie), acquis (tumeur ?), "fonctionnel" (maladie générale, trouble
  comportement alimentaire), isolé
- périphérique : sd de Turner chez \female, sd Klinefelter \male
- retard simple (élimination)

Clinique : 
- parents, grossesse, courbe de croissance. Chercher trbles digestifs,
polyuro-polydispise, céphalée, anomalies champ visuel
- pathologie acquise, OGE, testicules, anosmie (Kallmann)

Âge osseux : 13 ans \male, 11 ans \female

Biologie : 
- stéroïdes sexuels, si FSH, LH basses \thus hypothalamo-hypophysaire
- testostérone chez \male, oestradial/écho chez \female

IRM indispensable ! si déficit gonadotrope (tumeur)

Caryotype si FSH élevé. Toujours chez \female de taille < -2DS avec retard
pubertaire/gonadotrophine \inc

*** Étiologies
Hypogonadotropes
- congénitaux : isolés, sd de Kallman, autres déficits hypophysaires, sd
  polymalformatifs
- acquis : tumeurs hypophysaires, post-radiothérapie 
Hypogonadotropes fonctionnels
- chroniques digestives/cardaques/respi
- sport intense
- endocrio
Hypergonadotropes
- congénitaux : sd Turner, sd Klinefelter, autres atteintes primitevs
- acquis : castration, trauma, oreillons, chimio/radio

***  Traitement
Cause si possible. Sinon doses \inc de testostérone (\male) ou oestrogènes puis
oestroprogestatif (\female)
** Précoces
Avant 8ans \female ou 9.5 ans \male
*** Centrales
8x plus fréquent chez \female que \male. Chez \female, causes
idiopathiques. Chez \male, causes tumorales à 50\%

Clinique : 
- dév prématuré harmoniaux (pas de règles chez \female)
- crises de rires (harmatome hypothalamique), tâches cutanées (neurofibromatose
  I ou sd McCune-Albright)
Biologie :
- testostérone élevée chez \male mais variabilité d'oestradiol chez \female

IRM hypothalamo-hypophysaire indispensable \danger (petite taille
définitive). Écho pelvienne pour \female

Traitement si risque de petite taille adulte : analogues GnRH jusque âge normal
de puberté
*** Périphériques
Clinique : \inc vitesse de croissance, avance maturation osseusse

Stéroïdes élevées, LH et FSH bas. Écho pelvienne chez fille

Étiologie :
- tumeurs ovarienne (rares) : écho puis histologies
- kystes folliculaires : bénins, régression spontanée possible
- sd McCune-Albright : {puberté précoce ovarienne, taches cutanées
  "café-au-lait", dysplasie fibreuses os}. \danger tableau pas toujours complet
  !\\
Oestradiol élevé, gonadotrophines basses, écho = utérus stimulé, kystes
ovariens. Dominance \female
- médicaments
- testotoxicose (rare, cellule de Leydig activé et LH basses), adénome leydigien
  (très rare)
- tumeurs à hCG (\male)
*** Avances dissociées
- Isolé des seins : beaucoup de filles [3mois, 3 ans]
- Métrorragies isolées : chercher vulvite, vulvovaginite, prolapsus urétrale,
  corps étranger. Éliminter kyste ovarien, sd McCune-Albright par l'absence des
  sein
\thus écho pelvienne
- Pilosité pubienne isolée : chercher forme d'hyperplasie congénitale des
  surrénales (\inc 17-hydroxyprogestérone, stimulation ACTH), prémature pubarche
  (élimination !)

* Footnotes

[fn:4] Transmission mère-fils. Expansion instable des triplets CGG jusqu'à
l'absence de transcript de FMR1 (Fragile X Mental Retardation 1). \\
\danger Risque d'IOP pour la pré-mutation seulement \thus dépister chez
\female + IOP < 40 ans par PCR et Southern Blot

[fn:3] Séborrhéee, acné, hirsutisme, \inc testostérone

[fn:2] Sd des ovaires polykystiques

[fn:1] $\frac{N}{N_e/10}\times 100$ avec N = nb grossesses
accidentelles, $N_e$ nombres de mois d'exposition

