#+title: Fiches d'endocrinologie
#+author: Alexis Praga
#+latex_header: \usepackage{booktabs}
#+latex_header: \input{header}

* 35 : Contraception
** Contraception hormonale
Oestroprogestatifs
- Contient {oestrogène, progestatif (gen 1,2 ou 3), autres progestatif}
- Administration orale, transdermique ou vaginale
- Action : {pas d'ovulation, endomètre peu à apte à la nidation, glaire
  cervicale imperméable aux spermatozoïdes}
Progestatifs seuls 
- Microprogestatifs : action sur glaire cervicale, endomètre
- Macroprogestatifs : si CI oestroprogestatifs
- Administration : orale, injection, implant, intra-utérin (stérilet)
** Pratique
Oestroprogestatifs : 
- à commencer le premier jour des règles pendant 21j puis 7 j
d'arrêt.
- au même moment
- Si oubli < 12h, ASAP sinon contraception mécanique $\ge 7$ jours
Microprogestatifs : toujours à la même heure. Si oubli < 3h, ASA, sinon
contraception mécanique $\ge 7$ jours
Macroprogestatifs : ccommencer le 5eme jour du cycle

** Contre-indications
Oestroprogestatifs : absolues =
- thromboemboliques veineux/artériels, prédisposition thromboses
- lupus évolutif, connectivites, porphyries
- vasc, cardiaque, cérébrales, oculaires
- valvulopathie, troubles rythmes thrombogènes
- HTA non contrôlée
- diabète et micro/macroangiopathie
- tumeur hormono-dépendantes (sein, utérus...)
- hépatiques sévères
- hémorragies génitales non diagnostiquées
- (tumeurs hypophysaires)
Macro/microprogestatifs : cancers {sein, endomètre}, insuf hépatique, accident
TEV récents

** Recommandation
Sans CI, oestroprogestatif minidosé et progestatif 2eme génération monophasique
(Minidril)

** Efficacité
Indice de Pearl[fn:1] < 0.07% pour oestroprogestatif
(< 2% pour les microprogestatifs)

Attention : certains inducteurs enzymatiques réduisens l'efficacité (ou
millepertuis).

Ado : sous- ou mal utilisée

** Tolérance
Oestroprogestatifs :
- bien tolérée, pas de perte de poids
- surveiller métabolisme
- active coagulation mais \inc fibrinolyse. Légère augmentation du risque
  d'accident TEV
- vasc : faible \inc PA
- cancer : ovaire = risque -50%, idem pour l'endomètre, faible \inc pour sein
Microprogestatifs : troubles des règles (spotting, aménorrhées), grossesse
extra-utérine

Macroprogestatifs : hypoestrogénie, aménorrhées, spotting

** Surveillance
Consulter si céphalée, déficit sensitivomoteur, (douleur ou oedème) MI, dyspnée,
douleur thoracique

Examen clinique : 
- préthérapeutique : gynéco, frottis cervico-vaginal dès 25 ans si
  asymptomatique.
- PA à +3mois puis tous 6 mois
- hyperoestrogénie (tension mammaire), hypoestrogénie (sécheresse vaginale)
Biologie : cholestérol total, triglycérides, glycémie à jeun à +3mois. Si FR, le
faire avant (!) prescription

Gynéco : métroragies, spottings. NB frottis cervico-utérin dès 25 ans (+1 an pui
tous 3 ans) indépendamment contraception

** Femmes à risques
Diabétique :
- non hormonale : si diabète 1 > 15 ans ou micro/macroangiopathie \thus locale
  (nullipare, peu de rapports) ou intra-utérin (multipare, diabète équilibré)
- hormonale :pas d'oestropregestatifs si {tabac, non équilibré, HTA, surpoids,
  diabète compliqué} \thus progestatif
Dyslipidémie : oestroprogestatif si < 3g/L cholestérol total, triglycérides <
9g/L

Thrombose veineuse
- prédisposant : anomalies de l'hémostase (génétique, acquises), ATCD familiaux
- dépistage : thrombose, multiples fausses couches, ATCD thrombose < 45 ans
- acétate de chlormadinone, CI oestrogène

Autres :
- HTA : oestroprogestatifs si 0 FR
- tabac = CI, migraine \land{} vascularite = spécialiste

** Urgence
- lévonorgesttrel ASAP < 72h
- ulipristal acétate ASAP < 120h mais 3x plus cher

* 37 : Stérilité du couple
Infertile : 0 grossesses après 1 an de rapports non protégés. Stérilité si
définitf.

Stérilité = partagée !!

** Interrogatoire
- Couple
- Femme : âge++ (détérioration après 35 ans), {grossesses antérieure,
  avortements}, infections/curetages++, ATCD chir/infectieux, douleurs
  pelviennes (rapports, règles), conditions de vie, radio/chimio
- Homme : trouble libido/érection, ATCD cryptorchidie/trauma testiculaire, ATCD
  chir pelvienne/scrotale, ATCD médicaux (oreillons++), tabac/anabolisants...

** Examen clinique
- \female : âge++, obésité/maigreur, tour taille et hanche, pilosité, PA,
  galactorrhé provoqué, gynéco.
  - Si anovulation (a-/oligo-ménorrhée) : hyperprolactinémie, hyperandrogénie,
    troubles comportement alimentaire, bouffées chaleur
- \male : IMC, pilosité, hypoandrisme, cicatrice chir, varicocèle,
  gynémocomastie, gynoïde/enuchoïde
  - volume testiculaire++, palpation cordospermatiques

** Examens complémentaires
Premiere intention, femme
- Hormonale++ : oestradiole, LH, FSH, prolactine plasmatique. Puis progestérone
plasmatique (si cycle réguliers)
- Écho ovarienne++
- Hystérographie++
Première intention, homme :
- spermogramme++ (concentration, mobilité, morphologie. Attention aux
  variabilités !
- hormonale++ si oligo-/azoo-spermie : testostérone, LH, FSH puir SHBG
Test poist-coïtal (discuté)

** Étiologie
Femme :
- anovulation : très fréquent ! Souvent aménorrhées ou irrégularités. Causes :
  sd des ovaires polymicrokystiques, hyperprolactinémie, insuf ovarienne
  primitive, déficit gonadotrope, psycho-nutritionnel
- obstacle mécanique :
  - anomalie du col utérin et insuf glaire cervilaie : post-conisation/curetage
  - obstacle, anomalie utérie : manoeuvres post-partum, polypes muqueux... \thus
    echographie
  - obstacle tubaire : cause majeure++. Souvent salpingite (Chlamydia++)
- Endométriose : rarement si modéré. hypstérosalpingographie pui coelioscopie
Homme :
- azoospermie 
  - sécrétoire : diagnostic = volume testiculaire < 10ml, concentration FSH
    faible
 \thus caryotype, analyse bras long Y, écho testiculaire (élimine
    cancer), déficit gonadotrope (rare)
  - obstructive : volume et concentration ormale, volume séminal \dec \thus
    examen clinique
    - cause congénitale : agénésie bilat des canaux déférent++ (soit anomalie
      biallélique gène CFTR, soit isolée)
    - acquis : infectieux  (gonocoque, tuberculose, Chlamydia) \thus échographie
  - exploration chir testiculaire et des voies excrétrices : si azoospermie
    confirmée par plusieurs spermogrammes, bilan génétique
- oligo-asthéno-térato-spermie : \dec nombre, mobilité, \inc hormes anormales
  \thus caryotype, brang long Y. Traitement = assistance médicale procréation
* 40 : Aménorrhée
Déf: absence de cycle menstruel après 16 ans (primaire) ou interruption chez
femme réglée (secondaire). Physiologique : grossesse, lactation, ménopause

Tout arrêt > 1 mois \thus enquête étiologique \danger

Atteinte de l'axe hypothalamo-hypophysio-ovarien ou anomalie tractus utérin

*Pas de traitement oestrogénique sans enquête étiologique*

** Conduite
*** Primaire
Forte proba de cause génétique/chromosomique. Chercher carences nutritionnelle

- Si absence de dév. puberture : doser FSH, LH
  - Si basses, tumeur hypothalamo-hypophysaire, dénutrition ou génétique : {sd
    de Kalmann (anosmie), mutation récepteur GnRH (rare), atteinte
    gonadotrophines (exceptionnels), mutation LH}
  - Si hautes : sd de Turner (caryotique 45, XO),
- Examen gynéco, écho pelvienne
  - Pas d'utérus : sd de Rokitanski, tissu testiculaire dans les canaux
    inguinaux (CAIS)
  - ambiguité OGA : dysgénésie gonadique, hyperplasie congénitale surrénales,
    anomalies sensibilité/biosynthèse androgènes
*** Secondaire 
Souvent acquises. 

Interrogatoire : médic, maladie endoc/chronique,
gynoc/obstétriques, insuf ovarienne (bouffées de chaleur). Douleurs pelviennes
cycliques : cause utérine

Examen clinique : 
- poids et taille (carence nutritionnelle
- hyperandrogénie : sd ovaires polykystiques, déficit 21-hydroxylase, (sd
  Cushing)
- carence oestrogénique : pas de glaire +2 semainesa après saignement \thus
  anovulation
- pas de signe d'appel : enquête nutritionnelle

Dosages hormonaux :
- hCG : grossesse
- prolactine \inc : médciament ou tumeux hypothalamo-hypophysaire (ou adénome)
- FSh \inc, estradiol \dec : insuf ovarienne primitive
- estradiol, LH, FSH basse : hypothalamo-hypophysaire ou nutritionnelle
- testostérone : tumeur surrénalienne/ovarienne
- sinon SOPK[fn:2]

** Causes

*** Déficit gonadotrope organique/fonctionnel

**** Hypothalamus, prolactine normales
Hypothalamus n'arrive pas à libérer la GnRH au bon rythme. 

Atteintes organiques : tumeur/infiltration \thus IRM
- macroadénomes hypophysaires, craniopharyngiomes
- chercher hyperprolactinémie, insuf antéhypophysaire associé

Atteintes fonctionnelles : apports nutritionnels insufissants par rapport à l'activité physique intense+++
**** Hypothalamo-hypophysaire dû à une hyperprolactinémie
Cause majeure

Médicaments ou tumeurs \thus pas de traitement dopaminergique sans imagerie \danger
**** Autres
- Endocrinopathies : sd de Cushing, dysthyroïdes déficits 21-hydroxylase
- Hypophysaire (rare) : auto-immune (majorité), sd de Sheehan (très rare, nécrose hypophysaire post-partum)
*** Anovulation non hypothalamique
**** SOPK (majorité)
 Pas de pic de LH, ni de progestérone. Oestradiol mais non cycliques

Irrégularité menstruelles, puis aménorrhées avec acné, hirsutisme

Diagnostic :
- 2 parmi : {hyperandrogénie clinique[fn:3], oligo-/a-novulation, hypertrophie
  ovarienne (écho)}
- exclure bloc 21-hydroxylase, tumeur de l'ovaire, sd Cushing
- exclure hyperprolactinémie

Diagnostic parfois difficile :
- sans hyperandrogénie \thus écho
- {atteinte partielle axe gonadotrope, macroprolactinémie} peuvent y ressembler

Acné : cherche hyperandrogénie, régularité cycle menstruel \thus éliminer
hyperplasie congénitale des surrénales

2 causes :
- tumeur ovarienne ou résistance insuline
  - virilisation si tumeur
  - imagerie si testostérone > 1.5ng/mL. Si normale, cherche hypothécose
    (obésité morbide androïde, acanthosis nigricans, insulino-résistance)
- pathologie surrénale :
  - sd de Cushing si signes hypercortisolisme \thus cortisol libre urinaier et
    freinage minute
  - tumeur surrénale \thus scanner des surrénales
  - déficit enzymatique en 21-hydroxylase (\danger formes tardives qui peuvent
    mimer SOPK)
*** Insuf ovarienne primitive
\inc FSH

Causes :
- chir, chimio, radiothérapie
- anomalie caryotype (sd Turner)
- anomalie gènes /FMR1/ (sd X fragile)[fn:4]
- auto-immune
*** Anomalie utérine
**** Congénitales :
Si dév pubertaire normale et douleurs pelviennes cycliques, imperfortanio
hyménéale/malformation vaginale \thus examen gynéco.\\
Idem sans douleurs \thus agénésie utérus ?

Difficulté : différence agénésie mullérienne isolée (46,XX)- anomalies androgènes
(46,XY) \thus testostérone
**** Secondaires :
Synéchies utérines (trauma de l'utérus), tuberculose utérine
* 47 : Puberté
** Normale
~4 ans, acquisition de la taille définitive, fonction de
reproduction. Classification de Tanner (5 stades)

\female : seins ~11 ans [8,13]ans, règles ~13ans [10,15]

\male : \inc volume testiculaire ~11.5 [9.5,14], \inc taille verge ~12.5ans.

Accélération de la croissance : 5 -> 8cm (163cm) \female, 5-10cm (175cm)
** Retards 
\male :  volume testiculaire < 4mL ou longeur < 25mm > 14 ans 

\female : pas de seins à 13 ans, pas de règles à 15 ans

Centrale ou périphérique ?
- centrale : congénital (pas de cassure de croissance, micropénise,
  cryptorchidie), acquis (tumeur ?), "fonctionnel" (maladie générale, trouble
  comportement alimentaire), isolé
- périphérique : sd de Turner chez \female, sd Klinefelter \male
- retard simple (élimination)

Clinique : 
- parents, grossesse, courbe de croissance. Chercher trbles digestifs,
polyuro-polydispise, céphalée, anomalies champ visuel
- pathologie acquise, OGE, testicules, anosmie (Kallmann)

Âge osseux : 13 ans \male, 11 ans \female

Biologie : 
- stéroïdes sexuels, si FSH, LH basses \thus hypothalamo-hypophysaire
- testostérone chez \male, oestradial/écho chez \female

IRM indispensable ! si déficit gonadotrope (tumeur)

Caryotype si FSH élevé. Toujours chez \female de taille < -2DS avec retard
pubertaire/gonadotrophine \inc

*** Étiologies
Hypogonadotropes
- congénitaux : isolés, sd de Kallman, autres déficits hypophysaires, sd
  polymalformatifs
- acquis : tumeurs hypophysaires, post-radiothérapie 
Hypogonadotropes fonctionnels
- chroniques digestives/cardaques/respi
- sport intense
- endocrio
Hypergonadotropes
- congénitaux : sd Turner, sd Klinefelter, autres atteintes primitevs
- acquis : castration, trauma, oreillons, chimio/radio

***  Traitement
Cause si possible. Sinon doses \inc de testostérone (\male) ou oestrogènes puis
oestroprogestatif (\female)
** Précoces
Avant 8ans \female ou 9.5 ans \male
*** Centrales
8x plus fréquent chez \female que \male. Chez \female, causes
idiopathiques. Chez \male, causes tumorales à 50\%

Clinique : 
- dév prématuré harmoniaux (pas de règles chez \female)
- crises de rires (harmatome hypothalamique), tâches cutanées (neurofibromatose
  I ou sd McCune-Albright)
Biologie :
- testostérone élevée chez \male mais variabilité d'oestradiol chez \female

IRM hypothalamo-hypophysaire indispensable \danger (petite taille
définitive). Écho pelvienne pour \female

Traitement si risque de petite taille adulte : analogues GnRH jusque âge normal
de puberté
*** Périphériques
Clinique : \inc vitesse de croissance, avance maturation osseusse

Stéroïdes élevées, LH et FSH bas. Écho pelvienne chez fille

Étiologie :
- tumeurs ovarienne (rares) : écho puis histologies
- kystes folliculaires : bénins, régression spontanée possible
- sd McCune-Albright : {puberté précoce ovarienne, taches cutanées
  "café-au-lait", dysplasie fibreuses os}. \danger tableau pas toujours complet
  !\\
Oestradiol élevé, gonadotrophines basses, écho = utérus stimulé, kystes
ovariens. Dominance \female
- médicaments
- testotoxicose (rare, cellule de Leydig activé et LH basses), adénome leydigien
  (très rare)
- tumeurs à hCG (\male)
*** Avances dissociées
- Isolé des seins : beaucoup de filles [3mois, 3 ans]
- Métrorragies isolées : chercher vulvite, vulvovaginite, prolapsus urétrale,
  corps étranger. Éliminter kyste ovarien, sd McCune-Albright par l'absence des
  sein
\thus écho pelvienne
- Pilosité pubienne isolée : chercher forme d'hyperplasie congénitale des
  surrénales (\inc 17-hydroxyprogestérone, stimulation ACTH), prémature pubarche
  (élimination !)
* 48 : Cryptorchidie
** Enfant
 Localisation anormale et inaboutie du testicule. Très fréquente : 3%
 nouveaux-nés, 20% préma. 2/3 descendent spontanément à 1 an de vie

 Clinique : checher micropénis (< 2cm, hypospadias, autres)

 Explorations : endocrinienne pour toute cryptorchidie \danger
 - bilatérale : doser 17-hydroxyprogestérone chez \female virilisée pour élimire hyperplasie
   congénitale des surrénales
 - testostérone, INSL3 (cellule de Leydig), AMH, inhibine B sérique (c. de
   Sertoli), FSH, LH mesurée jusque 4-6mois[fn:5]
 - écho pour vérifier l'absece de dévirés mülleriens

 Étiologie
 - hypogonadisme hypogonadotrope congénital
 - anorchidie rare
 - si hypospade en plus, chercher dysgénésie testiculaire
 - sd polymalformatif

 Suivre l'âge de l'apparition de la puberté !

 Traitement : chir dès 2 ans, indispensable ! (risque de cancer)
** Adulte
- Risque : hypogonadisme, infertilité, cancer testicule
- Examen clinique : scrotume, gynécomastie, signes d'hypogonadisme
- Complémentaire : {FSH, LH, testostérone}, hCG si tumeur à la palpation, écho
  scrotale, spermogramme
* 51 : Retard de croissance
\danger Ne pas passer à côté de pathologies sévères

Phases : foetale (rapide, {nutrition, insuline, IGF-2}), précoce 0-3ans (rapide,
{insuline, IGF, hormones thyroïdiennes}), prépubertaire (plus lente, décroît,
{génétique, GH/IGF, hormones thyroïdiennes}), pubertaire ({stéroïdes sexuels,
GH, nutrition})

Retard statural = {taille < -2DS, ralentissements croissance, croissance <<
parents}

Prise de poids, obésite, ralentissement croissance \thus chercher
hypercorticisme, tumeux craniopharyngiome sur l'hypothalamus, hypopituitarisme

Examen :
- ATCD : taille, parents, néonatale, médicaux/chir, contexte social
- morphotype, dév. pubertaire, tous les système, psychoaffectif

** Principales causes
#+caption: Retard poid
| Maladie coeliaque             | IgA {totales, transglutamase}, fibro                   |
| Crohn                         | VS, écho anse grêle                                    |
| Mucoviscidose                 | Test sueur                                             |
| Anorexie mentale              | Courbe de poids                                        |
| Insuf rénale chroniques       | Créat, iono, explo fonctionnelles                      |
| Anémie chroniques             | NFS                                                    |
| Rachitisme hypophosphatémique | Bilan phosphocalcique                                  |
| Patho mitochondriales         | lactate/pyruvate, génétique, biopsie musc, fond d'oeil |
| Nanisme psychosocial          |                                                        |

#+caption: Retard statural
| Endocrino         | Déficit GH (congénital, acquis [tumeur]) | IRM                                 |
|                   | Hypothyroïdie                            | T4L, TSH, Ac anti-TPO               |
|                   | Hypercorticisme (iatrogène)              | Cortisol libre urinaire/à 23h, ACTH |
|                   | Déficit hormones sex.                    | Testostérone, GnRH, IRM             |
|-------------------+------------------------------------------+-------------------------------------|
| Constitutionelles | Sd Turner                                | Caryotype                           |
|                   | Sd noonan                                | Gène PTPN11                         |
|-------------------+------------------------------------------+-------------------------------------|
| Autres            | Osseuses (a-/hypo-chondroplasie)         | Radio                               |
|                   | RCIU                                     | Taille naissance                    |
|                   | Petite taille idiopathique               | Élimination                         |

- Test de stimulation de l'hormone de croissance (\danger si doute, IRM)
- Ralentissement sévère \thus bilan en urgence (craniopharyngiome, thyroïdite de
  Hashimoot) \skull
- [0, 3] ans : digestives pédiatrique (coeliaque, mucoviscidose), [3,puberté] :
  endoc constitutionnelle, à la puberté : déficit hormone, patho osseuse
- Savoir différenceier retard pubertaire syimple d'un vrai  retard

** Exploration :
- Caryotype : fille taille < -2DS ou < -1.5DS sous taille parentale moyenne
- NFS, VS, foie, rein
- IgA totales, anti-transglutaminase
- GF-1, T4L, TSH
- Radio

* 78 : Dopage
** Substances augmentant la testostérone 
- Stéroïdes anabolisant, testostérone : \inc masse musc, puissance
- Risque : thrombotique, rupture musculo-tendineuse, touble personnalité, foie,
trouble libido, adénome/cancer de la prostate
- Femmes : masculinisation, hirsutisme, acné, aménorrhée, anovulation,
  hypertrophie clitoridienne, libido exacerbée

\vspace*{0.5cm}
- Testostérone : test chromatographique + spectrométrie de masse (très sensible
  et spécifique)
- Dihydrotestostérone (DHT) : traitement gynécomastie
- Anabolisants : \inc tissu cellulaire (muscle). ES : rétention hydrosodée, HTA,
  IDM, hépatite
- hCG : diminuer épitestostérone/testostérone après dopage (IM, SC). Testée dans
  le sang ou urine.
- Anti-oestrogène : stimule production testiculaire de stéroïdes

** Hormone de croissance (GH), IGF-1
- GH \inc masse musculaire, modifie architecture sequelette, acromégalie /mais/
  pas d'effert sur volume d'activité physique. Détection difficile : approche indirecte (cascade biologique) et mesure des
forme circulante et comparaison à r-hGH
- IGF-1 mime certains effet GH

** Glucocorticoïdes, ACTH
- Glucocorticoïdes : antalgiques, psychostimulants, combativité. ES : HTA,
  oedème, rupture ligament/tendon
\danger arrêt brutal = dangereux \skull

* 120 : Ménopause et andropause
\label{sec:120}
** Ménopause
Déf: plus de règle > 1 an \pm sd climatérique, lié à une carence
oestrogénique. Vers 51 ans.

Pré-ménopause : irrégularités cycles puis dysovulation puis anovulation ~5 ans
avants.

*** Diagnostic
Clinique seulement \danger : bouffées de chaleur, \female > 50 ans. Bio
seulement si hystérectomie \thus \dec oestradiol et \inc FSH

En pratique : progestatif seul 10j/mois x3 \thus pas de saignement à l'arrêt =
diagnostic

Aménorrhée < 40 ans = pathologique !

*** Conséquences
Court terme : bouffées de chaleur, trouble sommeil/humeur, \dec sécrétions
vaginailes
Moyen terme : douleurs ostéoarticulaires, \inc perte osseuse (selon ATCD d'insuf
ovarienne prématurée, fractures no traumatique, médicaments, calcium/vit D)

Long terme :: \inc risque CV. Incertitude sur SNC

*** Traitement 
Bénéfices
- court terme : qualité de vie à +5-10 ans
- long terme :
  - prévention ostéoporose
  - cardiovasculaire et neuro = incertain
  - cancer du côlon
Risques :
- \inc cancer du sein, accident veineux thromboemboliques (mais chiffres absolus
  faibles)
- \inc AVC ischémique, lithiase bilaires

**** Thérapeutique 
- oestrogène (17\beta-oestradiol)
oral/percutané/transdermique[fn:6] 25 jours/mois
- *et* progestatif (au moins les 12 derniers jours) per os/transdermique
\danger hémorragie de privation possible. Si pendant le traitement, faire écho
pelvienne, hystéroscopie

**** CI 
Cancer du sein, endomètre, ATCD thromboembolique artériel (ischémique,
cardiopathie embolinogène) ou veineux, hémorragie génitale sans diag, hépatique

**** Mise en route
- Interrogatoire : ATCD {cancer, métabolique, vasculaire}, carence oestrogénique
- Examen physique : poids, PA, palpation seins, gynéco, frottis cervico-vaginal
- Mammograhpie !
- Cholestérol, triglycérides, glycémie

**** En pratique 
1ere intention si trouble fonctionnels importants. 2eme si risque
d'ostéoporose. Sinon au cas par cas.

**** Surveillance 
3-6mois (surdosage = douleur, tension mammaire). Puis tous les 6-12 mois,
mammographie tous les 2 ans, frottis CV tous les 3 ans.

Traitement \ge 5 ans !!

**** Alternatives
- Modulateurs spécifiques du récepteur des oestrogènes : raloxifène
- tibolone

NB : traitement local préserve tractus urogénital. Dépister FR CV. Promouvoir
exercice, calcium, vit D

** Andropause
Chez majorité des hommes mûrs/âgés en bonne santé non obèse, baisse de
testostérone inconstante (2%).

*** Démarche
 - Interrogatoire : libido, érection, énergie vitale, mobilité/activité physique
 - Examen clinique : IMC, virilisation, gynécomastie, palper testicules
 - Mesure de testostérone totale :
   - > 3.2ng/mL = normale \thus étiologies non endocrino
   - \in [2.3, 3.2] : dosier SHBG, calculer index de T libre, si bas cherche cause
   - < 2.3 ng/mL : chercher cause
*** Étiologie
Si FSH, LH élevée, insuf testiculaire primitive 
- lésionnelle : chimio, radiation, alcoolisme surtout. Autres : castration,
  torsion, orchite ourlienne
- cryptorchidie bilatérale
- chromosomique : sd Klienfelter++
- lié à sénescene, cause génétique (rare !)
Sinon hypogonadisme hypogonadotrope 
- tumeur région hypothalamo-hypophysaire : craniopharyngiome, adénome
  hypophysaire++, autres
- infiltratif : sarcoïdose, hémochromatose
- chir, radiothérapie, traumau
- hyperprolactinémie, carence nutritionnelle, Cushing, tumeur testiculaire

* 122 : Troubles de l'érection 
Nécessite : vasculaire, musculaire lisse, retour veineux, signal  nerveux,
hormonal, psychisme = fonctionnels

Déf : incapacité persistante à obtenir/maintenir érection pour rapport sexuel satisfaisant

Âge = FR (déficit neurosensorile, \inc testostérone, comorbidités)

** Conduite  diagnostique
*** Interrogatoire
- DD avec perte désire, trouble éjaculation, douleurs pendant, anomalies morphologiques
- Caractérisation : primaire/secondaire, brutal/progressif,
  permanent/situationnel, sévérité (délai trouble-consult, capacité résiduelle,
  masturbation)
- Pathologies, facteur :
    - primaire : trouble psychogène perso, complexe identitaire, trouble
      relationnel, conflit socioprof, anomalie génitale
    - secondaire : ATCD abdo-pelvien, diabète, FR CV, patho CV, neuro, trouble
      miction, endocrinopathie, troubles sommeil, traitement, déficit
      androgénique, sd dépressif, troubles addictifs
*** Clinique
- Gynécomastie, hypoandrisme, petits testicules, anomalies du pénis (La Peyronie)
- CV : HTA, pouls, souffle
- neuro : sensibilités périnée, MI
- endoc : anomalie CV
*** Bio
Glycémie, lipidique (si > 1 an), {NFS, iono, créat}, foie (si > 5 ans), déficit
androgénique

Doser prolactine, hormones thyroïdiennes

** Bilan secondaire et approfondi
Secondaire : sexo/psychologique, épreuve pharmacologique (prostaglandien,
inhibiteur de la phospohdiestérase 5)

** Étiologies
Plus fréquentes :
- vasculaire : FR = HTA
- endocrino++ : diabète
- génito-pelvien : chir pelvienne
- trauma médullaire
- neuro dégénératif
- iatrogène : antihypertenseur

** Aspects endocriniens
*** Androgènes circulants
Influe libido, intérêt sexuel. Pour l'érection . seulement spontanées !

Hypogonadisme (diag difficile) : 
- asthénie, gynécomastie, dépilation, perte force musculaire, adiposité androïde
- doser testostérone totale \pm SHBG, prolactine. FSH, LH pour l'origin (cf
  Sec. \ref{sec:120})
  
*** Hyperprolactinémie 
Tumeur hypophysaire (IRM), champ visuel si tumeur
supra-sellaire, {T4L, cortisol, IGF-1, testostérone}
\thus agoniste dopaminergique

*** Diabète
sucré = 1ere cause de trouble érectile (TE). TE fréquents chez diabètique. 

Facteurs : mal équilibré, complications, âge, ancienneté diabète

Physiopatho : neuropathie autonomie, microangiopathie \thus défaut relaxation
musculaire. Macroangiopathie \thus ischémie organes érectiles

\danger facteurs psychènes hyportants !

Diabète et TE \thus mesure testostérone systématique (hypogonadisme ?)

Clinique : 
- TE peut révéler diabète. 
- diabète et TE : cherche trouble endoc, vasc, neuro, médicament, dépression
- TE = FR d'ischémie myocardite silencieuse \danger
  
Thérapeutique : inhibiteurs des phosphodiésterases de type 5 moins efficaces

** PEC
Ttt étiologie : seulement trouble psychogène pur, chir possible, endocrino

*** Trouble endocrinien
- Si hypogonadisme confirmé par bio[fn:7] : androgène oraux/intramusc/transderm
- CI : nodule prostatique palpable, PSA > 3ng/mL
- Surveiller prostate, foie, hématocrite
  
*** Pharmacologique
- FR, Hb glyquée < 7%, psycho/sexologique
- 1ere intention : inhibiteurs des phosphodiésterases type 5 = efficaces
- Sinon apomorphine, yohimbine = peu efficace
- "Pompe" = efficace mais résistance psycho
- 2eme intention : droge vasoactive = efficace mais douleurs peniennes, priapisme
- Prothèses péniennes = dernier recours, par chirurgien spécialisé

* Footnotes

[fn:7] Baisse libido, testostérone totale < 3 ng/mL

[fn:6] Percutané, transdermique : limite \inc facteur de coagulation.

[fn:5] \danger Testostérone, FSH, LH interprétables [6mois, puberté]

[fn:4] Transmission mère-fils. Expansion instable des triplets CGG jusqu'à
l'absence de transcript de FMR1 (Fragile X Mental Retardation 1). \\
\danger Risque d'IOP pour la pré-mutation seulement \thus dépister chez
\female + IOP < 40 ans par PCR et Southern Blot

[fn:3] Séborrhéee, acné, hirsutisme, \inc testostérone

[fn:2] Sd des ovaires polykystiques

[fn:1] $\frac{N}{N_e/10}\times 100$ avec N = nb grossesses
accidentelles, $N_e$ nombres de mois d'exposition

