#+title: Ophtalmologie
#+author: Alexis Praga
#+latex_header: \usepackage{booktabs}
#+latex_header: \input{header}
#+latex_header: \usepackage[linesnumbered,ruled,vlined]{algorithm2e}
#+OPTIONS: H:4

\input{bacteries-header}
* 1 Sémiologie oculaire
** Globe
Membranes (d'avant en arrière)
- externe = {cornée (avant), conjonctive (sur sclère antérieure), sclère}
- intermédiaire (uvée) = {iris, corps ciliaires, choroïde}
- interne (rétine) = {épithelium pigmentaire, neurosensorielle (photorécepteurs,
  fibres optiques}}. NB : phototransduction = pigment visuel
  (épithelium) \rightarrow photorécepteurs (bâtonnets = {vision périphérique,
  nocturne}, cône = {détails, couleurs} \in macula)
Contenu : 
- humeur aqueuse \in chambre antérieure, évacuée dans l'angle iridocornéen. P
  normale si \le 22 mmHg.
- cristallin : biconvexe, convergente, déformation par zonule \thus accomodation
- corps vitré : 4/5e cavité oculaire \thus segment antérieur vs postérieur
Voies optiques : 
- nerf optique - chiasma - bandelettes optiques - corps genouillés externes - radiations optiques - cortex occipital
- mydriase "sensorielle"[fn:1] vs "paralytique"[fn:2]
- voie efférente sympathique : si atteinte, sd Claude-Bernard-Horner (myosis, ptosis)
Annexes
- oculomoteur : nerf IV = {oblique supérieur}, VI = {droit externe} et III =
  {droit sup, droit inf, droit médial, oblique inf}
- protection : paupière (muscle orbiculaire, tarse), conjonctive (face interne
  paupière, globe antérieur), film lacrymal
  
** Examen
Interrogatoire : 
- baisse d'acuité visuelle (BAV), fatigue visuelle, myodésopsies,
métamorphopsies, héméralopie, scotome/amputation champ visuel, 
- mode d'installation : urgente si brutal
- douleur superficielles/profondes
- diplopie mono/bi-noculaire
- évolution : aggration rapide = grave
Acuité visuelle : échelle de Monoyer (à 5m), de Parinaud (33cm)

Segment antérieur : "lampe à fente"
- conjonctive : rougeur (diffuse/localisée/culs-de-sac inférieure/avec
  sécrétions/cercle périkératique/paupière), chemosis[fn:3]
- cornée (transparence)
- iris : myosis/mydriase
- chambre antérieure : inflammation (Tyndall[fn:4], précipités rétro-cornéens,
  synéchies iridocristaliniennes), hypopion (pus), hyphéma (sang)
Pression intraoculaire par tonomètre à air pulsé. Hypertonie si \ge 22 mmHg

Gonioscopie : angle iridocornéen

Fond d'\oe{}il
- direct, indirect (apprentissage++), biomicroscopie
- aspect : pôle postérieur = {papille, vaisseaux rétitiens, macula}, rétine
  périphérique (si besoin)
- lésions : microanévrisme (points rouges), hémorragie (intravitréennes,
  prérétiniennes, sous-rétiniennes, intra-rétiniennes[fn:5]), nodules cotonneux,
  exsudats profonds, \oe{}dème papillaire[fn:6]

Oculomotricité

** Complémentaires
Fonctions visuelles
- Champ visuel :
  - sensibilité lumineuse \dec périphérie, papille = zone aveugle
  - périmétrie cinétique (Goldman : trace isoptères) ou statique (dépistage
  glaucome)
- Vision des couleurs : si dépistage anomalie congénitale (planches colorées) ou
affection acquise (Farnsworth = classer couleurs). Utile pour antipaludéens de
synthèse ou {éthambutal, isoniazide}
Angiographie du fond d'\oe{}ils : fluorescine ou vert d'indocyanine (DMLA++)

Électrophysio : électrorétinogramme (si lésion rétiniennes étendues), potentiels
évoqués visuels (cortex occipital) (SEP++), électro-oculogramme (épithelium pigmentaire)

Echographie : mode A (longueur globe oculaire) ou B (décollement rétine, corps
étranger intraoculaire, tumeur)

Tomographie en cohérence optique (OCT) : affection maculaire (trou, DMLA),
dépistage glaucome chronique

* 2 Réfraction
\OE{}il \approx 60 dioptries (cornée = 42, cristallin = 20)
Emmétrope = \oe{}il normal. Amétrope = anomalie de réfraction

Punctum remotum (PR) : point le plus éloigné visible /sans/ accomoder. Punctum
proximum (PP) = point le plus proche visible /en/ accomodant.

Acuité visuelle = $\frac{1}{\alpha}$ où \alpha = pouvoir séparateur de
l'\oe{}il. Mesurée par l'échelle de Monoyer (de loin) en 10eme (!) et de Parinaud
(de près)

** Accomodation
Amplitude \dec jusque 0 (79 ans) \thus presbytie (BAV vision de près). Compensée
par verres sphériques convexes progressifs ou implant cristallinien

Sinon, \dec vision de près par : médicaments, paralysie III, maladie générale,
spasmes de l'accomodation

** Anomalies de la réfraction
Différencier maladie de l'\oe{}il/voie optique et anomalie réfraction !

Examen : réfractomètres automatiques \thus réfraction, kératométrie[fn:7]. [fn:8]

*** Myopie 
\OE{}il trop convergent. \approx 20% population occidentale. PR à distance finie,
PP plus proche.

Types : myopie d'indice (\inc indice de réfraction), de courbure (courbure
cornée \inc) ou axile (longueur axiale \inc)

Myopie
- faible : < 6 dioptrie
- forte : > 6 dioptries ou longueur axiale \ge 26mm. Héréditaire, \in [1/10,
  5/10] /après/ correction. Complications : glaucome chronique à angle ouvert,
  cataracte, décollement de la rétine++

Correction : verres sphériques concaves.

Chirurgie par photoablation au laser ecited dimer[fn:9]. Chirugie du cristallin
possible.

*** Hypermétropie
Fréquent (enfant++). Pas assez convergent. PR = virtuel à l'arrière. Correction
par verres sphériques convexes, lentilles ou chir.

*** Astigmatisme
Rayons de courbures différents pour les méridiens. Régulier si 2 méridiens
principaux \bot.

1 point à l'infini = 2 droite perpendiculaire (= focales) \thus myopique,
hypermétropiique ou mixtes

Correction par verres cylindriques convexes/concaves, lentilles ou chir

* 3 Suivi d'un nourisson
Déficits mineurs (amétropie, strabisme) ou sévères (grave !) (milieux transparents,
  malforamtion, rétinopathie, atteintes neuro centrales)

20% d'enfant < 6 ans avec anomalie visuelle. Si non traitée, amblyopie (BAV),
définitive > 6ans !

Développement :
- 1ere semaine : réflexe lumière, RPM
- 2-4e semaine : reflexe de poursuite
- 4-12e semaine : reflexe de poursuite
- 3e mois : vision des formes
- 4-5e mois : coordinatio \oe{}il-tête-main
- > 2 ans : AV mesurable
Examens obligatoires pour {strabisme, nystagmus, anomalie organique, trouble
comportement visuel}:
- dépistage anténal (écho)
- 1ere semaine
- 4eme mois
- 9eme mois
- 2 ans
- 3-6 ans
  
Dépistage : leucocorie, glaucome congénital, malformations, infections
maternelles, maladies enfants secoués, rétinopathie des prématurés
* 4 Strabisme de l'enfant
  
Position de l'\oe{}il anormale et altération vision binoculaire. Provient d'une
perturbation de la fusion.

Conséquences :
- Si aigu : diplopie possible. Si ancien : corrigé par cerveaux \thus vision
binoculaire non acquise si strabisme dans premiers mois de vie !. Amblyopie
possible
- Perturbation vision stéréoscopie (3D)
 
Souvent dans l'enfance. 4% population. *Dépistage avant 2 ans*

** Dépistage
Jamais normal, toujours symptôme

Interrogatoire :
- date d'apparition
- horizontal : /eso-/ si convergent, /exo-/ si divergent. Vertical : /hyper-/,
  /hypo-/. Si divergent < 9 mois, examen neuroradio
- intermittent ?
- \oe{}il dominé
  
Examen : 
- motilité : strabisme paralytique ?
- segment antérieur et FO (fond d'\oe{}il) : perte transparence, patho rétinienne ? Si nystagmus : électrorétinogramme, PEV, IRM
- réfraction sous cycloplégique : amyotropie ? Hypermétropie fréuente
- acuité visuelle : amblyopie ? (> 2/10 entre 2 yeux)
- mesure de l'angle de déviation (si chir), vision binoculaire (pronostique)

** Traitement
Correction optique. Si amblyopie, occlusion de l'\oe{}il dominant (jusque 6-8ans)

Chir si angle résident avec correction. Correction optique après opération
* 5 Diplopie (binoculaire)
Binoculaire : disparaît à l'occlusion d'un \oe{}il[fn:10]. Souvent une urgence
\danger

Noyaux des nefs oculomoteurs \in tronc cérébral - racine - troncs -
muscle. Voies supranucléaire (latéralité, verticalité), internucléraires.

#+caption: Champ d'action (\danger \ne action) 
| oblique inférieur | droit supérieur |
|-------------------+-----------------|
| droit médial      | droit latéral   |
|-------------------+-----------------|
| oblique supérieur | droit inférieur |

Mouvement bilatéraux : synergie des muscles

Vision binoculaire :
- loi de Hering : même influx nerveux pour muscles antagonistes. Loi de
  Sherrington : muscle antagonistes se relachent quand muscles synergistes se
  contractent.
- si correspondance rétinienne anormale (\oe{}ux non \parallel) : diplopie
  
** Diagnostic
- Signes fonctionnels : dédoublement toujours même direction[fn:11], disparaît à
l'occlusion
- Interrogatoire : terrain, circonstance, brutal/progressif, {douleurs, vertiges,
céphalées, nausées}, {horizontale, verticale, oblique}, moment journée
- Attitude vicieuse ? Chercher déviation en position primaire par reflets
  cornéens

Examens :
- motilité
- cover-test (\oe{}il dévié puis se redresse)
- au verre rouge (dissociation point rouge et blanc)
- test de Lancaster (superposer flèche de couleurs différente) \thus diagnostic
  paralysie oculomotrie
- RPM, inégalité pupillaire
  
** Sémiologie
- Paralysie du III : totale (ptosis total, mydriase aréflective, 0 accomodation)
ou partielle
- Paralysie du IV : diplopie verticale oblique
- Paralysie du VI : convergence \oe{}il atteint, déficit abduction
- Formes particulières :
  - paralysie supranucléaire : sd Foville (latéralité), sd Parinaud (verticalité
    et cv \thus pinéalome++)
  - paralysie intranucléaire : ophtalmoplégie intranucléaire (parallélisme OK mais
    déficie adduction) \thus SEP
  - paralysie intraxile : {fonction et diplopie, diplopie et signe neuro
    controlatéraux}

** DD
Diplopie monoculaire, simulation, hystérie

** Étiologie
- Traumatique : fracture du plancher de l'orbite (élévation globe douleureuse),
  hémorragie méningé traumatique
- Tumeurs : HTIC, de la base du crâne
- Vasculaires : AVC, insuf vertébrobasilaire, *anévrime
  intracranien* (Y penser si atteinte partielle, signes
  pupillaires, sujet jeune, 0 FR vasc, céphalée \thus angioscanner urgence
  \skull)A, fistule carotidocaverneuse
- Avec exophtalmie : Basedow, tumeurs de l'orbite
- douleureuse : penser anévrisme intracrânnien, dissection carotidienne, fistule
  carotidocaverneuse = urgence \skull. Maladie de Horton. Sd Tolosa-Hunt
- SEP : paralysie VI, ophtalmoplégie internucléaire
- Myasthénie : diag = {test Prostigmine, Ac anti récepteur acétylcholine, électromyographie}
* 6 \OE{}il rouge/douloureux
** Examen
Interrogatoire : mode d'apparition, douleur superficielle/profonde, BAV
   ?, ATCD ophtalmo et généraux, signes locaux associés
   
Examen à lampe à fente (bilatéral) :
- acuité visuelle
- conjonctive : rougeur en nappe hémorragique (hémorragie
  sous-conjonctivale[fn:12], diffuse (conjonctivite), secteur (épisclérite),
  cercle (kératite aigüe, uvéite antérieure)
  périkératique
- cornée : perte de transparence, dépôts rétro-cornéens
- collyre à fluorescine pour ulcération cornéenne : unique (trauma), localisée
  avec zone blanche (kératite bactérienne), dendritique (kératite herpétique),
  petites ed disséminées (kératite à adénoviruse, sd sec oculaire, corps
  étranger)
- iris et pupille : synéchie iridocristallinienne (uvéite), atrophie iris
  (herpès), myosis (kératite aigùe, uvéite aigǜe), semi-mydriase
  aréflexique (glaucome aigü)
- chambre antérieure : étroite, plate (glaucome aigù, plaie perforante), signes inflammatoires
- tonus oculaire : hypertonie (glaucome aigu par fermeture de l'angle, glaucome
  néovasculaire), hypotonie (plaie oculaire transfixiante)
- conjonctive palpébrale : follicules (conjonctivite virale), papilles
  (conjonctivite allergique), corps étranger 
- FO 

** Étiologies
\OE{}il rouge, non douloureux, sans BAV
- hémorragie sous-conjonctivale spontanée : chercher HTA, trouble
  coagulation. Penser corps étranger, plaie sclérale \danger
- conjonctivite : "grain de sable", prurit
- conjonctivite  bactérienne : sécrétions mucopurulentes (paupières collées le
matin). Germe Gram+. /Ttt/ : hygiène des mains, lavage sérum phy, collyre
antiseptique (pas forcément ATB !!)

\OE{}il rouge unilatéral, douloureux, sans BAV
- épisclérite (sous conjonctive) : rougeur disparaissant avec collyre
  vasoconstricteur. /Ttt/ corticothérapie locale
- sclérite : douleur \inc mobilisation du globe. Ne disparait pas au
  collyre. Cherche maladie de système (articulaire, vasc, granulomateuse,
  infectieuse). /Ttt/ AINS générale et cause.

Yeux rouges bilatéraux, douloureux, sans BAV
- conjonctivite virale : fréq++, contagieux. Sécrétion claires, ADP prétragienne
  douloureuses à palpation. /Ttt/ inutile
- conjonctivite allergique : terrain, prurit, chemosis[fn:13], sécrétion claire,
  volumineuses papilles. /Ttt/ bilan allergique, évition, collyre antiallergique
- conjonctivite à \bact{chlamydia} : tiers-monde++
- sd sec oculaire : fréq++. Diag = test Schirmer (quantité sécrétion lacrymale),
  qualité film lacrymal, surfarce cornéenne, surface conjonctivale}. Cause :
  involution (âge), sd Gougerot-Sjögren. /Ttt/ substituts lacrymaux, évictions
  facteurs irritants, occlusion points lacrymaux
- autres : Basedow, malpositions palpébrale, conjonctivite d'irritation

\OE{}il rouge, douloureux, BAV
- Kératite aigüe : BAV, douleurs
  superficielles importantes, larmoiement, photophobie,
  blépharospasme. Érosion/ulcérationsc cornée, \dec transparence cornée,
  cercle périkératique
  - kératite à adénovirus : petite ulcérations disséminées. Évolution favorable
    (?)
  - kératite herpétique : ulcération en "feuille de fougère". /Ttt/ :
    valaciclovir \pm aciclovir en pommadex. Jamais de corticothérapie locale
    sans avoir élimine une ulcération cornéenne \skull
  - kératite zostérienne : zona ophtalmique \thus (?) kératite superficielle ou
    neuroparalytique (grave). 9Ttt/ : valaciclovir et protecteurs locaux
    cornéens
  - kératite bactérienne, parasitaire, mycosique : plage blanchâtre. Prélèver
    sur l'abcès. /ttt/ collyre ATB (si important : "collyre fortifiés"). \danger
    évolution : endophtalmie, perforation cornéenne, taie cornéenne cicatricielle
  - kératite sur sd sec
  - kératite d'exposition (paralysie faciale) : /ttt/ protecteurs cornéens en
    prévention, tarsorraphie (=suture)
- Uvéite antérieure : cercle périkératique, transparence cornée OK, myosis,
  (synéchies iridocristalliniennes ou iridocornéennes), Tyndall, précipités
  rétro-cornéens. FO systématique ! 
  - Causes : inconnue, spondylarthrite ankylosante (diag = {sacro-iléite, rachis,
    Ag HLA B27), uvéite herpétique, arthrite juvénile idiopathique, sarcoïdose,
    Behçet, lupus erythémateux disséminé.
  - /Ttt/ collyre mydriatique, collyres corticoïdes
- Glaucome aigu par fermeture de l'angle : rare, pronostic sévère.
  - prédisposition anatomique, pendant une mydriase
  - humeur aqueuse ne peut plus passer dans la chambre antérieure, s'accumule
    dans champre postérieure et bloque le trabeculum.
  - signes fonctionnels .: douleurs profondes++ irradiant dans trijumeau,
    souvent nausées, vomissement, BAV
  - examen : douleurs intenses, \oe{}il rouge, transparence cornée \dec diffuse,
    semi-mydriase aréflexique, angle iridocornéen fermé, hypertonie oculaire++
  - cécité en qq jours sans ttt \danger 
  - /ttt/ = urgence \skull : antalgique, inhibiteurs de l'anhydrase
    carbonique [fn:14], solutés hyperosmolaires[fn:15], collyre hypotonisants,
    collyres myotiques
  - post-crise : iridotomie périphérique sur *les deux yeux* (laser ou chir)
- Glaucome néovasculaire : VEGF crée néovaisseux qui empêche la résorption de
  l'humeur aqueuse
  - néovaisseaux sur l'iri
  - /Ttt/ hypotonisants locaux et généraux, photocoagulation ou injection anti-VEGF
- Endophtalmie post-opératoire : douleur intense, \oe{}dème palpébral, hyalite
* 7 Altération de la fonction visuelle
** Examen
Interrogatoire : BAV objective, altération CV  (myodésopsies, phosphènes,
métamorphopsies, éclipse viusuelle (qq secondes) ou cécité monoculaire
transitoire (qq min-heures), aura visuelle), installation, unilatéral ?, douleur
? ATCD, ttt, traumatisme ?

Examen ophtalmo : AV (avec correction), RPM, segment antériur, tonus oculaire,
{cristallin, vitré, rétine, vaisseux, nerf optique}

** BAV progressive [fn:16]
Si améliorié par correction optique, trouble de réfraction. Sinon 

*** Transparence anormale
Cataracte : BAV bilatérale, photophobie, myopie d'indice, diplopie
monoculaire. Perte de transparence du cristallin (opalescent). Étiologie : âge
surtout. /Ttt/ : chir

Autres : cornées, vitré (hyalite des uvéite)

*** Atteinte nerf optique
Glaucome chronique à angle ouvert (GCAO) : longtemps asymptomatique. Diag =
{\inc tonus oculaire, altération CV, excavation glaucomateuse de la
papille}. /Ttt/ : collyre hypotonisants, trabéculoplastie (laser/chir)

Autres : neuropathie toxiques (alcool-tabac, médic), héréditaires, compressive

*** Atteinte de la rétine/macula
Dystrophies rétiniennes héréditaires :
- maculoopathies héréditaires : maladie de Stargardt = débute vers 7-12 ans,
  1/10e en fin d'évolution (!), en "\oe{}il de b\oe{}uf"
- rétinopathies pigmentaires : héméralopie, rétrécissement progressif du CV
  (débute dans l'enfance), aspect réticulé "en ostéoblastes"
"Interface vitréomaculaire" = séparation vitré-région maculaire
- membranes épi-/pré-maculaire (par tissu fibreux). "reflet" cellophane". OCT
  maculaire. Chir possible
- trous maculaires : OCT
Dégénérescence maculaire liée à l'âge 

\OE{}dème maculaire : en "pétales de fleur" si important. Causes : 
  - rétinopathie diabétique : /ttt/ : injection IV anti-VEGF ou corticoïdes
  - occlusion veine centrale de la rétine : /ttt/ idem
  - chir cataracte 
  - uvéite postérieures : /ttt/ : cause ou corticoïdes retard
    
Maculopathies toxiques aux antipaludéens de synthèse : potentiellement cécité
irréversible. Pas avant 5 ans ? Commence par périfovéolopathie \thus arrêt
immédiat du ttt \danger

** Altération du CV
= altération vision périphérique

*** Affections rétiniennes 
Scotomes (para)centraux , déficits périphériques

*** Atteinte des voies optiques
Atteinte nerf optique : cécité unilatérale (trauma, tumeur) 
- scotome central unilatéral ou caecocentral uni-/bi-latéral
- déficicit fasciculaire possible
- déficit altitudinal si neuropathie optique ischémique antérieure (NOIA)
- étiologies :
  - SEP (névrite optique rétrobulbaire)
  - NOIA 
  - toxiques et métabolique : bilatéral, progressive. {alcool-tabac, médicament,
    professionnelle, métabolique}, tumoral (tumeurs intraorbitaires, étage
    antérieur du crâne)}

Lésion du chiasma optique : hémianopsie/quadranopsie bitemporale (décussation
!). Étiologies : adénome hypophyse surtout

Lésions rétrochiasmatique : hémianopsie latérale homonyme. Si atteinte des
radiaton optiques, quadranopsie latérale homonymes. Étiologies vasc, tumoral,
trauma

Cécité corticale : bilatérale, brutale. Examen ophtalmo OK, RPM OK,
désorientation, hallucination visuelles, anosognosie
* 8 Anomalies de la vision d'apparition brutale
** Diagnostic
Interrogatoire : BAV ? altération CV ? myodésopsies,  phosphènes,
métamorphopsies ? rapidité, latéralité, type de douleurs, ATCD, ttt, trauma ?

Examen ophtalmo ( 2 yeux) : AV, RPM, segment antérieur, tonus oculaire, FO

** Étiologie
BAV, \oe{}il rouge et douloureux 
- kératite aigüe : douleur superficielles importantes, photophobie,
  blépharospasme. \dec transparence cornée, cercle périkératique, ulcération(s)
  cornéenne(s)
- glaucome aigü par fermeture de l'angle : douleurs profondes, intense,
  irradiant dans trijumeaux. \inc\inc tonus oculaire ("bille de bois" à la
  palpation)
- uvéites 
  - antérieure aigüe : BAV, douleurs, cercle périkératique, myosis par synéchies
    iridocristalliniennes. Tyndall, chercher uvéite postérieure
  - postérieure : toxoplasmose oculaire le plus souvent. Myodésopises, BAV. FO =
    foyer blanchâtre puis cicatrice. /Ttt/ antiparasitaire si AV menacée
- autres  : glaucome néovasculaire, endophtalmie (contexte post-op)

BAV, \oe{}il blanc indolore
- FO non visible 
  - hémorragie intravitréenne : précédée d'une "pluie de cendre", BAV
    variable. Écho. B pour éliminer un décollement de la rétine. Causes :
    rétinopathie diabétique proliférante, occlusions ischémique de la veine
    centrale de la rétine, déchirure rétinienne, sd de Terson[fn:17], plaie
    perforante
  - uvéite intermédiaire (dans le vitré) : cellules inflammatoires
- FO visible anormal
  - occlusion de l'artère centrale de la rétine : BAV brutale, mydriase
    aréflexique et RPM direct aboli, \dec diffuse du calibre artériel, \oe{}dème
    blanc rétinien ischémique de la rétine (macula rouge cerise)
  - occlusion de la veine centrale de la rétine : BAV variable, {\oe{}dème
    papillaire, hémorragie rétiniennes disséminées, nodules cotonneux,
    tortuosités veineuse}. Préciser si ischémique
  - DMLA : BAV et métamorphopsies brutales, décolleme exsudatif de la rétine
    maculaire \pm hémorragies, exsudats profonds
  - décollement de la rétine rhegmatogène : après une déhiscence, le vitré va
    sous la rétine. 
    - causese : idiopathique (âgé), myopie (forte), chir cataracte
    - évolution spontanée = cécité
    - /ttt/ chir (semi-urgence \danger) 
    - clinique : myodésopsies, phosphènes, amputation CV périphérique, BAV
    - diag par FO : rétine en relief, mobile, avec des plis
    - toujours examiner \oe{}il controlatéral (ttt préventif par photocoagulation)
      \danger
  - neuropathie optique ischémique antérieure : BAV unilatérale brutale, \dec
    RPM direct, \oe{}dème papillaire, déficit fasciculaire pour CV. Cause : surtout
    artériosclérose mais penser à Horton (urgence \skull)
FO visible normal
  - névrite optique rétrobulbaire : BAV unilatérale progresse en qq jours (!),
    douleur \inc mouvement oculaires, RPM direct \dec, FO normal, scotome
    (caeco)-central
  - atteinte des voies (rétro)chiasmatiques : tumorale (si progressive), vasc (si brutale)
    
Anomalies transitoire 
  - cécité monoculaire transitoire (qq minute) = amarause. FO pour embole
    rétinien. Urgence \skull. Cherhe athérome carotidien, cardiopathie embolinogène
  - insuf vertébrobasilaire, éclipses visuelle, scotome scintillant
* 9 Prélèvement de cornée
Le médecine prélèveur \ne celui qui a fait le constat de mort

Sérologies à faire : HIV, HTLV, hépatite B et C, syphils
CI :
- locale : chir sur segment antérieure, uvéite, conjonctivite, tumeur,
  rétinoblastome, mélanome choroïdien
- infectieuses (Sida, rage, Creutzfeld-Jakob, héatite..),
- neuro inexpliquée, démence

Prélèvement *in situ*

* 10 Greffe de cornée
Couches (depuis l'extérieur) = épithelium, couche de Bowman, stroma, membrane
  de Descemet, endothelium
  
Techniques
- kératoplastie transfixiante = toute les couches
- kératoplastie lamellaire antérieure = épithelium, Bowman et stroma seulement
- kératoplastie endothéliale : membrane de Descemet et endotheliale seulement.

Indications : trauma perforant de la cornée, brûlures chimiques, dégénérescene
cornéenne (kératocône), kératite (herpétique), dystrophie bulleuse chez âgé

Bon pronostic dans $\frac{2}{3}$

Complications rare (retard d'épithélialisation, \oe{}dème cornéen précoce, rejet
immuntaire, récivide de maladie causale, hypertonie oculaire, astigmatisme post-op
* 11 Traumatismes oculaires
** Globe fermé (contusions)
Dangerosité inversement \propto taille agent.

Interrogatoire : douleurs, AV, heure dernier repas, lésions associées.

Examen :
- contusions du segment antérieur 
  - cornée : /ttt/ lubrifiant cicatrisant
  - conjonctive : plaie ou hémorragie sous-conjonctivale. Toujours chercher plaie
    sclérale, corps étranger
  - chambre antérieure : hyphéma. Résorption spontanée
  - iris : iridodyalise [fn:18], rupture sphincter irien, mydriase post-trauma
  - cristallin : (sub)luxation, cataracte contusive (plusieurs mois après...)
  - hypertonie oculaire : si lésions de l'angle iridocornée, hyphéma, luxation
    antérieure du cristallin
- contusions du segment postérieur
  - \oe{}dème rétinien du pôle supérieur : guérison spontanée
  - hémorragie intravitréenne : résorption spontanée. Écho B si décollement de
    rétine (DR) suspecté
  - déchirure rétiniennes périph. Photocoagulation prophylactique possible
    (contre DR)
  - rupture de la choroïde : BAV définite si macula

** Globe ouverts
Rupture du globe : pronostic plus péjoratif si postérieur

Trauma perforant : 
- AVP, accidents domestique, bricolage, agression.
- larges, mauvais pronostic ou petite plais (cornée ou sclère)
- risque : méconnaître plaie, corps étranger. Si doute, scanner !

** Corps étrangers
Diagnosic évident : 
- superficiel 
  - circonstance, symptôme de conjonctivite ou kératite
  superficielle. Corps étranger souvent visible
  - bon pronostic, ttt lubrifiant et antiseptique/ATB local
- intraoculaire : circonstance, porte d'entrée et trajet visible
Délicat si trauma non remarqué, pas de porte d'entrée, trajet et corps non visible

Examens : TDM si doute. Pas d'écho B si transfixiante. Pas d'IRM \danger

Complications (si intraoculaire) : endophtalmie (grave++), DR, cataracte traumatique

Complications tardives : ophtalmie sympathique [fn:19], sidérose, chalcose
* 12 Brûlures oculaires
Accident industriels (graves), domestiques, aggression

Brûlures 
- thermique : peu grave (brûlure par cigarette). Cicatrisation rapide, sans séquelles
- acides : gravité modérée-moyenne, grave si très concentré
- basiques : grave !
  
Classification de Roper-Hall
1. bon pronostic 
2. bon pronostic : opacité cornéenne mais détails iris, ischémie < 1/3 \diameter
3. pronostic réservé : désépithélialisation cornéenne totale, opacité cornéenne
   , ischémie \in [1/3, 1/2] \diameter
4. pronostic péjoratif 

Ttt d'urgence par lavage (20-30min) par sérum phy (ou eau), puis collyre
corticoïde ASAP

Autres :
- brûlures des UV (ski, UV)
- soudure à l'arc sans lunette
- phototraumatisme (éclipse) : BAV définitive !

* 13 Cataracte
Déf: opacification (partielle ou non) du cristallin. 

** Diagnostic
Découvert sur BAV (progressive, vision de loin), photophobie, (diplopie
monoculaire), jaunissement

Examen clinique :
- interrogatoire : âge, profession, ATCD (diabète, corticoïdes), myodésopsies,
  métamorphopsies
- AV (\oe{}il par \oe{}il, bionculaire)
- lampe à fente : 
  - cristallin (caracte {nucléaire, sous-capsulaire postérieure, corticale, totale})
  - éliminer autre patho (cornée, iris, vitré, rétine (DMLA, glaucome)
  - mesure tonus oculaire (hypertonie, glaucome)

Diagnostic clinique mais en complémentaire :
- écho en mode B si décollement de rétine/tumeur intraoculaire
- pour le cristallin artificiel : kératométire, longeur axiale

* 14 Glaucome chronique
= Glaucome primite à angle ouvert (GPAO) Neuropathie optique progressive altération
fonction/structure.
FR : âge, hypertonie oculaire (\ne cause !!), ATCD familaux directs, noirs
d'origine africaine, myopie

Physio : perte accélére des fibres optiques liée à l'âge

** Formes cliniques :
GPAO à préssion élevée (> 21 mmHg) (70% des pop. occidentales)
- anomalies de structures visibles cliniquement : papille = {\dec surface,
  hémorragies péripapillaires en flammèches, atrophie péripapillaire \beta, \inc
  excavation papillaire}. Rapport de taille entre papilles des 2 yeux > 0.2
  \thus suspect
- autres anomalies de structures : OCT
- anomalies de foncton : champ visuel mais AV touchée très tardivement

GPAO à pression normale (70% pop. asiatique) : plutôt femmes, migraine, acrosyndromes

DD : 
- hypertonie oculaire : pression intraoculaire > 21mmHg, angle ouvert (gonio),
  \emptyset neuropathie optique. Pas forcément de ttt.
- glaucomes à angles ouvert secondaires
- glaucomes par fermeture de l'angle
- crise aigüe de fermeture de l'angle : douleur, urgence \skull
- neuropathie optiques non glaucomateuses

** Traitement
Dépistage : seulement ATCD familaux de GPAO, myopie, > 40 ans

Ttt : \dec pression intra oculaire

Médicaments :
- à vie 
- 1ere intention : collyre à base de prostaglandines [fn:20](\inc élimination humeur
  aqueuse) ou collyre betabloquant
  (\dec sécrétion humeur aqueuse)
- association possible mais \le 3
- rarement : acétazolamide par voie générale
  
Trabéculoplastie au laser = photocoagulation de l'angle. Effet modeste, non durable.

Chir : trabéculectomie. Complications (rare) = cataracte, hyoptonie précoce
avec décollement choroïdien, infection globe oculaire. Principal échec :
fermeture de la voie par fibrose sous-conjonctivale.

* 15 Dégénérescence maculaire liée à l'âge
Atteinte de la macula chez > 50 A. Débutante/intermédaire : drusent, altération
pigmentaire, AV normale ou peu \dec. Évoluée : atrophique ou exsudative

Prévalence : 18% après 50 ans, 37% à 85 ans.

FR : âge, pop européennes, polymorphisme facteur H du complément, tabac, régime
pauvre en anti-oxydant/riches en (acide gras saturés et cholestérol)

** Diagnostic
- Mesure AV (loin et près, recherche scotome central ou métamorphopsies (grille
d'Amsler)
- FO (drusen, altération pigmentaires, atrophie épithelium pigmentaire,
forme exsudative [cf /infra/].
- OCT : suivi, ou diagnostic si + FO

** Formes cliniques
- débutante : /drusen/ = résidus de phagocytose des photorécepteurs. Petites
  lésions profondes jaunâtre. OCT
- atrophique : disparition de l'épithelium pigmentaire. FO : atrophie de
  l'épithelium pigmentaire et choroïde. BAV sévère avec scotome centrale
- exsudative (néovaisseaux sous rétine) : \oe{}dème intrarétinien, hémorragies,
  décollement maculaire exsudatif (BAV, métamorphopsies brutales). Sans ttt :
  BAV sévère, scotome central définitif. BAV chez drusen = urgence \skull

** Ttt
- débutante : vit E, C, zinc, lutéine, zéaxantine
- atrophique : \emptyset
- exsudative : injection d'anti-VEGF : ranibizumab,
  aflibercet. bévacizumab. Stoppent néovaisseux, font régresser l'\oe{}dème. 40%
  ont amélioration visuelle à 2 ans. 
Laser possible mais risque thrombose
* 16 Occlusions artérielles rétiniennes
Artères ciliaires postérieure alimente les couches profondes (épithelium
pigmentaire de la rétine, photorécepteurs). 
Artère centrale de la rétine = couche internes (cellules bipolaires,
ganglionnaires, fibres optiques).

Arrêt circulatoire \thus lésions définitives en 90min \danger

** Occlusion de l'artère centrale de la rétine
Diagnostic : 
- BAV brutale (amaurose transitoires précédentes possibles)
- Oeil blanc indolore, AV effondrée, mydriase aréflective (RPM direct aboli)
- FO : dans les heures : oedème ischémique rétinien blanchâtre, tache "rouge
  cerise de la macula")

Étiologie : 
- embolies : athérome carotidien++, cardiopathie embolinogène, ( fractures des os
  lng ou emboles tumoraux)
- thromboses : maladie de Horton (urgence \skull, à rechercher), (maladies de systèmes)
- troubles coagulation : anomalie primitive, sd antiphospholipides, hyperhomocystéinémie

Évolution spontanée quasiment toujours défavorable

CAT : urgence \danger \skull (fonction visuelle et patho sous-jacente)
- bilan étio : athérome, carotidien, cardiopathie embolinogène, dissection
  carotidienne (si jeune), horton
- ttt décevant : hypotonisant (acétazolamide IV/per os), vasodilatateur,
  anticoagulant si  bespoin fibrinolytique
- bilan cardio
- Aspirine dans tous les cas. Si jeune, bon état général, ttt max. 
- selon étio : antiagrégant plaquettaire (athérome carotidien), anti-vit K (emboles
  cardiaques), endartériectomie

** Occlusion de branche l'artère centrale de la rétine
Amputation du CV. BAV possible. FO : \oe{}dème rétinie ischémique en secteur

Évolution : \inc AV en qq semaines, pronostic visuel bon mais amputation
perisiste.

Même étio, sausf Horton. Même ttt.

** Nodules cotonneux
Occlusion d'artérioles rétiniennes précapillaire \thus nodules cotonneux =
petites lésions blanches superficielles d'aspect duveteux.

Étio : HTA, diabète, occlusions veineuses rétiniennes, sida, lupus érythémateux
disséminé, périartérite noueuses, embolies graisseuses, pancréatite aigüe, sd Purtscher
* 17 Occlusions veineuses rétiniennes
** Occlusion de la veine centrale de la rétine
SF : vision trouble brutalement, BAV variable, \oe{}il blanc indolore
FO : 
- diagnostic = {\oe{}dème papillaire, veines rétitiennes tortueuses et dilatées,
  hémorragies sur la surface rétitienne, nodules cotonneux}
- formes non ischémiques (freq) : AV > 2/10, hémorragies en flammèches, ischémie
  peu étendue
- formes ischémiques[fn:21] : AV < 1/10, réflexe pupillaire direct diminué, hémorragies
  plus volumineuses, en tache
  
Suivi par OCT

Étiologie inconnue 
- mais > 50 ans avec FR vasc \thus recherche {tabac, HTA,
diabète, hypercholestérolémie, SAS}, hypertonie oculaire++
- si < 50 ans, 0 FR ou OVCR bilatérale, chercher anomalie primitive de la
  coagulation, sd antiphospholipides, hyperhomocystéinémie, contraception, hyperviscosité
  
Évolution :
- formes non ischémiques : normalisation AV en 3-6 mois. Sinon : conversion en
  forme ischémique, peristance d'un \oe{}dème maculaire cystoïde (BAV permanente !)
- formes ischémiques : 
  - pas de récupération fonctionnelle. 
  - Pire complication = néovascularisation irienne \thus progression rapide vers glaucome
  néovasculaire (3 mois) \thus prévention par photocoagulation panrétinienne
  - néovascularisation prérétiniennes ou précapillaire (hémorragie intravitréenne)
    
Ttt 
- formes non ischémique : injection d'anti-VEGF/triamcinolone si \oe{}dème
  maculaire cystoïde avec BAV persistante. Surveillance tous les mois
- formes ischémiques : photocoagulation panrétinienne (PPR) pour éviter glaucome
  néovasculaire
- glaucome néovasculaire : PPR en urgence après hypotonisant local \danger
  

** Occlusion de branche veineuse rétinienne
Identique à OVCR mais territoire plus limité.
Signe du croisement (cf chap 23) \thus > 60 ans, FR d'artériosclérose

Clinique : BAV variable, FO identique OVCR

Évolution favorable en majorité. Défavorable si maculopathie ischémique,
\oe{}dème maculaire persistante, néovaisseaux prérétiniennes \thus hémorragie du
vitré mais *pas* de GNV

Ttt similaire. 
- Si \oe{}dème maculaire peristant : injection intravitréenne
- photocoagulation maculaire en grille (si \ge 3 mois, \oe{}dème maculaire
  perisistante, AV ɇ 5/10)
- photocoagulation sectorielle
* Footnotes

[fn:21] Différence avec l'angiographie fluorescinique

[fn:20] EI : rougeur, irrit. oculaire. Puis iris plus sombre, \inc pousse cils. 

[fn:19] Uvéite auto-immune sévère

[fn:18] Désinsertion de la base de l'iris

[fn:17] Hémorragie itnravitréen uni-/bi-latérale et hémorragie méningée par
rupture d'anévrisme intracrânien

[fn:16] Cf chapitre suivant pour BAV brutale

[fn:15]  Déshydratation du vitré

[fn:14] \dec production d'humeur aqueuse.

[fn:13] \OE{}dème conjonctival

[fn:12] Cherche plaie conjonctivale !

[fn:11] \danger méconnu si ptosis/\oe{}dème palpébral

[fn:10] Monoculaire : cause cornéenne, irienne, cristalinienne \thus pas une urgence.

[fn:9] Abrasion épithelium cornéen ou volet dans cornée.

[fn:8] Chez l'enfant, cycloplégique

[fn:7] Courbure de la cornée

[fn:6] Si BAV, vasculaire probable. Sinon HTIC

[fn:5] Punctiformes, flammèches, profondes

[fn:4] Cellules inflammatoires, protéines dans l'humeur aqueuse

[fn:3] \OE{}dème conjonctival

[fn:2] Plus de voie efférente \thus \oe{}il atteint : RPM direct aboli. \OE{}il sain : RPM consensuel aboli

[fn:1] Plus de voie afférente  \thus RPM (réflexe photomoteur) direct et
consensuel aboli pour l'\oe{}il atteint
