#+title: Ophtalmologie
#+author: Alexis Praga
#+latex_header: \usepackage{booktabs}
#+latex_header: \input{header}
#+latex_header: \usepackage[linesnumbered,ruled,vlined]{algorithm2e}
#+OPTIONS: H:4

\input{bacteries-header}
* 1 Sémiologie oculaire
** Globe
Membranes (d'avant en arrière)
- externe = {cornée (avant), conjonctive (sur sclère antérieure), sclère}
- intermédiaire (uvée) = {iris, corps ciliaires, choroïde}
- interne (rétine) = {épithelium pigmentaire, neurosensorielle (photorécepteurs,
  fibres optiques}}. NB : phototransduction = pigment visuel
  (épithelium) \rightarrow photorécepteurs (bâtonnets = {vision périphérique,
  nocturne}, cône = {détails, couleurs} \in macula)
Contenu : 
- humeur aqueuse \in chambre antérieure, évacuée dans l'angle iridocornéen. P
  normale si \le 22 mmHg.
- cristallin : biconvexe, convergente, déformation par zonule \thus accomodation
- corps vitré : 4/5e cavité oculaire \thus segment antérieur vs postérieur
Voies optiques : 
- nerf optique - chiasma - bandelettes optiques - corps genouillés externes - radiations optiques - cortex occipital
- mydriase "sensorielle"[fn:1] vs "paralytique"[fn:2]
- voie efférente sympathique : si atteinte, sd Claude-Bernard-Horner (myosis, ptosis)
Annexes
- oculomoteur : nerf IV = {oblique supérieur}, VI = {droit externe} et III =
  {droit sup, droit inf, droit médial, oblique inf}
- protection : paupière (muscle orbiculaire, tarse), conjonctive (face interne
  paupière, globe antérieur), film lacrymal
  
** Examen
Interrogatoire : 
- baisse d'acuité visuelle (BAV), fatigue visuelle, myodésopsise,
métamorphopsies, héméralopie, scotome/amputation champ visuel, 
- mode d'installation : urgente si brutal
- douleur superficielles/profondes
- diplopie mono/bi-noculaire
- évolution : aggration rapide = grave
Acuité visuelle : échelle de Monoyer (à 5m), de Parinaud (33cm)

Segment antérieur : "lampe à fente"
- conjonctive : rougeur (diffuse/localisée/culs-de-sac inférieure/avec
  sécrétions/cercle périkératique/paupière), chemosis[fn:3]
- cornée (transparence)
- iris : myosis/mydriase
- chambre antérieure : inflammation (Tyndall[fn:4], précipités rétro-cornéens,
  synéchies iridocristaliniennes), hypopion (pus), hyphéma (sang)
Pression intraoculaire par tonomètre à air pulsé. Hypertonie si \ge 22 mmHg

Gonioscopie : angle iridocornéen

Fond d'oeil
- direct, indirect (apprentissage++), biomicroscopie
- aspect : pôle postérieur = {papille, vaisseaux rétitiens, macula}, rétine
  périphérique (si besoin)
- lésions : microanévrisme (points rouges), hémorragie (intravitréennes,
  prérétiniennes, sous-rétiniennes, intra-rétiniennes[fn:5]), nodules cotonneux,
  exsudats profonds, oedème papillaire[fn:6]

Oculomotricité

** Complémentaires
Fonctions visuelles
- Champ visuel :
  - sensibilité lumineuse \dec périphérie, papille = zone aveugle
  - périmétrie cinétique (Goldman : trace isoptères) ou statique (dépistage
  glaucome)
- Vision des couleurs : si dépistage anomalie congénitale (planches colorées) ou
affection acquise (Farnsworth = classer couleurs). Utile pour antipaludéens de
synthèse ou {éthambutal, isoniazide}
Angiographie du fond d'oeils : fluorescine ou vert d'indocyanine (DMLA++)

Électrophysio : électrorétinogramme (si lésion rétiniennes étendues), potentiels
évoqués visuels (cortex occipital) (SEP++), électro-oculogramme (épithelium pigmentaire)

Echographie : mode A (longueur globe oculaire) ou B (décollement rétine, corps
étranger intraoculaire, tumeur)

Tomographie en cohérence optique (OCT) : affection maculaire (trou, DMLA),
dépistage glaucome chronique

* 2 Réfraction
Oeil \approx 60 dioptries (cornée = 42, cristallin = 20)
Emmétrope = oeil normal. Amétrope = anomalie de réfraction

Punctum remotum (PR) : point le plus éloigné visible /sans/ accomoder. Punctum
proximum (PP) = point le plus proche visible /en/ accomodant.

Acuité visuelle = $\frac{1}{\alpha}$ où \alpha = pouvoir séparateur de
l'oeil. Mesurée par l'échelle de Monoyer (de loin) en 10eme (!) et de Parinaud
(de près)

** Accomodation
Amplitude \dec jusque 0 (79 ans) \thus presbytie (BAV vision de près). Compensée
par verres sphériques convexes progressifs ou implant cristallinien

Sinon, \dec vision de près par : médicaments, paralysie III, maladie générale,
spasmes de l'accomodation

** Anomalies de la réfraction
Différencier maladie de l'oeil/voie optique et anomalie réfraction !

Examen : réfractomètres automatiques \thus réfraction, kératométrie[fn:7]. [fn:8]

*** Myopie 
Oeil trop convergent. \approx 20% population occidentale. PR à distance finie,
PP plus proche.

Types : myopie d'indice (\inc indice de réfraction), de courbure (courbure
cornée \inc) ou axile (longueur axiale \inc)

Myopie
- faible : < 6 dioptrie
- forte : > 6 dioptries ou longueur axiale \ge 26mm. Héréditaire, \in [1/10,
  5/10] /après/ correction. Complications : glaucome chronique à angle ouvert,
  cataracte, décollement de la rétine++

Correction : verres sphériques concaves.

Chirurgie par photoablation au laser ecited dimer[fn:9]. Chirugie du cristallin
possible.

*** Hypermétropie
Fréquent (enfant++). Pas assez convergent. PR = virtuel à l'arrière. Correction
par verres sphériques convexes, lentilles ou chir.

*** Astigmatisme
Rayons de courbures différents pour les méridiens. Régulier si 2 méridiens
principaux \bot.

1 point à l'infini = 2 droite perpendiculaire (= focales) \thus myopique,
hypermétropiique ou mixtes

Correction par verres cylindriques convexes/concaves, lentilles ou chir

* 3 Suivi d'un nourisson
Déficits mineurs (amétropie, strabisme) ou sévères (grave !) (milieux transparents,
  malforamtion, rétinopathie, atteintes neuro centrales)

20% d'enfant < 6 ans avec anomalie visuelle. Si non traitée, amblyopie (BAV),
définitive > 6ans !

Développement :
- 1ere semaine : réflexe lumière, RPM
- 2-4e semaine : reflexe de poursuite
- 4-12e semaine : reflexe de poursuite
- 3e mois : vision des formes
- 4-5e mois : coordinatio oeil-tête-main
- > 2 ans : AV mesurable
Examens obligatoires pour {strabisme, nystagmus, anomalie organique, trouble
comportement visuel}:
- dépistage anténal (écho)
- 1ere semaine
- 4eme mois
- 9eme mois
- 2 ans
- 3-6 ans
  
Dépistage : leucocorie, glaucome congénital, malformations, infections
maternelles, maladies enfants secoués, rétinopathie des prématurés
* 4 Strabisme de l'enfant
  
Position de l'oeil anormale et altération vision binoculaire. Provient d'une
perturbation de la fusion.

Conséquences :
- Si aigu : diplopie possible. Si ancien : corrigé par cerveaux \thus vision
binoculaire non acquise si strabisme dans premiers mois de vie !. Amblyopie
possible
- Perturbation vision stéréoscopie (3D)
 
Souvent dans l'enfance. 4% population. *Dépistage avant 2 ans*

** Dépistage
Jamais normal, toujours symptôme

Interrogatoire :
- date d'apparition
- horizontal : /eso-/ si convergent, /exo-/ si divergent. Vertical : /hyper-/,
  /hypo-/. Si divergent < 9 mois, examen neuroradio
- intermittent ?
- oeil dominé
  
Examen : 
- motilité : strabisme paralytique ?
- segment antérieur et FO (fond d'oeil) : perte transparence, patho rétinienne ? Si nystagmus : électrorétinogramme, PEV, IRM
- réfraction sous cycloplégique : amyotropie ? Hypermétropie fréuente
- acuité visuelle : amblyopie ? (> 2/10 entre 2 yeux)
- mesure de l'angle de déviation (si chir), vision binoculaire (pronostique)

** Traitement
Correction optique. Si amblyopie, occlusion de l'oeil dominant (jusque 6-8ans)

Chir si angle résident avec correction. Correction optique après opération
* 5 Diplopie (binoculaire)
Binoculaire : disparaît à l'occlusion d'un oeil[fn:10]. Souvent une urgence
\danger

Noyaux des nefs oculomoteurs \in tronc cérébral - racine - troncs -
muscle. Voies supranucléaire (latéralité, verticalité), internucléraires.

#+caption: Champ d'action (\danger \ne action) 
| oblique inférieur | droit supérieur |
|-------------------+-----------------|
| droit médial      | droit latéral   |
|-------------------+-----------------|
| oblique supérieur | droit inférieur |

Mouvement bilatéraux : synergie des muscles

Vision binoculaire :
- loi de Hering : même influx nerveux pour muscles antagonistes. Loi de
  Sherrington : muscle antagonistes se relachent quand muscles synergistes se
  contractent.
- si correspondance rétinienne anormale (oeux non \parallel) : diplopie
  
** Diagnostic
- Signes fonctionnels : dédoublement toujours même direction[fn:11], disparaît à
l'occlusion
- Interrogatoire : terrain, circonstance, brutal/progressif, {douleurs, vertiges,
céphalées, nausées}, {horizontale, verticale, oblique}, moment journée
- Attitude vicieuse ? Chercher déviation en position primaire par reflets
  cornéens

Examens :
- motilité
- cover-test (oeil dévié puis se redresse)
- au verre rouge (dissociation point rouge et blanc)
- test de Lancaster (superposer flèche de couleurs différente) \thus diagnostic
  paralysie oculomotrie
- RPM, inégalité pupillaire
  
** Sémiologie
- Paralysie du III : totale (ptosis total, mydriase aréflective, 0 accomodation)
ou partielle
- Paralysie du IV : diplopie verticale oblique
- Paralysie du VI : convergence oeil atteint, déficit abduction
- Formes particulières :
  - paralysie supranucléaire : sd Foville (latéralité), sd Parinaud (verticalité
    et cv \thus pinéalome++)
  - paralysie intranucléaire : ophtalmoplégie intranucléaire (parallélisme OK mais
    déficie adduction) \thus SEP
  - paralysie intraxile : {fonction et diplopie, diplopie et signe neuro
    controlatéraux}

** DD
Diplopie monoculaire, simulation, hystérie

** Étiologie
- Traumatique : fracture du plancher de l'orbite (élévation globe douleureuse),
  hémorragie méningé traumatique
- Tumeurs : HTIC, de la base du crâne
- Vasculaires : AVC, insuf vertébrobasilaire, *anévrime
  intracranien* (Y penser si atteinte partielle, signes
  pupillaires, sujet jeune, 0 FR vasc, céphalée \thus angioscanner urgence
  \skull)A, fistule carotidocaverneuse
- Avec exophtalmie : Basedow, tumeurs de l'orbite
- douleureuse : penser anévrisme intracrânnien, dissection carotidienne, fistule
  carotidocaverneuse = urgence \skull. Maladie de Horton. Sd Tolosa-Hunt
- SEP : paralysie VI, ophtalmoplégie internucléaire
- Myasthénie : diag = {test Prostigmine, Ac anti récepteur acétylcholine, électromyographie}
* 6 Oeil rouge/douloureux
** Examen
Interrogatoire : mode d'apparition, douleur superficielle/profonde, BAV
   ?, ATCD ophtalmo et généraux, signes locaux associés
   
Examen à lampe à fente (bilatéral) :
- acuité visuelle
- conjonctive : rougeur en nappe hémorragique (hémorragie
  sous-conjonctivale[fn:12], diffuse (conjonctivite), secteur (épisclérite),
  cercle (kératite aigüe, uvéite antérieure)
  périkératique
- cornée : perte de transparence, dépôts rétro-cornéens
- collyre à fluorescine pour ulcération cornéenne : unique (trauma), localisée
  avec zone blanche (kératite bactérienne), dendritique (kératite herpétique),
  petites ed disséminées (kératite à adénoviruse, sd sec oculaire, corps
  étranger)
- iris et pupille : synéchie iridocristallinienne (uvéite), atrophie iris
  (herpès), myosis (kératite aigùe, uvéite aigǜe), semi-mydriase
  aréflexique (glaucome aigü)
- chambre antérieure : étroite, plate (glaucome aigù, plaie perforante), signes inflammatoires
- tonus oculaire : hypertonie (glaucome aigu par fermeture de l'angle, glaucome
  néovasculaire), hypotonie (plaie oculaire transfixiante)
- conjonctive palpébrale : follicules (conjonctivite virale), papilles
  (conjonctivite allergique), corps étranger 
- FO 

** Étiologies
Oeil rouge, non douloureux, sans BAV
- hémorragie sous-conjonctivale spontanée : chercher HTA, trouble
  coagulation. Penser corps étranger, plaie sclérale \danger
- conjonctivite : "grain de sable", prurit
- conjonctivite  bactérienne : sécrétions mucopurulentes (paupières collées le
matin). Germe Gram+. /Ttt/ : hygiène des mains, lavage sérum phy, collyre
antiseptique (pas forcément ATB !!)

Oeil rouge unilatéral, douloureux, sans BAV
- épisclérite (sous conjonctive) : rougeur disparaissant avec collyre
  vasoconstricteur. /Ttt/ corticothérapie locale
- sclérite : douleur \inc mobilisation du globe. Ne disparait pas au
  collyre. Cherche maladie de système (articulaire, vasc, granulomateuse,
  infectieuse). /Ttt/ AINS générale et cause.

Yeux rouges bilatéraux, douloureux, sans BAV
- conjonctivite virale : fréq++, contagieux. Sécrétion claires, ADP prétragienne
  douloureuses à palpation. /Ttt/ inutile
- conjonctivite allergique : terrain, prurit, chemosis[fn:13], sécrétion claire,
  volumineuses papilles. /Ttt/ bilan allergique, évition, collyre antiallergique
- conjonctivite à \bact{chlamydia} : tiers-monde++
- sd sec oculaire : fréq++. Diag = test Schirmer (quantité sécrétion lacrymale),
  qualité film lacrymal, surfarce cornéenne, surface conjonctivale}. Cause :
  involution (âge), sd Gougerot-Sjögren. /Ttt/ substituts lacrymaux, évictions
  facteurs irritants, occlusion points lacrymaux
- autres : Basedow, malpositions palpébrale, conjonctivite d'irritation

Oeil rouge, douloureux, BAV
- Kératite aigüe : BAV, douleurs
  superficielles importantes, larmoiement, photophobie,
  blépharospasme. Érosion/ulcérationsc cornée, \dec transparence cornée,
  cercle périkératique
  - kératite à adénovirus : petite ulcérations disséminées. Évolution favorable
    (?)
  - kératite herpétique : ulcération en "feuille de fougère". /Ttt/ :
    valaciclovir \pm aciclovir en pommadex. Jamais de corticothérapie locale
    sans avoir élimine une ulcération cornéenne \skull
  - kératite zostérienne : zona ophtalmique \thus (?) kératite superficielle ou
    neuroparalytique (grave). 9Ttt/ : valaciclovir et protecteurs locaux
    cornéens
  - kératite bactérienne, parasitaire, mycosique : plage blanchâtre. Prélèver
    sur l'abcès. /ttt/ collyre ATB (si important : "collyre fortifiés"). \danger
    évolution : endophtalmie, perforation cornéenne, taie cornéenne cicatricielle
  - kératite sur sd sec
  - kératite d'exposition (paralysie faciale) : /ttt/ protecteurs cornéens en
    prévention, tarsorraphie (=suture)
- Uvéite antérieure : cercle périkératique, transparence cornée OK, myosis,
  (synéchies iridocristalliniennes ou iridocornéennes), Tyndall, précipités
  rétro-cornéens. FO systématique ! 
  - Causes : inconnue, spondylarthrite ankylosante (diag = {sacro-iléite, rachis,
    Ag HLA B27), uvéite herpétique, arthrite juvénile idiopathique, sarcoïdose,
    Behçet, lupus erythémateux disséminé.
  - /Ttt/ collyre mydriatique, collyres corticoïdes
- Glaucome aigu par fermeture de l'angle : rare, pronostic sévère.
  - prédisposition anatomique, pendant une mydriase
  - humeur aqueuse ne peut plus passer dans la chambre antérieure, s'accumule
    dans champre postérieure et bloque le trabeculum.
  - signes fonctionnels .: douleurs profondes++ irradiant dans trijumeau,
    souvent nausées, vomissement, BAV
  - examen : douleurs intenses, oeil rouge, transparence cornée \dec diffuse,
    semi-mydriase aréflexique, angle iridocornéen fermé, hypertonie oculaire++
  - cécité en qq jours sans ttt \danger 
  - /ttt/ = urgence \skull : antalgique, inhibiteurs de l'anhydrase
    carbonique [fn:14], solutés hyperosmolaires[fn:15], collyre hypotonisants,
    collyres myotiques
  - post-crise : iridotomie périphérique sur *les deux yeux* (laser ou chir)
- Glaucome néovasculaire : VEGF crée néovaisseux qui empêche la résorption de
  l'humeur aqueuse
  - néovaisseaux sur l'iri
  - /Ttt/ hypotonisants locaux et généraux, photocoagulation ou injection anti-VEGF
- Endophtalmie post-opératoire : douleur intense, oedème palpébral, hyalite
* Footnotes

[fn:15]  Déshydratation du vitré

[fn:14] \dec production d'humeur aqueuse.

[fn:13] Oedème conjonctival

[fn:12] Cherche plaie conjonctivale !

[fn:11] \danger méconnu si ptosis/oedème palpébral

[fn:10] Monoculaire : cause cornéenne, irienne, cristalinienne \thus pas une urgence.

[fn:9] Abrasion épithelium cornéen ou volet dans cornée.

[fn:8] Chez l'enfant, cycloplégique

[fn:7] Courbure de la cornée

[fn:6] Si BAV, vasculaire probable. Sinon HTIC

[fn:5] Punctiformes, flammèches, profondes

[fn:4] Cellules inflammatoires, protéines dans l'humeur aqueuse

[fn:3] Oedème conjonctival

[fn:2] Plus de voie efférente \thus oeil atteint : RPM direct aboli. Oeil sain : RPM consensuel aboli

[fn:1] Plus de voie afférente  \thus RPM (réflexe photomoteur) direct et
consensuel aboli pour l'oeil atteint
