#+title: Ophtalmologie
#+author: Alexis Praga
#+latex_header: \usepackage{booktabs}
#+latex_header: \input{header}
#+latex_header: \usepackage[linesnumbered,ruled,vlined]{algorithm2e}
#+OPTIONS: H:4

\input{bacteries-header}
* 1 Sémiologie oculaire
** Globe
Membranes (d'avant en arrière)
- externe = {cornée (avant), conjonctive (sur sclère antérieure), sclère}
- intermédiaire (uvée) = {iris, corps ciliaires, choroïde}
- interne (rétine) = {épithelium pigmentaire, neurosensorielle (photorécepteurs,
  fibres optiques}}. NB : phototransduction = pigment visuel
  (épithelium) \rightarrow photorécepteurs (bâtonnets = {vision périphérique,
  nocturne}, cône = {détails, couleurs} \in macula)
Contenu : 
- humeur aqueuse \in chambre antérieure, évacuée dans l'angle iridocornéen. P
  normale si \le 22 mmHg.
- cristallin : biconvexe, convergente, déformation par zonule \thus accomodation
- corps vitré : 4/5e cavité oculaire \thus segment antérieur vs postérieur
Voies optiques : 
- nerf optique - chiasma - bandelettes optiques - corps genouillés externes - radiations optiques - cortex occipital
- mydriase "sensorielle"[fn:1] vs "paralytique"[fn:2]
- voie efférente sympathique : si atteinte, sd Claude-Bernard-Horner (myosis, ptosis)
Annexes
- oculomoteur : nerf IV = {oblique supérieur}, VI = {droit externe} et III =
  {droit sup, droit inf, droit médial, oblique inf}
- protection : paupière (muscle orbiculaire, tarse), conjonctive (face interne
  paupière, globe antérieur), film lacrymal
  
** Examen
Interrogatoire : 
- baisse d'acuité visuelle (BAV), fatigue visuelle, myodésopsise,
métamorphopsies, héméralopie, scotome/amputation champ visuel, 
- mode d'installation : urgente si brutal
- douleur superficielles/profondes
- diplopie mono/bi-noculaire
- évolution : aggration rapide = grave
Acuité visuelle : échelle de Monoyer (à 5m), de Parinaud (33cm)

Segment antérieur : "lampe à fente"
- conjonctive : rougeur (diffuse/localisée/culs-de-sac inférieure/avec
  sécrétions/cercle périkératique/paupière), chemosis[fn:3]
- cornée (transparence)
- iris : myosis/mydriase
- chambre antérieure : inflammation (Tyndall[fn:4], précipités rétro-cornéens,
  synéchies iridocristaliniennes), hypopion (pus), hyphéma (sang)
Pression intraoculaire par tonomètre à air pulsé. Hypertonie si \ge 22 mmHg

Gonioscopie : angle iridocornéen

Fond d'oeil
- direct, indirect (apprentissage++), biomicroscopie
- aspect : pôle postérieur = {papille, vaisseaux rétitiens, macula}, rétine
  périphérique (si besoin)
- lésions : microanévrisme (points rouges), hémorragie (intravitréennes,
  prérétiniennes, sous-rétiniennes, intra-rétiniennes[fn:5]), nodules cotonneux,
  exsudats profonds, oedème papillaire[fn:6]

Oculomotricité

** Complémentaires
Fonctions visuelles
- Champ visuel :
  - sensibilité lumineuse \dec périphérie, papille = zone aveugle
  - périmétrie cinétique (Goldman : trace isoptères) ou statique (dépistage
  glaucome)
- Vision des couleurs : si dépistage anomalie congénitale (planches colorées) ou
affection acquise (Farnsworth = classer couleurs). Utile pour antipaludéens de
synthèse ou {éthambutal, isoniazide}
Angiographie du fond d'oeils : fluorescine ou vert d'indocyanine (DMLA++)

Électrophysio : électrorétinogramme (si lésion rétiniennes étendues), potentiels
évoqués visuels (cortex occipital) (SEP++), électro-oculogramme (épithelium pigmentaire)

Echographie : mode A (longueur globe oculaire) ou B (décollement rétine, corps
étranger intraoculaire, tumeur)

Tomographie en cohérence optique (OCT) : affection maculaire (trou, DMLA),
dépistage glaucome chronique

* 2 Réfraction
Oeil \approx 60 dioptries (cornée = 42, cristallin = 20)
Emmétrope = oeil normal. Amétrope = anomalie de réfraction

Punctum remotum (PR) : point le plus éloigné visible /sans/ accomoder. Punctum
proximum (PP) = point le plus proche visible /en/ accomodant.

Acuité visuelle = $\frac{1}{\alpha}$ où \alpha = pouvoir séparateur de
l'oeil. Mesurée par l'échelle de Monoyer (de loin) en 10eme (!) et de Parinaud
(de près)

** Accomodation
Amplitude \dec jusque 0 (79 ans) \thus presbytie (BAV vision de près). Compensée
par verres sphériques convexes progressifs ou implant cristallinien

Sinon, \dec vision de près par : médicaments, paralysie III, maladie générale,
spasmes de l'accomodation

** Anomalies de la réfraction
Différencier maladie de l'oeil/voie optique et anomalie réfraction !

Examen : réfractomètres automatiques \thus réfraction, kératométrie[fn:7]. [fn:8]

*** Myopie 
Oeil trop convergent. \approx 20% population occidentale. PR à distance finie,
PP plus proche.

Types : myopie d'indice (\inc indice de réfraction), de courbure (courbure
cornée \inc) ou axile (longueur axiale \inc)

Myopie
- faible : < 6 dioptrie
- forte : > 6 dioptries ou longueur axiale \ge 26mm. Héréditaire, \in [1/10,
  5/10] /après/ correction. Complications : glaucome chronique à angle ouvert,
  cataracte, décollement de la rétine++

Correction : verres sphériques concaves.

Chirurgie par photoablation au laser ecited dimer[fn:9]. Chirugie du cristallin
possible.

*** Hypermétropie
Fréquent (enfant++). Pas assez convergent. PR = virtuel à l'arrière. Correction
par verres sphériques convexes, lentilles ou chir.

*** Astigmatisme
Rayons de courbures différents pour les méridiens. Régulier si 2 méridiens
principaux \bot.

1 point à l'infini = 2 droite perpendiculaire (= focales) \thus myopique,
hypermétropiique ou mixtes

Correction par verres cylindriques convexes/concaves, lentilles ou chir

* 3 Suivi d'un nourisson
Déficits mineurs (amétropie, strabisme) ou sévères (grave !) (milieux transparents,
  malforamtion, rétinopathie, atteintes neuro centrales)

20% d'enfant < 6 ans avec anomalie visuelle. Si non traitée, amblyopie (BAV),
définitive > 6ans !

Développement :
- 1ere semaine : réflexe lumière, RPM
- 2-4e semaine : reflexe de poursuite
- 4-12e semaine : reflexe de poursuite
- 3e mois : vision des formes
- 4-5e mois : coordinatio oeil-tête-main
- > 2 ans : AV mesurable
Examens obligatoires pour {strabisme, nystagmus, anomalie organique, trouble
comportement visuel}:
- dépistage anténal (écho)
- 1ere semaine
- 4eme mois
- 9eme mois
- 2 ans
- 3-6 ans
  
Dépistage : leucocorie, glaucome congénital, malformations, infections
maternelles, maladies enfants secoués, rétinopathie des prématurés
* 4 Strabisme de l'enfant
  
Position de l'oeil anormale et altération vision binoculaire. Provient d'une
perturbation de la fusion.

Conséquences :
- Si aigu : diplopie possible. Si ancien : corrigé par cerveaux \thus vision
binoculaire non acquise si strabisme dans premiers mois de vie !. Amblyopie
possible
- Perturbation vision stéréoscopie (3D)
 
Souvent dans l'enfance. 4% population. *Dépistage avant 2 ans*

** Dépistage
Jamais normal, toujours symptôme

Interrogatoire :
- date d'apparition
- horizontal : /eso-/ si convergent, /exo-/ si divergent. Vertical : /hyper-/,
  /hypo-/. Si divergent < 9 mois, examen neuroradio
- intermittent ?
- oeil dominé
  
Examen : 
- motilité : strabisme paralytique ?
- segment antérieur et FO (fond d'oeil) : perte transparence, patho rétinienne ? Si nystagmus : électrorétinogramme, PEV, IRM
- réfraction sous cycloplégique : amyotropie ? Hypermétropie fréuente
- acuité visuelle : amblyopie ? (> 2/10 entre 2 yeux)
- mesure de l'angle de déviation (si chir), vision binoculaire (pronostique)

** Traitement
Correction optique. Si amblyopie, occlusion de l'oeil dominant (jusque 6-8ans)

Chir si angle résident avec correction. Correction optique après opération
* Footnotes

[fn:9] Abrasion épithelium cornéen ou volet dans cornée.

[fn:8] Chez l'enfant, cycloplégique

[fn:7] Courbure de la cornée

[fn:6] Si BAV, vasculaire probable. Sinon HTIC

[fn:5] Punctiformes, flammèches, profondes

[fn:4] Cellules inflammatoires, protéines dans l'humeur aqueuse

[fn:3] Oedème conjonctival

[fn:2] Plus de voie efférente \thus oeil atteint : RPM direct aboli. Oeil sain : RPM consensuel aboli

[fn:1] Plus de voie afférente  \thus RPM (réflexe photomoteur) direct et
consensuel aboli pour l'oeil atteint
