#+title: Ophtalmologie
#+author: Alexis Praga
#+latex_header: \usepackage{booktabs}
#+latex_header: \input{header}
#+latex_header: \usepackage[linesnumbered,ruled,vlined]{algorithm2e}
#+latex_header: \usepackage[nonumberlist]{glossaries}
#+latex_header: \makeglossaries
#+latex_header_extra: \newacronym{RPM}{RPM}{Réflexe photomoteur}
#+latex_header_extra: \newacronym{DMLA}{DMLA}{Dégénérescence maculaire liée à l'âge}
#+latex_header_extra: \newacronym{PEV}{PEV}{Potentiels évoqués visuels}
#+latex_header_extra: \def\ttt{\hspace*{1cm}Ttt: }
#+latex_header_extra: \newacronym{NOIA}{NOIA}{Neuropathie optique ischémique antérieure}
#+latex_header_extra: \newacronym{GPAO}{GPAO}{Glaucome primitif à angle ouvert}
#+latex_header_extra: \newacronym{GNV}{GNV}{Glaucome néovasculaire}

#+OPTIONS: H:4

\input{bacteries-header}

* 1 Sémiologie oculaire
** Globe
Membranes (d'avant en arrière)
- externe = {cornée (avant), conjonctive (sur sclère antérieure), sclère}
- intermédiaire (uvée) = {iris, corps ciliaires, choroïde}
- interne (rétine) = {épithelium pigmentaire, neurosensorielle (photorécepteurs,
  fibres optiques}}. NB : phototransduction = pigment visuel
  (épithelium) \rightarrow photorécepteurs (bâtonnets = {vision périphérique,
  nocturne}, cône = {détails, couleurs} \in macula)
Contenu : 
- humeur aqueuse \in chambre antérieure, évacuée dans l'angle iridocornéen. P
  normale si \le 22 mmHg.
- cristallin : biconvexe, convergente, déformation par zonule \thus accomodation
- corps vitré : 4/5e cavité oculaire \thus segment antérieur vs postérieur
Voies optiques : 
- nerf optique - chiasma - bandelettes optiques - corps genouillés externes - radiations optiques - cortex occipital
- mydriase "sensorielle"[fn:1] vs "paralytique"[fn:2]
- voie efférente sympathique : si atteinte, sd Claude-Bernard-Horner (myosis, ptosis)
Annexes
- oculomoteur : nerf IV = {oblique supérieur}, VI = {droit externe} et III =
  {droit sup, droit inf, droit médial, oblique inf}
- protection : paupière (muscle orbiculaire, tarse), conjonctive (face interne
  paupière, globe antérieur), film lacrymal
  
** Examen
Interrogatoire : 
- baisse d'acuité visuelle (BAV), fatigue visuelle, myodésopsies, métamorphopsies, héméralopie, scotome/amputation champ visuel, 
- mode d'installation : urgence si brutal \skull
- douleur superficielles/profondes
- diplopie mono/bi-noculaire
- évolution : aggration rapide = grave
Acuité visuelle : échelle de Monoyer (à 5m), de Parinaud (33cm)

Segment antérieur : "lampe à fente"
- conjonctive : rougeur (diffuse/localisée/culs-de-sac inférieure/avec
  sécrétions/cercle périkératique/paupière), chemosis[fn:3]
- cornée (transparence)
- iris : myosis/mydriase
- chambre antérieure : inflammation (Tyndall[fn:4], précipités rétro-cornéens,
  synéchies iridocristaliniennes), hypopion (pus), hyphéma (sang)
Pression intraoculaire par tonomètre à air pulsé. Hypertonie si \ge 22 mmHg

Gonioscopie : angle iridocornéen

Fond d'\oe{}il
- direct, indirect (apprentissage++), biomicroscopie
- aspect : pôle postérieur = {papille, vaisseaux rétitiens, macula}, rétine
  périphérique (si besoin)
- lésions : microanévrisme (points rouges), hémorragie (intravitréennes,
  prérétiniennes, sous-rétiniennes, intra-rétiniennes[fn:5]), nodules cotonneux,
  exsudats profonds, \oe{}dème papillaire[fn:6]

Oculomotricité

** Complémentaires
Fonctions visuelles
- Champ visuel :
  - sensibilité lumineuse \dec périphérie, papille = zone aveugle
  - périmétrie cinétique (Goldman : trace isoptères) ou statique (dépistage glaucome)
- Vision des couleurs : si dépistage anomalie congénitale (planches colorées) ou
affection acquise (Farnsworth = classer couleurs). Utile pour antipaludéens de
synthèse ou {éthambutal, isoniazide}

Angiographie du fond d'\oe{}ils : fluorescine ou vert d'indocyanine (gls:DMLA++)

Électrophysio : électrorétinogramme (si lésion rétiniennes étendues), gls:PEV (cortex occipital) (SEP++), électro-oculogramme (épithelium pigmentaire)

Echographie : mode A (longueur globe oculaire) ou B (décollement rétine, corps
étranger intraoculaire, tumeur)

Tomographie en cohérence optique (OCT) : affection maculaire (trou, DMLA),
dépistage glaucome chronique

* 2 Réfraction
\OE{}il \approx 60 dioptries (cornée = 42, cristallin = 20)
Emmétrope = \oe{}il normal. Amétrope = anomalie de réfraction

Punctum remotum (PR) : point le plus éloigné visible /sans/ accomoder. Punctum
proximum (PP) = point le plus proche visible /en/ accomodant.

Acuité visuelle = $\frac{1}{\alpha}$ où \alpha = pouvoir séparateur de
l'\oe{}il. Mesurée par l'échelle de Monoyer (de loin) en 10eme (!) et de Parinaud
(de près)

** Accomodation
Amplitude \dec jusque 0 (79 ans) \thus presbytie (BAV vision de près). Compensée
par verres sphériques convexes progressifs ou implant cristallinien

Sinon, \dec vision de près par : médicaments, paralysie III, maladie générale,
spasmes de l'accomodation

** Anomalies de la réfraction
Différencier maladie de l'\oe{}il/voie optique et anomalie réfraction !

Examen : réfractomètres automatiques \thus réfraction, kératométrie[fn:7]. [fn:8]

*** Myopie 
\OE{}il trop convergent. \approx 20% population occidentale. PR à distance finie,
PP plus proche.

Types : myopie d'indice (\inc indice de réfraction), de courbure (courbure
cornée \inc) ou axile (longueur axiale \inc)

Myopie
- faible : < 6 dioptrie
- forte : > 6 dioptries ou longueur axiale \ge 26mm. Héréditaire, \in [1/10,
  5/10] /après/ correction. Complications : glaucome chronique à angle ouvert,
  cataracte, décollement de la rétine++

Correction : verres sphériques concaves.

Chirurgie par photoablation au laser excited dimer[fn:9]. Chirurgie du cristallin
possible.

*** Hypermétropie
Fréquent (enfant++). Pas assez convergent. PR = virtuel à l'arrière. Correction
par verres sphériques convexes, lentilles ou chir.

*** Astigmatisme
Rayons de courbures différents pour les méridiens. Régulier si 2 méridiens
principaux \bot{}.

1 point à l'infini = 2 droite perpendiculaire (= focales) \thus myopique,
hypermétropique ou mixtes[fn:26]

Correction par verres cylindriques convexes/concaves, lentilles ou chir

* 3 Suivi d'un nourisson
Déficits mineurs (amétropie, strabisme) ou sévères (grave !) (milieux transparents,
  malformation, rétinopathie, atteintes neuro centrales)

20% d'enfant < 6 ans avec anomalie visuelle. Si non traitée, amblyopie[fn:27] ,
définitive après 6ans !

Développement :
- 1ere semaine : réflexe lumière, RPM
- 2-4e semaine : reflexe de poursuite
- 4-12e semaine : reflexe de poursuite
- 3e mois : vision des formes
- 4-5e mois : coordinatio \oe{}il-tête-main
- > 2 ans : AV mesurable
Examens obligatoires pour {strabisme, nystagmus, anomalie organique, trouble
comportement visuel}: /dépistage anténal - S1 - 4M - 9M - 2A - 3 à 6A/
  
Dépistage : leucocorie, glaucome congénital, malformations, infections
maternelles, maladies enfants secoués, rétinopathie des prématurés
* 4 Strabisme de l'enfant
  
Position de l'\oe{}il anormale et altération vision binoculaire. Due à une perturbation de la fusion.

Conséquences :
- Si aigu : diplopie possible. Si ancien : corrigé par cerveau \thus vision binoculaire non acquise si strabisme dans premiers mois de vie !. Amblyopie possible
- Perturbation vision stéréoscopie (3D)
 
Souvent dans l'enfance. 4% population. *Dépistage avant 2 ans*

** Dépistage
Jamais normal, toujours symptôme

Interrogatoire :
- date d'apparition
- horizontal : /eso-/ si convergent, /exo-/ si divergent. Vertical : /hyper-/,
  /hypo-/. Si divergent < 9 mois, examen neuroradio
- intermittent ?
- \oe{}il dominé
  
Examen : 
- motilité : strabisme paralytique ?
- segment antérieur et FO (fond d'\oe{}il) : perte transparence, patho rétinienne ? Si nystagmus : électrorétinogramme, PEV, IRM
- mesure de réfraction sous collyre cycloplégique : amyotropie ? Hypermétropie fréquente
- acuité visuelle : amblyopie ? (> 2/10 entre 2 yeux)
- mesure de l'angle de déviation (si chir), vision binoculaire (pronostique)

** Traitement
Correction optique. Si amblyopie, occlusion de l'\oe{}il dominant (jusque 6-8ans)

Chir si angle résiduel avec correction. Correction optique après opération
* 5 Diplopie (binoculaire)
Binoculaire : disparaît à l'occlusion d'un \oe{}il[fn:10]. Souvent une urgence
\danger

Noyaux des nefs oculomoteurs \in tronc cérébral - racine - troncs -
muscle. Voies supranucléaires (latéralité, verticalité), internucléraires.

#+caption: Champ d'action (\danger \ne action) avec l'innervation
| oblique inférieur (III) | droit supérieur (III) |
|-------------------------+-----------------------|
| droit médial (III)      | droit latéral (VI)    |
|-------------------------+-----------------------|
| oblique supérieur (IV)  | droit inférieur (III) |

Mouvement bilatéraux : synergie des muscles

Vision binoculaire :
- loi de Hering : même influx nerveux pour muscles antagonistes. Loi de
  Sherrington : muscle antagonistes se relâchent quand muscles synergistes se
  contractent.
- si correspondance rétinienne anormale (yeux non \parallel) : diplopie
  
** Diagnostic
- Signes fonctionnels : dédoublement toujours même direction[fn:11], disparaît à
l'occlusion
- Interrogatoire : terrain, circonstance, brutal/progressif, {douleurs, vertiges,
céphalées, nausées}, {horizontale, verticale, oblique}, moment journée
- Attitude vicieuse ? Chercher déviation en position primaire par reflets
  cornéens

Examens :
- motilité
- cover-test (\oe{}il dévié puis se redresse)
- au verre rouge (dissociation point rouge et blanc)
- test de Lancaster (superposer flèches de couleurs différentes) \thus diagnostic
  paralysie oculomotrie
- RPM, inégalité pupillaire
  
** Sémiologie
- Paralysie du III : totale (ptosis total, mydriase aréflective, 0 accomodation) ou partielle
- Paralysie du IV : diplopie verticale oblique
- Paralysie du VI : convergence \oe{}il atteint, déficit abduction
- Formes particulières :
  - paralysie supranucléaire : sd Foville (latéralité), sd Parinaud (verticalité
    et cv \thus pinéalome++)
  - paralysie intranucléaire : ophtalmoplégie intranucléaire (parallélisme OK mais
    déficit adduction) \thus SEP
  - paralysie intraxiale : (atteinte fonction et diplopie) ou (diplopie et signe neuro
    controlatéraux)
** DD
Diplopie monoculaire, simulation, hystérie

** Étiologie
- Traumatique : fracture du plancher de l'orbite (élévation globe douleureuse),
  hémorragie méningé traumatique
- Tumeurs : HTIC, de la base du crâne
- Vasculaires : AVC, insuf vertébrobasilaire, *anévrisme
  intrâcranien* (Y penser si atteinte partielle, signes
  pupillaires, sujet jeune, 0 FR vasc, céphalée \thus angioscanner urgence
  \skull), fistule carotidocaverneuse
- Avec exophtalmie : Basedow, tumeurs de l'orbite
- douleureuse : penser {anévrisme intracrânnien, dissection carotidienne, fistule
  carotidocaverneuse} = urgences \skull. Maladie de Horton. Sd Tolosa-Hunt
- SEP : paralysie VI, ophtalmoplégie internucléaire
- Myasthénie : diag = {test Prostigmine, Ac anti récepteur acétylcholine, électromyographie}
* 6 \OE{}il rouge/douloureux
** Examen
Interrogatoire : mode d'apparition, douleur superficielle/profonde, BAV
   ?, ATCD ophtalmo et généraux, signes locaux associés
   
Examen à lampe à fente (bilatéral) :
- acuité visuelle
- conjonctive : rougeur en nappe hémorragique (hémorragie
  sous-conjonctivale[fn:12], diffuse (conjonctivite), secteur (épisclérite),
  cercle (kératite aigüe, uvéite antérieure)
  périkératique
- cornée : perte de transparence, dépôts rétro-cornéens
- collyre à fluorescine pour ulcération cornéenne : unique (trauma), localisée
  avec zone blanche (kératite bactérienne), dendritique (kératite herpétique),
  petites et disséminées (kératite à adénoviruse, sd sec oculaire, corps
  étranger)
- iris et pupille : synéchie iridocristallinienne (uvéite), atrophie iris
  (herpès), myosis (kératite aigüe, uvéite aigüe), semi-mydriase
  aréflexique (glaucome aigü)
- chambre antérieure : étroite, plate (glaucome aigü, plaie perforante), signes inflammatoires
- tonus oculaire : hypertonie (glaucome aigu par fermeture de l'angle, glaucome
  néovasculaire), hypotonie (plaie oculaire transfixiante)
- conjonctive palpébrale : follicules (conjonctivite virale), papilles
  (conjonctivite allergique), corps étranger 
- FO 

** Étiologies

#+caption: Étiologies résumées d'\oe{}il rouge
| Non douloureux sans BAV     | Douloureux avec BAV                           |
|-----------------------------+-----------------------------------------------|
| hémorragie ss-conjonctivale | kératite aigüe                                |
| conjonctivite               | uvéite antérieure aigüe |
| (épi)sclérite               | crise aigüe de glaucome par fermeture d'angle |
|                             | glaucome néovasculaire                        |

*** \OE{}il rouge, non douloureux, sans BAV
- /hémorragie sous-conjonctivale spontanée/ : chercher HTA, trouble
  coagulation. Penser corps étranger, plaie sclérale \danger
- /conjonctivite/ : sensation de "grain de sable", prurit
- /conjonctivite bactérienne/ : sécrétions mucopurulentes (paupières collées le
  matin). Germe Gram+. 
\ttt hygiène des mains, lavage sérum phy, collyre antiseptique (pas forcément ATB !!)

\OE{}il rouge unilatéral, douloureux, sans BAV
- /épisclérite/ (sous conjonctive) : rougeur disparaissant avec collyre
  vasoconstricteur. 
\ttt corticothérapie locale
- /sclérite/ : douleur \inc mobilisation du globe. Ne disparait pas au
  collyre. Cherche maladie de système (articulaire, vasc, granulomateuse,
  infectieuse). 
\ttt AINS générale et cause.

*** Yeux rouges bilatéraux, douloureux, sans BAV
- /conjonctivite virale/ : fréq++, contagieux. Sécrétion claires, ADP prétragienne
  douloureuses à palpation. 
\ttt inutile
- /conjonctivite allergique/ : terrain, prurit, chemosis[fn:13], sécrétion claire,
  volumineuses papilles. 
\ttt bilan allergique, éviction, collyre antiallergique
- /conjonctivite à \bact{chlamydia}/ : tiers-monde++
- /sd sec oculaire/ : fréq++. Diag = test Schirmer (quantité sécrétion lacrymale),
  qualité film lacrymal, surfarce cornéenne, surface conjonctivale}. Cause :
  involution (âge), sd Gougerot-Sjögren. 
\ttt substituts lacrymaux, évictions
  facteurs irritants, occlusion points lacrymaux
- autres : Basedow, malpositions palpébrale, conjonctivite d'irritation

*** \OE{}il rouge, douloureux, BAV
- /Kératite aigüe/ : BAV, douleurs
  superficielles importantes, larmoiement, photophobie,
  blépharospasme. Érosion/ulcérationsc cornée, \dec transparence cornée,
  cercle périkératique
  - /kératite à adénovirus/ : petite ulcérations disséminées. Évolution favorable
    (?)
  - /kératite herpétique/ : ulcération en "feuille de fougère". 
\ttt
    valaciclovir \pm aciclovir en pommade. Jamais de corticothérapie locale
    sans avoir éliminé une ulcération cornéenne \skull
  - /kératite zostérienne/ : zona ophtalmique \thus (?) kératite superficielle ou
    neuroparalytique (grave). 
\ttt valaciclovir et protecteurs locaux
    cornéens
  - /kératite bactérienne, parasitaire, mycosique/ : plage blanchâtre. Prélèver
    sur l'abcès. 
\ttt collyre ATB (si important : "collyre fortifiés"). \danger
    évolution : endophtalmie, perforation cornéenne, taie cornéenne cicatricielle
  - /kératite sur sd sec/
  - /kératite d'exposition/ (paralysie faciale) : 
\ttt protecteurs cornéens en prévention, tarsorraphie (=suture)
- /Uvéite antérieure/ : cercle périkératique, transparence cornée OK, myosis,
  (synéchies iridocristalliniennes ou iridocornéennes), Tyndall, précipités
  rétro-cornéens. FO systématique ! 
  - Causes : inconnue, spondylarthrite ankylosante (diag = {sacro-iléite, rachis,
    Ag HLA B27), uvéite herpétique, arthrite juvénile idiopathique, sarcoïdose,
    Behçet, lupus erythémateux disséminé.
\ttt collyre mydriatique, collyres corticoïdes
- /Glaucome aigu par fermeture de l'angle/ : rare, pronostic sévère.
  - prédisposition anatomique, pendant une mydriase
  - humeur aqueuse ne peut plus passer dans la chambre antérieure, s'accumule
    dans chambre postérieure et bloque le trabeculum.
  - signes fonctionnels .: douleurs profondes++ irradiant dans trijumeau,
    souvent nausées, vomissement, BAV
  - examen : douleurs intenses, \oe{}il rouge, transparence cornée \dec diffuse,
    semi-mydriase aréflexique, angle iridocornéen fermé, hypertonie oculaire++
  - cécité en qq jours sans ttt \danger 
\ttt antalgique, inhibiteurs de l'anhydrase en urgence \skull
    carbonique [fn:14], solutés hyperosmolaires[fn:15], collyre hypotonisants,
    collyres myotiques
  - post-crise : iridotomie périphérique sur *les deux yeux* (laser ou chir)
- /Glaucome néovasculaire/ : VEGF crée néovaisseux qui empêche la résorption de
  l'humeur aqueuse
  - néovaisseaux sur l'iris
\ttt hypotonisants locaux et généraux, photocoagulation ou injection anti-VEGF
- /Endophtalmie post-opératoire/ : douleur intense, \oe{}dème palpébral, hyalite
  
\begin{tcolorbox}
Uvéite : penser maladie générale (rhumatismal, sarcoïdose, MICI, arthrite juvénile idiopathique [enfant++])
\end{tcolorbox}

* 7 Altération de la fonction visuelle
** Examen
Interrogatoire : BAV objective, altération CV  (myodésopsies, phosphènes,
métamorphopsies, éclipse visuelle (qq secondes) ou cécité monoculaire
transitoire (qq min-heures), aura visuelle), installation, unilatéral ?, douleur
? ATCD, ttt, traumatisme ?

Examen ophtalmo : AV (avec correction), RPM, segment antérieur, tonus oculaire,
{cristallin, vitré, rétine, vaisseaux, nerf optique}

** BAV progressive [fn:16]
Si améliorée par correction optique, trouble de réfraction. Sinon :

*** Transparence anormale
/Cataracte/ : BAV bilatérale, photophobie, myopie d'indice, diplopie
monoculaire. Perte de transparence du cristallin (opalescent). Étiologie : âge
surtout.\\
\ttt chir

Autres : /cornée, vitré/ (hyalite des uvéite)

*** Transparence normale: atteinte nerf optique
/Glaucome chronique à angle ouvert/ (GCAO) : longtemps asymptomatique. Diag =
{\inc tonus oculaire, altération CV, excavation glaucomateuse de la
papille}. \\
\ttt collyre hypotonisants, trabéculoplastie (laser/chir)

Autres : /neuropathie toxiques/ (alcool-tabac, médic), /héréditaires, compressive/

*** Transparence normale: atteinte de la rétine/macula
Dystrophies rétiniennes héréditaires :
- /maculopathies héréditaires/ : maladie de Stargardt = débute vers 7-12 ans,
  1/10e en fin d'évolution (!), en "\oe{}il de b\oe{}uf"
- /rétinopathies pigmentaires/ : héméralopie, rétrécissement progressif du CV
  (débute dans l'enfance), aspect réticulé "en ostéoblastes"
"Interface vitréomaculaire" = /séparation vitré-région maculaire/
- membranes épi-/pré-maculaire (par tissu fibreux). "reflet" cellophane". OCT
  maculaire. Chir possible
- trous maculaires : OCT
/Dégénérescence maculaire liée à l'âge/

/\OE{}dème maculaire/ : en "pétales de fleur" si important. Causes : 
  - rétinopathie diabétique : /ttt/ : injection IV anti-VEGF ou corticoïdes
  - occlusion veine centrale de la rétine : /ttt/ idem
  - chir cataracte 
  - uvéite postérieures : /ttt/ : cause ou corticoïdes retard
    
/Maculopathies toxiques aux antipaludéens de synthèse/ : potentiellement cécité
irréversible. Pas avant 5 ans ? Commence par périfovéolopathie \thus arrêt
immédiat du ttt \danger

** Altération du CV
= altération vision périphérique

*** Affections rétiniennes 
Scotomes (para)centraux , déficits périphériques

*** Atteinte des voies optiques
Atteinte nerf optique : cécité unilatérale (trauma, tumeur) 
- scotome central unilatéral ou caecocentral uni-/bi-latéral
- déficicit fasciculaire possible
- déficit altitudinal si gls:NOIA
- étiologies :
  - SEP (névrite optique rétrobulbaire)
  - NOIA 
  - toxiques et métabolique : bilatéral, progressive. {alcool-tabac, médicament,
    professionnelle, métabolique}, tumoral (tumeurs intraorbitaires, étage
    antérieur du crâne)}

Lésion du chiasma optique : hémianopsie/quadranopsie bitemporale (décussation
!). Étiologies : adénome hypophyse surtout

Lésions rétrochiasmatique : hémianopsie latérale homonyme. Si atteinte des
radiaton optiques, quadranopsie latérale homonymes. Étiologies vasc, tumoral,
trauma

Cécité corticale : bilatérale, brutale. Examen ophtalmo OK, RPM OK,
désorientation, hallucination visuelles, anosognosie
* 8 Anomalies de la vision d'apparition brutale
** Diagnostic
Interrogatoire : BAV ? altération CV ? myodésopsies,  phosphènes,
métamorphopsies ? rapidité, latéralité, type de douleurs, ATCD, ttt, trauma ?

Examen ophtalmo ( 2 yeux) : AV, RPM, segment antérieur, tonus oculaire, FO

** Étiologie
*** BAV, \oe{}il rouge et douloureux 
- /kératite aigüe/ : douleur superficielles importantes, photophobie,
  blépharospasme. \dec transparence cornée, cercle périkératique, ulcération(s)
  cornéenne(s)
- /glaucome aigü par fermeture de l'angle/ : douleurs profondes, intense,
  irradiant dans trijumeaux. \inc\inc tonus oculaire ("bille de bois" à la
  palpation)
- /uvéites/
  - /antérieure aigüe/ : BAV, douleurs, cercle périkératique, myosis par synéchies
    iridocristalliniennes. Tyndall, chercher uvéite postérieure
  - /postérieure/ : toxoplasmose oculaire le plus souvent. Myodésopsies, BAV. FO =
    foyer blanchâtre puis cicatrice. \\
\ttt antiparasitaire si AV menacée
- autres  : glaucome néovasculaire, endophtalmie (contexte post-op)

*** BAV, \oe{}il blanc indolore
- FO non visible 
  - /hémorragie intravitréenne/ : précédée d'une "pluie de cendre", BAV
    variable. Écho. B pour éliminer un décollement de la rétine. Causes :
    rétinopathie diabétique proliférante, occlusions ischémique de la veine
    centrale de la rétine, déchirure rétinienne, sd de Terson[fn:17], plaie
    perforante
  - /uvéite intermédiaire/ (dans le vitré) : cellules inflammatoires
- FO visible anormal
  - /occlusion de l'artère centrale de la rétine/ : BAV brutale, mydriase
    aréflexique et RPM direct aboli, \dec diffuse du calibre artériel, \oe{}dème
    blanc rétinien ischémique de la rétine (macula rouge cerise)
  - /occlusion de la veine centrale de la rétine/ : BAV variable, {\oe{}dème
    papillaire, hémorragie rétiniennes disséminées, nodules cotonneux,
    tortuosités veineuse}. Préciser si ischémique
  - /DMLA/ : BAV et métamorphopsies brutales, décollement exsudatif de la rétine
    maculaire \pm hémorragies, exsudats profonds
  - /décollement de la rétine rhegmatogène/ : après une déhiscence, le vitré va
    sous la rétine. 
    - causes : idiopathique (âgé), myopie (forte), chir cataracte
    - évolution spontanée = cécité
    - /ttt/ chir (semi-urgence \danger) 
    - clinique : myodésopsies, phosphènes, amputation CV périphérique, BAV
    - diag par FO : rétine en relief, mobile, avec des plis
    - toujours examiner \oe{}il controlatéral (ttt préventif par photocoagulation)
      \danger
  - /neuropathie optique ischémique antérieure/ : BAV unilatérale brutale, \dec
    RPM direct, \oe{}dème papillaire, déficit fasciculaire pour CV. Cause : surtout
    artériosclérose mais penser à Horton (urgence \skull)
- FO visible normal
  - /névrite optique rétrobulbaire/ : BAV unilatérale progresse en qq jours (!),
    douleur \inc mouvement oculaires, RPM direct \dec, FO normal, scotome
    (caeco)-central
  - /atteinte des voies (rétro)chiasmatiques/ : tumorale (si progressive), vasc (si brutale)
    
Anomalies transitoire 
  - /cécité monoculaire transitoire/ (qq minute) = amarause. FO pour embole
    rétinien. Urgence \skull. Chercher athérome carotidien, cardiopathie embolinogène
  - insuf vertébrobasilaire, éclipses visuelle, scotome scintillant
* 9 Prélèvement de cornée
Le médecine prélèveur \ne celui qui a fait le constat de mort

Sérologies à faire : HIV, HTLV, hépatite B et C, syphilis

CI :
- locale : chir sur segment antérieure, uvéite, conjonctivite, tumeur,
  rétinoblastome, mélanome choroïdien
- infectieuses (Sida, rage, Creutzfeld-Jakob, hépatite..),
- neuro inexpliquée, démence

Prélèvement *in situ*

* 10 Greffe de cornée
Couches (depuis l'extérieur) = épithelium, couche de Bowman, stroma, membrane
  de Descemet, endothelium
  
Techniques
- kératoplastie transfixiante = toute les couches
- kératoplastie lamellaire antérieure = épithelium, Bowman et stroma seulement
- kératoplastie endothéliale : membrane de Descemet et endotheliale seulement.

Indications : trauma perforant de la cornée, brûlures chimiques, dégénérescence
cornéenne (kératocône), kératite (herpétique), dystrophie bulleuse chez âgé

Bon pronostic dans $\frac{2}{3}$

Complications rares (retard d'épithélialisation, \oe{}dème cornéen précoce, rejet
immunitaire, récivide de maladie causale, hypertonie oculaire, astigmatisme post-op)
* 11 Traumatismes oculaires
** Globe fermé (contusions)
Dangerosité inversement \propto taille agent.

Interrogatoire : douleurs, AV, heure dernier repas, lésions associées.

Examen :
- contusions du segment antérieur 
  - cornée : /ttt/ lubrifiant cicatrisant
  - conjonctive : plaie ou hémorragie sous-conjonctivale. Toujours chercher plaie
    sclérale, corps étranger
  - chambre antérieure : hyphéma. Résorption spontanée
  - iris : iridodyalise [fn:18], rupture sphincter irien, mydriase post-trauma
  - cristallin : (sub)luxation, cataracte contusive (plusieurs mois après...)
  - hypertonie oculaire : si lésions de l'angle iridocornée, hyphéma, luxation
    antérieure du cristallin
- contusions du segment postérieur
  - \oe{}dème rétinien du pôle supérieur : guérison spontanée
  - hémorragie intravitréenne : résorption spontanée. Écho B si décollement de
    rétine (DR) suspecté
  - déchirure rétiniennes périph. Photocoagulation prophylactique possible
    (contre DR)
  - rupture de la choroïde : BAV définite si macula

** Globe ouverts
Rupture du globe : pronostic plus péjoratif si postérieur

Trauma perforant : 
- AVP, accidents domestique, bricolage, agression.
- plaies : larges (mauvais pronostic) ou petites (cornée ou sclère)
- risque : méconnaître plaie, corps étranger. Si doute, scanner !

** Corps étrangers
Diagnosic évident : 
- superficiel 
  - circonstance, symptôme de conjonctivite ou kératite superficielle. Corps étranger souvent visible
  - bon pronostic, ttt lubrifiant et antiseptique/ATB local
- intraoculaire : circonstance, porte d'entrée et trajet visible
Délicat si trauma non remarqué, pas de porte d'entrée, trajet et corps non visible

Examens : TDM si doute. Pas d'écho B si transfixiante. Pas d'IRM \danger

Complications (si intraoculaire) : endophtalmie (grave++), DR, cataracte traumatique

Complications tardives : ophtalmie sympathique [fn:19], sidérose (fer), chalcose (cuivre)
* 12 Brûlures oculaires
Accident industriels (graves), domestiques, aggression

Brûlures 
- thermique : peu grave (brûlure par cigarette). Cicatrisation rapide, sans séquelles
- acides : gravité modérée-moyenne, grave si très concentré
- basiques : grave !
  
Classification de Roper-Hall
1. bon pronostic 
2. bon pronostic : opacité cornéenne mais détails iris, ischémie < 1/3 \diameter
3. pronostic réservé : désépithélialisation cornéenne totale, opacité cornéenne
   , ischémie \in [1/3, 1/2] \diameter
4. pronostic péjoratif 

Ttt d'urgence par lavage (20-30min) par sérum phy (ou eau), puis collyre
corticoïde ASAP

Autres :
- brûlures des UV (ski, UV)
- soudure à l'arc sans lunette
- phototraumatisme (éclipse) : BAV définitive !

* 13 Cataracte
Déf: opacification (partielle ou non) du cristallin. 

** Diagnostic
Découvert sur BAV (progressive, vision de loin), photophobie, (diplopie
monoculaire), jaunissement

Examen clinique :
- interrogatoire : âge, profession, ATCD (diabète, corticoïdes), myodésopsies,
  métamorphopsies
- AV (\oe{}il par \oe{}il, bionculaire)
- lampe à fente : 
  - cristallin (caracte {nucléaire, sous-capsulaire postérieure, corticale, totale})
  - éliminer autre patho (cornée, iris, vitré, rétine (DMLA, glaucome))
  - mesure tonus oculaire (hypertonie, glaucome)

Diagnostic clinique mais en complémentaire :
- écho en mode B si décollement de rétine/tumeur intraoculaire
- pour le cristallin artificiel : kératométrie, longeur axiale

Étiologies :
- âge++
- traumatique (contusion violent, trauma perforant)
- secondaire à uvéites chroniques (postérieures), myopie forte, rétinopathie
  pigmentaires, chir oculaire
- secondaire à diabète, hypoparathyroïdie
- secondaire aux corticoïdes locaux/généraux au long cours, à radiothérapie
  orbitaire
- secondaire à dystrophie myotonique de Steinert, trisomie 21
- congénitales

** Traitement = chir
Anesthésique topique/locorégionale[fn:28], en ambulatoire. Sous dilatation
pupillaire. 

Technique = extraction extracapsulaire automatique par phacoémulsification. Puis
collyre anti-inflammatoire+ATB (1 mois).

Correction optique : implant de chambre postérieure (rarement antérieure)
- monofocal = sphérique (hypermétropie/myopie) ou torique (idem + astigmatisme)
- multifocaux : corrige vision de loin et de près
- si implant impossible : lentilles de contact/ ou lunettes (exceptionnel)

Indication : quand BAV = 5/10.

Complications :
- opacification de la capsule postérieure
- endophtalmie[fn:29] : à J2-J7. Ttt : ATB local, intravitréenne et générale
- décollement de la rétine
- \oe{}dème maculaire : semaines/mois. ttt : anti-inflammatoire
  (local/locorégional)
- kératite bulleuse

* 14 Glaucome chronique
= gls:GPAO. Neuropathie optique progressive altérant la fonction/structure.

FR : âge, hypertonie oculaire (\ne cause !!), ATCD familaux directs, noirs
d'origine africaine, myopie

Physio : perte accélérée des fibres optiques liée à l'âge

** Formes cliniques :
GPAO à pression élevée (> 21 mmHg) (70% des pop. occidentales)
- anomalies de structures visibles cliniquement : papille = {\dec surface,
  hémorragies péripapillaires en flammèches, atrophie péripapillaire de type \beta, \inc
  excavation papillaire}. Rapport de taille entre papilles des 2 yeux > 0.2
  \thus suspect
- autres anomalies de structures : OCT
- anomalies de foncton : champ visuel mais AV touchée très tardivement

GPAO à pression normale (70% pop. asiatique) : plutôt femmes, migraine, acrosyndromes

DD : 
- hypertonie oculaire : pression intraoculaire > 21mmHg, angle ouvert (gonio),
  \emptyset neuropathie optique. Pas forcément de ttt.
- glaucomes à angles ouvert secondaires
- glaucomes par fermeture de l'angle
- crise aigüe de fermeture de l'angle : douleur, urgence \skull
- neuropathie optiques non glaucomateuses

** Traitement
Dépistage : seulement ATCD familaux de GPAO, myopie, > 40 ans

Ttt : \dec pression intra oculaire

Médicaments :
- à vie 
- 1ere intention : collyre à base de prostaglandines [fn:20](\inc élimination humeur
  aqueuse) ou collyre betabloquant
  (\dec sécrétion humeur aqueuse)
- association possible mais \le 3
- rarement : acétazolamide par voie générale
  
Trabéculoplastie au laser = photocoagulation de l'angle. Effet modeste, non durable.

Chir : trabéculectomie. Complications (rare) = cataracte, hypotonie précoce
avec décollement choroïdien, infection globe oculaire. Principal échec :
fermeture de la voie par fibrose sous-conjonctivale.

* 15 Dégénérescence maculaire liée à l'âge
Atteinte de la macula chez > 50 A. Débutante/intermédaire : drusen, altération
pigmentaire, AV normale ou peu \dec. Évoluée : atrophique ou exsudative

Prévalence : 18% après 50 ans, 37% à 85 ans.

FR : âge, pop européennes, polymorphisme facteur H du complément, tabac, régime
pauvre en anti-oxydant/riches en (acide gras saturés et cholestérol)

** Diagnostic
- Mesure AV (loin et près), recherche scotome central ou métamorphopsies (grille d'Amsler)
- FO (drusen, altération pigmentaires, atrophie épithelium pigmentaire, forme
  exsudative [cf /infra/ ].
- OCT : suivi, ou diagnostic si + FO

** Formes cliniques
- débutante : /drusen/ = résidus de phagocytose des photorécepteurs. Petites
  lésions profondes jaunâtre. OCT
- atrophique : disparition de l'épithelium pigmentaire. FO : atrophie de
  l'épithelium pigmentaire et choroïde. BAV sévère avec scotome centrale
- exsudative (néovaisseaux sous rétine) : \oe{}dème intrarétinien, hémorragies,
  décollement maculaire exsudatif (BAV, métamorphopsies brutales). Sans ttt :
  BAV sévère, scotome central définitif. BAV + drusen = urgence \skull

** Ttt
- débutante : vitamine E, C, zinc, lutéine, zéaxantine
- atrophique : \emptyset
- exsudative : injection d'anti-VEGF : ranibizumab,
  aflibercet. bévacizumab. Stoppent néovaisseux, font régresser l'\oe{}dème. 40%
  ont amélioration visuelle à 2 ans. 
Laser possible mais risque thrombose
* 16 Occlusions artérielles rétiniennes
Artères ciliaires postérieure alimente les couches profondes (épithelium
pigmentaire de la rétine, photorécepteurs). 
Artère centrale de la rétine = couche internes (cellules bipolaires,
ganglionnaires, fibres optiques).

Arrêt circulatoire \thus lésions définitives en 90min \danger

** Occlusion de l'artère centrale de la rétine
Diagnostic : 
- BAV brutale (amaurose transitoires précédentes possibles)
- Oeil blanc indolore, AV effondrée, mydriase aréflective (RPM direct aboli)
- FO : dans les heures : oedème ischémique rétinien blanchâtre, tache "rouge
  cerise de la macula")

Étiologie : 
- embolies : athérome carotidien++, cardiopathie embolinogène, ( fractures des os
  long ou emboles tumoraux)
- thromboses : maladie de Horton (urgence \skull, à rechercher), (maladies de systèmes)
- troubles coagulation : anomalie primitive, sd antiphospholipides, hyperhomocystéinémie

/Très mauvais pronostic fonctionnel/ (régression \oe{}dème,
atrophie rétine et papille)

CAT : urgence \danger \skull (fonction visuelle et patho sous-jacente)
- bilan étio : athérome, carotidien, cardiopathie embolinogène, dissection
  carotidienne (si jeune), horton
- ttt décevant : hypotonisant (acétazolamide IV/per os), vasodilatateur,
  anticoagulant si besoin, fibrinolytique
- bilan cardio
- Aspirine dans tous les cas. Si jeune, bon état général, ttt max. 
- selon étio : antiagrégant plaquettaire (athérome carotidien), anti-vit K (emboles
  cardiaques), endartériectomie

** Occlusion de branche de l'artère centrale de la rétine
Amputation du CV. BAV possible. FO : \oe{}dème rétinien ischémique en secteur

Évolution : \inc AV en qq semaines, pronostic visuel bon mais amputation
persiste.

Même étio, sauf Horton. Même ttt.

** Nodules cotonneux
Occlusion d'artérioles rétiniennes précapillaire \thus nodules cotonneux =
petites lésions blanches superficielles d'aspect duveteux.

Étio : HTA, diabète, occlusions veineuses rétiniennes, sida, lupus érythémateux
disséminé, périartérite noueuses, embolies graisseuses, pancréatite aigüe, sd Purtscher
* 17 Occlusions veineuses rétiniennes
** Occlusion de la veine centrale de la rétine
SF : vision trouble brutalement, BAV variable, \oe{}il blanc indolore
FO : 
- diagnostic = {\oe{}dème papillaire, veines rétitiennes tortueuses et dilatées,
  hémorragies sur la surface rétitienne, nodules cotonneux}
- formes non ischémiques (freq) : AV > 2/10, hémorragies en flammèches, ischémie
  peu étendue
- formes ischémiques[fn:21] : AV < 1/10, réflexe pupillaire direct diminué, hémorragies
  plus volumineuses, en tache

\begin{tcolorbox}
Diag facile car tableau typique : BAV brutale, dilatation veineuse, nodules cotonneux,
hémorragies disséminées, oedème papillaire
\end{tcolorbox}

Suivi par OCT

Étiologie inconnue 
- mais > 50 ans avec FR vasc \thus recherche {tabac, HTA, diabète, hypercholestérolémie, SAS}, hypertonie oculaire++
- si < 50 ans, 0 FR ou OVCR bilatérale, chercher anomalie primitive de la
  coagulation, sd antiphospholipides, hyperhomocystéinémie, contraception, hyperviscosité
  
Évolution :
- formes non ischémiques : normalisation AV en 3-6 mois. Sinon : conversion en
  forme ischémique, persistance d'un \oe{}dème maculaire cystoïde (BAV permanente !)
- formes ischémiques : 
  - pas de récupération fonctionnelle. 
  - Pire complication = néovascularisation irienne \thus progression rapide vers glaucome
  néovasculaire (3 mois) \thus prévention par photocoagulation panrétinienne
  - néovascularisation prérétiniennes ou précapillaire (hémorragie intravitréenne)
    
Ttt 
- formes non ischémique : injection d'anti-VEGF/triamcinolone si \oe{}dème
  maculaire cystoïde avec BAV persistante. Surveillance tous les mois
- formes ischémiques : photocoagulation panrétinienne (PPR) pour éviter glaucome
  néovasculaire
- glaucome néovasculaire : PPR en urgence après hypotonisant local \danger
  

** Occlusion de branche veineuse rétinienne
Identique à OVCR mais territoire plus limité.
Signe du croisement (cf chap 23) \thus > 60 ans, FR d'artériosclérose

Clinique : BAV variable, FO identique OVCR

Évolution favorable en majorité. Défavorable si maculopathie ischémique,
\oe{}dème maculaire persistante, néovaisseaux prérétiniennes \thus hémorragie du
vitré mais *pas* de gls:GNV

Ttt similaire. 
- Si \oe{}dème maculaire persistant : injection intravitréenne
- photocoagulation maculaire en grille (si \ge 3 mois, \oe{}dème maculaire
  persistante, AV ɇ 5/10)
- photocoagulation sectorielle
* 18 Pathologies des paupières
Anatomie : plan antérieur cutanéomusculaire, plan postérieur : tarse,
conjonctive (papébrale, cul-de-sac, bulbaire). Sécrétion des larmes par la
glande lacrymale principale, évacuées par les voies lacrymales excrétrices

Fermeture paupière : nerf VII, ouverture par nerf III

** Pathologies
Orgelet : furoncle du bord libre, centré sur follicule du cil.
- infection bactérienne (\bact{dore}), tuméfaction rouge autour point blanc
- ttt : ATB 8 jour
Chalazion : granulome inflammatoire sur glande de Meibomius (tarse)
- tuméfaction douloureuses
- Ttt : pommade corticoïde locale, massage des paupières. Éventuellement
  incision

** Autres
Malformation palpébrales : 
- entropion : bascule vers l'intérieur. Sénile, cicatriciel
- ectropion : sénile, cicatriciel, paralytique
- ptosis : neurogène, myogène, sénile, traumatique
- lagophtalmie (inoclusion palpébrale) : anesthésie générale, coma prolongé,
  paralysie faciale
Tumeurs palpébrales :
- bénignes : papillome, hydrocystome (kyste lacrymal), xanthélesmas (dépôts
  cholestérol). Ttt : chir
- malignes : 
  - épithéliale : carcinome basocellulaire surtout (nodule perlé,
    télangiectasise; peut menacer globe oculaire, pas de métastases), carcinome
    épidermoide (métastase)
  - mélaniques : pronostic peut être effroyable. suspecter si tuméfaction
    (pigmentée) des paupières
  - carcinomes sébacés, lymphomes MALT
Trauma : vérifier septum orbitaire, globe oculaire, canalicules lacrymaux
arrachés (urgence \skull)

* 19 SEP
Névrite optique rétrobulbaire \in SEP (20% = inaugurale). Atteint adulte \in
[20,40]ans, surtout \female

Neuropathie optique :
- BAV variable sur qq jours, douleurs rétro oculaires (80%) 
- pupille de Marcus gunn (dilatation paradoxale). Si inflammation intraoculaire,
  penser syphilis, sarcoïdose
- Complémentaire :
  - examen du CV : scotome (caeco)central.
  - dyschromatopsie d'axe rouge-vert
  - IRM encéphalique systématique (SEP)
- régression en 3-6 mois. Risque de SEP = 50% à 15 ans (75% si lésions
  encéphaliques à l'IRM). Phénomène d'Uhthoff possible[fn:22]
- ne pas confondre avec neuromyélite de Devic ! Inflammation (\ne auto-immune) du
  SNC, BAV profonde rapide. IRM : pas d'inflammation cérébrale mais médullaire 
- ttt : corticothérapie  parentérale 3-5j (1g/j) puis oral court (11 j). Retarde
  un nouvel épisde. Si SEP, ttt de fond (immunomodulateur [interférons, acétate
  de glatiramère] ou natalizumab, fingolimod)
- pronostic fonctionnel souvent favorable
- DD : autres neuropathies optiques

Autres :
- oculomotrice : paralysie du VI, internucléaire (penser SEP si bilatérale chez jeune)[fn:23]
- nystagmus : 1/3 patient avec SEP > 5 ans
- périphlibite rétiniennes (5%)
* 20 Neuropathie optique ischémique antérieure
Ischémie de la tête du nerf optique (artères ciliaire postiérieures)

Diagnostic clinique :
- BAV unilatérale brutale indolore
- AV variable, \dec RPM direct, FO = \oe{}dème papillaire++, papille souvent
  pâle, hémorragie en flammèche sur le bord papillaire
- complémentaire : examen CV++ = {déficit fasciculaire, altitudinal},
  angiographique du fond d'\oe{}il

Étiologie : 
- maladie de Horton = urgence \skull (cécité bilatérale définitive) \thus 
  - signes systémique, modif artères temporale
  - signes oculaire : amaurose fugace, défaut de remplissage choroïdien (angiographie)
  - bio : VS \inc (non systématique), CRP \inc
  - biopsie de l'artère temporale (ne doit pas retarder les soins !)
- artériosclérose (fréq) : FR (tabac, HTA, diabète, hypercholestérolémie)

Évolution : résorbtion de l'\oe{}dème en 6-8 semaines (atrophie). Pas de récup
visuelle. Bilatéralisation possible en qq jours \danger

DD : causes d'\oe{}dème papillaire (HTIC)

Ttt : 
- artéritique = urgence ! Corticothérapie générale à forte dose puis per os
  1mg/kg/j
- non artéritique : pas de ttt efficace
  
* 21 Rétinopathie diabétique
30% diabétique en ont une. Diabète 1 : 90% après 20 ans. Diabète 2 : 60% à 15
ans

Physiopatho : hyperglycémie \thus {accumulation sorbitol, glycation, stress
oxydatif} \thus {inflammation, activation rénine-angiotensine, modif flux
sanguin rétinien, production VEGF} puis 
- occlusion capillaire et néovascularisation
- \oe{}dème maculaire
  
** Diagnostic
Photographie du FO = référence et dépistage
- microanévrisme rétitiens : dilatations punctiformes rouges (postérieure)
- hémorragie rétiniennes punctiformes
- nodules cotonneux
- signes d'ischémie : hémorragies intrarétiniennes "en taches" ou en flammèche, anomalies
  microvasculaire intrarétinienne, dilatations veineuses "en chapelet",
  néovaisseaux prérétiniens et précapillaires, hémorragie prérétiniennes/intravitréennes
- complications : hémorragie intravitréenne, décollement de la rétine /par
  traction/, néovascularisation irienne (\thus glaucome néovasculaire !)
- signes maculaires : \oe{}dème maculaire (cystoïde), exsudats lipidiques
  (souvent en couronne)

Complémentaire : OCT pour diagnostic et suivi \oe{}dème maculaire, echo en mode B
pour décollement de rétine par traction

** Dépistage RD
Diabète 1 : photo FO à la découverte puis surveillance annuelle
- enfant: pas avant 10 ans
- grossesse : avant puis tous les 3 mois (tous les mois si RD !)
Diabète 2 : dès découverte

Surveillance :
- \emptyset RD on non proliférante minime : annuelle
- sinon tous 4 à 6 mois
- renforcé si puberté, adolescence, si équilibrage trop rapide de la glycémie,
  chir bariatrique, diabète ancien mal équilibré, chir de la cataracte,
  \oe{}dème maculaire
  
Classification :
- \emptyset RD
- RD non proliférante : minime, modérée, sévère (hémorragie rétiniennes dans 4
  quadrants ou dilatations veineuses 2 quadrants ou AMIR 1 quadrant)
- RD proliférante (néovaisseaux): minime, sévère, compliquée (décollement de
  rétine par traction, gls:GNV)
  
Progression lente, aggravations rapides possibles. \danger prolifération néovasc
peut donner cécité 

** Traitement
Médical :
- équilibre glycémique et hypertension pour 2 diabètes !
- pas de ttt médicamenteux
RD proliférante 
- photocoagulation panrétinienne : régression dans 90%. Indication : RD
  proliférante ou (RD non proliférante sévère si grossesse, sujet jeune
  diabétique 1 avec normalisation rapide glycémie, chir cataracte)
- injection intravitréenne anti-VEGF (pour néovasc. iridienne, glaucome
  néovasculaire)
- chir si RD proliférante avec hémorragie intravitréenne persistante/décollement
  de rétine tractionnel
\OE{}dème maculaire 
- photocoagulation au laser si exsudats lipidiques ou liquides
- injection anti-VEGF mensuelle. Dexaméthasone retard possible mais cataracte,
  risque d'hypertonie oculaire (30%)
* 22 Orbitopathie dysthyroïdienne
Surtout maladie de Basedow (ou thyroïdite auto-immune d'Hashimoto

Thyrotoxicose : {palpitations, tachycardie}, {nervosité, tremblement, insomnie},
thermophobie, {amaigrissement, fatigue}

Classification :
- gravité = NOSPECS[fn:24]
- inflammation = CAS (clinical activity score)

Manifestation :
- exophtalmie : bilatérale (75%), axile, non pulsatile, réductible, indolore,
 > 21 mm
- rétraction paupière, asynergie oculopalpébrale vers le bas, \dec fréquence
  clignement
- trouble oculomoteur : myosite \thus diplopie
  
Complications :
- cornée : kératite, peforation
- neuropathie optique compressive (3%) \thus méthylprednisolone forte dose ou
  décompression rapide \skull !

Complémentaire : TSH effondrée (hyperthyroïdie), scanner et IRM pour conforter,
{pupille, champ visuel, couleurs, PEV}

DD : infection orbitaire, fistules artériocaverneuses, tumeurs, orbitopathies
inflammatoires

Traitement 
- médical : 
  - traiter thyrotoxicose (\danger iode radioactif peut aggraver orbitopathie) arrêt tabac, ttt locaux (symptômes), sélénium si forme modérée
  - CAS \ge 3 \thus anti-inflammatoire (méthylprednisolone)
- chir : décompression orbitaire, muscles oculomoteurs, paupières
* 23 Rétinopathie et choroïdopathie hypertensive
Bien différencier modifications liée à l'HTA (réversible par ttt de l'HTA) et
celles irréversibles liées à l'artériosclérose 

\inc Pa \thus vasoconstriction artérieur active (autorégulation)

** Rétinopathie hypertensive
AV normale. Signes oculaires seulement si sévère :
- barrière hématorétinienne rompue \thus hémorragies rétiniennes superficielles,
  \oe{}dème maculaire et exsudat secs, \oe{}dème papillaire
- occlusion artérioles précapillaires \thus nodules cotonneux, hémorragies
  rétiniennes profondes
- hémorragies en flammèches péripapillaire (superficielles) ou rondes sur toute
  la rétine (profondes)
\thus non spécifiques mais évocateurs d'HTA si associés. Pas de BAV

** Choroïdopathie hypertensive
Pas d'autorégulation pour les vaisseaux choroïdiens. Occlusion \thus ischémie et
nécrose de l'épithelium pigmentaire. cicatrices en petite taches pigmentées
("d'Elschnig").

Formes plus sévères : décollement de rétine exsudatif (post) avec
BAV. Normalisation avec ttt

** Artériosclérose
Lésions chroniques irréversibles mais asymptomatiques :
- accentuation du reflet artériolaire
- signe du croisement[fn:25]
  

Classification de Kirkendall 
- rétinopathie hypertensive : I (rétrécissement artériel sévère et disséminé),
  II (idem + hémorragies rétiniennes, exsudats secs, nodules cotonneux), III
  (idem + \oe{}dème papillaire
- artériosclérose : I (croisement), II (idem plus rétrécissement marqué), III
  (idem plus occlusion de branche)

\printglossaries

* Footnotes

[fn:24] No sign, Only lid retraction, Soft tissues, Proptosis \ge
  3mm, Extraocular muscle, Corneal

[fn:29] Infection intraoculaire sévère.

[fn:28] Voire générale

[fn:27] BAV par altération précoce de l'expérience visuelle. 

[fn:26] Focales en avant/arrière/des 2 côtes de la rétine resp.

[fn:25] Veine "écrasée" sur le croisement avec l'artère, dilatée en amont

[fn:23] Pas d'adduction de l'\oe{}il atteint mais adduction des yeux OK à la
convergence. Nystagmus pendulaire en abduction de l'\oe{}il sain !

[fn:22] BAV transitoire quand température \inc 

[fn:21] Différence avec l'angiographie fluorescinique

[fn:20] EI : rougeur, irrit. oculaire. Puis iris plus sombre, \inc pousse cils. 

[fn:19] Uvéite auto-immune sévère

[fn:18] Désinsertion de la base de l'iris

[fn:17] Hémorragie intravitréenne uni-/bi-latérale et hémorragie méningée par
rupture d'anévrisme intracrânien

[fn:16] Cf chapitre suivant pour BAV brutale

[fn:15]  Déshydratation du vitré

[fn:14] \dec production d'humeur aqueuse.

[fn:13] \OE{}dème conjonctival

[fn:12] Cherche plaie conjonctivale !

[fn:11] \danger méconnu si ptosis/\oe{}dème palpébral

[fn:10] Monoculaire : cause cornéenne, irienne, cristalinienne $\ne$ urgence.

[fn:9] Abrasion épithelium cornéen ou volet dans cornée.

[fn:8] Chez l'enfant, cycloplégique

[fn:7] Courbure de la cornée

[fn:6] Si BAV, vasculaire probable. Sinon HTIC

[fn:5] Punctiformes, flammèches, profondes

[fn:4] Cellules inflammatoires, protéines dans l'humeur aqueuse

[fn:3] \OE{}dème conjonctival

[fn:2] Plus de voie efférente \thus \oe{}il atteint : RPM direct aboli. \OE{}il sain : RPM consensuel aboli

[fn:1] Plus de voie afférente  \thus gls:RPM direct et consensuel aboli pour l'\oe{}il atteint

