#+title: Graal
#+roam_tags: review
Notes sur "Le livre du Graal" de la Pléiade.

* General
  Il s'agit d'un mythe purement littéraire, sans racine biblique.
  Inventé par Chrétien de Troyes au XIIe siècle, il s'inspire de tradition païenne. Dans l'oeuvre originale, le Graal est simplement décrit comme un plat d'origine mystérieuse.
  L'oeuvre de Chrétient de Troyes (Le /Conte de Graal/) a engendré une myriade d'oeuvres avec leurs propres versions.
  Il y a eu une récupération religieuse où le Graal devient un calice qui aurait recueilli le sang du Christ. ce tte version se dit biblique mais il n'y aurait pas de mentions de la Bible.
  Cette nouvelle interprétation est du à Robert de Boron.
  La christianisation du mythe est aussi relancée par les croisades, qui ramènent des reliques de Jérusalem

  Second point : inspiré donc par la légende créée par Chrétien de Troyes, se créé un ensemble de textes établis sur plusieurs décennies. Il y a 2 groupes :
  - /Lancelot/ (inspiré du /Chevalier à la Charette/ de C. d. T), complété par /La quête du Saint Graal/ et /La Mort du roi Arthur/
  - /Joseph d'Arimathie/, /Merlin/, /Les Premiers faits du roi Arthur/
  L'ensemble fait le cycle du Graal que l'on connait. Chacun a son propre style :
  - Joseph = récit pseudo-biblique,
  - Merlin = conte merveilleux
  - Les Premiers Faits = épopée historiographique
    Lancelot = roman d'aventures
  - La Quête du saint Graal = allégorie/homélie
  - La mort du roi Arthur = tragédie

  Troisième point : à part la version de C. de T., il s'agit d'un ensemble disparate de manuscrits qui ont été copiés . La notion d'auteur n'a pas vraiment de sens car les copistes choisissaient et éditaient l'oeuvre également !
  La pléiade a choisit la manuscrit le plus complet et le plus ancien (1286). Cela évite aussi un travail d'édition titanesque (une centaine de manuscrits existents)

* Joseph d'Arimathie
  Préquelle écrite, semble-t-il, après les évènements pour justifier leur origine.
  On voit l'origine du Graal (receuil du sang de Jésus par Joseph) et le transport depuis l'Orient vers la grande-Bretagne. Le style est très biblique, didactique afin de convaincre les populations de se convertir au christianisme.
  Lecture souvent ennuyeuse pour cette raison....
* Merlin
  Adapté de la petite trilogie de Robert de Boron (écrivan mystérieux de la fin du XIIe).
  On y découvre la naissance de Merlin, suite à l'accouplement du diable (sic) et d'une femme. Suite à la piété de cette dernière, Dieu va l'accepter. Il aura donc le don de voir le passé (par le diable) et le futur (par Dieu).
  Servira de conseiller et prophète au roi Uter (renommé UterPandragon en souvenir de son frère) et d'Arthur.
  Passage de l'épée dans l'eclume que seul Arthur peut retirer
  On voit la naissance d'Arthur : le roi Uther couche avec la femme d'un de ses barons (qui ne veut absolument pas) après avoir emprunté son apparence à l'aide de Merlin. Après avoir tué le baron, le roi se marie et donne l'enfant.
  La moralité est assez compliquée...
  Se lit très bien.
* Les Premiers Faits du Roi Arthur
  Il s'agit d'une oeuvre qui vient compléter les "trous" dans le cycle de Graal et a été écrit plus tardivement.
  On a ici une fresque épique où Arthur apparait comme un seigneur de guerre invincible ainsi qu'un tacticien hors pair.
  Merlin fait office cependant de maitre du jeu: il s'occupe de la politique, négociation, stratégie et tactique ! Avec parfois des dons d'ubiquité.
  Évidemment, lisant l'avenir, cela est facile pour lui.
  À la fin du livre, il se fait capturer par Niniane : éperdu d'amour, il lui apprend tous ses secrets alors que celle-ci lui refuse sa virginité (d'autant plus intéressant que Merlin est un tombeur !).
  Au final, elle l'enfermera grâce à sa magie. Selon les versions, elle apparaîtra comme plus ou moins vicieuse, à savoir qu'elle retournera son amour.

  L'intrigue montre la révolte des seigneurs envers Arthur et leur défaite contre les Saxons. Pendant ce temps, Arthur va accumuler les victoirs en Gaule, y trouver sa femme Gueièvre.
  Avec l'aide de Merlin, il unira les seigneurs dans une bataille finale qui chassera les Saxons.
  À noter que les Saxons ne font pas seulement référence au peuple historique mais est influencé par les Sarrasins des chansons de gestes et des ennemis celtiques.
  Arthur ira aussi mener la guerre contre les Romains en Gaule en leur disputant leur droit de conquête. Il gagnera et tuera l'empereu

  Sur le style, se lit très bien avec beaucoup de batailles, répétitives mais cela fait partie du genre de l'époque.
* Lancelot: La marche de Gaule
  Mélange la chronique "historique" et les aventures des chevaliers dans leurs quêtes. Le second fonctionne mieux
  Sur le plan amoureux, on a l'histoire et l'adultère Lancelot-Guenièvre (qui arrive au moment où Arthur fait la même chose pendant une bataille). C'est Lancelot, érigé en remplacement du roi qui permet de gagner la bataille.
  L'amour de Lancelot est parfois complètement exagéré (il se noit presque, perdu dans ses pensée). On a également le pendant avec Galehaut (amour "masculin"). Et un "quatuor" avec Galehaut-la dame de Malehaut.
  
  Les quêtes suivent Lancelot, Gauvain surtout.
La part de la magie est curieuse et alterne entre des explications pseudo-rationnelles et de la magie complètement exagérée.
  
