#+TITLE: Homère

Lecture de la version de la Pléiade (1955)
* Version historique
** Parallèle entre la civilisation minocéenne et l'âge des héros selon homère ?
Source: [[https://www.reddit.com/r/AskHistorians/comments/14df5g/did_the_trojan_war_actually_happen/c7c3z1s/][Askhistorians]]
1.
#+BEGIN_QUOTE
Very nearly all artefacts and cultural practices described in Homer match the
late Iron Age or early Archaic periods -- i.e. centuries after Troy VIi -- and
not the late Bronze Age. Where Homer does describe elements that are
demonstrably earlier than the text of the epics, they are almost always more
easily explained as false archaisms (i.e. attempts to describe a past age by
using old-fashioned elements indiscriminately and anachronistically).
#+END_QUOTE
2. On a bien une destruction de Troie VI concomitante à celles dees Mycénéens

** Réalité de la guerre de Troie
Selon [[https://www.reddit.com/r/AskHistorians/comments/14df5g/did_the_trojan_war_actually_happen/c7c3z1s/][Askhistorians]], concernant la guerre de troie, plus d'arguments contre que pour.
#+BEGIN_QUOTE
There is some circumstantial evidence in favour of a real Trojan War, but no
direct evidence to support it. There is no evidence at all of historical figures
named Agamemnon, Achilleus, Hektor, etc.
#+END_QUOTE
* Odyssée
** Cyclope
Selon Victor Bérard (hélléniste et traducteur), le Cyclope est une personnification du volcan. Arguments :
- la race désigne "oeil rond"
- de forme non humaine, ressemblant à un sommet de la montagne, lance des rochers
Un article [fn:scarth] détaille cette comparaison afin d'illuster la possibilité qu'il ait servi d'inspiration. Quelques arguments
- Polyphème = Etna (cf arguments géographique)
- épisode du pieu planté dans l'oeil = lave au contact de l'eau...
- quand le cyclope dévorre les humaines, référence à une éruption (couleur du sang + vomissement)
- entrée/sortie du cyclope et de ses moutons de sa caverne = éruption
- moutons représentent les flux de laves descendant lentement les pentes
- autres cyclopes = cônes autour de l'Etna
- fils de Poséidon (fait trembler la terre) et les volcans sont reliés aux tremblements de terre
- fertilité des terrains aux alentours (propriété de la lave)
** Pourquoi Posédion poursuit Ulysse ?
Passage dans l'odyssée = blasphème, surprenant pour Victor Brar

* Footnotes

[fn:scarth] Scarth, A. (1989). Volcanic origins of the polyphemus story in the "odyssey":
  a non-classicist's interpretation. The Classical World, 83(2), 89.
  http://dx.doi.org/10.2307/4350550
