#+title: Graal
Notes sur "Le livre du Graal" de la Pléiade.

Il s'agit d'un mythe purement littéraire, sans racine biblique.
Inventé par Chrétien de Troyes au XIIe siècle, il s'inspire de tradition païenne. Dans l'oeuvre originale, le Graal est simplement décrit comme un plat d'origine mystérieuse.
L'oeuvre de Chrétient de Troyes (Le /Conte de Graal/) a engendré une myriade d'oeuvres avec leurs propres versions.
Il y a eu une récupération religieuse où le Graal devient un calice qui aurait recueilli le sang du Christ. ce tte version se dit biblique mais il n'y aurait pas de mentions de la Bible.
Cette nouvelle interprétation est du à Robert de Boron.
La christianisation du mythe est aussi relancée par les croisades, qui ramènent des reliques de Jérusalem

Second point : inspiré donc par la légende créée par Chrétien de Troyes, se créé un ensemble de textes établis sur plusieurs décennies. Il y a 2 groupes :
- /Lancelot/ (inspiré du /Chevalier à la Charette/ de C. d. T), complété par /La quête du Saint Graal/ et /La Mort du roi Arthur/
- /Joseph d'Arimathie/, /Merlin/, /Les Premiers faits du roi Arthur/
L'ensemble fait le cycle du Graal que l'on connait. Chacun a son propre style :
- Joseph = récit pseudo-biblique,
- Merlin = conte merveilleux
- Les Premiers Faits = épopée historiographique
  Lancelot = roman d'aventures
- La Quête du saint Graal = allégorie/homélie
- La mort du roi Arthur = tragédie

Troisième point : à part la version de C. de T., il s'agit d'un ensemble disparate de manuscrits qui ont été copiés . La notion d'auteur n'a pas vraiment de sens car les copistes choisissaient et éditaient l'oeuvre également !
La pléiade a choisit la manuscrit le plus complet et le plus ancien (1286). Cela évite aussi un travail d'édition titanesque (une centaine de manuscrits existents)

* Joseph d'Arimathie
Préquelle écrite, semble-t-il, après les évènements pour justifier leur origine.
On voit l'origine du Graal (receuil du sang de Jésus par Joseph) et le transport depuis l'Orient vers la grande-Bretagne. Le style est très biblique, didactique afin de convaincre les populations de se convertir au christianisme.
Lecture souvent ennuyeuse pour cette raison....
* Merlin
Adapté de la petite trilogie de Robert de Boron (écrivan mystérieux de la fin du XIIe).
On y découvre la naissance de Merlin, suite à l'accouplement du diable (sic) et d'une femme. Suite à la piété de cette dernière, Dieu va l'accepter. Il aura donc le don de voir le passé (par le diable) et le futur (par Dieu).
Servira de conseiller et prophète au roi Uter (renommé UterPandragon en souvenir de son frère) et d'Arthur.
Passage de l'épée dans l'eclume que seul Arthur peut retirer
On voit la naissance d'Arthur : le roi Uther couche avec la femme d'un de ses barons (qui ne veut absolument pas) après avoir emprunté son apparence à l'aide de Merlin. Après avoir tué le baron, le roi se marie et donne l'enfant.
La moralité est assez compliquée...
Se lit très bien.
