#+TODO: TODO RETRY | DONE

* Desserts
** DONE Biscuit cuiller
(Patisserie, Leçons pas-à-pas) : 12min environ
3 blanc
75g sucre
55g farine37g fécule
4 jaunes
** RETRY Biscuit de Savoie
[[https://www.meilleurduchef.com/cgi/mdc/l/fr/recette/biscuit-savoie.html)][meilleur du chef]] : cuire vraiment plus longtemps en bas du four. Bien beurrer et fariner.
** RETRY Bounty
[[http://www.750g.com/bounty-maison-r97803.htm)][750g]] : prendre du bon chocolat
  + noix de coco
  + lait concentré sucré
  + chocolat noir
** RETRY Brioche
[[http://www.enviedebienmanger.fr/fiche-recette/recette-brioche-pur-beurre)][Enviedebienmanger]] : bonne consistance et bon aspect. Attention, 30min est un maximum.
  + 250 g de beurre gastronomique (+30 g pour beurrer les moules)
  + 10 cl de lait entier
  + 500 g de farine T45
  + 18 g de levure fraîche
  + 100 g de sucre
  + 4 oeufs
  + 1 jaune d'oeuf
  + 12 g de sel (+ 1 pincée)
** RETRY Brownie
2 recettes :
  + https://tasty.co/recipe/ultimate-brownies
    ** -33% en sucre
    ** café en poudre ok
    ** problème de cuisson : centre pas assez cuit. Brownie trop épais ?
    ** 2eme essai : avec les temps recommandé, au milieu du four, trop cuit ! (comme un cake, trop épais)
    ** => cuire moins+++ (30min), utiliser du chocolat à 70%, bien respecter la dose de cacao en poudre, bien battre++
  + Préférence pour celle-ci : https://www.seriouseats.com/recipes/2018/02/bravetart-glossy-fudge-brownies.html
    ** diviser quantité par 2 : brownie fin dans un plat à tarte.
    ** 20-25min à 180 degré (30min = un peu trop cuit). Cuisson homogène
  + différences entre les 2 : un peu plus de beurre pour SE, un peu plus de chocolat (normal + poudre) pour tasty

** RETRY Carrot cake
https://www.seriouseats.com/recipes/2017/10/carrot-cake-recipe.html
  + un peu trop trop humide
  + glacage non fait (version rapide = beurre + cream cheese + sucre glace)

** RETRY Cinnamon rolls
[[https://www.bingingwithbabish.com/recipes/cinnamonrolls?rq=cinnamon][de Babish]]
  + Le glacage est trop lourd (et seulement testé avec fromage frais + sucre) en soi !
  + Soit réessayer la recette de babish (en petite quantités), soit simplement nature.

** RETRY Clafoutis aux pommes
[[http://www.ptitecuisinedepauline.com/article-clafoutis-aux-pommes-122364862.html)][ptitecuisinedepauline]]
  + Avec un peu plus de farine, on a un clafoutis bien compact.

** RETRY Cornbread (salé)
[[https://www.seriouseats.com/recipes/2015/11/southern-unsweetened-cornbread-recipe.html][Seriouseats]]
  Bien moelleux mais très mietteux. Probablement pas assez mélangé
** RETRY Crepes
https://www.marmiton.org/recettes/recette_pate-a-crepes-simple_27121.aspx
2.5 oeufs
250 g de farine
500g l de lait demi-écrémé
1.5 cuillères à soupe d'huile
1 cuillère à café de rhum
=> décent
** RETRY Croissants
(PPAP). Pas encore ça... Remarques après plusieurs essais :
  + 45min à 190° = trop !!  pas assez cuits++ à l'intérieur mais un peu trop à
    l'extérieur. 180° était trop, essayer 160° ? Changer la position dans le
    four ?
  + Bien laisser pousser avant d'enfourner (45min n'est pas assez !)
  + Beurre qui s'échappe = pâte trop malmenée ?
  + essayer cette recette : https://www.weekendbakery.com/posts/classic-french-croissant-recipe/

** RETRY Framboisier :
  + Recette de PPAP : bon, pas assez de crème ?
  + Felden : 2/3 seulement de dacquoise et de la crème seulement pour la moitié
    ... Crème OK mais gâteau globablement un poil lourd mais bon.
** RETRY Galette des rois
[[https://www.youtube.com/watch?v=ETkk7QXbtlw][de Conticini]]
  + Problème de la quantité : avec 3/4 de la crème, léger surplus pour une
    grosse galette ?
  + Pâte feuilletée inversée plus intéressante que la simple => prendre la recette de PPAP
  + Attention à mettre suffisament d'eau dans la pâte feuilletée : trop dure
    sinon (et se déchire)
  + Frangipane sortie de la galette (alors qu'il en manquait) => réappuyer pour
    souder après l'avoir retourné semble fontionner

** RETRY Gâteau au chocolat
essayer
  [[https://tasty.co/recipe/the-ultimate-chocolate-cake][recette de Tasty]] vs
  [[https://www.bonappetit.com/recipe/blackout-cake][Blackout cake]]
  + Tasty : attention, bien cuire le gâteau et *bien* attendre qu'il soit froid
   (sinon tombe en morceaux) !!
   Pas de bière mais la moitié en eau chaude. Bien dilueer le café en poudre avant.
   Pour le glacage, quantité de sucre divisée par 2, ok. Pas assez de glacage ?
  + Blackout cake : en séparant la cuisson en 2, 2 très petits gâteaux Possible
    de les couper en deux mais avec soin. Trop de glacage dans la recette par
    contre (50% en trop ?). Résultat OK
** RETRY Gaufres
pas de souci de cuisson avec [[https://www.hervecuisine.com/recette/gaufres-croustillantes-ultra-legeres/). Temps de repos qui fait la différence ? (Souvent pas assez cuite dans les essais précédents][cette recette]]
** RETRY Guimauve
[[http://www.jujube-en-cuisine.fr/marshmallow-ou-guimauve-maison/)][jujube-en-cuisine]]: trop sucré mais bonne texture
** TODO Ile flottante
https://cooking.nytimes.com/recipes/1017447-ile-flottante-with-fresh-cherries
Problèmes :
- sauce trop liquide après qq minutes de cuisson et malgré 2h au frais après.
  Goût un peu curieux avec la cardamone (diminuer dose ?)
- meringue aplatie après la cuisson à la vapeur => au four la prochaine fois

** TODO Lebkuchen
1er essai avec une recette de 750g il y a quelques années
2eme essai avec cette recette :
https://www.bbcgoodfood.com/recipes/1941/lebkuchen
mais plusieurs modifications :
Ajout : 1 oeufs, 25g sucre roux, orange confite, noisettes concassées
Globalement : plus de farine que mentionné
Glacage = 200g chocolat + huile de coco mais pas assez pour tous les gâteaux.
Important : couper cuisson quand les bords commencent à brûnir (10min à 180% max)
=> résultat : pas mal

** RETRY Macarons
Pour 30 macarons
Coque =
- 125g poudre d'amandes
- 125g sucre glace
- 1.5 blanc
Meringue
- 125g sucre semoule
- 35g eau
- 1.5 blanc
Ganache
- 80g lait
- 20g crème
- 150g chocolat 64%
- 30g beurre

*** Notes
- Le plus important = Macaronage => mélanger jusqu'à pouvoir faire des "8"
- Recette de LPAP = valeur sûre. Faisable avec 2 plaques mais celle du bas
  (plaque pâtisserie) est moins jolie
-  Recette de Felden avec du cacao en poudre : pâte d'amande trop épaisse mais
  résultant décevant malgré tout (plus un cookie) => des doutes à réessayer...
- Essayer avec meringue française
- Pas de sucre roux !
** RETRY Mille-feuille [[https://www.facebook.com/PhConticini/photos/a.108115932681384.17237.101025623390415/713491585477146/?type=3) : bien mettre un poids sur la pâte feuilletée pendant la cuisson. Trop de gélatine (crème un peu trop gélatineuse][
de Conticini]]
** RETRY Millionaire short-bread / Twix familial
- Ne pas trop étaler la pâte.
- Quantité pour avoir autant de caramel de que shortbread... Peut-être diminuer un
peu les doses de caramel ?
- J'ai utilisé 250g de chocolat, un peu juste sinon
** RETRY Moka
Felder plutôt que PPAP :
   + le biscuit est plus simple chez Felder et plus aéré
   + doubler la dose de crème... => au final, un gâteau avec une légère couche de crème donc pas trop lourd
   + beaucoup trop de sirop dans la recette, diviser au moins par 3
   + le plus difficile (dans les 2 recettes ) : bien gérer le beurre
      * le prendre bien pommade
      * quand on le mélange aux oeufs encore chaud, refroidir les oeufs avant ... et y aller par petite quantités avec le beurre (NB: possible de recongeler si c'est trop liquide mais éviter...)

** RETRY Mousse au chocolate
Philippe Conticini : éviter une ganache trop liquide. Ne pas lésiner sur les blancs. Pour 5 parts :
   + 37 g de sucre roux
   + 250 g de blancs d’oeuf
   + 70 g de lait demi-écrémé
   + 150 g de crème liquide
   + 180 g de chocolat noir (68%)
   + 60 g de chocolat au lait

** RETRY Mousse de fruit
Recette meilleur du chef
** RETRY Pain au lait
[[https://www.youtube.com/watch?v=wAKaJRl3Ieg)][750g]] : bon mais levée sur la nuit semble préférable
** RETRY Pancake
America test kitchen recipe. Pas mal et pas prise de tête
** RETRY Paris-Brest
(PPAP) : crème au beurre toujours un peu trop liquide. Vient du
  praliné "maison" (loupé par ailleurs) ?

** RETRY Pâte à chou
(Patisserie, Leçons pas-à-pas) : 45-50min de cuisson
** RETRY Tarte au chocolat
[[https://www.youtube.com/watch?v=ZISKki8AcE0)][750g]] : pas mal mais plus avec une texture de mousse au chocolat
  + 1 pâte sablée
  + 300g de chocolat pâtissier
  + 500g de crème fraîche liquide
  + lait ? (donne plus une )
  + 2 oeufs
** RETRY Tarte aux pommes
Recette de la PPAP : pommes un peu crues, pâte ok. Mieux choisir les pomme la
prochaine fois et couper *très* fin

** RETRY Tiramisu
1. https://www.seriouseats.com/2017/06/how-to-make-the-best-tiramisu.html =>
  échec, pâte trop liquide car
2. Mieux avec
   3 jaune + sucre en sabayon.
   Ajouter 200g mascarpone battu au fouet et battre le tout.
   Ajout 20cl crème fouettée délicatement.
   => au final, pas de prise au frigo, consistence crème fouettée molle.
** RETRY Yaourt à la yaourtière
5 yaourts = 1L de lait entier + 1 yaourt (avec ferments) avec 10h
  + Un peu liquide au fond => essayer avec du lait entier en poudre
  + lait de brebis : 1L + 3 CC de lait en poudre + 12h de fermentation = bien ferme. Diminuer lait en poudre

* Plat principal
** RETRY Bolognaise
https://cooking.nytimes.com/recipes/1015181-marcella-hazans-bolognese-sauce
Pas mal (ajouté concentré de tomate + feuille basilic). Manque un peu de tomate à la fin ?
** RETRY Cassoulet
Recette http://www.confrerieducassoulet.com/la-recette.html
Fait avec :
- lard (gros morceaux)
- canard non confit (erreur)
- épaule de porc
- 2 saucisses de toulouse
Au final : 1h30 pour les haricots blancs (sans trempage) et 2h30 au four pour
commencer à avoir une croûte à 170°.
=> au final, le lard n'est pas tout à fait bien mélangé donc peut-être le faire
fondre avant / couper en tout petit morceaux ?
Sinon, pas mal mais bouillon un peu fade. Essayer https://foodwishes.blogspot.com/2016/03/cassoulet-worlds-most-complex-simple.html
** RETRY Choux de bruxelles frais rôtis
45min à 195° = fondant mais trop cuit à l'extérieur
Cuits entiers + huile + sel
** RETRY Cornbread
https://www.bonappetit.com/recipe/buttermilk-cornbread
Bien moelleux mais quantité approximative de farine et de lait (+50% ?). Trop de
levure (1 sachet) ?
** RETRY Couscous : [[http://www.ptitecuisinedepauline.com/article-clafoutis-aux-pommes-122364862.html][recette de semoule traditionnelle]]
** RETRY Crevettes
https://cooking.nytimes.com/recipes/1013144-yucatan-shrimp
Pas mal, très rapide à faire. Je mets les crevettes dans la sauce directement
** RETRY Falafels (traditionnels) :
3 échecs successifs...
Réssayer en
- mixant bien, bien la pâte
- mettre au frais pour éviter qu'ils ne se détachent dans la friture
OK avec ces 2 modifications !
** DONE Haricots blancs à la tomate
Bien cuire la sauce tomate 10min avant d'ajouter le reste
https://www.thecookierookie.com/white-beans-recipe/
** Kluski na parze ([[http://lespolonais.forumpro.fr/t133-les-kluski-na-parze  vb)][recette]]
** RETRY Lasagnes
https://www.bonappetit.com/recipe/ba-best-lasagna => ok mais
+ bien saler béchamel et viande sinon un peu fade
+ cuisson avec 1h four et 1h à la cocotte => meilleur au four ?
+ NB : sauce = viande + un peu de liquide à côté. Je regrette de ne pas avoir
  une texture plus crémeuse
+ on ne sent pas le parmesan
+ la couche supérieure de pâte n'a pas cuite malgré le papier alu => supprimer ?
** RETRY Porc fondant
*** Oignon rouge, ail chemisé, curry, porc à braiser. Le tout cuit pendant 2h au moins avec couvercle
*** Pulled pork
https://cooking.nytimes.com/recipes/1020497-slow-cooker-bbq-pulled-pork
6 heures à 160% avec "searing". Écrasé à la fourchette au bout de 3h pour
permettre d'absorber le gras.
Bien en burger avec sauce BBQ
** RETRY Poulet glacage soja-miel-gingembre
https://cooking.nytimes.com/recipes/1019804-honey-and-soy-glazed-chicken-thighs
Cuisson à 1950 45min avec poulets non décongelés : ok, manque un peu de
crispiness
À ressayer avec du gingembre (oups
** RETRY Quiche
Bien cuire le fond de tarte avant (15-20min). Les bords doivent être parfaitement cuits !
** RETRY Soupe maïs-lait de coco (Des soupes qui nous font du bien)
Même en diminuant le ratio lait de coco/maïs à 40/60 au lieu de 60/40, encore
très riche. Essayer 70/30
** RETRY Vegan burger
Pois chiches 500g + 1 oeuf + assaissonnement + 150g de farine de sarrasin =
texture à la poêle OK. On peut probablement diminuer les doses de farine à 100g
Le plus important est d'avoir une pôle qui n'attache pas.
Source https://www.bbcgoodfood.com/recipes/chickpea-coriander-burgers
Avec du yaourt grec : moins sec mais une petite amertume

* Fermentation
** Levain :
  + tentative 1 : J1 = 100g sarrasin, 150g eau de source. J2 = pousse ! On garde
    70g, on ajoute 100g de sarrasin, 115g d'eau (robinet cette fois)

* Pains
Pour une croûte : augmenter la vapeur
*** Pain blanc
** Recette du NYT "No-Knead" fonctionne bien, avec 1/2 CC de levure pour 500g

*** Pain au sarrasin
** 1/3 sarassin, 2/3 farine complète : goût curieux, un peu lourd

*** Pain complet
http://bakeryaddict.canalblog.com/archives/2012/07/24/24767223.html
** Sans moule, pas mal
** [[http://www.abreaducation.com/wholewheat.php][Breadeducation]] lève mais un peu
    costaud 
    + seulement de la farine complète !

*** Pain de seigle
** Majoritairement farine de seigle, avec un peu de farine de blé au début +
    pendant processus
    + 1h pour première levée, 1h (?) seconde levée : n'a pas assez levé
    + 30min premiere levée, retravaillé 10min après, 1h15 seconde levée, cuisson
        50min à 200° : pas levé, juste étalé.

*** Pizza
** Overnight pizza from "Flour, yeast, water, salt"
Bonne pâte, difficulté est d'enfourner. Faire la pizza sur la pelle directement...
10min à 250 + 3 min gril !
