#+title: Workout
#+STARTUP: overview
* 2018
** 2018-07
*** 2018-07-18
**** Workout
Frog Stand 3x5s
Wall HeSPU 3x1
Muscle Up négatives 3x3 (1/3 de la descente)
Advanced back lever 7+8+15s
Advanced tuck Front lever 12+13+14s

*** 2018-07-22
**** Workout
Sun Jul 22 11:19:47 CEST 2018
Frog Stand : plus la force
Wall HeSPU 0
Muscle Up négatives 3+2+2 (1/3 de la descente)
Advanced back lever 10x3
Advanced tuck Front lever 10x3

*** 2018-07-25
**** Workout
Wed Jul 25 10:00:13 CEST 2018
Frog Stand 3x2s
Wall HeSPU 2
Muscle Up négatives 3x3 (1/2 de la descente)
Advanced back lever 3x5s
Advanced Front lever 3x5s

** 2018-08
*** 2018-08-13
**** Workout
Mon Aug 13 14:24:09 CEST 2018
Short-term goals (5 sets of 6-8s for static, 5 sets of 9-12 repeats):
- Free Handstand 10s (ATM: 3x3s max)
- L-sits 6s (ATM: 3x4s)
- Negative muscle-up (ATM: 0)
- Straddle planche (ATM : advanced tuck planche 3x3s)
- Back lever advanced tuck (ATM: tuck)
- Front lever advanced tuck (ATM: tuck/advanced tuck)
- Pull-over (ATM : weak L-pull-ups, 3x3)
Programme :
(Negative muscle-up x1 - 2.5min - L-sit x1 - 2.5min)x 3
(planche x1 - 2.5min - front lever x1 - 2.5min)x 3
Negative muscle-up : 3x5 but failed
L-sit 3x6s
SA frog stand : 6-5-4s
back lever : 3x5s

*** 2018-08-23
**** Workout
Thu Aug 23 19:39:30 CEST 2018
Negative muscle-up : 3x3, knee at 100 degree
Lsit 6-7-7-7-6s
Advanced tuck back lever : 4-3-1 s but bad form, go back on tuck
Wall HeSPU : during breaks (1). 2 at once
Tuck planche : 8-7-8s
Advanced tuck front lever : 6-8-9-5

*** 2018-08-29
**** Workout
Wed Aug 29 20:15:55 CEST 2018
Negative muscle-up : 4 avec genou à 90 degré, 4 à 45 degré, 3 avec anneaux au
niveau triceps mais besoin des pieds
L-sit 8-7-7-7-5
Wall HeSPU 5x1 + 1x2
Tuck back lever 15s
Advanced tuck back lever 2x6s (work on form)
Tuck planche 9-8-8

** 2018-09
*** 2018-09-02
**** Workout
Sun Sep  2 22:14:06 CEST 2018
Negative muscle-up : 3-4-4 avec aideavec genou à 90 degré, 4 à 45 degré, 3 avec anneaux au
Lsit : 8-8-8
Wall HeSPU 6x1
Advanced tuck back lever : 3-7-7 (90)
Front lever : 8-8-7

*** 2018-09-07
**** Workout
Fri Sep  7 19:45:50 CEST 2018
Negative muscle-up : 3-7-5-5 en partant accroupi + aidee jambes
Lsit : 9-8-8-7
Wall HeSPU 6x1. 1x2
Advanced tuck back lever : 7-7-6
Advanced front lever :  7-9-8
Advanced tuck Planche 8-7-6

*** 2018-09-10
**** Workout
Negative muscle-up : 3 simple-3x3 montée+descente en partant accroupi, anneaux aux épules (cf FitnessFAQ) aidee jambes
Lsit : 10-8-7
Wall HeSPU 5x1
Advanced tuck back lever : 2x6 (un peu plus propre)
Advanced front lever :  8-10-10
Advanced tuck Planche : 9-8-9

*** 2018-09-13
**** Workout
Negative muscle-up : 3x5
Lsit : 10-10-10
Wall HeSPU 5x1
Advanced tuck back lever : 10

*** 2018-09-18
**** Workout
Negative muscle-up : 3x5 (avec l'aide de al pointe des pieds)
Lsit : 10-9-9
Wall HeSPU : 6x1
Advanced tuck back lever : 3x10
Advanced tuck planche : 3x7

*** 2018-09-19
**** Workout
Stretch : splits

*** 2018-09-20
**** Workout
Stretch : splits
Negative muscle-up : 5-4-3-2
Lsit :  10-10-9
Wall HeSPU  6x1
Advanced tuck back lever : 11-10
Advanced tuck planche : 9-5

*** 2018-09-24
**** Workout
2x10s pancake split
1x10s toe touch
Shoulder

*** 2018-09-25
**** Workout
Negative muscle-up : 3x5
Lsit : 11-9-6
Wall HeSPU : 7x1
Advanced tuck back lever : 7-8-8
Advanced tuck planche : 9-7-6
Advanced tuck front lever : 8
Shoulder 3 (cf reddit) 10s each
1x90s pancake split

*** 2018-09-27
**** Workout
Pancake split 60s
Split routine 1x10s each
Toe-touching

*** 2018-09-28
**** Workout
Pancake split 90s

*** 2018-09-30
**** Workout
Équilibre x5

*** 2018-09-30
**** Workout
Pancake 80-55-40 Assis doit droit avec radiateur
Splits : avec des tabourets pour avoir le dos droit. 15s de chaque : 2xhip
flexor et split (cf routine d'Antranik)
Negative muscle-up : 5-2-4-83
Lsit : 9-9-8
Wall HeSPU 7x1
Advanced tuck back lever : 8-7-7
Advanced tuck planche : 9-8-9

** 2018-10
*** 2018-10-01
**** Workout
Pancake : 60

*** 2018-10-03
**** Workout
Pancake : 80-60
Split : 20s pour 3 échauffement et 40s de splits de chaque côté

*** 2018-10-04
**** Workout
Équilibre

*** 2018-10-05
**** Workout
Équilibre
Pancake : douleur au dos assis au sol en tiran sur le radiateur. Progression de
Tom Maverick à la place. 2x70 sur une chaise (ok) puis 65 sur une marche (seuil
actuel). Pas de douleurs

*** 2018-10-06
**** Workout
Negative muscle-up : 4.5-4.5-3-3
Lsit : 3x9
Wall HeSPU 6x1 (plus exigeant sur la forme !)
Tuck back lever :  3x7 (dos rond...)
Advanced tuck planche : 3x9
Pancake : 90 sur une chaise, 2x60 sur une marche

*** 2018-10-07
**** Workout
**Objectifs** étirement à 2 semaines : handstand 10s, pancake assis au sol 30s,
split 60

*** 2018-10-08
**** Workout
Splits : 30s (3 échauffement et split)
Pancake 60s chaise 60s marche

*** 2018-10-09
**** Workout
Handstand : max = 8s
Toe-touching x1

*** 2018-10-11
**** Workout
Handstand : 11s une fois !
Pancake : 1x chaise, 1x marche, non chrono

*** 2018-10-12
**** Workout
Negative muscle-up : 4-5-3
Lsit :  3x9
Wall HeSPU 11x1 + 2
Tuck back lever : 2x7-8
Advanced tuck planche : 9-9-7

*** 2018-10-24
**** Workout
Pushup planche 6-3
Negative muscle-up : 4-4-3
Lsit : 8-6-7 (jambe quasi tendu)
Handstand pushup lvl 2 : 3-4-3 (new progression, see https://www.youtube.com/watch?v=h0HjqYRlXYg)
Advanced tuck back lever : 5-5
Planche : 6x1 passages (rapide) tuck - genou écartés - tuck (http://gmb.io/planche/ "straddle open tuck hold").


** 2018-11
*** 2018-11-12
**** Workout
Negative muscle-up : 5-4-4
L-sit 6-6-6
Handstand pushup lvl 2 : 4-4-4
Tuck back : 4-5-4

*** 2018-11-19
**** Workout
Negative muscle-up : 4-3-3
Lsit : 5-5 (jambes tendues)
Handstand pushup lvl 2 : 4-4
Advanced tuck back lever : 5-4 (dos droits, jambe 90 ?)
Planche : 4x1 passages (rapide)

*** 2018-11-26
**** Workout
Muscle-up : 4-2 (réussi ???)-0
Lsit : 7-5-5 (jambes tendues)
Advanced tuck back lever : 5 (fesse hautes)-5 (dos droit !)-5
Handstand pushup lvl 2 : 4-4-5 (dernier quasi sans appuis)
Planche : 1x2 passages (rapide)

*** 2018-11-30
**** Workout
Muscle-up : 1.5-2-1 (assis, bras tendus)
Lsit : 7-6-5
Wall HeSPU : 4-4
Advanced tuck back lever : 5-6-5
Tucked planche (outside-inside) 2-3-3

** 2018-12
*** 2018-12-02
**** Workout
Muscle-up : 2-1-1 (L-sit sans toucher le sol !)
Lsit : 6-6-6
Wall HeSPU : 4-4-4
Advanced tuck back lever : 6-6-5
Tucked planche (outside-inside) 3-3-4

*** 2018-12-07
**** Workout
Muscle-up (L-sit) : 0 (6 tentatives)-2-1
Lsit : 7-5-6
Wall HeSPU  : 5-4-4
Advanced tuck back lever : 8-8-7
Tucked planche (outside-inside) 5-4-2

*** 2018-12-11
**** Workout
Muscle-up : (3 tentatives)-1-1
Lsit : 7-7-7
Wall HeSPU  : 5-4-4
Advanced tuck back lever : 7-7-7
Tuck - one-leg : 3x1s

*** 2018-12-15
**** Workout
Muscle-up : 1-2-2
Lsit : 9-5-6
Wall HeSPU 4-4-4 (les pieds "sautent")
Advanced tuck back lever : 8-5-6
Tuck - one-leg : 3x0.5s (2 pieds l'un après l'autre)

*** 2018-12-20
**** Workout
Muscle-up : 2-0-1
Lsit : 9-9-8
Wall HeSPU  4-3-2
Advanced tuck back lever : 4-6-4
Tuck - one-leg : 2x1s

*** 2018-12-30
**** Workout
Muscle-up : 0-1.5-1:5
Lsit : 10-9-7
Advanced tuck back lever : 4-6-6
Tuck - one-leg : 11


** 2018-12
** 2018-10 October
*** 2018-10-19 Friday
**** Handstand
**** Handstand
*** 2018-10-20 Saturday
**** Handstand
*** 2018-10-21 Sunday
**** Handstand
*** 2018-10-24 Wednesday
**** Handstand
Un peu de travail de changement position ("banane"-"droit"). Super dur
*** 2018-10-25 Thursday
**** Handstand
*** 2018-10-28 Sunday
**** Handstand
*** 2018-10-29 Monday
**** Handstand
*** 2018-10-30 Tuesday

**** Handstand
** 2018-11 November
*** 2018-11-01 Thursday
**** Handstand
*** 2018-11-02 Friday
**** Handstand
*** 2018-11-03 Saturday
**** Handstand
*** 2018-11-05 Monday
**** Handstand
*** 2018-11-09 Friday
**** Handstand
*** 2018-11-11 Sunday
**** Handstand
*** 2018-11-12 Monday
**** Handstand
*** 2018-11-13 Tuesday

**** Handstand
* 2019
** 2019-01 January
*** 2019-01-02
**** Workout
Wall straddle press eccentrics : moitié du mouvement
Straddle L-sit  ( https://www.youtube.com/watch?v=FAkSQE9cLDM ) seated : 2x10 (jambes mi-pliées...)
Muscle-up : 0-2x0.5-1.5
PLanche pull-up : 5-4-4
L-sit (rings, jambes pliées) : 3x3
Advanced tuck back lever : 7-6-6

*** 2019-01-04
**** Workout
Wall straddle press eccentrics : 2x4 (demi en remontée)
Straddle L-sit seated : 2x10 (jambes mi-pliées...)
Muscle-up : 1.5-2-2
L-sit (rings, jambes tendues à 80%) : 2x3
Advanced tuck back lever : 6-6-5
Handstand push-up : 3x3
Tuck - one-leg : 4x1s (2 jambes à la fois, extension complète !)

*** 2019-01-07
**** Workout
Wall straddle press eccentrics : 2x2 (demi en remontée)
Straddle L-sit seated : 2x10 (jambes mi-pliées...)
Muscle-up : 3x2 :)
Advanced tuck back lever : 6-6-6
Handstand push-up :  2 (sans "sauter" avec les pieds)
Tuck - one-leg : 3x1s

*** 2019-01-10
**** Workout
Wall straddle press eccentrics : 4-2
Straddle L-sit seated : 3x10
Muscle-up : 2-1.5-(0.5x2)
L-sit (rings, jambes tendues à 80%) : 4-4
Advanced tuck back lever : 7-6(jambe 45° !)-5
Handstand push-up : 3x3
Tuck - one-leg : 3x1

*** 2019-01-12
**** Workout
Wall straddle press eccentrics : 3x4
Straddle L-sit seated : 3x10
Muscle-up : 3x2 (bras tendu ! et false grip)
L-sit (rings, jambes non parallèles au sol) : 3x3s
Advanced tuck back lever : 3x6s
Handstand push-up : 3x3
Tuck - one-leg : 4x1s

*** 2019-01-19
**** Workout
Wall straddle press eccentrics : 4-1
Straddle L-sit seated : 3x10
Muscle-up : 4x3 (que du négatif, impossible d'en refaire normalement ajourd'hui)
L-sit (rings, jambes non parallèles au sol) : 2x3
Advanced tuck back lever : 5-4-3
Handstand push-up : 3x4
Tuck - one-leg : 3x1

*** 2019-01-23
**** Workout
Wall straddle press eccentrics : 3-3-2
Straddle L-sit seated : 3x10
Muscle-up : 3 (négatif) - 3 avec appui - 3 (appui)
L-sit (rings, jambes non parallèles au sol) : 3x1s
Advanced tuck back lever : 3x3s
Handstand push-up : 3-3-2.5 (plus en avant)
Tuck - one-leg : 3x1

*** 2019-01-25
**** Workout
Wall straddle press eccentrics : 3-5-5
Straddle L-sit seated : 3x10
Muscle-up : 4x3 (avec pied pour travailler technique)
L-sit : 3-2-2
Advanced tuck back lever : 5-6-4 (dernier = jambe mi pliées)
Handstand push-up : 1.5-3
Tuck : 8-6 -4-4(retour dos droit en statique, 30° avec le sol, 2 derniers avec jambes pliées)

*** 2019-01-30
**** Workout
Wall straddle press eccentrics : 5-4-4
Straddle L-sit seated : 3x10
Muscle-up : 4-3-3 (appui)
L-sit : 5-3-4 (au sol)
Advanced tuck back lever : 5-5-5
Handstand push-up :  4-3-2
Tuck : 4-4-2s

** 2019-02 Feburary
*** 2019-02-03
**** Workout
all straddle press eccentrics : 4-5-4
Straddle L-sit seated : 3x10
Muscle-up : 6x3 (test, pour l'instant anneau niveaau épaule)
L-sit : 6-5-3 (au sol)
Advanced tuck back lever : 3x3
Handstand puss-up :  4-1-3
Tuck : 4-s

*** 2019-02-07
**** Workout
Wall straddle press eccentrics : 4-4
Straddle L-sit seated : 3x10
Muscle-up : 3x3
L-sit : 4-4-4
Advanced tuck back lever : 4-4-4
Handstand puss-up : 3-3-1
Tuck : 3x4

*** 2019-02-12
**** Workout
Wall straddle press eccentrics : 4-3-5
Straddle L-sit seated : 3x10
Muscle-up : 3 debout épaule, 3 debout tiers nuque, 3 machoire, 3 oreille
L-sit : 4-4-4
Advanced tuck back lever : 6-6-6
Handstand push-up : 3-3-3
Tuck : 5-5-5

*** 2019-02-17
**** Workout
Wall straddle press eccentrics : 4-3-3
Straddle L-sit seated : 3x10
Muscle-up : 3 (machoire, accroupi) 2x3 (milieu cou, idéal pour ne pas s'aider des pieds)
L-sit : 4-4-4
Advanced tuck back lever : 7-7-5 (jambes sous thorax encore)
Handstand push-up : 3x3
Tuck : 6-5-5

*** 2019-02-20
**** Workout
Wall straddle press eccentrics : 4
Straddle L-sit seated : 3x10
Muscle-up : 3-3-2-2-1 (mi cou)
L-sit : 6-6-5
Advanced tuck back lever : 7-7-5
Handstand push-up :3-2-3 (plus dur si plus en vanat)
Tuck : 6-6-5

*** 2019-02-22
**** Workout
Wall straddle press eccentrics : 3-4-6
Straddle L-sit seated : 3x10
Muscle-up : 3-3-2-2 (base cou pour technique)
L-sit : 6-3-4-5
Advanced tuck back lever : 7-7-6
Handstand push-up : 3-3-3
Tuck : 6-4-5

*** 2019-02-27
**** Workout
Wall straddle press eccentrics : 3x10
Straddle L-sit seated : 3x3
Muscle-up : 3-3
L-sit : 4-5-4
Advanced tuck back lever : 7-7-7
Handstand push-up :  3-3-2
Tuck : 6-5-4
*** 2019-02-02 Saturday
**** Handstand
*** 2019-02-03 Sunday
**** Handstand
Travail de changement de position. Difficile mais semble super utile
*** 2019-02-07 Thursday
**** Handstand
Pieds joints en changeant de position
** 2019-03 March
*** 2019-03-02
**** Workout
Wall straddle press eccentrics : 2-2-7
Straddle L-sit seated :
Muscle-up : 3-3-2-2
L-sit : 4-4-4 (jambes bien droite mais un peu bas)
Advanced tuck back lever : 6-6-5 (plus à angle droit)
Handstand push-up : 3-2-2 (peut-être plus droit)
Tuck : 3x5

*** 2019-03-10
**** Workout
Wall straddle press eccentrics : 3x10
Straddle L-sit seated : 6-6-5
Muscle-up : 3-3-3
L-sit : 4-5-4
Advanced tuck back lever : 6-6-5
Handstand push-up : 3-2-3
Tuck : 5-5-5

*** 2019-03-13
**** Workout
Wall straddle press eccentrics : 6-3-3
Straddle L-sit seated : 3x10s
Muscle-up : 3-3-3 (niveau épaule pour technique)
L-sit : 4-4-5
Advanced tuck back lever : 6-6
Handstand push-up : 3-3-2
Tuck : 6

*** 2019-03-25
**** Workout
Wall straddle press eccentrics : 4-4-2
Straddle L-sit seated : 3x3
Muscle-up : 3-3-3
L-sit : 4-4-5
Advanced tuck back lever :6-7-6
Handstand push-up : 2.5-2-2
Tuck : 6-5-5

*** 2019-03-29
**** Workout
Wall straddle press eccentrics : 6-6-5
Straddle L-sit seated : 3x10
Muscle-up :  3-2-2-2
L-sit : 5-5-4

** 2019-04 April
*** 2019-04-01
**** Workout
Wall straddle press eccentrics : 6-5-5
Straddle L-sit seated : 3x10
Muscle-up : 3-3-2
L-sit : 3x4
Advanced tuck back lever : 7-7-6
Handstand push-up : 3-2-3
Tuck : 5-4-4

*** 2019-04-03
**** Workout
Wall straddle press eccentrics : 3x5
Straddle L-sit seated : 3x10
Muscle-up : 3-3-3
L-sit : 5-4-5
Advanced tuck back lever : 6-6
Handstand push-up : 3-3-3

*** 2019-04-09
**** Workout
Wall straddle press eccentrics : 3x4
Straddle L-sit seated : 3x10
Muscle-up : 3x3
L-sit : 3x4
Advanced tuck back lever : 3x6
Handstand push-up : 3-3
Tuck : 4-4-4

*** 2019-04-11
**** Workout
Floor to hEADstand : 1-2-2
Straddle L-sit seated (lent) : 5-5
Muscle-up : 3-2-3
Tucked planche (retour aux bases) : 10s-10

*** 2019-04-17
**** Workout
Wall straddle press eccentrics : 5-5-3
Straddle L-sit seated : 3x5 (lent)
Muscle-up : 3x3 (rings au niveau des épaules, usage de la pointe des pieds
encore)
L-sit : 5-5-4
Advanced tuck back lever : 6s-6
Handstand push-up : 3-3-2
Straddle Open Tuck Hold: 1-2s

*** 2019-04-24
**** Workout
Wall straddle press eccentrics : 3-3-4
Straddle L-sit seated : 2x5
Muscle-up : 3-3-2
L-sit : 4 (crampe...)-2-3
Advanced tuck back lever : 6-6-6
Handstand push-up : 3-3-2
Straddle Open Tuck Hold: 1-2-2s

*** 2019-04-27
**** Workout
Wall straddle press eccentrics : 5-6-7
Straddle L-sit seated : 6-6-6
Muscle-up : 3-3-3
L-sit : 5-4-5
Tuck back lever : 6-7
Handstand push-up : 3-3-3
Tuck : 0-1
*** 2019-04-23 Tuesday
**** Handstand
**** Handstand
*** 2019-04-24 Wednesday

**** Handstand
** 2019-05 May
*** 2019-05-01
**** Workout
Straddle L-sit seated : 5-5-5
Muscle-up : 3-2-2-1
L-sit : 4-4
Tuck back lever : 4-5
Tuck : 2-1-3

*** 2019-05-09
**** Workout
Wall straddle press eccentrics : 4-5-3 (3 quasi complets)7
Straddle L-sit seated : 5-5-5
Muscle-up : 3-3-3
L-sit : 5-4-4
Handstand push-up : 3-3-3
Tuck : 2-2

*** 2019-05-17
**** Workout
Wall straddle press eccentrics : 1 (entier, négatif)-2-2
Straddle L-sit seated : 3x3
Muscle-up : 3x3
L-sit : 5
Advanced tuck back lever : 7-6
Handstand push-up : 3x3
Tuck : 3-4

*** 2019-05-23
**** Workout
Wall straddle press eccentrics : 2-3-3 (negative)
Straddle L-sit seated : 3x5
Muscle-up : 3x3
L-sit : 5-5-4
Tuck back lever : 6-5-5
Handstand push-up : 3x3 (travailler forme)
Tuck to single leg (each leg) : 0.5(sic)x3

*** 2019-05-29
**** Workout
Wall straddle press eccentrics : 3x3
Straddle L-sit seated : 3x5
Muscle-up : 3x3
*** 2019-05-01 Wednesday
**** Handstand
*** 2019-05-07 Tuesday
**** Handstand
*** 2019-05-08 Wednesday
**** Handstand
*** 2019-05-09 Thursday
**** Handstand
*** 2019-05-10 Friday
**** Handstand
*** 2019-05-15 Wednesday
**** Handstand
*** 2019-05-16 Thursday
**** Handstand
*** 2019-05-17 Friday
**** Handstand
*** 2019-05-20 Monday
**** Handstand
*** 2019-05-21 Tuesday
**** Handstand
*** 2019-05-23 Thursday
**** Handstand
*** 2019-05-24 Friday
**** Handstand
*** 2019-05-25 Saturday
**** Handstand
*** 2019-05-26 Sunday
**** Handstand
*** 2019-05-27 Monday
**** Handstand
*** 2019-05-28 Tuesday
**** Handstand
*** 2019-05-29 Wednesday
**** Handstand
*** 2019-05-30 Thursday
**** Handstand
*** 2019-05-31 Friday

**** Handstand
** 2019-06 June
*** 2019-06-02
**** Workout
Straddle L-sit seated : 3x5
Muscle-up : 3-3-2 (2 complet !!!)
L-sit : 5-5-5
Advanced tuck back lever : 5-5-3
Handstand push-up : 3x3
Tuck (un peu tendu): 2-2
*** Revisiting goals (2019-06)
**** Workoutgoals:
***** Pushing vs pulling
**** Workout
Muscle-up        : vertical pushing, extension
Back lever       : horizontal pulling, extension
Planche          : horizontal pushing, flexion
V-sit            : pulling, extension

Handstand pushup : vertical pushing, flexion
Front lever      : horizontal pulling, flexion
***** Next levels
**** Workout
Advance if : 6s for static or 3 clean repetitions for dynamics
***** Goals
**** Workout
Note :
- handstand + manna are mandataroy fo S. Low and very interesting to combine
- straitght arm press handstand is mandatory and useful for planche
| Exercice          | Current level |
|-------------------+---------------|
| Handstand         |               |
| L-sit/V-sit/manna |               |
| Press handstand   |               |
| Back lever        |               |
| Planche           |               |
| Muscle-up         |               |
***** Routine
**** Workout
3x5-8
4-5x9-12s
(Muscle-up, rest 2.5min, Back lever, rest 2.5min) x3
(Planche, rest 2.5min, V-sit, rest 2.5min) x3

1. Warmup : static hold on rings
2. Skill work : L-sit, handstand, tumbling, core compression
3. Power/eccentrics/isometrics
4. Flexibility
*** 2019-06-09
**** Workout
NB: pairs with resting 2.5min
L-sit: 5-4-4
Compression: 1-5-3s (1cm ...)
Straddle L-sit: fail
Muscle-up: 1tentative avec appui-1 réussi-2 avec appui
Tuck planche: 3x7
*** 2019-06-13
**** Workout
NB: pairs with resting 2.5min
L-sit: 3x1s
Compression: 5-8
Straight-arm rings: 10-17-10
Straddle L-sit: fail
Muscle-up: 3-3-2 (avec pieds. Frayeur car barre de traction tombée...)
Tuck planche: 3-5
*** 2019-06-16
**** Workout
Straight arms rings : 20-17-15
Pull-up 3-2
Compression 3x8
Muscle-up + L-sit : 3x3 (2'30 de repos, L-sit entre 3s et 1s (à la fin))
Plank on rings + back lever + front lever: 1-1-1 (~3s chaque, mais mauvaise position)
*** 2019-06-20
**** Workout
Compression 8-6-6
Muscle-up + L-sit : 3.5#3s-2.5#2s-2#2s
Tuck planche on rings + tuck front lever + tuck back lever: 3s#3s#5s-5s#11s#7s-6s#12s#6s
*** Setting goals (2019-06-22)
**** Workoutgoals:
  | Now                         | Date      | Goal                |
  |-----------------------------+-----------+---------------------|
  | Muscle-up with feet         | +3 months | Strict muscle-up    |
  | Tuck back lever 7s          | +1 year   | Full back lever 1s  |
  | Avanced tuck front lever 1s | +1 year   | Full front lever 1s |
  | Semi-straddle planche 1s    | +3 months | Straddle planche 5s |
  | Handstand 3s                | +6 months | Handstand 30s       |
  | L-sit 7s                    | +6 months | Straddle L-sit 3s   |
*** 2019-06-22
**** Parkour
Essai des exercices pour le wall climb :
**** Parkour
- position chat x3
**** Parkour
- "pull-up" en position chat
**** Parkour
- knee raises (à droite)
**** Parkour
- extension de la jambe en position chat (x2, jambe non complètement tendue)
**** Parkour
*** 2019-06-23
**** Workout
Compression 8-6-6
Straigth arms RTO :  19-20-13
Extension (lower-back) : 10-9-10
L-sit (ground) : 3-4-4-2
Muscle-up + tuck planche : 4#2s-3#2s
tuck front lever + tuck back lever: 12#12-10#10-12#12-10#6
*2019-06-29 Sat
Compression 8-6-6
Straigth arms RTO :  20-19-19
Extension (lower-back) : 20-20
L-sit (ground) : 6-5-4
Muscle-up + tuck planche : 5#1s-5#1-5#1
tuck front lever + tuck back lever: 6#58+7#6+7#6
*** 2019-06-09 Sunday
**** Handstand
*** 2019-06-10 Monday
**** Handstand
*** 2019-06-11 Tuesday
**** Handstand
*** 2019-06-15 Saturday
**** Handstand
*** 2019-06-16 Sunday
**** Handstand
*** 2019-06-17 Monday
**** Handstand
*** 2019-06-18 Tuesday
**** Handstand
*** 2019-06-20 Thursday
**** Handstand
*** 2019-06-21 Friday
**** Handstand
*** 2019-06-22 Saturday
**** Handstand
*** 2019-06-24 Monday
**** Handstand
*** 2019-06-25 Tuesday
**** Handstand
*** 2019-06-26 Wednesday
**** Handstand
*** 2019-06-28 Friday
**** Handstand
*** 2019-06-30 Sunday

**** Handstand
** 2019-07 July
*** 2019-07-01 Mon
**** Parkour
Rambarde trop glissante...
**** Parkour
Toujours des difficultés pour le wall-climb : est-ce de la force brute pour les bras ? Impossible de pousser avec les jambes et envoyer vers le haut...
**** Parkour
**** Handstand
*** 2019-07-02 Tuesday
**** Handstand
*** 2019-07-03 Wed
**** Workout
Compression 3x8
Planch (sol + bras bien tendus cette fois !!) : 3x8
Straigth arms RTO :  17-15-12-10
Extension (lower-back) : 15
Muscle-up + L-sit : 3#1s-3#1-4#1-4#1 (jabmes presques horizontales)
advanced tuck front lever + advanced tuck back lever: 10#5 (dos courbé en back)-6#5 (fesse trop basses, dos droit)-6#5s (bonne position, maintenant arriver à avoir jambes à 90°)-6#5-3#3
**** Handstand
*** 2019-07-04 Thursday
**** Handstand
*** 2019-07-07 Sunday
**** Handstand
*** 2019-07-08 Mon
**** Workout
Compression 8-8-7
Planch (sol + bras bien tendus cette fois !!) : 4-4-3
Straigth arms RTO :  20-20-17-8
Extension (lower-back) : 3x22
Muscle-up + L-sit : 3x3#1-2#1 (mais jambes à 90° quasi tendues, bras tendus au début)
advanced tuck front lever + advanced tuck back lever: 4x4#4 (dos toujours courbé sur le back... mais front ok sur la forme)
**** Handstand
*** 2019-07-09 Tue
Passe-muraille :
- cat hang leg press 3x2
- cat hang pull-up 3x2
- cat hang shimmy 3x1
- top out
- 2 négatifs !!! Le problème est le placement des mains (que l'on ne travaille
pas en courant...)
**** Handstand
*** 2019-07-11 Thu
**** Workout
Burpee : 5-5
Skin the cat : 3-2
Compression 8-8-8
Straigth arms RTO :  21-20-16
Planch (sol + bras bien tendus cette fois !!) : 5-3-4
Extension (lower-back) : 21-21-15
Muscle-up + L-sit : 4#1-4#1-3#1-4#1 (dernière répétition pas terrible en forme)
advanced tuck front lever + advanced tuck back lever: 5#5-6#3 (dos droit pour
back lever)
*** 2019-07-12 Fri
**** Handstand
**** Parkour
Passe-muraille :
- cat hang leg press 3x3
- cat hang pull-up 3-3-2
- cat hang shimmy 3x1
- top out
- 4 négatifs
*** 2019-07-13 Sat
**** Handstand
**** Running
20min à allure moyenne. 3x10 burpee pour "couper la course", à la Spartan race

*** 2019-07-14 Sun
**** Handstand
**** Workout
Compression 8-7-8
Straigth arms RTO :  22-20-17
Planch (sol + bras bien tendus cette fois !!) : 3x4
Extension (lower-back) : 3x22
Muscle-up + L-sit : 4#1-4#1-4#1-3#1 (15! mais forme un peu limite)
advanced tuck front lever + advanced tuck back lever: 4x6#5
*** 2019-08-07 Wed
**** Handstand
**** Parkour
Passe-muraille :
- cat hang leg press 3x3
- cat hang pull-up 3-3-2
- cat hang shimmy 3x1
- top out
**** Parkour
- 3 négatifs
**** Parkour
** 2019-08 August
*** 2019-08-06 Tue
**** Handstand
*** 2019-08-08 Thu
**** Workout
Compression 3x8
Straigth arms RTO :  17-17-17-10
Planche tucked (sol + bras bien tendus cette fois !!) : 2x7s et 3 tentatives sur anneaux
Extension (lower-back) : 3x22
Muscle-up + L-sit : 4#1-3#1-3#1-2#1
advanced tuck front lever + advanced tuck back lever: 6#6-8#8
*** 2019-08-09 Fri
**** Handstand
**** Parkour
Passe-muraille :
- cat hang leg press 3x2
- cat hang pull-up 3-3
- cat hang shimmy 3x1
- top out
- 7 négatifs (!) dont 2 combiné à des top out
*** 2019-08-12 Mon
**** Workout
Extension (lower-back) : 3x22
Muscle-up + L-sit : 3x3#1
advanced tuck front lever + advanced tuck back lever:
*** 2019-08-14 Wed
**** Running
:PROPERTIES:
:reps: 13
:sprint: 45s
:rest: 45s
:END:
rythme constant, essayer d'accéler. 30s marche, 15s trot
*** 2019-08-15 Thu
**** Handstand
**** Parkour
Petite session technique avec Yvain
5 négatifs. Essayer en marchant avec changement de main
*** 2019-08-16 Fri
**** Running
:PROPERTIES:
:reps: 10
:sprint: 45s
:rest: 30s
:END:
*** 2019-08-17 Sat
**** Handstand
*** 2019-08-18 Sun
**** Handstand
**** Workout
Compression : 3x8
Straigth arms RTO : 20-20-17
Planche tucked : 1-1-1 (anneau)
Extension (lower-back) : 3x22
Muscle-up + L-sit : 3#1-3#2-3#2-3#2 (jambes pliées)
Advanced tuck front lever + advanced tuck back lever: 10#8-10#8-11#9
*** 2019-08-19 Mon
**** Handstand
*** 2019-08-21 Wed
**** Running
:PROPERTIES:
:reps: 11
:sprint: 45s
:rest: 30s
:END:
Marche
*** 2019-08-22 Thu
**** Parkour
Passe-muraille :
- cat hang leg press 3-2-2
- cat hang shimmy 3x1
- top out
- 3 négatifs
- knee-raises : 9 => presque !!
*** 2019-08-23 Fri
**** Workout
Compression : 3x8
Straigth arms RTO : 22-22-20
Planche tucked : 4x1 (commence à venir)
Extension (lower-back) : 24-23-21
Muscle-up + L-sit : 4x3#3
Advanced tuck front lever + advanced tuck back lever: 7#7-5#5-10#5 (dos courbé....)
*** 2019-08-24 Sat
**** Handstand
**** Running
:PROPERTIES:
:duration: 17min
:END:
Rythme moyen sans pauses (objectif = 20min)
*** 2019-08-25 Sun
**** Parkour
Passe-muraille :
- cat hang leg press 3x3
- cat hang pull-up 3x3
- cat hang shimmy 3x1
- top out 3
- 5 négatifs
- knee raises : 5. On pose maintenant les mains à plat, mais pas encore le ventre...
*** 2019-08-30 Fri
**** Running
:PROPERTIES:
:duration: 13min
:END:
rythme moyen sans pauses (objectif = 20min)
** 2019-09 September
*** 2019-09-01 Sun
**** Handstand
*** 2019-09-02 Mon
**** Workout
Compression : 3x8
Straigth arms RTO : 3x20
Planche tucked : 3x1
Extension (lower-back) : 3x22
Muscle-up + L-sit : 3x4#3
Advanced tuck front lever + advanced tuck back lever: 3x7#3
*** 2019-09-03 Tue
**** Running
:PROPERTIES:
:reps: 10
:sprint: 45
:rest: 30s
:END:
Tentative d'augmenter la fréquence
*** 2019-09-05 Thu
**** Parkour
Passe-muraille :
- cat hang leg press 3-2-2
- cat hang pull-up 3x3
- cat hang shimmy 3x1
- top out 3
- 3 négatifs
- knee raises 8
*** 2019-09-11 Wed
**** Workout
Compression : 3x8
Skin the cat : 3
Planche tucked : 3x1
Extension (lower-back) : 3x20
Muscle-up + L-sit : 3x4#3
Advanced tuck front lever + advanced tuck back lever: 5#5-7#5-8#5 (attention au dos)
*** 2019-09-15 Sun
**** Running
:PROPERTIES:
:duration: 15min
:END:
Medium
*** 2019-09-22 Sun
**** Workout
Compression : 3x8
German : 3-2
Active hang : 2min30 avec repos (max = 10s)
Passive hang : 1min
Extension (lower-back) : 3x22
Muscle-up + L-sit : 4#3-4#3-4#1
Advanced tuck front lever + advanced tuck back lever: 7#4-7#5-7#3 (dos rond....)
*** 2019-09-25 Wed
**** Running
:PROPERTIES:
:duration: 15min
:END:
Medium
*** 2019-09-30 Mon
**** Workout
Compression : 3x8
Straigth arms RTO : 2
Planche tucked : 3x1
Extension (lower-back) : 3x22
Muscle-up + L-sit : 3x4#3 (sauf dernier, 1seconde en L-sit)
Advanced tuck front lever + advanced tuck back lever: 7#5 5#5 5#5 (attention dos
rond...)
** 2019-10 October
*** 2019-10-01 Tue
**** Running
:PROPERTIES:
:reps: 8
:sprint: 45s
:rest: 30s
:END:
*** 2019-10-03 Thu
**** Parkour
Douleur IPP 4 donc brève séance : travail flux
*** 2019-10-04 Fri
**** Running
Moyenne : 9min30 + 2min30
*** 2019-10-07 Mon
**** Parkour
Entorse au doigts toujours.
Échauffement, equilibre et side vault du côté gauche OK.
**** Handstand
*** 2019-10-08 Tue
**** Workout
Compression : 3x8
German hang : 2-2-2
Planche tucked : 3x4 (au sol, jambes pliées, bras tendus)
Extension (lower-back) : 3x23
Muscle-up + L-sit : 4#3-2x4#{3-2-1}
Advanced tuck front lever + advanced tuck back lever: 5#2 (dos rond :/)
*** 2019-10-13 Sun
**** Parkour
Underbar, equilibre
*** 2019-10-14 Mon
**** Running
:PROPERTIES:
:duration: 15min
:END:
Medium
*** 2019-10-15 Tue
**** Handstand
**** Workout
Compression : 3x8
Skin the cat x3
Planche tucked : 4-3-3 au sol
Extension (lower-back) : 3x22
Muscle-up + L-sit : 4#3-4#3-2 (fixationo cassée...)
Advanced tuck front lever + advanced tuck back lever: Front sur une branche d'arbre : 4s max sur 10 essais
*** 2019-10-16 Wed
**** Handstand
*** 2019-10-17 Thu
**** Handstand
**** Running
:PROPERTIES:
:reps: 15
:sprint: 45s
:rest: 30s
:END:
*** 2019-10-18 Fri
**** Parkour
Travail de l'enchaînement
*** 2019-10-19 Sat
**** Workout
Compression : 3x8
Straigth arms RTO :
Planche tucked : 3x5 (sol, jambes pliées)
Extension (lower-back) : 3x22
Muscle-up + L-sit : 5#3-4#3-4#3
Advanced tuck front lever + advanced tuck back lever: 5#3-4#3
*** 2019-10-25 Fri
**** Workout
Compression : 3x8
Skin the cat: 3-2-2
Planche tucked : 3x5
Extension (lower-back) : 3x22
Muscle-up + L-sit : 3x{4#3}
Advanced tuck front lever + advanced tuck back lever: 5#5-5#5-5#4
*** 2019-10-26 Sat
**** Handstand
*** 2019-10-27 Sun
**** Handstand
*** 2019-10-28 Mon
**** Handstand
**** Parkour
Passe-muraille :
- cat hang 3x10s
- top out 3
- cat hang pull-up 3x3
- knee raises  3x2
*** 2019-10-29 Tue
**** Workout
Compression : 3x8
Skin the cat : 3x1
Planche tucked : 3x5
Extension (lower-back) : 3x22
Muscle-up + L-sit : 3x{4#3}
Advanced tuck front lever + advanced tuck back lever: 3x{5#3} (dos toujours rond)
*** 2019-10-07 Monday
** 2019-11 November
*** 2019-11-11 Mon
**** Handstand
**** Workout
Compression : 3x8
Skin the cat : 3-2-2
Planche tucked : 3x4
Extension (lower-back) : 3x22
Muscle-up + L-sit : 4#3-4#3-4#1
Advanced tuck front lever + advanced tuck back lever: 6#4-6#5-6#5 (travail dos droit... mais à confirmer)
*** 2019-11-16 Sat
**** Workout
Compression : 3x8
Skin the cat : 3x2
Planche tucked : 3x4
Extension (lower-back) : 3x22
Muscle-up + L-sit : 4#3-4#2-4#2
Advanced tuck front lever + advanced tuck back lever: 6#5 - 6#5-6#5 (dos droit si jambes pliées)
*** 2019-11-18 Mon
**** Workout
Compression : 3x8
Skin the cat : 0
Planche tucked : 3x6
Extension (lower-back) : 3x22
Muscle-up + L-sit : 6#3-6#3-3#2 (anneau mi pectoral => à travailler comme ça)
Advanced tuck front lever + advanced tuck back lever: 3x7#5
*** Weekly-routine                                                     :goals:
**** Goals
***** Workout
 - Long term : 5 muscle up, 2s levers complets
 - Short-term : 1 muscle-up reussi avec anneau mi-pectoral, 10s front lever
   (jambes 90°) et 10s back (jambes pliées)
***** Running
- Long term : 12km
- Short-term : 1h de course
https://www.reddit.com/r/running/comments/3bckeh/base_training_a_guide_to_your_foundation_to/
***** Trampoline
- Short-term : Front-flip propre, backflip
***** Parkour
- Long-term : wall-climb, 10 enchaînements
- Short-term : wall-climb, 5 echaînements faciles, lazy vault sans pause
**** Routine :routine:
Tous les jours : trampoline, handstand
Lundi : sprints (10min échauffement, 6x sprints de 100m à 95% avec 2min de pauses)
Mardi : parkour (technique, endurance)
Mercredi : muscu haut du cours
Jeudi : squats, course 30min tranquille
Vendredi : parkour (muscu, technique)
Samedi : muscu
Dimanche : squats, course 1h
*** 2019-11-21 Thu
**** Handstand
**** Parkour
Lazy vault : continue travail
Climb-up : toujours travail à l'arrêt mais avec élan sur un pied. Pas de
négatifs réussis.
*** 2019-11-22 Fri
**** Handstand
**** Running
:PROPERTIES:
:type:     easy
:duration: 25min
:distance: 4km
:END:
*** 2019-11-23 Sat
**** Handstand
 3x3s, 2x4s, 1x5s
*** 2019-11-24 Sun
**** Handstand
**** Parkour
Nouveau circuit : 2x2 cat hang shimmy, 2x3 pull-up, 3xnegatif, 2x2 knee raises,
2xtop out en jumpant
Aujourd'hui : 2 circuit + 0.2
*** 2019-11-25 Mon
**** Handstand
 3x3
 23x3
*** 2019-11-26 Tue
**** Handstand
**** Running
:PROPERTIES:
:reps: 6
:sprint: 100m
:rest: 2min
:END:
*** 2019-11-27 Wed
**** Handstand
 2-4-5-6-8
**** Workout
Compression : 8-8-7
Skin the cat : 0
Planche tucked : 3x6
Extension (lower-back) : 3x22
Muscle-up + L-sit : 5#5-4#5-4#3
Advanced tuck front lever + advanced tuck back lever: 10#4 - 10#4 - 11#5 (2eme =
dos droit mais bien surveiller)
*** 2019-11-28 Thu
**** Handstand
 2-3x3-3x4-5
**** Parkour
Musculation, surtout jambes :
pull-up : 5x3 sur poteaux blancs (épais...)
knee-shoulder : 3x4
Kipping : 3 tentatives
Precision jump : 0
Stair jump : 1x10, 4 marches
Squat : 2x25
Rail squat : 2
lunge : 4x6+1
Step up : 3x10 (de chaque côté)
Box jamp : 3x5
Rail plank : 3
Rail push-up: 2 de chaque côté
*** 2019-11-29 Fri
**** Parkour
3 endurance (courts)
2 circuits passe-muraille :
- cat hang shimmy 2x2
- cat hang pull-up 4x2
- knee raises 3x2
*** 2019-11-30 Sat
**** Handstand
 2+3x3-4-4-5

**** Handstand
** 2019-12 December
*** 2019-12-01 Sun
**** Running
:PROPERTIES:
:type:     medium
:duration: 28min
:distance: 9.5km
:END:
*** 2019-12-02 Mon
**** Handstand
 3-2x4-2x5-8-10
*** 2019-12-05 Thu
**** Parkour
2x26 squats
2x10 burpee
Tentative de circuits passe-muraille mais fatigue ++:
- cat hang shimmy 0
- cat hang pull-up 2x{2x2}
- knee raises 2x2
- négatifs 0
- assistance avec jambe : 6 essais
*** 2019-12-06 Fri
**** Handstand
 2x2-2x3-5-2x8
**** Parkour
2 circuits : 2 shimmy - 2 pull up - 3 leg press
Négatifs avec le pied gauche en appui
Pseudo climb-up en appui sur le sol. Même sur petits obstacles, non validé...
*** 2019-12-07 Sat
**** Handstand
 2x2-2x3-2x4-5-11
**** Parkour
30 squat
15 burpee
Technique : 5 répétitions de simple, saut de chat, side vault (G + D, grosse difficultés
à gauche, travail de 0)
3x3 pull up, travail muscle-up avec balancé
*** 2019-12-08 Sun
**** Handstand
 3x2-3-4-2x5
**** Running
:PROPERTIES:
:type:     long
:distance: 9km
:duration: 56min
:END:
*** 2019-12-09 Mon
**** Workout
Compression : 3x8
Burpee : 10
Skin the cat : 3-2
Planche tucked : 5-5-3
Extension (lower-back) : 3x22
Muscle-up + L-sit : 5#5 - 4#4.8 - 4#5 - 4#4 - 3#4
Advanced tuck front lever + advanced tuck back lever: 10#5-10#5-10#5
*** 2019-12-10 Tue
**** Handstand
 2x2-3-5-6-10
**** Parkour
15 burpees
30 side squat
2 circuits où 1 circuit =
- cat hang shimmy x2
- top out x3 (sauf 2eme ciruit)
- négatifs 3 avec 1 pied au sol
- cat hang pull-up 2x3
- knee raises 2x3
- climb-up avec appui au sol
 Bilan : hauteur ok, maintenant poser le ventre (ou plutôt tenir la position)
**** L-sit
3x2-3-3
*** 2019-12-11 Wed
**** Handstand
 2-3-4-5-6-2x8
*** 2019-12-10 Tue
**** Handstand
 2x2-3-5-6-10
**** Running
:PROPERTIES:
:type:     easy
:distance: 4.44km
:duration: 25min
:END:
*** 2019-12-12 Thu
**** Handstand
 3-4-2x5
****  L-sit
4x4-2
*** 2019-12-13 Fri
**** Workout
Compression : 3x8
Skin the cat : Tentative de forward roll = échec
Planche tucked : 6-6-5
Extension (lower-back) : 3x23
Muscle-up + L-sit : 5#5-4#3-4#2-3#1
Advanced tuck front lever + advanced tuck back lever : 10#6 - 10#6 - 5#3
*** 2019-12-14 Sat
**** Handstand
**** Running
:PROPERTIES:
:reps: 6
:sprint: 100m
:rest: 2min
:type:     sprint
:END:
**** L-sit
*** 2019-12-15 Sun :goals:routine:
**** Goals
Motivation :
- Not enough progress on the muscle-up => remove L-sit.
- Isometrics : steven low recommadns dynamic moves for parkour => stop back lever.
Categories
- Vertical pushing : handstand
- Vertical pulling : muscle-up
- Horizontal pushing : planche push-up
- Horizontal pulling
- Core : L-sit
**** Goals (short-term)
5 tuck planche push-up (with good form)
L-sit 30s (many sets as needed)
3x15 Tuck FL pull-ups
**** Routine (workout only)
Pairs :
- Planche (dynamic) :
  3x5 pseudo planche push-up,
  3x5 tuck L-sit push-up
  3x5 Tuck Front-lever pull-up
- 3x5 Muscle-up (with eccentrics !!!)
  3x5 Pistols
- L-sit
Compression 3x10s
*** 2019-12-15 Sun
**** Parkour
2 circuits :
- cat hang hold 2x10
- négatifs 3
- cat hang pull-up 2x3 (sauf 2eme passage, 1x3)
- knee raises  2x3
- leg assisted : 2x3 (sauf 2eme passage, 1x3)
  Bilan : peu de progressif, fatigue
*** 2019-12-16 Mon
**** Handstand
 3x2-4x3-4-5
**** Workout
Muscle-up : 5-4 (dont 3 vrais !!) - 4 (dont 3 vrais)
Pistols (each side): 5 (Léger appui 1 main, 75% de la descente) - 2x5 (95% mais plus difficile jambe gauche)
Push-up tucked planche : 3x2 (bras a priori tendu)
Pull-up front lever tucked 3x3 (attention position du bassin !!)
L-sit 0
Compression :0
Extension (lower-back) :0
*** 2019-12-18 Wed
**** Handstand
 5-5-7
**** Parkour
2 circuits :
- cat hang hold 2x10
- négatifs 4
- cat hang pull-up 2x3
- knee raises  2x3
- leg assisted : 2x3
  Bilan : fatiguee
*** 2019-12-19 Thu
**** Handstand
 2x2-2x3-2x5-6
**** Workout
Muscle-up : 3 vrais, 2 aidés - 3 vrais, 2 aidés - 3 vrais, 2 aidés
Pistols (each side): 5 (sans appui , 80% amplitude) - 5 avec appui - 5 avec appui à 100%
Push-up tucked planche : 2x3(avec pauses) - 2.5
Pull-up front lever tucked : 3x3
L-sit 3x4
Compression : 3x9
Extension (lower-back) : 3x22
**** Running
:PROPERTIES:
:distance: 4.79km
:duration: 31min
:speed: 9.78km/h
:END:
* 2020
** 2020-01 January
*** 2020-01-02 Thu
**** Running
:PROPERTIES:
:distance: 4.6km
:duration: 25min
:speed: 10.8km/h
:END:
**** L-sit
4-3 (mains vers le côté)-2-2-2
**** Handstand
 3x2-4x3-4-5
*** 2020-01-03 Fr
**** Handstand
 2x2-3-2x4-7-8
**** Workout
:PROPERTIES:
:ID:      b18afa46ea65-4dd4-bcb4-264ce390dd65
:END
Warmup :
Burpe 9
RTO:20-20-13
Musce-up : 4 (0 vris)-4 (2 vrais) - 3 (2 vrais)
Pistls (assisted)  3x5
Fron-lever row (tuked) : 3x3
Planhe tucked pushup: 3x{1-1-1}
Extesion (lower-bak) : 3x21
Compession : 3x8
L-si : 0
**** L-sit
Mains côté + jambes pliées x3. 1-2s
*** 2020-01-04 Sat
**** L-sit
3x2-3 (main vers côté, jambes non tendues)
**** Handstand
 2x2-2x3-3x4-5
*** 2020-01-05 Sun
**** Parkour
:PROPERTIES:
:ID:      2e5e8ae2948f-4d00-ae16-57bd89265bff
:END
Lazyvault à gauche: travailler
Demitour : ok à gache !
Kip-p : échec
Pass-muraille : 1 ircuit
- to out 3 (travailer côté gauche !)
- néatifs 3 (échec..)
- ca hang pull-up x3
- kne raises 2x4
**** L-sit
Switching to grease the groove 2x10-5
**** Handstand
 Stomach-to-wall, sci: 45s-40-30
 Back-to-wall: 5x2-2x
*** 2020-01-06 Mon
**** Handstand
 STW 23-45-33
 BtW 2x2-5x3-3x4
**** Parkour
:PROPERTIES:
:ID:       76fe3440-1ba9-40ba-8002-09c85bc5d119
:END:
Lazy vault à gauche en progression
Wall turn ok à gauche !
Wall climb : knee-up x3 de chaque côté x2. Essai de diminuer la difficulté :
- jumping OK mais négatif à travailler
- aide d'une jambe : échec, à retravailler.
*** 2020-01-07 Tuesday
**** Handstand
:PROPERTIES:
:ID:       9ee669eb-d396-4d0c-a8c0-1b57c67bc0b6
:END:
 StW 45-40-35
 BtW 3x2-3x3-4
**** Running
:PROPERTIES:
:ID:       cfce029a-85d3-4c29-8b73-f37cdb715e34
:type: sprint
:reps: 6
:sprint: 100m
:rest: 2min
:END:
*** 2020-01-08 Wednesday
**** Handstand
:PROPERTIES:
:ID:       e780823c-37e1-483d-9f35-b318c2fb4183
:END:
 StW 40-39
 BtW 3-4-5-6-11
**** Workout
:PROPERTIES:
:ID:       1e193dc4-60b8-4bb2-b7a6-3d40375be8a5
:END:
Warm-up : 5 burpee
Muscle-up : 3 faux, 4 vrais avec 3 pauses - 5 vrais avec 1 pause (anneaux plus haut : 2cm au-dessus du mamelon)-4 vrais
Pistols (assisted) : 3x5
Front-lever row (tucked) : 3x4
Planche tucked push-up: 4 avec pauses - 4 (dont 2 consécutifs)  - 4 (dont 2 consécutifs)
Extension (lower-back) : 3x22
Compression : 3x10
L-sit (jambes presque tendues) : 6-6-5
*** 2020-01-09 Thursday
**** L-sit
:PROPERTIES:
:ID:       6b21d301-d315-4e38-bc85-f65800274add
:END:
 2x10
**** Handstand
:PROPERTIES:
:ID:       a17a7a8e-dc08-4a85-9dd1-6df4479124af
:END:
 StW 45-25-30
 BtW 3x3-5-22 (!!!)
**** L-sit
:PROPERTIES:
:ID:       22fc3acd-b1a0-4a3a-ba04-67808259056c
:END:
 3x10
**** Running
:PROPERTIES:
:ID:       d2219525-7684-4a35-af0c-1b45896ec1a2
:type: medium
:distance: 5.13km
:duration: 28min
:speed: 11km/h
:END:
(nouveau record de vitesse mais 2 pauses aux feux)
*** 2020-01-11 Saturday
**** Handstand
:PROPERTIES:
:ID:       c98cdb9e-4833-4b98-9bcd-e57a12cd9d24
:END:
 StW 42-35-35
 BtW 2-3x3-4-5-6
**** L-sit
:PROPERTIES:
:ID:       33312696-2b07-4a5b-9ae4-0c84f16eefda
:END:
 2x10
*** 2020-01-13 Monday
**** Handstand
:PROPERTIES:
:ID:       30d6f01e-6579-4538-af0d-062a0573e728
:END:
 StW 35-35-25
**** Workout
:PROPERTIES:
:ID:       ea940737-6472-4c60-b5e7-4179ab70c658
:END:
Demi-session
Muscle-up : 7-6-3 (vrais ! et anneau mi-épaule !)
Pistols (assisted) : 3x5
*** 2020-01-18 Saturday
**** Handstand
:PROPERTIES:
:ID:       569d613b-7c14-4481-b498-4f145bdac5c2
:END:
 StW 40-37-32
 BtW 2-3-4-7-8
**** Workout
:PROPERTIES:
:ID:       a47f8394-56b8-4461-bffb-85767cd93dd3
:END:
Warm-up :
Muscle-up : 5-3-3 (vrais, 1cm au dessus de l'épaule)
Pistols (assisted) : 3x5
Front-lever row (tucked) : 3x3
Planche tucked push-up: 2+1+1 - 2-2 - 1
Extension (lower-back) : 3x22
Compression : 3x10
L-sit: 3x3
*** 2020-01-19 Sunday
**** Handstand
:PROPERTIES:
:ID:       e33df212-8317-45b9-a75b-585a1f167851
:END:
 StW 40-40-30
 BtW 2x2-3-2x4-5-13
*** 2020-01-20 Monday
**** Handstand
:PROPERTIES:
:ID:       e5edcab8-4b4b-42b8-a75c-fe3f266db287
:END:
 StW 33-28-28
 BtW 2-3x4-5
**** Parkour
:PROPERTIES:
:ID:       c731a5e7-948b-4170-bc51-f4b4cce7d994
:END:
Échauffement + circuit
*** 2020-01-21 Tuesday
**** Handstand
:PROPERTIES:
:ID:       47e14561-680f-48c8-9eca-e8edc235386e
:END:
 StW 35-32-25
**** Workout
:PROPERTIES:
:ID:       de9aaa92-3e20-486c-916e-1f2a5310b0d2
:END:
Warm-up : 5 burpee
Muscle-up : 3-4-3 (anneau mi-cou)
Pistols (assisted) : 3x5
Front-lever row (tucked) : »x3
Planche tucked push-up: 2+2-2+2-2+#
Extension (lower-back) : 3x22
Compression : 10-9-10
*** 2020-01-30 Thursday
**** Handstand
:PROPERTIES:
:ID:       7be97d68-86f9-4824-91c9-c77d0d29e6de
:END:
 StW 30-30-25
**** Workout
:PROPERTIES:
:ID:       6d203d8f-5306-48a8-8af0-c6bdc479b169
:END:
Warm-up : 5 burpee
Muscle-up : 4-3-3 (anneau milieu coup)
Pistols (assisted) : 3x5
Front-lever row (tucked) : 3x3
Planche tucked push-up: 3+2 - 1-2-2 + 3-1
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 3s
*** 2020-01-31 Friday
**** Parkour
:PROPERTIES:
:ID:       fb76badf-bd10-47df-8484-639694ff6d04
:END:
Workout :
- crawl (front + back) x2
- knee-raises : 3x15 (each side)
- lunges : 3x10
- pull-up: 5+3 - 3+3 - 3+2
- dips : 3x6
** 2020-02 February
*** 2020-02-01 Saturday
**** Handstand
:PROPERTIES:
:ID:       95c25edd-dfd3-41a7-8814-d2593ff9053a
:END:
 StW 35-35-30
 BtW 2x2-3-4-5-8
**** Running
:PROPERTIES:
:ID:       deb9d9bc-06e4-4583-8b7b-67ba853bd912
:type: easy
:distance: 4.76km
:duration: 27min
:speed: 10.4km/h
:END:
*** 2020-02-02 Sunday
**** Handstand
:PROPERTIES:
:ID:       768f84e8-feb3-4d83-a9fc-9f1786bd3f0f
:END:
 StW 35-30-35
 BtW 4-5-6
**** Workout
:PROPERTIES:
:ID:       33f05722-e18f-403b-aab6-3d970a86e676
:END:
Muscle-up : 3-3-2
Pistols (assisted) : 3x5
Front-lever row (tucked) : 3x3
Planche tucked push-up: 3+2 - 3+1 - 3+1
Extension (lower-back) : 3x22
Compression : 3x10
L-sit: 3x2
*** 2020-02-15 Saturday
**** Handstand
:PROPERTIES:
:ID:       61a3108a-61a6-42af-9c91-90248fdaf7b2
:END:
 StW 45-32-33
 BtW 3x2-2x4-2x5
*** 2020-02-16 Sunday
**** Handstand
:PROPERTIES:
:ID:       f0e4c905-d650-4e86-88be-130206381687
:END:
 StW 48-38-40
 BtW 2x2-2x3-4-3x5
**** Workout
:PROPERTIES:
:ID:       638c9674-6d3e-4266-bd6a-f7669e004b0f
:END:
Warm-up : 3-2 skin the cat
Muscle-up : 0-2-3
Pistols (assisted) : 3x5
Front-lever row (tucked) : 3x3
Planche tucked push-up: 3+2 - 3+2 - 1+1+1
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 2-2-1
*** 2020-02-17 Monday
**** Handstand
:PROPERTIES:
:ID:       cfca5e1c-083c-4803-b64f-01c9e635d4e7
:END:
 StW 50 (scissors) -30 (close to wall)-35
 BtW 2-3-4-2x5-10
**** Running
:PROPERTIES:
:ID:       660e2181-befd-4146-a492-552b4c81a335
:distance: 5.24km
:duration: 30min
:speed: 10.47km/h
:type:     easy
:END:
*** 2020-02-18 Tuesday
**** Handstand
:PROPERTIES:
:ID:       e17502cb-bb47-4106-8e9c-ac457c25a952
:END:
 StW 43-40-25-25
 BtW 2x2 - 3x3 - 4-5
*** 2020-02-20 Thursday
**** Handstand
:PROPERTIES:
:ID:       017fc236-d15e-4cc5-9b19-3c44edf12940
:END:
 StW 47-32-32
 BtW 4x3-4-2x5-6
**** Workout
:PROPERTIES:
:ID:       cb948d2d-7b65-4b7c-b45f-3e001fc9c25c
:END:
Warm-up : 2 skin the cat
Muscle-up : 0-2-4 (milieu du cou à travailler...)
Pistols (assisted) : 3x5
Front-lever row (tucked) : 3+2 - 3+2 -2+1
Planche tucked push-up: 3x3
Extension (lower-back) : 22
Compression :
L-sit : 2
*** 2020-02-21 Friday
**** Handstand
:PROPERTIES:
:ID:       e4fe217c-5ce6-44c2-ae24-0e6a4186c661
:END:
 StW 45-33-32
 BtW 5x3-5-6-9
*** 2020-02-22 Saturday
**** Running
:PROPERTIES:
:ID:       6ef30974-2f33-4131-8fc2-967e5de6d0a9
:type:     long
:distance: 8km
:duration: 48min
:speed: 10.44km/h
:END:
*** 2020-02-23 Sunday
**** Handstand
:PROPERTIES:
:ID:       a0832156-27a9-4faa-9889-cf6b711e2cfe
:END:
 StW 43-37-33
 BtW 3x2-2x3-2x4-5
**** Workout
:PROPERTIES:
:ID:       d8046458-087e-4b46-9525-f624c1951594
:END:
Warm-up : 3 skin the cat
Muscle-up : 3-6-3 (on revient aux épaules pour travailler le grip => ne pas mettre sur l'ulna...)
Pistols (assisted) : 3x5
Front-lever row (tucked) : 4-3-3
Planche tucked push-up: 3+2 - 3+2 - 2+1
Extension (lower-back) : 3x22
Compression : 3x10 (jambes enfin tendues !)
L-sit : 3-2-2
*** 2020-02-25 Tuesday
**** Parkour
:PROPERTIES:
:ID:       6f076633-ab53-4a68-b076-c1f7db300792
:END:
Circuit : par tranches de 3 exercices
- crawl back + front x3
- knee drive 3x15
- dips 3x5
- pull-up 3x5
- lunges 3x10
*** 2020-02-26 Wednesday
**** Running
:PROPERTIES:
:ID:       aabfcc9b-2df2-4b05-a7f6-5cf0bfa9532a
:distance: 4.6km
:duration: 25min
:speed: 10.91km/h
:type:     easy
:END:
*** 2020-02-27 Thursday
**** Handstand
:PROPERTIES:
:ID:       328c88eb-4c90-4e45-82fb-85c15a09fb18
:END:
 StW 35-35-30
 BtW 3x2-3x3-5-2x7
**** Workout
:PROPERTIES:
:ID:       4430be35-f416-41e8-809f-886016030381
:END:
Warm-up :
Muscle-up : 3 - 2 - 3 - 2 (en intérieur, position "assise" mais pieds en l'air)
Pistols (assisted) : 4-2-3 (appui sur radiateur, plus dur qu'avec les anneaux !)
Front-lever row (tucked) : 4-4-3
Planche tucked push-up: 3x{3+2+1}
Extension (lower-back) : 3x22
Compression : 3x10
L-sit: 3x2
*** 2020-02-29 Saturday
**** Handstand
:PROPERTIES:
:ID:       24bf7f16-3aa4-4a0a-95d4-737c7bb3e582
:END:
 StW 35-32-28
  BtW 3x2-4x3-4-2x8
** 2020-03 March
*** 2020-03-01 Sunday
**** Handstand
:PROPERTIES:
:ID:       c2fa09db-74a6-47d6-ba81-2d820f742d88
:END:
 StW 35-30-30
 BtW 2x2-2x3-4-2x5-6
**** Parkour
2x5 pompes
3x4 dips
3x16 lunges
3x17 knee raises
3x3 pull -up (conditions météo difficiles)
*** 2020-03-02 Monday
**** Handstand
 StW 32-31-25
 BtW 2x3-4x4-6
*** 2020-03-03 Tuesday
**** Handstand
 StW 37-33-25
 BtW 3x2-2x3-2x4
**** Workout
Warm-up : 2 skin the cat, 3 burpee
Muscle-up : 3-5-3 (épaule)
Pistols (assisted) : 5-3-3 (plus dur avec un point d'appui bas)
Front-lever row (tucked) : 4-4-3
Planche tucked push-up: 4+3 - 1+2 - 2+1
Extension (lower-back) : 22
Compression : 10
L-sit: 3
*** 2020-03-04 Wednesday
**** Handstand
 StW 42-30-24
 BtW 2-3-4x4-5-7
**** Parkour
Passe-muraille : 2 circuits avec 1 circuit =
- cat hang shimmy 8s x2
- top out 3 x2
- cat hang pull-up 3x2
- knee raises 4 x2
- pied au sol 4
*** 2020-03-05 Thursday
**** Handstand
 StW 32-28-28
 BtW 3x3-3x4
**** Running
:PROPERTIES:
:distance: 4km
:duration: 21min
:speed: 11.6km/h
:type:     easy
:END:
*** 2020-03-06 Friday
**** Workout
(NB fatigue++)
Warm-up : 4 burpee
Muscle-up : 3-4-3
Pistols (assisted) : 5-4-4
Front-lever row (tucked) : 5-3-3
Planche tucked push-up: 2+2+1 - 3+2 - 2+1
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 3x3
*** 2020-03-07 Saturday
**** Handstand
 StW 30-27-31
 BtW 2x3-3x4-5-2x6-8
*** 2020-03-09 Monday
**** Handstand
 StW 41-35-30
 BtW 3x2-3x3-3x4-6
**** Parkour
échauffement 2x5 burpees (dos droit pour pompes)
endurance : 5 mouvements x 3
knee-drive : 4 de chaque côté
*** 2020-03-10 Tuesday
**** Handstand
 StW 20-20-18
 BtW
**** Workout
Warm-up : 2x5 burpees, 2 skin the cat
Muscle-up : 3x4
Pistols (assisted) : 3x5
Front-lever row (tucked) : 4-4
Planche tucked push-up: 2+2 - 3+2 - 2+2
Extension (lower-back) : 3x22
Compression : 3x10
L-sit: 3-3-2
*** 2020-03-12 Thursday
**** Handstand
 StW 35-23-23
 BtW 3x2-3-5-7
**** Workout
Warm-up : Skin the cat 2-1 et Burpee 2x6
Muscle-up : 3x4
Pistols (assisted) : 5-4-4
Front-lever row (tucked) : 4-4
Planche tucked push-up: 3+2 - 3+2
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 2-2
*** 2020-03-14 Saturday
**** Handstand
 StW 35-28
 BtW 2-2x3-2-4-5-6
*** 2020-03-15 Sunday
**** Parkour
Kong large : ok mais seulement milieu de la rampe.
Endurance : 4 obstacle x 3
*** 2020-03-16 Monday
**** Handstand
 StW 37-37-30
 BtW 3x2-5-2x6
**** Workout
Warm-up : Trampoline
Muscle-up : 5-4-4
Pistols (assisted) : 3x4
Front-lever row (tucked) : 3x4
Planche tucked push-up: 2+2 - 3+2 - 3+2
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 3-2-2
*** 2020-03-18 Wednesday
**** Parkour
Lazy vault x5
Underbar x5
Kong : presque ok au 1/3 latéral
Knee raise x4 de chaque côté
*** 2020-03-19 Thursday
**** Handstand
 StW 32-33-27
 BtW 6x3-4-2x5
**** Running
:PROPERTIES:
:distance: 4.82km
:duration: 27min
:speed: 10.58km/h
:type:     easy
:END:
*** 2020-03-20 Friday
**** Handstand
 StW 23-23 (on économise le poignet)
 BtW 2-5x3-3x4-2x5
**** Workout
Warm-up : Trampoline
Muscle-up : 1-3-3 (difficile ajourd'hui)
Pistols (assisted) : 3x3 (plus difficile si on descend à 90% seulement)
Front-lever row (tucked) : 3x4
Planche tucked push-up: 3+3 - 3+2 - 2+2+1
Extension (lower-back) : 3x4
Compression : 3x10
L-sit : 3x3
*** 2020-03-21 Saturday
**** Handstand
 StW 32-10
 BtW 3x2-5x3-2-4-5-8
**** Parkour
Kong : plateau
Knee -up : too tired
Underbar : need another place to train
*** 2020-03-22 Sunday
**** Handstand
 StW 40-35-35
 BtW 3x2-4x3-6
**** Running
:PROPERTIES:
:distance: 8km
:duration: 51min
:speed: 10.2km/h
:type:     long
:END:
*** 2020-03-23 Monday
**** Handstand
 StW 15-30-35 (fesses serrées !)
 BtW 3x3-4-2x5
**** Workout
Warm-up : Trampoline
Muscle-up : 4-4-3
Pistols (assisted) : 3-3(-1) - 3
Front-lever row (tucked) : 5-3-3
Planche tucked push-up: 4+2 - 4+1 - 3+1
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 3-3-4
*** 2020-03-24 Tuesday
**** Handstand
 StW 37-30
 BtW 2x3-2x5-7
*** 2020-03-25 Wednesday
**** Handstand
 StW 42-30-25
 BtW 2x3-4-2x5-8
*** 2020-03-26 Thursday
**** Handstand
 StW 43-32-30
 BtW 4x3-4-2x5+6
**** Workout
Warm-up : Trampoline
Muscle-up : 1 (+4 avec appui) - 2(+4) - 1(+4) ! Bien retravailler la descente
Pistols (assisted) : 3x3 (bien travailler la forme)
Front-lever row (tucked) : 3-4
Planche tucked push-up: 2+1 - 3+2 - 3+2
Extension (lower-back) : 2x2
Compression : 2x9
L-sit : 2x3
*** 2020-03-28 Saturday
**** Handstand
 StW 37-42-30
 BtW 2x2-4x3-2x4-2x5-10
*** 2020-03-29 Sunday
**** Handstand
 StW 40-35-32
 BtW 4x2-3x3-4-2x5
**** Parkour
Kong, à retravailler
Reverse passe muraille, idem
Lazy vault à continuer
Demi-tour ok, à maintenir
*** 2020-03-30 Monday
**** Handstand
 StW 45-30-25
 BtW 3x3-3x4-5
**** L-sit
 7-7-6 (jambes pliées)
**** Workout
Warm-up : RTO 2x15, trampoline, skin the cat x2
Muscle-up : 1(+4) - 3(+2) - 3(+1)
Pistols (assisted) : 4-4 (dont 1 sans appui à jambe gauche !) - 5D+2G (sans appui à G)
Front-lever row (tucked) : 5-4-5
Planche tucked push-up: 3+3 - 4+1 - 3+2
Extension (lower-back) :
Compression :
*** 2020-03-31 Tuesday
**** Running
:PROPERTIES:
:reps: 8
:sprint: 20s
:rest: 10s
:type:     sprint
:END:
** 2020-04 April
*** 2020-04-02 Thursday
**** Handstand
 StW 35-35-25
 BtW 5x2-3x3-4-7
**** L-sit
 7-7
*** 2020-04-03 Friday
**** Parkour
Léger progres en lazy vault D. Constant à gauche
Régression en kong
*** 2020-04-04 Saturday
**** Workout
Warm-up : RTO 17x2-10, trampoline, skin the cat x2
Muscle-up : 1(+4 assisté) - 1(+4) sans toucher le sol
Pistols (assisted) : 3x5 (appui)
Front-lever row (tucked) : 5-5-3
Planche tucked push-up: 4+4 - 4+3 - 3+1
Extension (lower-back) : 3x22
Compression : 3x9
L-sit : 3x2
*** 2020-04-05 Sunday
**** Handstand
 StW 35-35-30
 BtW 3x2-3x3-2x4
**** L-sit
 3x7
**** Parkour
Workout (sans pause sur une série, 20m ?)
Quadrupédie avant + sprint : 5 puis 2 min pause
Quadrupédie arrière + sprint : 3 puis 2 min pause
Kong avant :  3 puis 2 min pause
Kong arrière : 1
*** 2020-04-07 Tuesday
**** Handstand
 StW 25
 BtW 2x2-2x3-2x4-6
**** L-sit
 7-6-7
**** Workout
Warm-up : RTO 20-20-7
Muscle-up : 0(+5 avec appui bout du pied) - 2(+3) - 1(+4)
Pistols (assisted) : 3x5
Front-lever row (tucked) : 5-5-5
Planche tucked push-up: 4+3 - 4+1 - 3+1
Extension (lower-back) : 3x22
Compression : 10-9-10
*** 2020-04-09 Thursday
**** Parkour
Stride : à peaufiner

Passe-muraille :
- négatifs 3-3
- pull-up 3 chaque chote
- top out 4
- cat hold
- cat move sideway
- knee up 4
- with help
*** 2020-04-10 Friday
**** Handstand
 StW 37-32-33
 BtW 5x3-3x4-2x5
**** L-sit
 3x7
*** 2020-04-11 Saturday
**** Workout
NB: début de torticolis
Warm-up : RTO : 6x10
Burpee : 4
Muscle-up : 0(+5) - 1(+4) - 1(+3)
Pistols (assisted) : 3x5
Front-lever row (tucked) : 5-4-3
Planche tucked push-up: 4+2 - 3+2 - 4+1
Extension (lower-back) : 2x22
Compression : 9-10
L-sit : 3-4
*** 2020-04-13 Monday
**** Handstand
 StW 37-37-36
 BtW 2x2-2x3-4
**** L-sit
 3x7
**** Parkour
Burpee 7+4+5
Side vault : légère progression (trottine à droite, contact à gauche...)
Kong : 2 validés
Demi tour ok
*** 2020-04-15 Wednesday
**** Workout
Warm-up : RTO 20-10-10 (dos droit = dur++)
Muscle-up : 0(+5) - 1(+4) - 2(+3)
Pistols (assisted) : 3x5
Front-lever row (tucked) : 4-4
Planche tucked push-up: 2+2+1 - 3+2
Extension (lower-back) : 2x22
Compression : 3x10
*** 2020-04-16 Thursday
**** Handstand
 StW 20-37-30
 BtW 4x4-2x5-7
**** Parkour
Passe-muraille :
- cat hang 8s de chaque côté x2
- cat hang shimmy 3 de chaque côté
- top out 4 (dont 3 combiné avec un négatif = fatiguant++)
-  négatifs
- cat hang leg press 3 de chaque côté
- cat hang pull-up 3 de chaque côté
- knee raises 4 de chaque côté x2
- wall climb avec appui au sol : 4 x 2
*** 2020-04-17 Friday
**** Handstand
 StW 41-31-33
 BtW 2-2x3-2x4-2x5
**** L-sit
 3x7
**** Running
:PROPERTIES:
:distance: 4.7km
:duration: 25min
:speed: 11.44km/h
:type:     easy
:END:
*** 2020-04-18 Saturday
**** Handstand
 StW 37-30-31 (quasiment main au bas du mur mais difficile !)
 BtW 2x2-4x3-3x4-5-8
**** Workout
Warm-up : RTO 3x10
Muscle-up : 2(+3) - 4 - 2(+2) Attention à ne pas tricher et garder les bras le plus tendus
Pistols (assisted) : 3x5
Front-lever row (tucked) : 5-5-4
Planche tucked push-up: 4+4 - 4+2 - 5+1
Extension (lower-back) :
Compression :
L-sit :
*** 2020-04-19 Sunday
**** Handstand
 StW 30-30-25
 BtW 3x3-2x4-2x7-8
*** 2020-04-21 Tuesday
**** Running
:PROPERTIES:
:distance: 4.75km
:duration: 25.50min
:speed: 11km/h
:type:     easy
:END:
*** 2020-04-22 Wednesday
**** Handstand
 StW 35-28-26
 BtW 2-2x3-4x4-2x5
**** Workout
Warm-up : RTO 3x10, burpee 3x5
Muscle-up : 5-6-4 (dont 3 répétitions enchaînées ! Bras pas assez tendu mais impression de franchir un plateau)
Pistols (assisted) : 3x4
Front-lever row (tucked) : 2x4
Planche tucked push-up: 4+2 - 4+2
Extension (lower-back) : 3x22
Compression : 2x9
L-sit :
*** 2020-04-23 Thursday
**** Parkour
Side vault : à retravailler
Kong vault : enfin la sensation d'un kong sur une barrière ! désormais, travailler la distance
Passe-muraille : 2x4 knee drive, 10 negative
*** 2020-04-24 Friday
**** Handstand
 StW 36-27-27
 BtW 7x3-3x4
**** Running
:PROPERTIES:
:distance: 7.5km
:duration: 42min
:speed: 10.8km/h
:type:     medium
:END:
*** 2020-04-25 Saturday
**** Workout
Warm-up : Burpee 2x6, RTO 4x10
Muscle-up : 3x3 (négatifs complets ! Jambes tendues mais bras encore pliés)
Pistols (assisted) : 3x5
Front-lever row (tucked) : 5-5
Planche tucked push-up: 5+2 - 3+1 - 3+1+1
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 3x3
*** 2020-04-26 Sunday
**** Handstand
 StW 35-35-30
 BtW 2x2-2x3-4-5-3x6
**** Parkour
Passe-muraille :
- cat hang shimmy : 3 moves
- top out : 3
- negative : 2x4 (assisted)
- cat hang leg press : 3 (each side)
- cat hang pull-up 3 (each side)
- knee raises : 4 (each side)
- assisted (1 foot down) 2x4
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15s
Low lunge : 30s
Front split  : 30s
Frog pose (dynamic) : 30s
Horse stance : 15s-15s
Standing pancake : 1min
*** 2020-04-27 Monday
**** Handstand
 StW 40-30-25
 BtW 2-2x3-4x4-4x6
**** Running
:PROPERTIES:
:type: sprint
:reps:     8
:sprint:   50m
:rest:     2min
:END:
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 0
Low lunge : 30s
Front split : 2x30s
Frog pose (dynamic) : 1min
Horse stance : 2x30s
Standing pancake : 2x1min
*** 2020-04-28 Tuesday
**** Splits
Standing splits (2-5s + rest) : 2x30
Wall calf :
Low lunge : 2x30s
Front split : 1min
Frog pose (dynamic) : 1min
Horse stance : 2x30s
Standing pancake : 1min
*** 2020-04-29 Wednesday
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15s
Low lunge : 40s
Frog pose (dynamic) : 1min
Horse stance : 40s
Standing pancake : 1min10
Front split : 1min
**** Parkour
Kong workout : 20m + 20m sprint + 40m marche
5 quadrupédie
5 reverse kong
5 quadrupédie à l'enverse
*** 2020-04-30 Thursday
**** Running
:PROPERTIES:
:type:     medium
:distance: 4.1km
:duration: 20min46s
:speed:    11.7km/h
:END:
** 2020-05 May
*** 2020-05-01 Friday
**** Handstand
 StW 35-30-30
 BtW 4x2-2x3-4-5-6-7
*** 2020-05-02 Saturday
**** Handstand
 StW 40-32-30
 BtW 5x2-2x3-2x4-7
**** Workout
Warm-up : 4x10 RTO
Muscle-up : 0(+4 avec bras plus tendus) - 1+(3) - 2+(2 mais négatifs avec appui
Pistols (assisted) :  3-2-3 (appui avec barre mais difficile de se relever)
Front-lever row (tucked) : 4-4
Planche tucked push-up: 1+1+1 - 3+2
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 3x3
**** Splits
Standing splits (2-5s + rest) : 40s
Wall calf : 10s
Low lunge : 40s
Frog pose (dynamic) : 1min
Horse stance : 5+10-10-5
Standing pancake : 1min25
Front split : 1min
*** 2020-05-03 Sunday
**** Handstand
 StW 32-29-29
 BtW 3x3-3x4-2x5
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf :
Low lunge : 50s
Frog pose (dynamic) : 1min
Horse stance : 30s
Standing pancake : 1min
Front split : 1min
**** Parkour
15 burpee avec 1 pause
Kong : 3 validés
Passe-muraille :
- 3x5 négatifs (avec appui
- 4 kip up
- avec appui : 5
! Je pense avoir compris comment poser le pied !
*** 2020-05-04 Monday
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 20s
Low lunge : 1min
Frog pose (dynamic) : 1min
Horse stance : 30s
Standing pancake : 1min
Front split : 1min
*** 2020-05-05 Tuesday
**** Handstand
 StW 43-37-33
**** Workout
Warm-up : trampoline
Muscle-up : 4 (en tendant de plus en plus les bras : mieux. Et descendant au maximum) - 1 (douleur)-4
Pistols (assisted) : 3x4
Front-lever row (tucked) : 5-6-6 (Dos un peu rond mais on valide quand même => niveau supérieur !)
Planche tucked push-up: 6+3 (!!) - 6+2 - 6+2 (On peut passer au niveau supérieur !)
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 3x3
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 0
Low lunge : 40s
Frog pose (dynamic) : 1min
Horse stance : 30s
Standing pancake : 1min
Front split : 1min
**** Notes
Augmenter la difficulté pour FL row : commencer à tendre les jambes
Idem pour le planche push-up
*** 2020-05-06 Wednesday
**** Parkour
fatigue++
Passe-muraille :
- cat hang shimmy (each side) : 10s
- top out (each side) : 3
- negative : 3x5
- cat hang leg press (each side) : 3
- cat hang pull-up (each side) : 4
- knee raises (each side) : 2x4
*** 2020-05-07 Thursday
**** Running
:PROPERTIES:
:type:     long
:distance: 7.54km
:duration: 41min25
:speed:    10.93
:END:
*** 2020-05-08 Friday
**** Handstand
 StW
 BtW 2x2-2x3
**** Splits
Standing splits (2-5s + rest) :
Wall calf : 15s
Low lunge :
Frog pose (dynamic) :
Horse stance :
Standing pancake : 1min
Front split :
**** Handstand
 StW 35-35-32
 BtW 2x2-4x3-4x4
**** Workout
Warm-up : 5x10s RTO
Muscle-up (négatifs lents) : 7-5-5
Pistols (assisted) : 5-5-3
Front-lever row (advanced tuck) : 0-1-1
Planche push-up (advanced tuck : 0-0-0 (que des négatifs)
*** 2020-05-09 Saturday
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 10s
Low lunge : 50s
Frog pose (dynamic) : 1min
Horse stance : 30s
Standing pancake : 45s
Front split : 45s
**** Handstand
 StW 32-32-32-31
 BtW 2x2-4x3-3x4-2x5
*** 2020-05-10 Sunday
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15
Low lunge : 40s
Frog pose (dynamic) : 1min
Horse stance : 30s
Standing pancake : 1min
Front split : 1min
**** Parkour
Side vault, endurance training (low intensity)
*** 2020-05-11 Monday
**** Handstand
 StW 35-35-32
 BtW
**** Workout
Warm-up : 20-20-19 RTO
Muscle-up (négatifs lents) : 7-5-4
Pistols (assisted) : 3x5
Front-lever row (advanced tuck) : 0-0-0
Planche push-up (advanced tuck): 0-0-0
Extension (lower-back) : 3x14 (dynamique)
Compression : 3x10
L-sit : 3-1-2
*** 2020-05-12 Tuesday
**** Handstand
 StW 35-38-30
 BtW 5x2-3x3-3x4
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15s
Low lunge : 40s
Frog pose (dynamic) : 1min
Horse stance : 30s
Standing pancake : 1min
Front split : 1min
**** Running
:PROPERTIES:
:type:     medium
:distance: 4.1km
:duration: 21min
:speed:    11.5km/h
:END:
*** 2020-05-13 Wednesday
**** Handstand
 StW 47-32-33
 BtW 3x3-6-10
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15s
Low lunge : 40s
Frog pose (dynamic) : 1min
Horse stance : 30s
Standing pancake : 1min
Front split : 1min
*** 2020-05-16 Saturday
**** Parkour
Quadrupédie avant + sprint x10
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15s
Low lunge :
Frog pose (dynamic) : 30s
Horse stance : 20s
Standing pancake : 30s
Front split :
**** Handstand
 StW 27-36-37-27
 BtW 5x2-3-2x4-5
*** 2020-05-17 Sunday
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 10s
- top out (each side) : 5 (avec 1 négatif à chaque fois)
- negative : 2x5
- cat hang leg press (each side) : 3
- cat hang pull-up (each side) : 4
- knee raises (each side) : 4
- avec appui : 2.5 x 4 (2 côtés)
Progression sur le passe-muraille avec appui. Bien pousser avec les jambes
*** 2020-05-18 Monday
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15
Low lunge : 45s
Frog pose (dynamic) : 1min
Horse stance : 30s
Standing pancake : 20s
Front split : 30s
**** Running
:PROPERTIES:
:type: sprint
:reps:     8
:sprint:   150m
:rest:     2min
:END:
Les sprint précédents étaient plus longs que prévus...
Essayé de forcer plus aujourd'hui sur la distance mais diminution des distances à la moitié
**** Handstand
 StW 37-27-26
 BtW 2x2-3x3
*** 2020-05-19 Tuesday
**** Workout
Warm-up : RTO 17x3
Muscle-up (négatifs lents) : 5
Pistols (assisted) : 5-5-4
Front-lever row (advanced tuck) : 3x2 tentatives. À la 3eme dos droit mais difficile. Pas d'amplitude encore (1cm max)
Planche push-up (advanced tuck): 3x2 négatifs
Extension (lower-back) : 3x22 (dynamique)
Compression : 3x10
L-sit : 2-3-2
**** Splits
*** 2020-05-20 Wednesday
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 3 déplacements
- top out (each side) : 3
- negative : 3x5
- cat hang leg press (each side) : 3
- cat hang pull-up (each side) : 4
- knee raises (each side) : 4
- avec appui : 4
**** Handstand
Freestanding : 12 essais
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 10s
Low lunge : 30s
Frog pose (dynamic) : 1min
Horse stance : 30s
Standing pancake : 1min
Front split : 30s
*** 2020-05-21 Thursday
**** Running
:PROPERTIES:
:type:     medium
:distance: 4.1km
:duration: 20min46s
:speed:    11.7km/h
:END:
*
*** 2020-05-22 Friday
**** Handstand
 StW
 BtW 2-3x3-4
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15s
Low lunge : 30s
Frog pose (dynamic) : 40s
Horse stance : 30s
Standing pancake : 30
Front split : 35
**** Handstand
 StW 40-35-32
 BtW 2-3-5x4-2x5
**** Workout
Warm-up : RTO 17-15-10-9
Muscle-up (négatifs lents) : 3x5
Pistols (assisted) : 3x5
Front-lever row (advanced tuck) : 3x3 tentatives. dos droit mais 1mm amplitude
Planche push-up (advanced tuck): 3x2 négatifs
Extension (lower-back) : 3x22
Compression : 3x10
*** 2020-05-23 Saturday
**** Handstand
 StW 30-27-25
 BtW 3x3-4-2x5-6
*** 2020-05-25 Monday
**** Handstand
 StW 39-33-27-25
 BtW 3x2-3-4-2x6
*** 2020-05-27 Wednesday
**** Handstand
 StW 32-30-25
**** Workout
Warm-up : RTO 17-7 (mais combiné au muscle-up)))
Muscle-up (négatifs lents) : 3x5
Pistols (assisted) : 5-4-3
Front-lever row (advanced tuck) : 3x3 tentative (1cm max mais dos droit)
Planche push-up (advanced tuck): 3-2-2 négatifs
Extension (lower-back) : 2x22
Compression : 2x10
L-sit : 3x4 (échauffement)
*** 2020-05-28 Thursday
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15s
Low lunge : 40s
Frog pose (dynamic) : 1min
Horse stance :
Standing pancake : 1min
Front split : 55s
**** Handstand
 StW 35-35-25
 BtW 7x3-2x4-5
**** Running
:PROPERTIES:
:type: sprint
:reps:     8
:sprint:   150m
:rest:     2min
:END:
*** 2020-05-29 Friday
**** Parkour
Passe-muraille :
- cat hang : 10
- top out (each side) : 5 (un seul côté)
- negative : 2x5 (toujours avec appui)
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 3
- knee raises (each side) : 4
- avec appui : 4
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15s
Low lunge : 40S
Frog pose (dynamic) : 1min
Horse stance : 15s
Standing pancake : 40s
Front split : 40s
*** 2020-05-31 Sunday
**** Handstand
 StW 39-30-25-25
 BtW 3x2-3-3x4-5
**** Workout
Warm-up : RTO 18-18-15
Muscle-up (négatifs lents) : 3x5
Pistols (assisted) : 3x5
Front-lever row (advanced tuck) : 3x3 tentatives (fesses un peu hautes)
Planche push-up (advanced tuck): 3x2 négatifs
Extension (lower-back) : 3x22
Compression : 3x10
** 2020-06 June
*** 2020-06-01 Monday
**** Handstand
 StW 38-28-24 (mains plus prèss = max, avec pieds qui décollent du mur légèrement => semble bien aider !!)
 BtW 4x3-2x4-6-9
**** Running
:PROPERTIES:
:type:     medium
:distance: 3.43km
:duration: 17min30s
:speed:    11.79km/h
:END:
*** 2020-06-03 Tuesday
**** Splits
Standing splits (2-5s + rest) : 30s
Wall calf : 15s
Low lunge : 40S
Frog pose (dynamic) : 1min
Horse stance : 15s
Standing pancake : 40s
Front split : 40s
**** Handstand
 StW 37-39-32-28-24 (main au max)
 BtW 4-5-6-7
*** 2020-06-05 Friday
**** Running
:PROPERTIES:
:type:     medium
:distance: 5.2km
:duration: 25min30s
:speed:    12km/h
:END:
*** 2020-06-06 Saturday
**** Handstand
 StW 40-37-27
 BtW 2-3x3-4-2x5-6
**** Workout
Warm-up : RTO 19-15-15
Muscle-up (négatifs lents) : 3x5
Pistols (assisted) : 3x5
Front-lever row (advanced tuck) : 3 x 3 tentatives (dos droit, 1cm amplitude max)
Planche push-up (advanced tuck): 3x3 tentatives en négatif
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 2-3-2
*** 2020-06-08 Monday
**** Parkour
Passe-muraille :
- cat hang (each side) : 10s
- top out : 5
- negative : 3x5
- cat hang leg press (each side) : 5
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- assisted : 4
*** 2020-06-09 Tuesday
**** Handstand
 StW 35-30-30-23 (en quasi équilibre !)
*** 2020-06-11 Thursday
**** Handstand
 StW 31-37-25
 BtW 3x2-3-2x4-2x6
**** Handstand
 StW 33-23-21
*** 2020-06-13 Saturday
**** Handstand
 StW 10-10-26-23
 BtW 5x3-2x5
*** 2020-06-14 Sunday
**** Handstand
 StW 32-25
 BtW
*** 2020-06-17 Wednesday
**** Handstand
 StW
 - 29-25-34
 - 23-32-26
 BtW 2-6x3-2x4
**** Workout
Warm-up : RTO 23-21
Muscle-up (négatifs lents) : 3x5
Pistols (assisted) : 3x5
Front-lever row (advanced tuck) : 3 tentatives
Planche push-up (advanced tuck): 3 tentatives
Extension (lower-back) : 3x22
Compression : 3x10
L-sit : 4x4
*** 2020-06-18 Thursday
**** Handstand
 StW 20-33-32
 BtW 5x3-4-2x5-6
*** 2020-06-19 Friday
**** Handstand
 StW 48-35-31
 BtW 2x3-3x4-5-7
*** 2020-06-20 Saturday
**** Parkour
Passe-muraille :
- cat hang hold (each side) : 10s
- top out assisted (each side) : 2x4 (en mettant le coude pour retenir le mouvement)
- negative : 3x5
- cat hang leg press (each side) : 4 (jambes bien tendues !)
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4 (sans pause !)
*** 2020-06-21 Sunday
**** Handstand
 StW : 3 répétitions filéme : ok
 BtW : 6 essai filmé : non aligné !! Après 3 essais, aligné mais ne tient pas la position
**** Workout
RTO-up : 2x23
L-sit : 3x4
Muscle-up (négatifs lents) : 5-5-4 (transitiont très lente !)
Pistols (assisted) : 3x5 (sensation de plus contrôler)
Extension (lower-back) : 3x22
Front-lever row (advanced tuck) : 3x{2(+1)} tentatives (attention à ne pas bouger que les fesses... pas de triche)
Planche push-up (advanced tuck): 4-3-3 tentatives
Norwegian curls: 3x3 (15° ? douloureux...)
Compression : 9-10
*** 2020-06-22 Monday
**** Handstand
 StW 40-37-25
 BtW 5 (travailler la posture en filmant depuis hier)
**** Running
:PROPERTIES:
:type:     sprint
:distance: 4.6km
:duration: 24min15s
:speed:    11.5km/h
:END:
*** 2020-06-23 Tuesday
**** Handstand
 StW 45-39-33)
 BtW 4x2-4x3-2x5
*** 2020-06-24 Wednesday
**** Handstand
 StW 46-32-35-30 (jambes pas assez droites et pieds trop en avant ! travailler plus près du mur)
 BtW 2x2-2x3-4-6-8
*** 2020-06-25 Thursday
**** Handstand
 StW 47-41-25
 BtW 2-2x4-5-6
*** 2020-06-26 Friday
**** Workout
RTO-up : 20-19-17
L-sit : 3x4
Muscle-up (négatifs lents) : 5-5-4 (ok pour le false grip ! descendre plus bas)
Pistols (assisted) : 3x5
Extension (lower-back) : 3x22
Front-lever row (advanced tuck) : 3 essais (1er = 1cm)
Planche push-up (advanced tuck): 3 essais avec début de remontée
Norwegian curls: 4
Compression : 9
**** Handstand
 StW 37-32-31
*** 2020-06-27 Saturday
**** Tricks :goals:
- front flip propre sur trampoline
- front flip sur matelas
- back flip sur trampoline
- front handspring
- kip up (utile pour back handstring)
**** Tricks
Front flip plutôt propre sur trampoline
Kip up : essai méthode de pigme mais pas encore ça
Back flip : encore latéral. Selon Thibault, rester désaxé pour le moment mais travailler plus le tuck
Front handscsrip : handstand + roll pour le moment

*** 2020-06-28 Sunday
**** Tricks
Kip up
Back flip
Front handspring

*** 2020-06-29 Monday
**** Tricks
Kip up : 2 réussis
Back flip
Front flip : ok à mi-hauteur
Front handspring : toujours pas
**** Handstand
 StW 45-45-38
 BtW 2-3x3-3x4-6-7
*** 2020-06-30 Tuesday
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 3
- top out (un côté) : 5
- assisted : 7-2
- negative : 2x5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4

**** Tricks
Kip up : 4 réussis
Front handspring : toujours pas
** 2020-07 July
*** 2020-07-01 Wednesday
**** Handstand
 StW 55 (!) - 45
 BtW 2-2x3-5-7
**** Running
:PROPERTIES:
:type: sprint
:reps:     7
:sprint:   150m
:rest:     2min
:END:
**** Tricks
Kip up : aucun réussi
Back flip : 3 essais mais trop fatigué
Front flip : 0
Front handspring : : avec un peu d'élan, atterissage sur les fesses (attention au dos)
*** 2020-07-02 Thursday
**** Handstand
 StW 50-37-32
 BtW 4-4x5-9
*** 2020-07-03 Friday
**** Workout
RTO : 23-23-17 (!)
L-sit : 3x5 (!)
Muscle-up (négatifs lents) : 4-5-4 (descente trop rapide...)
Pistols (assisted) : 3x4 (jambe tendue = pluse difficile)
Extension (lower-back) : 22-30
Front-lever row (advanced tuck) : 3x3 tentatives
Planche push-up (advanced tuck): 3x3 tentatives
Norwegian curls: 3-4-4
Compression : 3x10
*** 2020-07-04 Saturday
**** Handstand
 StW 45-36-27
 BtW plusieurs tentatives non chronométrées
*** 2020-07-06 Monday
**** Handstand
 StW 47-35-30
 BtW 3 essais filmés
**** Tricks
Kip up : 5, semble bon la moitié du temps !
Back flip : Trop sur le côté...
Front flip : OK assez bas avec peu d'élan !
Front handspring : : au mieux, on arrive sur les fesses
**** Running
:PROPERTIES:
:type:     medium
:distance: 4.4km
:duration: 23min (+ 6min après une courte pause..)
:speed:    11.3
:END:
*** 2020-07-07 Tuesday
**** Handstand
 StW 40-30
 BtW 2 essais filmés
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 4
- top out (each side) : 5
- negative : 3x5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- assited : 4 dont 3 avec passage complet en haut du mur !!!!
**** Tricks
Kip up : travail avec moins d'élan
Back flip : oui
Front flip : oui, avec peu de hauteur
Front handspring : : travail transition équilibre - pont
*** 2020-07-08 Wednesday
**** Workout
RTO-up : 27-20
Muscle-up (négatifs lents) : 3x5 (essai de non négatifs mais bof sur 2 essais)
Pistols (assisted) : 3x5
Extension (lower-back) : 3x22
Front-lever row (advanced tuck) : 3x3 (qq mm en plus ?)
Planche push-up (advanced tuck): 3x3
Norwegian curls: 3-4-3
Compression : 3x10
**** Tricks
Kip up : 5
Back flip : 3
Front flip : 0
Front handspring : : travail lent
*** 2020-07-09 Thursday
**** Handstand
 StW 34-15-30
 BtW 3 essais
*** 2020-07-10 Friday
**** Running
:PROPERTIES:
:type: sprint
:reps:     7
:sprint:   150m
:rest:     2min
:END:
**** Tricks
Kip up : contine travail avec moins d'élan
Back flip : 0
Front flip : 0
Front handspring : : j'atteris en position accroupie. Pousser plus avec les bras
*** 2020-07-13 Monday
**** Running
:PROPERTIES:
:type:     medium
:distance: 4.4km
:duration: 41min
:speed:    10.7km/h
:END:
*** 2020-07-14 Tuesday
**** Handstand
 StW 25-32
 BtW 3 essais filmés
**** Tricks
Kip up : 4
Back flip : 3
Front flip : 0
Front handspring : : à l'arrêt et avec élan, pas de progrès
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 3
- top out (each side) : 5
- negative : 2x5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) :
- assisted : 4+2 avec arrivée sur le mur !
*** 2020-07-15 Wednesday
**** Handstand
 StW 20-30 (mains encore plus proches)
 BtW 0
**** Tricks
Kip up : 5
Back flip : 5
Front flip : 0
Front handspring : : 5
*** 2020-07-16 Thursday
**** Workout
RTO-up : 18-8-13
L-sit : 3x4
Muscle-up (négatifs lents) : 5-5-4 + 1 positif
Pistols (assisted) : 3 (pied gauche *sans* aide) / 3 (droite avec aide) - 1/3 - 2/3
Extension (lower-back) : 3x22s
Front-lever row (advanced tuck) : 2+2 - 3+1 - 3 essais
Planche push-up (advanced tuck): 3x2
Norwegian curls: 4-4-3
Compression : 3x10
*** 2020-07-17 Friday
**** Running
:PROPERTIES:
:type:     medium
:distance: 4.4km
:duration: 23min42
:speed:    11.1
:END:
**** Handstand
 StW
 BtW 3 essais de 2
**** Tricks
Kip up : 4
Back flip : 3
Front flip : 0
Front handspring : : 3
*** 2020-07-18 Saturday
**** Handstand
 StW 33-32-19
 BtW 4 essais
**** Tricks
Kip up : 5
Back flip : 9
Front flip :
Front handspring : :
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 4
- top out (each side) : 5
- negative : 2x5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- assisted : 2+2 (mais avec un seul bras)
*** 2020-07-19 Sunday
**** Workout
RTO-up : 2x17
L-sit : 5-4
Essai de circuit : notation = 1ere passe # 2eme passe # 3eme passe
Muscle-up (négatifs lents) : 3 # 5 # 5
Pistols (assisted) : 3x5 # 3x5 (avec aide)
Extension (lower-back) : 22 # 22
Front-lever row (advanced tuck) :  2 # 3
Planche push-up (advanced tuck):  2 # 3
Norwegian curls:  3 # 3
Compression : 10
*** 2020-07-21 Tuesday
**** Handstand
 StW
 BtW 4 essais
**** Tricks
Kip up : 5
Back flip : 5
Front flip :
Front handspring : :
**** Running
:PROPERTIES:
:type:     easy
:distance: 4.11km
:duration: 21min
:speed:    11.6km/h
:END:
*** 2020-07-22 Wednesday
**** Handstand
 StW 40-35-25
 BtW
**** Workout
RTO-up : 20-19
L-sit : 5-4
Muscle-up (montée avec appui (genou pliés, anneau hauteur cour + négatifs lents en descente) : 2-3-3
Pistols (assisted) : 3#4 - 3#4 - 3#4 (non assité à gauche, assisté à droite mais presque bon)
Extension (lower-back) : 3x22 (bien contracter et mouvement d'arcs de cercle)
Front-lever row (advanced tuck) : 3x3 tentatives
Planche push-up (advanced tuck): 3x3 tentatives
Norwegian curls: 3x4
Compression : 3x10
*** 2020-07-26 Sunday
**** Workout
Warm-up : 25-21
Muscle-up (négatifs lents) : 3x3 (normaux, jambes tendues inclinées au sol)
Pistols (assisted) : 3x5 (assisté)
Front-lever row (advanced tuck) : 3x3 (3 répétitions identiques)
Planche push-up (advanced tuck): 3x3
Extension (lower-back) : 3x22
Compression : 9-10-9
L-sit : 2x5
** 2020-08 August
*** 2020-08-09 Sunday
**** Running
:PROPERTIES:
:type:     medium
:distance: 4km
:duration: 22min
:END:
*** 2020-08-10 Monday
**** Workout
RTO-up : 2x17 (douleur en essayant de mettre les épaules en arrière ...)
Muscle-up : 3-4 (courbatures dans les pectoraux...)
Pistols (assisted) : 2x5
Extension (lower-back) : 2x21
*** 2020-08-11 Tuesday
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 3
- top out (each side) : 5
- negative : 3
- cat hang leg press (each side) : 3
- cat hang pull-up (each side) : 4
- knee raises (each side) : 4
- assisted : 2-2 (!)
*** 2020-08-12 Wednesday
**** Running
:PROPERTIES:
:type:     easy
:distance: 5.39km
:duration: 33min
:speed:    9.78km/h
:END:
*** 2020-08-15 Saturday
**** Workout
Demi-sessions
RTO-up : 11-13
L-sit : 2x4
Muscle-up (négatifs lents) : 4-4-2
Pistols (assisted) : 3x5
Compression : 3x9
*** 2020-08-17 Monday
**** Handstand
 BtW 5 essais
**** Workout
RTO-up : 18-20
L-sit : 6-5 (nouveau record !)
Muscle-up (négatifs lents) :
Pistols (assisted) :
Extension (lower-back) : 3x22
Front-lever row (advanced tuck) : 3+1 - 2+1 - 2 (presque la moitié !,  peut-être parce que demi-session ?)
Planche push-up (advanced tuck): 3x3 tentatives, début remontée
Norwegian curls: 3x4
**** Running
:PROPERTIES:
:type:     easy
:distance: 4.58
:duration: 25min
:speed:    11km/h
:END:
*** 2020-08-17 Monday
**** Handstand
 StW
 BtW 3 essais
**** Running
:PROPERTIES:
:type:     easy
:distance: 4.58km
:duration: 25min
:speed:    11km/h
:END:
*** 2020-08-18 Tuesday
**** Handstand
 StW
 BtW 3 essais
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 4 (nouveau record)
- top out (each side) : 5
- negative :
- cat hang leg press (each side) : 5
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- assisted : 5 (nouveau record !)
- non-assisted : 2 (!!!!! enfin !!!!!! Mais trop de brute force, plus s'aider des pieds)
*** 2020-08-20 Thursday
**** Handstand
 StW
 BtW 4 essais
**** Workout
RTO : 13-15
Skin-the-cat : 2
L-sit : 2x5
Muscle-up : 3-3-2 (quasiment sans pause sur une série, le temps de reprendre la bonne position)
Pistols (assisted) : 6/2 - 6/6 - 5/3 (gauche/droit) avec appui fort)
Extension (lower-back) : 3x22
Front-lever row (advanced tuck) : 2+1 - 2+1 (plus difficile en fin de session...)
Planche push-up (advanced tuck): 2x3 tentatives (idem)
Norwegian curls: 2x4
Compression : 2x9
*** 2020-08-30 Sunday
**** Handstand
 StW 37-19
 BtW 2 tentatives
*** 2020-08-30 Sunday
**** Workout
RTO : 25/17
Skin-the-cat : 2
L-sit : 2x5
Muscle-up : 3x3 (plus facile avec les pieds sous les anneaux)
Pistols (assisted) : 3x6 (assisté)
Extension (lower-back) : 3x22
Front-lever row (advanced tuck) : 2+1 - 2 - 2
Planche push-up (advanced tuck): 3x3
Norwegian curls: 3x4
Compression : 9-10-10
** 2020-09 September
*** 2020-09-19 Saturday
**** Running
:PROPERTIES:
:type:     medium
:distance: 5.5km
:duration: 33min
:speed:    10km/h
:END:
*** 2020-09-22 Tuesday
**** Workout
Reprise très tranquille
RTO :  ok
Skin-the-cat : ok
Muscle-up : 2x2 avec appui sur jambe + impulsion bras
Pistols (assisted) : 3#3 en moyenne
Extension (lower-back) :  ok
Front-lever row (advanced tuck) : 80%
Planche push-up (advanced tuck):  70%
Norwegian curls: ok
Compression :  ok
*** 2020-09-23 Wednesday
**** Running
:PROPERTIES:
:type:     medium
:distance: 6.4km
:duration: 40min
:speed:    9.8km/h
:END:
*** 2020-09-25 Friday
**** Workout
RTO : 13-15
Skin-the-cat : 2+1.5
L-sit : 2 tentatives sur anneaux
Muscle-up : 2-4-2 (descente avec appui !)
Pistols (assisted) : 3x4
Extension (lower-back) : 3x22 (bras tendus)
Front-lever row (advanced tuck) : 3-2-2 tentaives
Planche push-up (advanced tuck): 2-2 (+1 tentative straddle mais échec)
Norwegian curls: 3x3
Compression : 3x10
*** 2020-09-26 Saturday
**** Handstand
 StW 35-24
 BtW 1-2x2-3x3-5
*** 2020-09-27 Sunday
**** Handstand
 StW 35-20
 BtW 2x3-4-2x5-6-10

**** Goals : éviter les plateaux
- Front lever pull-up : descendre d'un niveau (tucked) et augmenter jusque 3x15
- Planche push-up : descendre d'un niveau (tucked) et sur barres parallèles
- L-sit: viser 60min au total
**** Workout
RTO : 18+18
Skin-the-cat : 2.5 normaux
L-sit : 3x8 + 5 (rings + tucked)
Muscle-up : 2-3-3 (seul la première série a des négatifs en plus)
Pistols (assisted) : 4-4-3
Extension (lower-back) : 3x22
Front-lever row (tuck) : 7+2 - 5+2 - 4+3
Planche push-up (tuck): 0 (douleur à l'essai sur les barres)
Norwegian curls: 3x3
Compression : 3x10
*** 2020-09-29 Tuesday
**** Running
:PROPERTIES:
:type:     medium
:distance: 7.26
:duration: 43min
:speed:    10.1km/h
:END:
*** 2020-09-30 Wednesday
**** Handstand
 StW 30-23
 BtW 5x2-3-4-5-2x6
** 2020-10 October
*** 2020-10-01 Thursday
**** Workout
RTO : 2x18
Skin-the-cat : 2
L-sit : 3x6+3
Muscle-up : 3x3 (+ négatifs !)
Pistols (assisted) : 3x4
Extension (lower-back) : 3x22
Front-lever row (tuck) : 3+3 - 3+3 + 3-2
Planche push-up (tuck): 3x{2+1+1}
Norwegian curls: 3x3
Compression : 3x10
*** 2020-10-03 Saturday
**** Handstand
 StW 40-18
 BtW 2-3x3-4
*** 2020-10-04 Sunday
**** Running
:PROPERTIES:
:type:     medium
:distance: 7.18km
:duration: 41min41
:speed:    10.33Km/h
:END:
*** 2020-10-05 Monday
**** Workout
RTO : 20-17-17
Skin-the-cat : 2-1
L-sit : 3x6
Muscle-up : 3x3 (négatifs)
Pistols (assisted) : 3x5
Extension (lower-back) : 3x22
Front-lever row (tuck) : 3x{5+3)
Planche push-up (tuck): 3x{3+2}
Norwegian curls: 3x3
Compression : 3x10
*** 2020-10-06 Tuesday
**** Handstand
 StW 35-25
 BtW 3x3-5
*** 2020-10-07 Wednesday
**** Parkour
Side vault : travailler fluidité (G) + sans pied (D)
Passe-muraille : 3 avec appui et 5 sans appuis !!!
 -> Travailler maintenant de l'autre côté (pente) et en mettant les 2 bras
*** 2020-10-10 Saturday
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) :  5
- top out (each side) : 5
- cat hang leg press (each side) : 3
- cat hang pull-up (each side) : 5
- knee raises (each side) : 2
- 4 assisted
- 3 non assisted
Continuer le travail (assisté + non-asisstié)

*** 2020-10-13 Tuesday
**** Handstand
 StW 32-25-22
BtW 2x2-3x3-5-6

*** 2020-10-14 Wednesday
**** Workout
Skin-the-cat : 2+1
L-sit : 4x6s
Muscle-up : 2-4-4 (sans descente sauf les 2 premiers)
Pistols (assisted) : 3x4
Extension (lower-back) : 3x22
Front-lever row (tuck) : 2x{5+3} - 4+4
Planche push-up (tuck): 2+2+1 - 3+2+1 - 3+271
Norwegian curls: 3x4
Compression : 3x10
*** 2020-10-16 Friday
**** Running
:PROPERTIES:
:type:     medium
:duration: 45min
:END:

*** 2020-10-18 Sunday
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 3
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- avec appui : 5 pour bien saisir le mouvement et du côté gauche
- sans appui : 3

*** 2020-10-19 Monday
**** Handstand
 StW 15-20
 BtW 2x2-3x4-7-8-11 (!)
**** Workout
(Anneau un peu plus écartés)
Skin-the-cat : 1.5-1.5
L-sit : 6-6-3-3-5-5-2-2
Muscle-up : 3(+3neg) - 4(+2neg) - 4(+2neg)
Pistols (assisted) : 3x5
Extension (lower-back) : 3x22
Front-lever row (tuck) : 8+2 - 5+2
Planche push-up (tuck): 4+3+1 - 4+2
Norwegian curls: 2-4
Compression : 10-9 (forcant plus)

*** 2020-10-20 Tuesday
**** Running
:PROPERTIES:
:type: sprint
:reps:     7
:sprint:   100m->50m
:rest:     2min
:END:

*** 2020-10-22 Thursday
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 3(0 autre côté)
- top out (each side) : 4
- negative :
- cat hang leg press (each side) :
- cat hang pull-up (each side) : 3
- knee raises (each side) : 4
- assisted : 6 (trop glissant pour normal)

*** 2020-10-24 Saturday
**** Workout
RTO :
Skin-the-cat : 2.5
L-sit : 4x7
Muscle-up : 3-4-3 (bras plus tendus et négatifs à chaque fois !)
Pistols (assisted) : 3x5
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+2 - 1+2 - 4+2
Planche push-up (tuck): 3+2+1 - 2+1 - 3+1
Norwegian curls: 3x3
Compression : 3x10

** 2020-11 November
*** 2020-11-06 Friday
**** Workout
RTO :
Skin-the-cat : 2
L-sit : 2 essais
Muscle-up : 2-4-4
Pistols (assisted) : 4-5-4
Extension (lower-back) : 3x22
Front-lever row (tuck) : 2+2 - 4+2 - 3+2
Planche push-up (tuck): 3+2 - 2+2 - 2+2
Norwegian curls: 3x3
Compression : 9-10-9

*** 2020-11-08 Sunday
**** Running
:PROPERTIES:
:type:     medium
:duration: 26min
:END:
*** 2020-11-10 Tuesday
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 10
- top out (each side) :
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 4
- knee raises (each side) : 4 (avec bonne amplitude)
- avec appui : 4
- réussis : 7 !

*** 2020-11-11 Wednesday
**** Handstand
 StW 37-36
 BtW 2x2 - 4x4s - 5 - 7

*** 2020-11-12 Thursday
**** Workout
Essai de forward roll : échec. Travailler
L-sit : 3x1s - 3x1s - 3x1s
Muscle-up : 2 - 2+1+1 - 2+1 - 1 (2 d'un coup. Pour la moitié, descente en négatifs)
Pistols (assisted) : 6-5-5
Extension (lower-back) : 3x22
Front-lever row (tuck) : 4+2 - 4+2 - 3+3
Planche push-up (tuck rings!!):  3x1s-3x1s-3x1s
Norwegian curls: 3x3
Compression : 3x10s

*** 2020-11-13 Friday
**** Handstand
 BtW 3x2-3x3-4-3x5-2x6

*** 2020-11-14 Saturday
**** Handstand
 StW 45-22 (nouvel objectif : trouver l'équilibre plutôt que de tenir la position)
 BtW 5x2-3-4-2x6
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 3
- top out (each side) : 3
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) :  4
- knee raises (each side) : 4
- passe-muraille : 5 (+1 assisted)
Double kong : travailler position des pieds

*** 2020-11-15 Sunday
**** Handstand
 StW 47-34-37
 BtW 2-3x3-5
**** Workout
Forward roll : travail position de départ et d'arrivée
Skin-the-cat : 2
L-sit : 5-3-3
Muscle-up : 1+1+1+1 (+neg) - 2+1+1 (neg pour les 2 premiers) - 2+1+1 (1 seul neg)
Pistols (assisted) : 3x5
Extension (lower-back) : 3x32
Front-lever row (tuck) : 5+2 - 5+2 - 3+3
Planche push-up (rings, tucked):  2s-1s-2x1s
Norwegian curls: 3x3
Compression : 3x10

*** 2020-11-16 Monday
**** Handstand
 StW 33
 BtW 4x2-3-5-7

*** 2020-11-22 Sunday
**** Workout
Forward rolls x 10
**** Handstand
 BtW 6x3-2x4-5-4x6

*** 2020-11-23 Monday
**** Workout
RTO : 15s
Skin-the-cat : 2
L-sit : 5-5
Forward roll : 5 essais mais toujours pas de false grip
Super-superset :
- Muscle-up : 2x{2+1}
- Pistols (non assisted mais non complet) : 2x{5}
- Extension (lower-back) : 2x{22}
- Planche tucke on rings: 2x{2s-1s}
- Norwegian curls: 2x{4}
- Compression : 2x{10}

*** 2020-11-24 Tuesday
**** Running
:PROPERTIES:
:type:     medium
:duration: 29min
:END:

*** 2020-11-25 Wednesday
**** Parkour
Passe-muraille :
- cat hang shimmy (each side) : 10
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 4
- knee raises (each side) : 4
- passe-muraille: 9

*** 2020-11-26 Thursday
**** Workout
Forward roll : 5 (mieux avec magnésie)
RTO : 2x12s
Skin-the-cat : 2
L-sit : 2x7s
Muscle-up : 1 - 2+1 - 1+1 [manque d'énergie...]
Pistols (assisted) : 3x5 (non assité mais incomplet)
Extension (lower-back) : 3x22
Front-lever row (tuck) : 4+2 - 3+1 - 4+2
Planche rings (tucked): 2x1s-3x1s - 3x1s
Norwegian curls: 3x4
Compression : 3x10s

*** 2020-11-28 Saturday
**** Running
:PROPERTIES:
:type:     medium
:duration: 25min
:END:

*** 2020-11-30 Monday
**** Workout
RTO : 2x5s
Skin-the-cat : 2
L-sit : 2x5s
Muscle-up : 1 - 2+1 - 2+1
Pistols (assisted) : 3x{5 à gauche et 2 à droite [complets non assistés à droite !])
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+2 - 5+3 - 5+3
Planche tucked (rings) : 3x {3x1s}
Norwegian curls: 4-4-5
Compression : 3x10

** 2020-12 December

*** 2020-12-03 Thursday
**** Workout
RTO : 3x3s
L-sit : 3x3s
Muscle-up : 1+1 - 1+1+1+1 - 1+1+1
Pistols (assisted) : 3x{4 à droite, 2 à gauche (complet)}
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+3 - 5+3 - 5+2
Planche tucked (rings): 2s+1s - 3s - 3s
Norwegian curls: 6-6
Compression : 3x10

*** 2020-12-07 Monday
**** Workout
RTO + L-sit : 12+8 - 10+6
Skin-the-cat : 2
Muscle-up : 2+1 - 2+1 - 2+1 (nouveau record !)
Pistols (assisted) : 4 droite 1.5 gauche - 4 droite 2 gauche - 4d 2g
Extension (lower-back) : 3x22
Front-lever row (tuck) : 6+3 - 6+3 - 4+2
Planche on rings (tuck): 2+1 - 4+1 (nouveau record)
Norwegian curls: 4 (un peu plus bas) - 5-2
Compression : 3x9s

*** 2020-12-08 Tuesday
**** Parkour
Street workout, par paires
- L-sit: 3x{3x1s}
- Sissy squat : 3x6
- Knee raises : 3x10
- Rail squat : 10x1
- Hollow : 3x10s
- Pull-up : 5x2 - 4x3 - 3+1+2
- Lunge : 3x10
- Burpee : 10

*** 2020-12-12 Saturday
**** Workout
RTO : 20-15-15
L-sit : 6-5-5
Muscle-up : 2+1 - 2+1+1 - 2+1 (négatifs complets)
Pistols (assisted) : 3x{5droit - 2 complets à gauche}
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+2 - 5+2 - 4+1
Planche on rings (tuck): 2+1 - 2+1 - 2+1
Norwegian curls: 3x4
Compression : 3x10
*** 2020-12-13 Sunday
**** Parkour
Passe-muraille :
- cat hang (each side) : 10s
- top out : 5
- cat hang leg press (each side) :  4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- passe-muraille: 8
Double kong : ok sur l'herbe, travailler sur obstacle maintenant
*** 2020-12-14 Monday
**** Running
:PROPERTIES:
:type:     medium
:duration: 38min
:END:

*** 2020-12-15 Tuesday
**** Workout
Petite routine :

- haut = 1 muscle-up + 1 tucked planche (1S) + 2 tucked row
- jabmes = 5 pists à droit, 2 à gauche complet + 22s extensions + 10s compression + 4 norwegian curl

Au total : 
Échauffement : 3x{RTO 2s - L-sit 2s - 1 muscle-up négatifs - 1skin the cat}
- 2xhaut {mais pas de row la 2eme)  + 1xjambes
- 2xhaut {mais 1 row la 2eme)  + 1xjambes
- 2xhaut {mais 1 row la 2eme)  + 1xjambes

*** 2020-12-17 Thursday
**** Parkour
Travail double kong
Passe-muraille :
- cat hang (each side) : 10s
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- passe-muraille: 5

*** 2020-12-18 Friday
**** Workout
RTO : 20-16-10
Skin-the-cat : 2
L-sit : 8-6-4
Muscle-up : 2+1 - 2+1+1 - 2+1
Pistols (assisted) : 3x{5droit, 2gauches complet}
Extension (lower-back) : 3x22
Front-lever row (tuck) : 4+2 - 4+3 - 4+2
Planche on rings (tuck): 2+1 - 1+1 - 1+1
Norwegian curls: 3x4
Compression : 3x19

*** 2020-12-27 Sunday
**** Handstand
 BtW 2x2-3x3-2x4-5-2x6
**** Jump rope
Forward criss cross : 1 ok 50% du temps
**** Goals : jump rope
https://docs.google.com/spreadsheets/d/171np9B2sRb7edzWfskd-LZBpAHsh8GhfjAGw2eglrXI/edit#gid=960294792

*** 2020-12-28 Monday
**** Handstand
 BtW
**** Jump rope
Enchainement : regular bounce - skier - forward criss-cross
Besoin de tenir plus de 10s ...

*** 2020-12-29 Tuesday
**** Handstand
 BtW
**** Jump rope
criss-cross
**** Workout
RTO : 3x18s
Skin-the-cat : 1
L-sit : 3x6s
Muscle-up : 2x1 -3x1 - 4x1 (sans négatifs. Reprise ?)
Pistols (assisted) : 2#6  - 2#5 - 2#5
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+2 - 4+2 - 4+2
Planche on rings (tuck): 3+2 - 2+2 - 2+2
Norwegian curls: 5-3-3
Compression : 3x9

* 2021

** 2021-01 January

*** 2021-01-03 Sunday
**** Workout
RTO : 18-18-13
L-sit : 7-7-5
Muscle-up : 3x1 - 2+2x1 - 3x1  (+ négatifs)
Extension (lower-back) : 3x22
Front-lever row (tuck) : 3x{4+3 }
Planche on rings (tuck): 3+2 - 3+1 - 2+1+1
Compression : 3x10

On ménage les genoux aujourd'hui

*** 2021-01-05 Tuesday
**** Jump rope
**** Parkour
Passe-muraille :
- cat hang (each side) : 10s
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- passe-muraille: 8

*** 2021-01-06 Wednesday
**** Workout
RTO : 18-16-15
Skin-the-cat : 1
L-sit : 7-6-5
Muscle-up : 3x{2+1 (2 neg)}
Pistols (assisted) : 3x{2#4(d)}
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+3 - 4+3
Planche on rings (tuck): 3+1 - 3+1
Norwegian curls: 2x4
Compression : 9-10

*** 2021-01-07 Thursday
**** Jump rope
**** Running
:PROPERTIES:
:type:     medium
:duration: 30min
:END:

*** 2021-01-11 Monday
**** Running
:PROPERTIES:
:type:     medium
:duration: 23min42

*** 2021-01-12 Tuesday
**** Workout
RTO : 20-18-18
Skin-the-cat : 2
L-sit : 9-7-7
Muscle-up : 3x1(1 neg) - 4x1 - 3x1 (pas de nég... compliqué aujourd'hui)
Pistols (assisted) : 3x{5#2}
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+2 - 4+3 - 4+3
Planche on rings (tuck): 3+1 - 1+1 - 1+1
Norwegian curls: 3x4
Compression : 10-10-9

*** 2021-01-14 Thursday
**** Workout
RTO : 21-20-18
Skin-the-cat : 2
L-sit : 9-8-6
Muscle-up : 3x1 (1 neg) - 2+1+1 (2 neg) - 2+1 (2 neg)
Pistols (assisted) : 4#2-4#2-3#2
Extension (lower-back) : 3x22
Front-lever row (tuck) : 6+2 - 5+3 - 5+3
Planche on rings (tuck): 3+1+1 + 3+1+1 - 1+2+1
Norwegian curls: 3x4
Compression : 9-10-10

*** 2021-01-17 Sunday
**** Workout
RTO : 13-20-12
Skin-the-cat : 2
L-sit : 7-7-6
Muscle-up négatifs : 6
Pistols (assisted) : 5#2 - 4#3 - 3#2 (D#G)
Extension (lower-back) : 3x22
Front-lever row (tuck) : 4+2 - 4+2+1 - 4+2 (dur après les muscle-up)
Planche on rings (tuck): 3x1-2x1-3x1 (idem...)
Norwegian curls: 3x4
Compression : 10-9-9

*** 2021-01-19 Tuesday
**** Workout
Circuit training : tous les exercices echaînés (même à l'échauffement) et sans reposer le pied au sol pour anneaux
Échauffement = RTO + Lsit + skin the cat => 17+6+2 - 15+5+2

- Muscle-up + tucked planched + tucked FL
1+2s+3 puis 1+1s+1
- Pistols + norwegian curl + extension + compression
4#2 + 4 + 10s+ 22s

Pause 3min

- Muscle-up + tucked planched + tucked FL
1+2s+3 puis 1+1s+1
- Pistols + norwegian curl + extension + compression
4#2 + 4 + 10s+ 22s

Pause 3min
- Muscle-up + tucked planched + tucked FL
1+2s+3 puis 1+1s+1
- Pistols + norwegian curl + extension + compression
4#2 + 4 + 10s+ 22s

*** 2021-01-20 Wednesday
**** Parkour
Passe-muraille :
- cat hang (each side) : 10s
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 2x4
- passe-muraille: 8 (travail à gauche seulement, meilleure position la moitié du temps)

*** 2021-01-24 Sunday
**** Workout
RTO : 18-18-12
Skin-the-cat : 2-2
L-sit : 6-6-5
Muscle-up : 2+1 - 2+1+1 - 2+1 (négatifs en plus)
Pistols (assisted) :
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+3 - 5+3 - 5+3
Planche on rings (tuck): 2+1 - 3+1+1 - 2+1+1
Norwegian curls: 3x4
Compression : 10-9-10

*** 2021-01-29 Friday
**** Workout

RTO : 20-18-18
Skin-the-cat : 2
L-sit : 9-7-5
1 routine avec tout combiné :

Muscle-up + tucked planche + FL row tuked :
(
(1+3+2 - 1+1+1 - 1+0+0)
(1+2+2 - 1+1+1 - 1+1+1)
(1+2+2 - 1+1+1 - 1+1+1)
)
Pistols (assisted) + extension + cur + compresison:
(
(4#2 + 22 + 5 + 9)
(4#2 + 22 + 3 + 10)
(4#2 + 22 + 3 + 10)
)

** 2021-02 February

*** 2021-02-01 Monday
**** Workout
RTO : 28-20-13 (nouveau record)
Skin-the-cat : 2+2
L-sit : 10-8-8 (progrès)
Muscle-up : (négatifs) 3x5
Pistols (assisted) : 3x 4#2
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+3 - 5+3 - 3+3
Planche on rings (tuck): 3+2+1 - 2+1+1 - 2+1+1
Norwegian curls: 3x4
Compression : 9-10-9

*** 2021-02-03 Wednesday
**** Running
:PROPERTIES:
:type: sprint
:reps:     8
:sprint:   100m
:rest:     2min
:END:
*** 2021-02-05 Friday
**** Parkour
8 passe-murailles, meilleur technique
*** 2021-02-06 Saturday
**** Handstand
 BtW 3-4-5-9-11
**** Jump rope
record : 5x {4 normaux - 1 criss-cross)
boxer: mauvaise stratégie depuis le début : sauter simultanément !

*** 2021-02-09 Tuesday
**** Workout
RTO : 20-20
Skin-the-cat : 2-2
L-sit : 7-7
Muscle-up : 1+1 - 2+1+1 (1 négatif à chaque fois)
Pistols (assisted) : 3#2  - 3#2(D#G)
Extension (lower-back) : 2x22
Front-lever row (tuck) : 5+3 - 5+3 - 4+3
Planche on rings (tuck): 2-1-1 + 4-2 - 2-1
Norwegian curls: 3x4
Compression : 3x9
**** Jump rope
25min

*** 2021-02-15 Monday
**** Parkour
Passe-muraille :
- cat hang (each side) : 10s
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- passe-muraille: 8

*** 2021-02-16 Tuesday
**** Handstand
 StW 52
 BtW 2x3 - 4x5

*** 2021-02-18 Thursday
**** Workout
RTO : 20-18
Skin-the-cat : 2
L-sit : 8-8
Muscle-up : 2+1 - 2+1+1 - 2+1+1
Pistols (assisted) : 3 à gauche !, 2 demi à droite - 3 à gauche et 2 complet à droite - 3G et 2D
Extension (lower-back) : 3x22
Front-lever row (tuck) : 6+4 (!!) - 4+2 - 4+2
Planche on rings (tuck): 3+3 - 3+1 - 3+1
Norwegian curls: 4-4-3
Compression : 10-10-9
**** Jump rope
*** 2021-02-19 Friday
**** Jump rope
25min avec entraînement sur Hot and cold (130bpm) en box skip

*** 2021-02-22 Monday
**** Parkour
Passe-muraille :
- cat hang (each side) : 10
- top out (each side) : 5
- cat hang leg press (each side) : 5
- cat hang pull-up (each side) : 5
- knee raises (each side) : 5
- passe-muraille: 8

*** 2021-02-28 Sunday
**** Parkour
Passe-muraille :
- cat hang (each side) : 10
- top out (each side) : 5
- cat hang leg press (each side) : 5
- cat hang pull-up (each side) : 5
- knee raises (each side) : 5
- passe-muraille: 8
  Difficile aujourd'hui, tout en force
**** Jump rope
Début de compréhension du criss-cross
10 box skip succesifs max

** 2021-03 March

*** 2021-03-01 Monday
**** Running
:PROPERTIES:
:type:     medium
:duration: 20min
:END:
**** Jump rope
Comme hier

*** 2021-03-03 Wednesday
**** Jump rope
**** Workout
RTO : 13-13-18
L-sit : 7-7
Muscle-up : 6-7-6 (négatifs uniquement)
Pistols (assisted) : 3x {2#3}
Extension (lower-back) : 3x22
Front-lever row (tuck) : 3x{4+3}
Planche on rings (tuck): 3x{3+2}
Norwegian curls: 5-5-4
Compression : 3x10

*** 2021-03-05 Friday
**** Jump rope
2 criss-cross !
10s de boxer skip !
**** Jump rope
*** 2021-03-06 Saturday
**** Parkour
Passe-muraille :
- cat hang (each side) : 10
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 4
- knee raises (each side) : 4
- passe-muraille: 8 encore en force...
*** 2021-03-07 Sunday
**** Running
:PROPERTIES:
:type:     long
:duration: 44min
:END:

*** 2021-03-09 Tuesday
**** Workout
Tout echaîné sauf pauses (mais sans FL row)
Oubli de noter mais session correcte, sous-optimale par rappport à une session "normale"
Muscle-up : 1+1 - 1+1+1 - 1+1
Nouveau record en tucked planche: 4s !
*** 2021-03-10 Wednesday
**** Jump rope
Essai heel-toe : pas mal, à travailler !
Criss-cross: toujours difficile
Endurance en alterné mauvaise
*** 2021-03-11 Thursday
**** Workout
RTO : 20-15-7
Skin-the-cat : 2
L-sit : 7-5-3
Muscle-up : 1+1+1 - 2+1+1 - 2+1+1
Pistols (assisted) : 2#2 (assisté à droite) - 3#2 - 3#2
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+3 - 4+4
Planche on rings (tuck): 4+3 - 4+2
Norwegian curls: 5(!) - 4
Compression : 2x10

*** 2021-03-13 Saturday
**** Running
:PROPERTIES:
:type: sprint
:reps:     8
:sprint:   100m
:rest:     2min
:END:
**** Jump rope

*** 2021-03-14 Sunday
**** Jump rope
Criss-cross: faire la boucle plus tôt !
Ajout side swing (travailler les 2 côtés)
S'entraîner sur echaînement : heel-toe - skip - regular bounche

2eme session :
Echainement ok x 3 (HIIT !)
**** Parkour
Technique : passement + demi -tour

*** 2021-03-17 Wednesday
**** Jump rope
Entrainement à 120: un peu rapide..
**** Workout
Entraînement rapide : on echaîne tout :

3x le suivant :

2x {1 muscle-up - 3 tucked planche - 1 RTO 3S - 1 L-sit 3s - 1muscle-up négatif - 1 tucked planche pull-up 1 skin the cat}
Puis 2 L-sit (de chaque côté) - 4 norwegian curl -  10s compression - 22s superman

*** 2021-03-18 Thursday
**** Parkour
Passe-muraille seul (jump rope avant)
- cat hang (each side) : 10s
- top out (each side) :  5
- cat hang leg press (each side) : 4s
- cat hang pull-up (each side) :
- knee raises (each side) : 4
- passe-muraille: 8 mais seulement 1 non en force (prendre un rebord qui ne glisse pas, plus lever le genou...)
**** Jump rope
Ok pour pas sauté du rock mais fatiguant
Travail avec les playlist : bien pour cardio

*** 2021-03-19 Friday
**** Jump rope
Idem hier
**** Running
:PROPERTIES:
:type:     medium
:duration: 31min
:END:

*** 2021-03-21 Sunday
**** Workout
RTO : 23-18
Skin-the-cat : 2
L-sit : 8-6
Muscle-up : 2+1 - 2+1 - 2+1
Pistols (assisted) : 3x{3#2} (sans appui)
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+3 - 5+3 - 5+3
Planche on rings (tuck): 4+3 - 3+1 - 3+1
Norwegian curls: 3x4
Compression : 3x10

*** 2021-03-23 Tuesday
**** Jump rope
30min
Impossible de tourner !
**** Parkour
Passe-muraille juste (pas d'autre technique)
- cat hang (each side) : 10s
- top out (each side) : 5
- cat hang leg press (each side) :  4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- passe-muraille:  8 => important de bien poser son pied et d'avoir la jambe dans l'axe

*** 2021-03-25 Thursday
**** Jump rope
Focus sur le skipping (cf reddit)
Problem : plus difficile en appui à droite (mais il faut s'économiser en sautant moins haut)
Cheville un peu douloureuse
**** Parkour
Passe-muraille :
- cat hang (each side) : 10
- top out (each side) : 5
- cat hang leg press (each side) : 6
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- passe-muraille: 9
  Nouveau record :  meilleur appui à gauche. Maintenant penser à bien lever le genou => avec les 2, moins fatiguant !!

*** 2021-03-26 Friday
**** Workout
RTO : 23-18
Skin-the-cat : 2
L-sit : 8-6
Muscle-up : 2+1 - 2+1+1 - 2+1 mais formes ok avec négatifs
Pistols (assisted) : 2x3#2. Assistés à droite pour ménager la cheville. TODO: éviter de poser le pied désormais !
Extension (lower-back) : 3x22
Front-lever row (tuck) : 3x{5+3}
Planche on rings (tuck): 3x{4+2}
Norwegian curls: 3x4
Compression : 3x9 jambes tendues

*** 2021-03-29 Monday
**** Jump rope
40 min
**** Workout
Juste muscle-up aujourd'hui: objectif augmenter le nb de répétitions

RTO : 23-20
Skin-the-cat : 2
L-sit : 8-6
Muscle-up : 2+1+1+1+1 - 2+1 (sans nég) +1+1+1

*** 2021-03-30 Tuesday
**** Parkour
Passe-muraille :
- cat hang (each side) : 10
- top out (each side) : 5
- cat hang leg press (each side) : 5
- cat hang pull-up (each side) : 5
- knee raises (each side) : 4
- passe-muraille: 9 mais les premiers difficiles par manque d'élan

*** 2021-03-31 Wednesday
**** Running
:PROPERTIES:
:type: sprint
:reps:     8
:sprint:   100m->50m
:rest:     2min
:END:

** 2021-04 April

*** 2021-04-02 Friday
**** Jump rope
Moins se déplacer !
**** Workout
RTO : 23-20
Skin-the-cat : 2

Routine avec tout enchaîné :
Muscle-up - Tucked planche - Lsit - descente - Tucked pull-up
Série1 : 1-2-2-2 +  1-1-1-1  + 1 muscle-up
Série2 : 1-2-2-2 +  1-1-1-1
Série3 : 1-2-2-2 +  1-1-1-1

Et jambes à la suites :
Pistols (assistés à droite, non complet à gauche car jambe tendue) - Extension - Compression - Norwegian curls:
3x{3#2 - 22 - 9 - 4}

*** 2021-04-06 Tuesday
**** Workout
RTO : 23-20
Skin-the-cat : 1+1
L-sit : 10-8
Muscle-up : 5x1 - 4x1 - 4x1 (arrêt des négatifs au milieu)
Pistols (assisted) : 3x {3 assistés à drpoite, 2 non assisté à gauche)
Extension (lower-back) : 3x22
Front-lever row (tuck) : 5+3+2+2+2+1 - 5+3+2+2 - 5+2+2
Planche on rings (tuck): 6+3+1 (record) 5+2+1 5+3
Norwegian curls: 3x4
Compression : 9 -5 - 5

Au final, séance où j'ai poussé les limites, à refaire

*** 2021-04-07 Wednesday
**** Handstand
 StW 48-32-23
 BtW 3 - 2x6

*** 2021-04-08 Thursday
**** Handstand
 StW 38-42
 BtW
*** 2021-04-10 Saturday
**** Workout

Routine avec tout enchaîné :
Muscle-up - L-sit - Tucked planche - RTO - descente - Tucked pull-up - Skin the cat
Série1 : 3x1-2-2-2-2
Série2 : idem mais perte de forme à la 2e et 3e répetition
Série3 : idem mais perte de forme à la 2e et 3e répetition
+1 en répetition !

Et jambes à la suites :
Pistols (assistés à droite, complet à gauche) - Extension - Compression - Norwegian curls:
3x{2#2 - 22 - 10 - 4}

*** 2021-04-11 Sunday
**** Handstand
 StW 44-39-33
 BtW 2-4x3-2x4-5-7-8
**** Running
:PROPERTIES:
:type:     long
:duration: 44min
:END:

*** 2021-04-12 Monday
**** Handstand
 StW 51-25-25-25

*** 2021-04-13 Tuesday
**** Handstand
 StW 35-45-39-30
 BtW 2-3-5-8

*** 2021-04-14 Wednesday
**** Handstand
 StW 52 (!) - 42 - 22
 BtW 5x2 - 6x3 - 3x4 - 5 - 2x7

*** 2021-04-15 Thursday
**** Workout
RTO : 23
Skin-the-cat : 2-1
L-sit : 10-8
Muscle-up : 2+1+1 - 2+1+1+1+1 - 1+1+1
Pistols (assisted) : 3x{2#3} (appui à droite)
Extension (lower-back) : 2x10
Front-lever row (tuck) : 8+5+5 (!)
Planche on rings (tuck): 5+3 - 5+3
Norwegian curls: 5-5
Compression : 10-9
**** Handstand
 StW 30
 BtW

*** 2021-04-16 Friday
**** Handstand
 StW 57 (!) - 44 - 35

*** 2021-04-17 Saturday
**** Parkour
Passe-muraille :
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 5
- passe-muraille: 9 : la seconde moitié commence à moins utiliser les bras. Il faut penser à lever le genou le plus haut possible (toucher le mur avec)
*** 2021-04-18 Sunday
**** Running
:PROPERTIES:
:type:     sprint
:duration: 16min
:END:
*** 2021-04-19 Monday
**** Handstand
 StW 59-38
 BtW
**** Parkour
Passe-muraille :
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 5
- passe-muraille: 9 : la seconde moitié commence à moins utiliser les bras. Il faut penser à lever le genou le plus haut possible (toucher le mur avec)

*** 2021-04-20 Tuesday
**** Handstand
 StW 58
 BtW
**** Workout
RTO : 27 - 17
Skin-the-cat : 2-1
L-sit : 9-7
Muscle-up : 7x1 - 2+1+1+1 - 3x1
Pistols (non assisté !) : 2x{2#3} (utiliser toute la plante pour l'appui !)
Extension (lower-back) : 3x10
Front-lever row (dos droit ! mais amplitude très faible) : 3x{ 2x1cm}
Planche on rings (tuck): 3+3 - 3+2 - 3+2
Norwegian curls:  3x4
Compression :  3x9 (to failure)

*** 2021-04-22 Thursday
**** Parkour
Passe-muraille :
- cat hang (each side) : 7
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 4
- knee raises (each side) : 5
- passe-muraille: 10 (plus de poussée sur les jambes à la seconde moitié)

*** 2021-04-23 Friday
**** Handstand
 StW 50-25
 BtW

*** 2021-04-24 Saturday
**** Handstand
 StW 22-33-30-32
 BtW 2-3-10

*** 2021-04-26 Monday
**** Workout
RTO : 23-20
Skin-the-cat : 1-1
L-sit : 10-6
Muscle-up négatif : 6-7-7
Pistols (assisted) : 3#2 - 3#2 - 3#3 : attention, genou non contrôlé !! Retravailler
Extension (lower-back) : 3x22
Front-lever row (90°) : 3+1 - 2+2 - 2+1
Planche on rings (tuck): 4+3  -3+1 - 3+2
Norwegian curls: 3x4
Compression : 10-8-9

**** Handstand
 BtW 3x3s

*** 2021-04-27 Tuesday
**** Handstand
 StW 35-37-37-30
 BtW 3-3-4
 headstand : 1 essai

*** 2021-04-28 Wednesday
**** Handstand
 StW 47-21-37
 BtW 2x2-2x3-4-5-2x6-11
**** Running
:PROPERTIES:
:type:     medium
:duration: 30min
:END:

*** 2021-04-30 Friday
**** Parkour
Passe-muraille :
- cat hang (each side) : 10-5
- top out (each side) : 5
- cat hang leg press (each side) : 4
- cat hang pull-up (each side) : 5
- knee raises (each side) : 6
- passe-muraille: 9 => la moitié environ sans trop forcer

** 2021-05 May

*** 2021-05-01 Saturday
**** Workout
Routine: tout enchaîné sauf norwegian curls :
muscle-upx1 - planche tucked - RTO - L-sit - negatif - FL row tucked - skin the Cat - extension - compression (8s) - pistols (2#2 complètement assistés)
2.5 - 2.4

*** 2021-05-05 Wednesday
**** Handstand
 StW 43-23-35
 BtW 5x3-4

*** 2021-05-06 Thursday
**** Workout
RTO : 30(!)-18
Skin-the-cat : 2-2
L-sit : 11-7
Muscle-up : 2+1+1 - 3(!)+1+1 - 2+1+1
Pistols (assisted) : 3x3#3 assisté
Extension (lower-back) : 3x22
Front-lever row (tuck, 90°) :2x2cm (!) - 2x2cm + 2x1
Planche on rings (tuck): 3+2 - 3+2 - 2+1
Norwegian curls: 3x4
Compression : 10-9-8
**** Handstand
 BtW non chrono, x3

*** 2021-05-11 Tuesday
**** Running
:PROPERTIES:
:type: sprint
:reps:     8
:sprint:   50m
:rest:     2min
:END:

*** 2021-05-12 Wednesday
**** Handstand
 StW 53-17
 BtW oui
**** Workout
RTO : 30-22
Skin-the-cat : 2-1
L-sit : 8-5
Muscle-up : 3x{3+1} nouveau record !!!
Pistols (assisted) : 3x{3#3} assités
Extension (lower-back) : 3x22
Front-lever row (tuck) : 3+1 - 2+2 - 2+1
Planche on rings (tuck): 2+2 - 3+2 - 3+1
Norwegian curls: 4-4-3
Compression : 3x8

*** 2021-05-14 Friday
**** Handstand
 StW 36-19
 BtW 3 -2x5-  10 (?)

*** 2021-05-15 Saturday
**** Handstand
 StW 37-30
 BtW 11-4

*** 2021-05-16 Sunday
**** Handstand
 StW
 BtW 4 essais > 5s
**** Workout
Fatigué aujourd'hui, on se force
RTO : 13-12-10
Skin-the-cat : 2
L-sit : 6-5
Muscle-up négatifs : 6-6-6
Pistols (assisted) : 2x4#4-3#3
Extension (lower-back) : 3x22
Front-lever row (tuck) : 2+1 - 2+1 - 2
Planche on rings (tuck): 3+2 - 3+1 - 3+1
Norwegian curls: 3x4
Compression : 8-7-8

*** 2021-05-17 Monday
**** Handstand
 StW 40-30-20
 BtW 6-8

*** 2021-05-18 Tuesday
**** Parkour
Endurance sur obstacle x3
*** 2021-05-19 Wednesday
**** Running
:PROPERTIES:
:type:     medium
:duration: 30min
:END:

*** 2021-05-22 Saturday
**** Parkour
Passe-muraille :
- cat hang (each side) : 9
- top out (each side) : 5
- cat hang leg press (each side) : 0
- cat hang pull-up (each side) : 0
- knee raises (each side) : 6
- passe-muraille: 10 (meilleure technique)

*** 2021-05-24 Monday
**** Parkour
Escalade
Passe-muraille : ok en condition réelle !!
Endurance
**** Handstand
 StW
 BtW 3 essais

*** 2021-05-25 Tuesday
**** Workout
   RTO : 30-12-12
   Skin-the-cat : 1+1
   L-sit : 9-7
   Muscle-up : 2+1+1 - 3+1 - 1+1+1 (pas de négatifs + plue)
   Pistols (assisted) : 3x4#4
   Extension (lower-back) : 3x22
   Front-lever row (tuck) : 2+2 - 2+2 - 2+2
   Planche on rings (tuck):  3+3 - 3+3 - 3+2
   Norwegian curls: 4 - 5 - 5
   Compression :  3x8

*** 2021-05-26 Wednesday
**** Handstand
    StW 30-20
    BtW 2x2-5-7-10

*** 2021-05-28 Friday
**** Parkour
   Passe-muraille :
   - cat hang (each side) : 7
   - top out (each side) : 5
   - cat hang leg press (each side) : 4
   - cat hang pull-up (each side) : 5
   - knee raises (each side) : 5
   - passe-muraille: 11 !

*** 2021-05-29 Saturday
**** Handstand
    StW 54 33 32
    BtW 2-3-5-9

*** 2021-05-30 Sunday
**** Workout
   RTO : 28-17
   Skin-the-cat : 2-1.5
   L-sit : 9-7
   Muscle-up : 2+1+1 - 3+1(1 sans négatif) - 2+1+1 (2 non négatif)
   Pistols (assisted) : 4#4 - 3#3 - 3#3
   Extension (lower-back) : 3x22
   Front-lever row (tuck) : 3x1 - 2+2 - 2+2
   Planche on rings (tuck): 3x2 - 4+2+1 - 2+2
   Norwegian curls: 43x4
   Compression : 9-7-8

** 2021-06 June
*** 2021-06-01 Tuesday
**** Handstand
     StW 41-31
    BtW 2x2-6-7

*** 2021-06-02 Wednesday
**** Handstand
    StW 32
    BtW 3-5-6-13
**** Workout
   RTO : 28-18
   Skin-the-cat : 2
   L-sit : 9-7
   Muscle-up (L-sit !) : 4x1-4x1-1 + 1 normal bras tendu + rotation externe => à travailler comme ça !
   Pistols (assisted) : 3x{4#4}
   Extension (lower-back) : 3x22
   Front-lever row (tuck) : 3+2+1 - 3+2+1 - 3+2
   Planche on rings (tuck): 3+2 - 3+3 - 4+1
   Norwegian curls: 3x4
   Compression : 7-8-8

*** 2021-06-03 Thursday
**** Running
     :PROPERTIES:
     :type:     sprint
     :duration: 15min
     :END:
     Trop chaud !

*** 2021-06-04 Friday
**** Parkour
   Passe-muraille :
   - cat hang (each side) : 10
   - top out (each side) : 1
   - cat hang leg press (each side) : 6 (!)
   - cat hang pull-up (each side) : 6 (!)
   - knee raises (each side) : 5
   - passe-muraille: 23 (!!!) => amélioration de la technique, meilleure synchronisation donc fatigue diminuée. Pas forcément besoin de lever le genou très haut apparement

*** 2021-06-05 Saturday
**** Handstand
    StW 
    BtW 4essais
**** Handstand
    StW 35-37
    BtW 2-3-415(!)-17(!!)
**** Workout
   RTO : 28-18
   Skin-the-cat : 3
   L-sit : 9-7
   Muscle-upi l-sit bras tendus : 3x1 - 2x1 - 2x1
   Pistols (assisted) : 3x3
   Extension (lower-back) : 3x22
   Front-lever row (tuck) : 3+2 - 2+2 + 2+2
   Planche on rings (tuck): 3+2 - 2+2 - 3+2
   Norwegian curls: 3x4
   Compression : 8-7-7

*** 2021-06-06 Sunday
**** Running
     :PROPERTIES:
     :duration: 35min
     :misc:     avec pancho
     :END:

*** 2021-06-07 Monday
**** Handstand
    StW 31-17
    BtW

*** 2021-06-08 Tuesday
**** Handstand
    StW 42-35

**** Workout
     Tout echaîné : muscle-up bras tendus (sans L-sit) - RTO - L-sit - planche - FL row - skin the cat
     2x1 + oublie de la planche + 1 (!)
     2x1 + 1 muscle-up
     2x1 + 1 muscle-up

     pistols - extension - compression - curl :
     4-22-8-4
     4-22-8-4
     4-22-8-4

*** 2021-06-10 Thursday
**** Handstand
    StW 27-26
    BtW  2-5-7-8-12 (+ 3 essais) + 2x4
*** 2021-06-11 Friday
**** Handstand
    StW 42
    BtW 2-2x3-4-5-8
