#+TITLE: Command Line Tips
#+date: 2012-06-16s

** A better sudo
Use =doas= (from OpenBSD). The configuration is super easy, just write =/usr/local/etc/doas.conf= (on FreeBSD) :
#+begin_src
# Permit members of the wheel group to perform actions as root.
permit nopass :wheel
#+end_src
** Find files easily
Uses =fd= as a remplacement for =find=. Here is how I converted all the markdown files to org-mode :
#+begin_src
fd md -x pandoc git mv {} {.}.org
#+end_src
=-x= run a command, where ={}= contains the result, ={.}= contains the basename.
** Change your shell
Use [[https://fishshell.com/docs/current/tutorial.html][fish]]. Enough said :)
** Manage your ssh-keys
Simply using [[https://www.funtoo.org/Keychain][keychain]]. For fish shell, here's my configuration:

#+begin_src
# Keychain for gpg and ssh. We have to set ssh and gpg. And GPG ID...
if status is-login
   keychain --quiet --agents ssh,gpg id_rsa 65DCD80B3BFE5B80
end

if test -f ~/.keychain/(hostname)-gpg-fish
    source ~/.keychain/(hostname)-gpg-fish
end

if test -f ~/.keychain/(hostname)-fish
    source ~/.keychain/(hostname)-fish
end

# Bepo bindings for vim
for key in h l k j
    bind -e --user $key
    bind -e --user -M visual $key
end
#+end_src


** Splitting large files
Here is a simple tip for splitting a large file into small chunks on
Linux and reassemble it on Windows. No need to install anything !

On Linux, split largefile into small files of 2040M named small00,
small01... :

#+begin_src shell
  $ split -b 2048m -d largefile small
#+end_src

On Windows, Assembling the files is simply done inside the DOS terminal
with :

#+begin_src shell
  $ copy /b small00 + small01 final
#+end_src

Don't forget to use the binary mode with /b, otherwise it will not work.
** Video capture in Linux
*** Recordmydesktop
This is an easy-to-use command line utility. Just type

#+begin_src shell
  $ recordydesktop
#+end_src

and the capture starts.You can stop it with =Ctrl-C=. Easy, right ? Of
course, there are also several interesting options like

#+begin_src shell
  $ recordmydesktop ---no-cursor ---no-sound
#+end_src

which will make sure you have neither the cursor nor the sound in the
capture. I sometimes experienced intermittent lags, which broke the
overall fluidity. By default, the output format is OGG, one of the few
free formats. The main drawback here is the resolution of the output :I
could not set it at the highest level. But if you do not want to make HD
videos, this should suit you well enough.

*** Ffmpeg
I chose this one for my captures. Albeit not perfect, it
offers you the possibility of using several cores, leading to an
improvement in performances. The output can however set to very good
quality. For stopping the capture, juste type =q=. For example, you can
use it like that (refer to the man page for more details !) :

#+begin_src shell
  $ ffmpeg -f x11grab -s 1280x800 -r 25 -i :0.0+nomouse -s hd720 -vcodec libx264 -vpre lossless_ultrafast -an -threads 0 yourvideo.mkv </pre>
#+end_src

Now, what are all these options ?

- removes the mouse cursor from the capture: =-i :0.0+nomouse=
- enables multi-threading (if possible): =-threads 0=
- captures the screen: =-f x11grab=
- defines the size of the capture windows (here it is my entire screen):
  =-s 1280x800=
- sets the number of frames per seconds: =-r 25=
- sets the resolution: =-s hd720=
- no audio will be captured: =-an=
- using the H.264 encoding: =-vcodec libx264=
- these are settings for a fast encoding: =-vpre lossless_ultrafast=

You are all set for some capturing now :)

** Lock your screan
Simple use =xtrlock=
